import { test, expect } from '@playwright/test';

test.describe('Sentinel: Go Snippet Injection Mitigation', () => {
  test('JSONToGo removes backticks in struct tags', async ({ page }) => {
    await page.goto('http://localhost:5173/fr/outil/json-to-go');

    const maliciousJson = JSON.stringify({
      "foo`bar\": \"\", \"injection\": \"true": 1
    });

    await page.fill('#json-input', maliciousJson);

    // Wait for conversion
    await page.waitForTimeout(1000);

    const output = await page.innerText('pre');

    // Check that the backtick is removed and quotes are escaped
    expect(output).toContain('json:"foobar\\\": \\\"\\\", \\\"injection\\\": \\\"true"');

    // Ensure no breakout (backticks count)
    // type AutoGenerated struct {
    //   ...
    // }
    // Should have exactly 2 backticks.
    const backticks = output.split('`').length - 1;
    expect(backticks).toBe(2);
  });
});
