import { test, expect } from '@playwright/test';

test.describe('SQL & JSON to Elixir and JSON to Go Tool Suite', () => {
  test('JSON to Go Tool converts JSON payloads, loads presets, handles controls and shortcuts', async ({ page }) => {
    await page.goto('http://localhost:5173/fr/outil/json-to-go');

    // Verify header and input
    const inputArea = page.locator('#json-go-input');
    await expect(inputArea).toBeVisible();

    // Load User Profile Preset
    const profilePresetBtn = page.getByRole('button', { name: /Profil Utilisateur|User Profile/i });
    await profilePresetBtn.click();
    await expect(inputArea).toHaveValue(/johndoe/);

    const outputArea = page.locator('#go-output');
    await expect(outputArea).toHaveValue(/type AutoGenerated struct/);
    await expect(outputArea).toHaveValue(/FirstName string `json:"first_name"`/);

    // Toggle YAML tag
    const yamlCheckbox = page.locator('#use-yaml-tag');
    await yamlCheckbox.check();
    await expect(outputArea).toHaveValue(/yaml:"first_name"/);

    // Change struct name
    const structNameInput = page.locator('#go-struct-name');
    await structNameInput.fill('UserProfileResponse');
    await expect(outputArea).toHaveValue(/type UserProfileResponse struct/);

    // Test Esc shortcut clear
    await inputArea.focus();
    await page.keyboard.press('Escape');
    await expect(inputArea).toHaveValue('');
    await expect(outputArea).toHaveValue('');
  });

  test('SQL to Elixir Ecto Tool converts DDL, loads presets, and generates changeset', async ({ page }) => {
    await page.goto('http://localhost:5173/fr/outil/sql-to-elixir');

    const inputArea = page.locator('#sql-elixir-input');
    await expect(inputArea).toBeVisible();

    // Load User Auth Preset
    const userAuthPresetBtn = page.getByRole('button', { name: /Authentification & Rôles|User Auth & Roles/i });
    await userAuthPresetBtn.click();
    await expect(inputArea).toHaveValue(/CREATE TABLE users/);

    const outputArea = page.locator('#elixir-output');
    await expect(outputArea).toHaveValue(/defmodule MyApp\.User do/);
    await expect(outputArea).toHaveValue(/schema "users" do/);
    await expect(outputArea).toHaveValue(/field :email, :string/);
    await expect(outputArea).toHaveValue(/def changeset/);

    // Toggle Binary ID
    const binaryIdCheckbox = page.locator('#use-binary-id');
    await binaryIdCheckbox.check();
    await expect(outputArea).toHaveValue(/@primary_key {:id, :binary_id, autogenerate: true}/);

    // Test Esc shortcut
    await inputArea.focus();
    await page.keyboard.press('Escape');
    await expect(inputArea).toHaveValue('');
    await expect(outputArea).toHaveValue('');
  });

  test('JSON to Elixir Tool converts JSON into defstruct and embedded_schema', async ({ page }) => {
    await page.goto('http://localhost:5173/fr/outil/json-to-elixir');

    const inputArea = page.locator('#json-elixir-input');
    await expect(inputArea).toBeVisible();

    // Load User Profile Preset
    const profilePresetBtn = page.getByRole('button', { name: /Profil Utilisateur|User Profile/i });
    await profilePresetBtn.click();
    await expect(inputArea).toHaveValue(/johndoe/);

    const outputArea = page.locator('#elixir-struct-output');
    await expect(outputArea).toHaveValue(/defmodule MyApp\.User do/);
    await expect(outputArea).toHaveValue(/@type t :: %__MODULE__{/);
    await expect(outputArea).toHaveValue(/defstruct \[/);
    await expect(outputArea).toHaveValue(/username:/);

    // Switch to Ecto Embedded Schema
    const outputTypeSelect = page.locator('#elixir-output-type');
    await outputTypeSelect.selectOption('ecto_embed');
    await expect(outputArea).toHaveValue(/embedded_schema do/);
    await expect(outputArea).toHaveValue(/field :username, :string/);
    await expect(outputArea).toHaveValue(/def changeset/);

    // Test Esc shortcut
    await inputArea.focus();
    await page.keyboard.press('Escape');
    await expect(inputArea).toHaveValue('');
    await expect(outputArea).toHaveValue('');
  });
});
