import React, { useState, useEffect, useRef, useCallback, useMemo } from "react";
import { Search, Info, Copy, Check, Trash2, Download, CheckSquare, Square, FileCode, Sliders } from "lucide-react";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { Kbd } from "./ui/Kbd";

interface Preset {
  id: string;
  name: string;
  category: "languages" | "editors" | "os" | "frameworks";
  rules: string;
}

const PRESETS: Preset[] = [
  // Languages
  {
    id: "node",
    name: "Node.js",
    category: "languages",
    rules: `# Node.js gitignore
node_modules/
jspm_packages/
lerna-debug.log*
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*
.npm
.eslintcache
.stylelintcache
logs
*.log
pids
*.pid
*.seed
*.pid.lock
dist/
build/
.env
.env.local
.env.development.local
.env.test.local
.env.production.local
`
  },
  {
    id: "python",
    name: "Python",
    category: "languages",
    rules: `# Python gitignore
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST
.ipynb_checkpoints
.env
.venv
venv/
ENV/
env/
htmlcov/
.tox/
.coverage
.cache
nosetests.xml
coverage.xml
*.cover
.hypothesis/
`
  },
  {
    id: "go",
    name: "Go",
    category: "languages",
    rules: `# Go gitignore
# Compiled-out files
*.o
*.obj
*.a
*.exe
*.out

# Folders
bin/
pkg/
src/

# Architecture specific databases
fpdb/

# Vendor
vendor/
`
  },
  {
    id: "rust",
    name: "Rust",
    category: "languages",
    rules: `# Rust gitignore
# Generated by Cargo
# any backup files or templates
/target/

# Remove this line if you wish to store your raw Cargo.lock in the git repository
Cargo.lock

# These are backup files generated by rustfmt
**/*.rs.bk
`
  },
  {
    id: "java",
    name: "Java",
    category: "languages",
    rules: `# Java gitignore
*.class
*.log
*.ctxt
.mtj.tmp/
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar
hs_err_pid*
`
  },
  {
    id: "cpp",
    name: "C++",
    category: "languages",
    rules: `# C++ gitignore
# Prerequisites
*.d

# Compiled Object files
*.slo
*.lo
*.o
*.obj

# Precompiled Headers
*.gch
*.pch

# Compiled Dynamic Libraries
*.so
*.dylib
*.dll

# Fortran compiled modules
*.mod
*.smod

# Compiled Static Libraries
*.lai
*.la
*.a
*.lib

# Executables
*.exe
*.out
*.app
`
  },
  {
    id: "ruby",
    name: "Ruby",
    category: "languages",
    rules: `# Ruby gitignore
*.gem
*.rbc
/.config
/coverage/
/InstalledFiles
/pkg/
/spec/reports/
/spec/examples.txt
/test/tmp/
/test/version_tmp/
/tmp/

# Vendor Bundle
/vendor/bundle/
/.bundle/
`
  },
  {
    id: "php",
    name: "PHP",
    category: "languages",
    rules: `# PHP gitignore
/vendor/
composer.phar
.env
.env.local
.phpunit.result.cache
`
  },
  {
    id: "swift",
    name: "Swift",
    category: "languages",
    rules: `# Swift gitignore
.build/
Packages/
.DS_Store
*.swp
*.package.resolved
`
  },
  {
    id: "kotlin",
    name: "Kotlin",
    category: "languages",
    rules: `# Kotlin gitignore
*.class
*.klib
build/
.gradle/
/out/
`
  },

  // IDEs & Editors
  {
    id: "vscode",
    name: "VS Code",
    category: "editors",
    rules: `# VS Code gitignore
.vscode/
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
!.vscode/code-snippets
*.code-workspace
.history/
`
  },
  {
    id: "jetbrains",
    name: "JetBrains (IntelliJ, WebStorm, etc.)",
    category: "editors",
    rules: `# JetBrains gitignore
.idea/
*.iws
*.iml
*.ipr
out/
`
  },
  {
    id: "sublime",
    name: "Sublime Text",
    category: "editors",
    rules: `# Sublime Text gitignore
*.sublime-project
*.sublime-workspace
sftp-config.json
`
  },
  {
    id: "xcode",
    name: "Xcode",
    category: "editors",
    rules: `# Xcode gitignore
# Xcode user settings
xcuserdata/
DerivedData/
*.xcuserstate
*.xcworkspace
`
  },

  // Operating Systems
  {
    id: "macos",
    name: "macOS",
    category: "os",
    rules: `# macOS gitignore
.DS_Store
.AppleDouble
.LSOverride
Icon


# Thumbnails
._*

# Files that might be created on a File System Topic
.DocumentRevisions-V100
.Spotlight-V100
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent
`
  },
  {
    id: "windows",
    name: "Windows",
    category: "os",
    rules: `# Windows gitignore
Thumbs.db
ehthumbs.db
ehthumbs_vista.db
Desktop.ini
$RECYCLE.BIN/
*.lnk
`
  },
  {
    id: "linux",
    name: "Linux",
    category: "os",
    rules: `# Linux gitignore
*~
.fuse_hidden*
.directory
.Trash-*
.nfs*
`
  },

  // Frameworks
  {
    id: "react",
    name: "React.js",
    category: "frameworks",
    rules: `# React gitignore
build/
dist/
.env.local
.env.development.local
.env.test.local
.env.production.local
`
  },
  {
    id: "vue",
    name: "Vue.js",
    category: "frameworks",
    rules: `# Vue gitignore
dist/
node_modules/
.env.local
.env.development.local
.env.test.local
.env.production.local
`
  },
  {
    id: "angular",
    name: "Angular",
    category: "frameworks",
    rules: `# Angular gitignore
dist/
.angular/
node_modules/
`
  },
  {
    id: "svelte",
    name: "Svelte / SvelteKit",
    category: "frameworks",
    rules: `# Svelte gitignore
.svelte-kit/
build/
dist/
node_modules/
`
  },
  {
    id: "django",
    name: "Django",
    category: "frameworks",
    rules: `# Django gitignore
*.log
local_settings.py
db.sqlite3
db.sqlite3-journal
media/
staticfiles/
`
  },
  {
    id: "laravel",
    name: "Laravel",
    category: "frameworks",
    rules: `# Laravel gitignore
/vendor/
/public/hot
/public/storage
/storage/*.key
/bootstrap/cache/*
.env
.env.backup
`
  },
  {
    id: "rails",
    name: "Ruby on Rails",
    category: "frameworks",
    rules: `# Rails gitignore
/log/
/tmp/
/public/assets
/db/*.sqlite3
/db/*.sqlite3-journal
/config/initializers/secret_token.rb
/config/master.key
`
  },
  {
    id: "springboot",
    name: "Spring Boot",
    category: "frameworks",
    rules: `# Spring Boot gitignore
target/
*.jar
*.war
*.zip
*.tar.gz
`
  },
  {
    id: "unity",
    name: "Unity",
    category: "frameworks",
    rules: `# Unity gitignore
[Tt]emp/
[Ll]ibrary/
[Oo]bj/
[Bb]uild/
[Bb]uilds/
[Logs]/
UserSettings/
`
  },
  {
    id: "flutter",
    name: "Flutter",
    category: "frameworks",
    rules: `# Flutter gitignore
.build/
.dart_tool/
.flutter-plugins
.flutter-plugins-dependencies
build/
`
  }
];

export function GitignoreGenerator({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();

  const [selectedPresets, setSelectedPresets] = useState<string[]>(initialData?.selectedPresets || []);
  const [customRules, setCustomRules] = useState(initialData?.customRules || "");
  const [searchQuery, setSearchQuery] = useState("");

  const searchInputRef = useRef<HTMLInputElement>(null);
  const [copied, setCopied] = useState(false);

  // Sync state up
  useEffect(() => {
    onStateChange?.({ selectedPresets, customRules });
  }, [selectedPresets, customRules, onStateChange]);

  const filteredPresets = useMemo(() => {
    const q = searchQuery.toLowerCase().trim();
    if (!q) return PRESETS;
    return PRESETS.filter(
      p => p.name.toLowerCase().includes(q) || p.category.toLowerCase().includes(q)
    );
  }, [searchQuery]);

  const togglePreset = (id: string) => {
    setSelectedPresets(prev =>
      prev.includes(id) ? prev.filter(p => p !== id) : [...prev, id]
    );
  };

  const clearAll = useCallback(() => {
    setSelectedPresets([]);
    setCustomRules("");
    setSearchQuery("");
    toast.success(t("gitignore.toast_cleared", "Cleared all inputs and selections!"));
    setTimeout(() => {
      searchInputRef.current?.focus();
    }, 0);
  }, [t]);

  const generatedOutput = useMemo(() => {
    let output = "";
    if (selectedPresets.length > 0) {
      selectedPresets.forEach(presetId => {
        const preset = PRESETS.find(p => p.id === presetId);
        if (preset) {
          output += `# ==========================================\n`;
          output += `# Preset: ${preset.name}\n`;
          output += `# ==========================================\n`;
          output += preset.rules + "\n";
        }
      });
    }

    if (customRules.trim()) {
      output += `# ==========================================\n`;
      output += `# Custom Rules\n`;
      output += `# ==========================================\n`;
      output += customRules + "\n";
    }

    return output.trim();
  }, [selectedPresets, customRules]);

  const handleCopy = useCallback(() => {
    if (!generatedOutput) return;
    navigator.clipboard.writeText(generatedOutput);
    setCopied(true);
    toast.success(t("gitignore.toast_copied", "Content copied to clipboard!"));
    setTimeout(() => setCopied(false), 2000);
  }, [generatedOutput, t]);

  const handleDownload = () => {
    if (!generatedOutput) return;
    const blob = new Blob([generatedOutput], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = ".gitignore";
    link.click();
    URL.revokeObjectURL(url);
    toast.success(t("common.download_success", "Download successful"));
  };

  // Setup keyboard shortcuts using a useRef-backed current wrapper
  const handlersRef = useRef({ clearAll, handleCopy });
  useEffect(() => {
    handlersRef.current = { clearAll, handleCopy };
  }, [clearAll, handleCopy]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const active = document.activeElement;
      const isEditable =
        active instanceof HTMLInputElement ||
        active instanceof HTMLTextAreaElement ||
        active?.getAttribute("contenteditable") === "true";

      if (isEditable && e.key !== "Escape") return;

      if (e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;

      if (e.key === "Escape") {
        e.preventDefault();
        handlersRef.current.clearAll();
      } else if (e.key.toLowerCase() === "c") {
        e.preventDefault();
        handlersRef.current.handleCopy();
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, []);

  const categoriesList: { id: "languages" | "editors" | "os" | "frameworks"; name: string }[] = [
    { id: "languages", name: t("gitignore.cat_languages", "Languages") },
    { id: "frameworks", name: t("gitignore.cat_frameworks", "Frameworks") },
    { id: "editors", name: t("gitignore.cat_editors", "IDEs & Editors") },
    { id: "os", name: t("gitignore.cat_os", "Operating Systems") }
  ];

  return (
    <div className="max-w-6xl mx-auto space-y-8">
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Left Column: Preset Selection */}
        <div className="lg:col-span-5 space-y-6">
          <div className="p-6 bg-white dark:bg-slate-900/50 border border-slate-200 dark:border-slate-800 rounded-3xl space-y-6 shadow-sm">
            <div className="flex justify-between items-center">
              <h3 className="text-xs font-black uppercase tracking-widest text-slate-400 flex items-center gap-2">
                <Sliders className="w-4 h-4 text-indigo-500" />
                {t("gitignore.presets_title", "Presets")}
              </h3>
              <div className="flex items-center gap-1.5">
                <Kbd modifier={null} className="text-[10px] text-indigo-400 border-indigo-200 dark:border-indigo-800 dark:bg-slate-900">ESC</Kbd>
                <span className="text-[10px] font-black uppercase tracking-wider text-slate-400">{t("common.clear", "Reset")}</span>
              </div>
            </div>

            {/* Search Input */}
            <div className="relative">
              <label htmlFor="gitignore-preset-search" className="sr-only">{t("gitignore.search_presets", "Search presets...")}</label>
              <div className="absolute inset-y-0 left-3.5 flex items-center pointer-events-none">
                <Search className="w-4 h-4 text-slate-400" />
              </div>
              <input
                id="gitignore-preset-search"
                ref={searchInputRef}
                type="text"
                autoComplete="off"
                spellCheck={false}
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder={t("gitignore.search_presets", "Search presets...")}
                className="w-full pl-10 pr-4 py-2 bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-xl text-sm outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all dark:text-white"
              />
            </div>

            {/* Categories and Badges */}
            <div className="space-y-6 max-h-[350px] overflow-y-auto pr-1 no-scrollbar">
              {categoriesList.map(cat => {
                const catPresets = filteredPresets.filter(p => p.category === cat.id);
                if (catPresets.length === 0) return null;

                return (
                  <div key={cat.id} className="space-y-2">
                    <span className="text-[10px] font-black uppercase tracking-wider text-slate-400 dark:text-slate-500">
                      {cat.name}
                    </span>
                    <div className="flex flex-wrap gap-2">
                      {catPresets.map(preset => {
                        const isSelected = selectedPresets.includes(preset.id);
                        return (
                          <button
                            key={preset.id}
                            onClick={() => togglePreset(preset.id)}
                            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold transition-all border ${
                              isSelected
                                ? "bg-indigo-500 text-white border-indigo-500 shadow-md shadow-indigo-500/20"
                                : "bg-slate-50 hover:bg-slate-100 border-slate-200 text-slate-600 dark:bg-slate-800 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-750"
                            }`}
                          >
                            {isSelected ? <CheckSquare className="w-3.5 h-3.5" /> : <Square className="w-3.5 h-3.5" />}
                            {preset.name}
                          </button>
                        );
                      })}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Custom Rules Input */}
          <div className="p-6 bg-white dark:bg-slate-900/50 border border-slate-200 dark:border-slate-800 rounded-3xl space-y-3 shadow-sm">
            <label htmlFor="gitignore-custom-rules" className="text-xs font-black uppercase tracking-widest text-slate-400 block">
              {t("gitignore.custom_rules_label", "Custom Rules")}
            </label>
            <textarea
              id="gitignore-custom-rules"
              value={customRules}
              onChange={(e) => setCustomRules(e.target.value)}
              placeholder={t("gitignore.custom_placeholder", "e.g.\n.env.production\n/private-uploads/")}
              className="w-full h-36 p-4 bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-2xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all text-sm font-mono leading-relaxed dark:text-slate-300 resize-none"
            />
          </div>
        </div>

        {/* Right Column: Interactive Generated Preview */}
        <div className="lg:col-span-7 flex flex-col space-y-4">
          <div className="flex justify-between items-center px-1">
            <h3 className="text-xs font-black uppercase tracking-widest text-slate-400 flex items-center gap-2">
              <FileCode className="w-4 h-4 text-emerald-500" />
              {t("gitignore.preview_title", "Generated .gitignore")}
            </h3>
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                disabled={!generatedOutput}
                className="p-2 text-indigo-600 bg-indigo-50 dark:bg-indigo-900/20 rounded-lg hover:bg-indigo-100 disabled:opacity-50 transition-all focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
                title={t("common.download")}
                aria-label={t("common.download")}
              >
                <Download className="w-4.5 h-4.5" />
              </button>
              <button
                onClick={handleCopy}
                disabled={!generatedOutput}
                className={`flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold transition-all border focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
                  copied
                    ? "bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-200 dark:border-emerald-500/20"
                    : "text-slate-500 bg-slate-100 dark:bg-slate-800 border-transparent hover:bg-slate-200 dark:hover:bg-slate-700"
                } disabled:opacity-50 disabled:cursor-not-allowed`}
              >
                {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                {copied ? t("common.copied", "Copied") : t("common.copy", "Copy")}
                <Kbd modifier={null} className="ml-1 bg-white/50 dark:bg-slate-900/50">C</Kbd>
              </button>
            </div>
          </div>

          <textarea
            id="gitignore-output-preview"
            value={generatedOutput}
            readOnly
            placeholder={t("gitignore.output_placeholder", "Your generated .gitignore will appear here...")}
            className="w-full flex-grow min-h-[450px] p-6 bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400 resize-none shadow-sm"
          />
        </div>
      </div>

      {/* Guide & About Section */}
      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <div className="p-3 bg-white dark:bg-slate-800 text-indigo-600 rounded-2xl shadow-sm border border-slate-100 dark:border-slate-700 shrink-0">
          <Info className="w-6 h-6" />
        </div>
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">{t("gitignore.about_title", "About .gitignore Generator")}</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            {t("gitignore.about_text", "A `.gitignore` file specifies intentionally untracked files that Git should ignore. This tool allows you to combine production-ready ignore templates for various programming languages, popular IDEs, operating systems, and frameworks alongside custom ignore patterns in real-time, helping you keep your repositories clean and free of build artifacts, dependency directories, or sensitive environment credentials.")}
          </p>
        </div>
      </div>
    </div>
  );
}
