import { useState, useEffect, useCallback, useRef } from 'react';
import { FileCode, Copy, Check, Trash2, AlertCircle, Download, Info, Settings, Sparkles } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;

const PROTO_RESERVED_KEYWORDS = new Set([
  'package', 'import', 'message', 'service', 'syntax', 'enum', 'oneof', 'map',
  'reserved', 'extensions', 'extend', 'option', 'repeated', 'optional', 'required',
  'double', 'float', 'int32', 'int64', 'uint32', 'uint64', 'sint32', 'sint64',
  'fixed32', 'fixed64', 'sfixed32', 'sfixed64', 'bool', 'string', 'bytes', 'rpc', 'returns'
]);

const JS_RESERVED_KEYWORDS = new Set([
  'type', 'interface', 'class', 'function', 'var', 'let', 'const', 'import', 'export',
  'default', 'return', 'enum', 'extends', 'implements', 'public', 'private', 'protected',
  'readonly', 'static', 'package', 'new', 'this', 'super', 'in', 'of', 'for', 'if', 'else',
  'while', 'do', 'try', 'catch', 'finally', 'throw', 'delete', 'typeof', 'instanceof',
  'void', 'null', 'undefined', 'never', 'any', 'unknown', 'boolean', 'string', 'number'
]);

const toSnakeCase = (str: string) => {
  return str
    .replace(/([A-Z])/g, '_$1')
    .toLowerCase()
    .replace(/^_/, '')
    .replace(/[^a-z0-9_]/g, '_');
};

const toCamelCase = (str: string) => {
  return str.replace(/_([a-z0-9])/gi, (_, letter) => letter.toUpperCase());
};

const toPascalCase = (str: string) => {
  return (
    str
      .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
      .replace(/[^a-zA-Z0-9]/g, ' ')
      .split(' ')
      .filter(Boolean)
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join('') || 'AutoGenerated'
  );
};

export function GraphQLToProtobuf({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const inputRef = useRef<HTMLTextAreaElement>(null);

  const [input, setInput] = useState(initialData?.input || '');
  const [output, setOutput] = useState(initialData?.output || '');
  const [packageName, setPackageName] = useState(initialData?.packageName || 'model');
  const [syntaxVersion, setSyntaxVersion] = useState<'proto3' | 'proto2'>(initialData?.syntaxVersion || 'proto3');
  const [intType, setIntType] = useState<'int32' | 'int64'>(initialData?.intType || 'int32');
  const [floatType, setFloatType] = useState<'double' | 'float'>(initialData?.floatType || 'double');
  const [timestampType, setTimestampType] = useState<'timestamp' | 'string' | 'int64'>(initialData?.timestampType || 'timestamp');
  const [casingMode, setCasingMode] = useState<'original' | 'snake_case' | 'camelCase' | 'PascalCase'>(initialData?.casingMode || 'snake_case');
  const [activePreset, setActivePreset] = useState<string | null>(initialData?.activePreset || null);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    onStateChange?.({
      input,
      output,
      packageName,
      syntaxVersion,
      intType,
      floatType,
      timestampType,
      casingMode,
      activePreset
    });
  }, [input, output, packageName, syntaxVersion, intType, floatType, timestampType, casingMode, activePreset, onStateChange]);

  const PRESETS = {
    ecommerce: `# E-Commerce Schema
type Category {
  id: ID!
  name: String!
  slug: String!
  parent: Category
}

type Product {
  id: ID!
  title: String!
  description: String
  price: Float!
  sku: String!
  isActive: Boolean!
  category: Category!
  tags: [String!]!
  createdAt: DateTime!
}

input CreateProductInput {
  title: String!
  description: String
  price: Float!
  categoryId: ID!
  tags: [String!]
}

enum OrderStatus {
  PENDING
  PROCESSING
  SHIPPED
  DELIVERED
  CANCELLED
}`,
    user_auth: `# User Management & Auth Schema
enum Role {
  ADMIN
  MANAGER
  MEMBER
  GUEST
}

interface Node {
  id: ID!
}

type User implements Node {
  id: ID!
  email: String!
  fullName: String!
  role: Role!
  isVerified: Boolean!
  lastLogin: DateTime
  metadata: JSON
}

input RegisterUserInput {
  email: String!
  password: String!
  fullName: String!
  role: Role
}

union AuthResult = User | AuthError

type AuthError {
  code: String!
  message: String!
}`,
    social_feed: `# Social Feed & Comments Schema
type User {
  id: ID!
  username: String!
  avatarUrl: String
}

type Comment {
  id: ID!
  author: User!
  content: String!
  createdAt: DateTime!
  likesCount: Int!
}

type Post {
  id: ID!
  author: User!
  title: String!
  body: String!
  comments: [Comment!]!
  isPublished: Boolean!
}

union FeedItem = Post | Comment`
  };

  const sanitizeFieldName = (fieldName: string): string => {
    let transformed = fieldName;
    if (casingMode === 'snake_case') transformed = toSnakeCase(fieldName);
    else if (casingMode === 'camelCase') transformed = toCamelCase(fieldName);
    else if (casingMode === 'PascalCase') transformed = toPascalCase(fieldName);

    let safe = transformed.replace(/[^a-zA-Z0-9_]/g, '_');
    if (/^[0-9]/.test(safe)) safe = 'f_' + safe;

    if (PROTO_RESERVED_KEYWORDS.has(safe.toLowerCase()) || JS_RESERVED_KEYWORDS.has(safe.toLowerCase())) {
      safe = safe + '_';
    }

    return safe || 'field';
  };

  const mapGqlTypeToProto = (
    gqlTypeStr: string,
    customScalars: Set<string>,
    knownMessages: Set<string>,
    importsNeeded: Set<string>
  ): { protoType: string; isRepeated: boolean; isOptional: boolean } => {
    const raw = gqlTypeStr.trim();
    const isNonNull = raw.endsWith('!');
    const typeWithoutOuterBang = isNonNull ? raw.slice(0, -1).trim() : raw;

    let isRepeated = false;
    let base = typeWithoutOuterBang;

    if (base.startsWith('[') && base.endsWith(']')) {
      isRepeated = true;
      base = base.slice(1, -1).trim();
      if (base.endsWith('!')) {
        base = base.slice(0, -1).trim();
      }
    }

    let protoType = 'string';

    if (base === 'String' || base === 'ID') {
      protoType = 'string';
    } else if (base === 'Int') {
      protoType = intType;
    } else if (base === 'Float') {
      protoType = floatType;
    } else if (base === 'Boolean') {
      protoType = 'bool';
    } else if (base === 'DateTime' || base === 'Date' || base === 'Timestamp') {
      if (timestampType === 'timestamp') {
        protoType = 'google.protobuf.Timestamp';
        importsNeeded.add('google/protobuf/timestamp.proto');
      } else if (timestampType === 'int64') {
        protoType = 'int64';
      } else {
        protoType = 'string';
      }
    } else if (base === 'JSON' || base === 'JSONObject') {
      protoType = 'google.protobuf.Struct';
      importsNeeded.add('google/protobuf/struct.proto');
    } else if (customScalars.has(base)) {
      protoType = 'string';
    } else if (knownMessages.has(base)) {
      protoType = base;
    } else {
      protoType = toPascalCase(base);
    }

    const isOptional = syntaxVersion === 'proto2' && !isRepeated;

    return { protoType, isRepeated, isOptional };
  };

  const handleConvert = useCallback(() => {
    try {
      if (!input.trim()) {
        setOutput('');
        setError('');
        return;
      }

      if (input.length > MAX_LENGTH) {
        setError(t('error.max_length', { max: MAX_LENGTH.toLocaleString() }));
        setOutput('');
        return;
      }

      const cleanInput = input
        .replace(/#.*$/gm, '')
        .replace(/"""[\s\S]*?"""/g, '')
        .replace(/"[\s\S]*?"/g, (m: string) => (m.includes('\n') ? '""' : m));

      const customScalars = new Set<string>();
      const scalarRegex = /scalar\s+([A-Za-z0-9_]+)/g;
      let scalarMatch: RegExpExecArray | null;
      while ((scalarMatch = scalarRegex.exec(cleanInput)) !== null) {
        if (scalarMatch[1]) customScalars.add(scalarMatch[1]);
      }

      const knownMessages = new Set<string>();
      const typeCollectRegex = /(type|interface|input|enum|union)\s+([A-Za-z0-9_]+)/g;
      let typeMatch;
      while ((typeMatch = typeCollectRegex.exec(cleanInput)) !== null) {
        if (typeMatch[2]) knownMessages.add(toPascalCase(typeMatch[2]));
      }

      const importsNeeded = new Set<string>();
      const outputBlocks: string[] = [];

      // 1. Enums
      const enumRegex = /enum\s+([A-Za-z0-9_]+)\s*\{([^}]*)\}/g;
      let enumMatch;
      while ((enumMatch = enumRegex.exec(cleanInput)) !== null) {
        const rawEnumName = enumMatch[1];
        const enumName = toPascalCase(rawEnumName);
        const enumValues = enumMatch[2]
          .split(/\s+/)
          .map((v) => v.trim())
          .filter(Boolean);

        if (enumValues.length > 0) {
          let enumLines: string[] = [];
          if (syntaxVersion === 'proto3') {
            const unspecifiedName = `${toSnakeCase(enumName).toUpperCase()}_UNSPECIFIED`;
            enumLines.push(`  ${unspecifiedName} = 0;`);
            enumValues.forEach((val, idx) => {
              const safeValName = val.toUpperCase().replace(/[^A-Z0-9_]/g, '_');
              enumLines.push(`  ${safeValName} = ${idx + 1};`);
            });
          } else {
            enumValues.forEach((val, idx) => {
              const safeValName = val.toUpperCase().replace(/[^A-Z0-9_]/g, '_');
              enumLines.push(`  ${safeValName} = ${idx};`);
            });
          }

          outputBlocks.push(`enum ${enumName} {\n${enumLines.join('\n')}\n}`);
        }
      }

      // 2. Unions (mapped to a wrapper message with a oneof clause)
      const unionRegex = /union\s+([A-Za-z0-9_]+)\s*=\s*([^;\n]+)/g;
      let unionMatch;
      while ((unionMatch = unionRegex.exec(cleanInput)) !== null) {
        const rawUnionName = unionMatch[1];
        const unionName = toPascalCase(rawUnionName);
        const typesList = unionMatch[2]
          .split('|')
          .map((t) => t.trim())
          .filter(Boolean);

        if (typesList.length > 0) {
          const oneofFields = typesList.map((t, idx) => {
            const memberType = toPascalCase(t);
            const fieldName = sanitizeFieldName(t);
            return `    ${memberType} ${fieldName} = ${idx + 1};`;
          });

          outputBlocks.push(`message ${unionName} {\n  oneof value {\n${oneofFields.join('\n')}\n  }\n}`);
        }
      }

      // 3. Object types, Interfaces, Inputs
      const structRegex = /(type|interface|input)\s+([A-Za-z0-9_]+)(?:\s+implements\s+[^{]+)?\s*\{([^}]*)\}/g;
      let structMatch;

      while ((structMatch = structRegex.exec(cleanInput)) !== null) {
        const rawName = structMatch[2];
        const msgName = toPascalCase(rawName);
        const body = structMatch[3];

        const normalizedBody = body
          .replace(/(!|[a-zA-Z0-9_\]]+)\s+([a-zA-Z0-9_$]+)\s*:/g, '$1\n$2:')
          .trim();

        const lines = normalizedBody
          .split('\n')
          .map((l) => l.trim())
          .filter((l) => l && !l.startsWith('#'));

        let fieldIndex = 1;
        const msgFields: string[] = [];

        lines.forEach((line) => {
          const cleanLine = line.replace(/\([^)]*\)/, '');
          const colonIdx = cleanLine.indexOf(':');
          if (colonIdx === -1) return;

          const rawFieldName = cleanLine.substring(0, colonIdx).trim();
          const rawTypeStr = cleanLine.substring(colonIdx + 1).trim();

          if (!rawFieldName || !rawTypeStr) return;

          const fieldKey = sanitizeFieldName(rawFieldName);
          const { protoType, isRepeated, isOptional } = mapGqlTypeToProto(
            rawTypeStr,
            customScalars,
            knownMessages,
            importsNeeded
          );

          let prefix = '';
          if (isRepeated) {
            prefix = 'repeated ';
          } else if (isOptional) {
            prefix = 'optional ';
          }

          msgFields.push(`  ${prefix}${protoType} ${fieldKey} = ${fieldIndex};`);
          fieldIndex++;
        });

        outputBlocks.push(`message ${msgName} {\n${msgFields.join('\n')}\n}`);
      }

      if (outputBlocks.length === 0) {
        setError(t('graphqltoprotobuf.no_types_found', 'No valid GraphQL types, interfaces, inputs, or enums found.'));
        setOutput('');
        return;
      }

      const pkg = packageName.trim() ? packageName.trim().replace(/[^a-zA-Z0-9._]/g, '_') : 'model';
      let header = `syntax = "${syntaxVersion}";\n\npackage ${pkg};\n\n`;

      if (importsNeeded.size > 0) {
        Array.from(importsNeeded)
          .sort()
          .forEach((imp) => {
            header += `import "${imp}";\n`;
          });
        header += '\n';
      }

      const finalOutput = header + outputBlocks.join('\n\n');
      setOutput(finalOutput);
      setError('');
    } catch (e: any) {
      setError(t('graphqltoprotobuf.error_parsing', 'Error parsing GraphQL schema') + ': ' + e.message);
      setOutput('');
    }
  }, [input, packageName, syntaxVersion, intType, floatType, timestampType, casingMode, t]);

  useEffect(() => {
    handleConvert();
  }, [handleConvert]);

  const handleCopy = useCallback(() => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    toast.success(t('graphqltoprotobuf.toast_copied', 'Protobuf .proto definitions copied to clipboard!'));
    setTimeout(() => setCopied(false), 2000);
  }, [output, t]);

  const handleClear = useCallback(() => {
    setInput('');
    setOutput('');
    setError('');
    setActivePreset(null);
    toast.success(t('graphqltoprotobuf.toast_cleared', 'Inputs cleared!'));
    setTimeout(() => inputRef.current?.focus(), 0);
  }, [t]);

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${packageName || 'schema'}.proto`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(t('common.downloaded', 'Downloaded .proto file!'));
  };

  const loadPreset = (presetKey: keyof typeof PRESETS) => {
    setInput(PRESETS[presetKey]);
    setActivePreset(presetKey);
    toast.success(t('graphqltoprotobuf.preset_loaded', 'Loaded GraphQL preset!'));
  };

  const handlersRef = useRef({ handleClear, handleCopy, output });
  useEffect(() => {
    handlersRef.current = { handleClear, handleCopy, output };
  }, [handleClear, handleCopy, output]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const activeElement = document.activeElement;
      const isEditable =
        activeElement instanceof HTMLInputElement ||
        activeElement instanceof HTMLTextAreaElement ||
        activeElement instanceof HTMLSelectElement ||
        activeElement?.getAttribute('contenteditable') === 'true';

      if (isEditable && e.key !== 'Escape') return;

      if (e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;

      if (e.key === 'Escape') {
        e.preventDefault();
        handlersRef.current.handleClear();
      } else if (e.key.toLowerCase() === 'c') {
        if (handlersRef.current.output) {
          e.preventDefault();
          handlersRef.current.handleCopy();
        }
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  return (
    <div className="max-w-6xl mx-auto space-y-8 animate-in fade-in duration-500">
      {/* Configuration Panel */}
      <div className="bg-slate-50 dark:bg-slate-900/50 p-6 rounded-[2rem] border border-slate-200 dark:border-slate-800 space-y-6">
        <div className="flex items-center gap-2 px-1">
          <Settings className="w-4 h-4 text-indigo-500" aria-hidden="true" />
          <h2 className="text-xs font-black uppercase tracking-widest text-slate-400">
            {t('graphqltoprotobuf.options_title', 'Protobuf Configuration')}
          </h2>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-6 gap-4">
          {/* Package Name */}
          <div className="space-y-1.5 lg:col-span-2">
            <label htmlFor="package-name-input" className="text-xs font-bold text-slate-500 dark:text-slate-400">
              {t('graphqltoprotobuf.package_name', 'Package Name')}
            </label>
            <input
              id="package-name-input"
              type="text"
              value={packageName}
              onChange={(e) => setPackageName(e.target.value)}
              placeholder="model"
              className="w-full p-2.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl outline-none focus:ring-2 focus:ring-indigo-500 text-sm font-mono text-slate-800 dark:text-slate-200"
            />
          </div>

          {/* Syntax Version */}
          <div className="space-y-1.5">
            <label htmlFor="syntax-version-select" className="text-xs font-bold text-slate-500 dark:text-slate-400">
              {t('graphqltoprotobuf.syntax_version', 'Protobuf Syntax')}
            </label>
            <select
              id="syntax-version-select"
              value={syntaxVersion}
              onChange={(e) => setSyntaxVersion(e.target.value as any)}
              className="w-full p-2.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl outline-none focus:ring-2 focus:ring-indigo-500 text-sm font-semibold"
            >
              <option value="proto3">proto3</option>
              <option value="proto2">proto2</option>
            </select>
          </div>

          {/* Field Casing */}
          <div className="space-y-1.5">
            <label htmlFor="casing-mode-select" className="text-xs font-bold text-slate-500 dark:text-slate-400">
              {t('graphqltoprotobuf.casing_mode', 'Field Casing')}
            </label>
            <select
              id="casing-mode-select"
              value={casingMode}
              onChange={(e) => setCasingMode(e.target.value as any)}
              className="w-full p-2.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl outline-none focus:ring-2 focus:ring-indigo-500 text-sm font-semibold"
            >
              <option value="snake_case">snake_case</option>
              <option value="camelCase">camelCase</option>
              <option value="PascalCase">PascalCase</option>
              <option value="original">{t('graphqltoprotobuf.case_original', 'original')}</option>
            </select>
          </div>

          {/* Int Type */}
          <div className="space-y-1.5">
            <label htmlFor="int-type-select" className="text-xs font-bold text-slate-500 dark:text-slate-400">
              {t('graphqltoprotobuf.int_type', 'Int Mapping')}
            </label>
            <select
              id="int-type-select"
              value={intType}
              onChange={(e) => setIntType(e.target.value as any)}
              className="w-full p-2.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl outline-none focus:ring-2 focus:ring-indigo-500 text-sm font-semibold"
            >
              <option value="int32">int32</option>
              <option value="int64">int64</option>
            </select>
          </div>

          {/* Timestamp Type */}
          <div className="space-y-1.5">
            <label htmlFor="timestamp-type-select" className="text-xs font-bold text-slate-500 dark:text-slate-400">
              {t('graphqltoprotobuf.timestamp_type', 'DateTime Mapping')}
            </label>
            <select
              id="timestamp-type-select"
              value={timestampType}
              onChange={(e) => setTimestampType(e.target.value as any)}
              className="w-full p-2.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl outline-none focus:ring-2 focus:ring-indigo-500 text-sm font-semibold"
            >
              <option value="timestamp">Timestamp</option>
              <option value="string">string</option>
              <option value="int64">int64 (epoch)</option>
            </select>
          </div>
        </div>

        {/* Presets Bar */}
        <div className="pt-4 border-t border-slate-200 dark:border-slate-800 flex flex-wrap items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-amber-500" aria-hidden="true" />
            <span className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
              {t('graphqltoprotobuf.presets_title', 'Quick Start Presets:')}
            </span>
          </div>
          <div className="flex flex-wrap items-center gap-2">
            <button
              onClick={() => loadPreset('ecommerce')}
              aria-pressed={activePreset === 'ecommerce'}
              className={`px-3 py-1.5 text-xs font-bold rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none border ${
                activePreset === 'ecommerce'
                  ? 'bg-indigo-600 text-white border-indigo-600'
                  : 'bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700 hover:border-indigo-500 text-slate-700 dark:text-slate-300'
              }`}
            >
              {t('graphqltoprotobuf.preset_ecommerce', 'E-Commerce Catalog')}
            </button>
            <button
              onClick={() => loadPreset('user_auth')}
              aria-pressed={activePreset === 'user_auth'}
              className={`px-3 py-1.5 text-xs font-bold rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none border ${
                activePreset === 'user_auth'
                  ? 'bg-indigo-600 text-white border-indigo-600'
                  : 'bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700 hover:border-indigo-500 text-slate-700 dark:text-slate-300'
              }`}
            >
              {t('graphqltoprotobuf.preset_user_auth', 'User Management & Auth')}
            </button>
            <button
              onClick={() => loadPreset('social_feed')}
              aria-pressed={activePreset === 'social_feed'}
              className={`px-3 py-1.5 text-xs font-bold rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none border ${
                activePreset === 'social_feed'
                  ? 'bg-indigo-600 text-white border-indigo-600'
                  : 'bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700 hover:border-indigo-500 text-slate-700 dark:text-slate-300'
              }`}
            >
              {t('graphqltoprotobuf.preset_social_feed', 'Social Feed & Comments')}
            </button>
          </div>
        </div>
      </div>

      {/* Editor Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-indigo-500" aria-hidden="true" />
              <label htmlFor="graphql-proto-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('graphqltoprotobuf.graphql_input_label', 'GraphQL SDL Schema')}
              </label>
            </div>
            <div className="flex items-center gap-2">
              <Kbd modifier={null} className="hidden sm:inline-flex border-rose-200 dark:border-rose-800 text-rose-400 dark:bg-slate-900">Esc</Kbd>
              <button
                onClick={handleClear}
                disabled={!input && !output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 dark:hover:bg-rose-500/20 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-rose-500 focus-visible:outline-none"
              >
                <Trash2 className="w-3 h-3" aria-hidden="true" /> {t('common.clear')}
              </button>
            </div>
          </div>
          <textarea
            id="graphql-proto-input"
            ref={inputRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder={t('graphqltoprotobuf.placeholder_graphql', 'Paste GraphQL SDL schema here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none"
          />
        </div>

        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-emerald-500" aria-hidden="true" />
              <label htmlFor="proto-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('graphqltoprotobuf.output_label', 'Protobuf Schema (.proto)')}
              </label>
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                disabled={!output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-indigo-500 bg-indigo-50 dark:bg-indigo-500/10 hover:bg-indigo-100 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
              >
                <Download className="w-3 h-3" aria-hidden="true" /> {t('common.download')}
              </button>
              <button
                onClick={handleCopy}
                disabled={!output}
                className={`text-xs font-bold px-3 py-1.5 rounded-xl transition-all flex items-center gap-1 border focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-500/20'
                    : 'text-slate-500 bg-slate-100 dark:bg-slate-800 border-transparent hover:bg-slate-200 dark:hover:bg-slate-700 disabled:opacity-50 disabled:cursor-not-allowed'
                }`}
              >
                {copied ? <Check className="w-3 h-3" aria-hidden="true" /> : <Copy className="w-3 h-3" aria-hidden="true" />} {copied ? t('common.copied') : t('common.copy')}
                {!copied && input && <Kbd modifier={null} className="hidden sm:inline-flex w-4 h-4 bg-white/50 dark:bg-black/20 ml-1">C</Kbd>}
              </button>
            </div>
          </div>
          <textarea
            id="proto-output"
            value={output}
            readOnly
            placeholder={t('graphqltoprotobuf.placeholder_output', 'Generated .proto schema will appear here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400 resize-none"
          />
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold animate-in fade-in slide-in-from-top-2">
          <AlertCircle className="w-5 h-5" aria-hidden="true" />
          {error}
        </div>
      )}

      {/* Info Card */}
      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <Info className="w-6 h-6 text-indigo-500 mt-1 shrink-0" aria-hidden="true" />
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">{t('graphqltoprotobuf.about_title', 'About GraphQL SDL to Protocol Buffers Generator')}</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            {t(
              'graphqltoprotobuf.about_text',
              'Convert GraphQL Schema Definition Language (SDL) statements (types, interfaces, inputs, enums, unions) directly into Protocol Buffers (.proto) schema definitions supporting proto3 or proto2, customizable package names, scalar mappings, and field casing transformations.'
            )}
          </p>
        </div>
      </div>
    </div>
  );
}
