import { useState, useEffect, useCallback, useRef } from 'react';
import { FileCode, Copy, Check, Trash2, AlertCircle, Download, Info, Settings, Sparkles } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;

const RUST_RESERVED_KEYWORDS = new Set([
  'as', 'async', 'await', 'become', 'box', 'break', 'const', 'continue', 'crate', 'dyn',
  'else', 'enum', 'extern', 'false', 'fn', 'for', 'if', 'impl', 'in', 'let',
  'loop', 'match', 'mod', 'move', 'mut', 'pub', 'ref', 'return', 'self', 'Self',
  'static', 'struct', 'super', 'trait', 'true', 'type', 'unsafe', 'use', 'where', 'while'
]);

interface Preset {
  name: string;
  sdl: string;
}

const PRESETS: Preset[] = [
  {
    name: 'E-Commerce Catalog',
    sdl: `type Product {
  id: ID!
  name: String!
  description: String
  price: Float!
  inStock: Boolean!
  category: Category
  tags: [String!]!
}

enum Category {
  ELECTRONICS
  CLOTHING
  BOOKS
  HOME
}

input CreateProductInput {
  name: String!
  description: String
  price: Float!
  categoryId: ID!
  tags: [String!]
}`
  },
  {
    name: 'User Management & Auth',
    sdl: `type User {
  id: ID!
  username: String!
  email: String!
  role: UserRole!
  profile: UserProfile
  createdAt: String!
}

enum UserRole {
  ADMIN
  DEVELOPER
  MEMBER
  GUEST
}

type UserProfile {
  firstName: String
  lastName: String
  avatarUrl: String
  bio: String
}

input RegisterUserInput {
  username: String!
  email: String!
  role: UserRole
}`
  },
  {
    name: 'Social Feed & Comments',
    sdl: `type Post {
  id: ID!
  title: String!
  content: String!
  author: User!
  comments: [Comment!]!
  likeCount: Int!
  isPublished: Boolean!
}

type Comment {
  id: ID!
  text: String!
  authorName: String!
  createdAt: String!
}

union FeedItem = Post | Comment`
  }
];

const toSnakeCase = (str: string) => {
  return str
    .replace(/([A-Z])/g, '_$1')
    .toLowerCase()
    .replace(/^_/, '')
    .replace(/[^a-z0-9_]/g, '_');
};

const toCamelCase = (str: string) => {
  return str.replace(/_([a-z0-9])/gi, (_, letter) => letter.toUpperCase());
};

const toPascalCase = (str: string) => {
  return (
    str
      .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
      .replace(/[^a-zA-Z0-9]/g, ' ')
      .split(/\s+/)
      .filter(Boolean)
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join('') || 'AutoGenerated'
  );
};

const sanitizeRustIdentifier = (name: string): string => {
  let safe = name.replace(/[^a-zA-Z0-9_]/g, '_');
  if (/^[0-9]/.test(safe)) safe = 'r_' + safe;
  if (RUST_RESERVED_KEYWORDS.has(safe)) safe = 'r#' + safe;
  return safe || 'field';
};

export function GraphQLToRust({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const [input, setInput] = useState(initialData?.input || PRESETS[0].sdl);
  const [output, setOutput] = useState(initialData?.output || '');
  const [selectedPreset, setSelectedPreset] = useState<string | null>(initialData?.selectedPreset || PRESETS[0].name);
  const [casingMode, setCasingMode] = useState<'snake_case' | 'camelCase' | 'PascalCase' | 'original'>(initialData?.casingMode || 'snake_case');
  const [idType, setIdType] = useState<'String' | 'uuid::Uuid' | 'i64'>(initialData?.idType || 'String');
  const [intType, setIntType] = useState<'i32' | 'i64'>(initialData?.intType || 'i32');
  const [floatType, setFloatType] = useState<'f64' | 'f32'>(initialData?.floatType || 'f64');
  const [deriveSerde, setDeriveSerde] = useState(initialData?.deriveSerde ?? true);
  const [deriveDebug, setDeriveDebug] = useState(initialData?.deriveDebug ?? true);
  const [deriveClone, setDeriveClone] = useState(initialData?.deriveClone ?? true);
  const [addSerdeRename, setAddSerdeRename] = useState(initialData?.addSerdeRename ?? true);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  const inputRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    onStateChange?.({
      input,
      output,
      selectedPreset,
      casingMode,
      idType,
      intType,
      floatType,
      deriveSerde,
      deriveDebug,
      deriveClone,
      addSerdeRename
    });
  }, [input, output, selectedPreset, casingMode, idType, intType, floatType, deriveSerde, deriveDebug, deriveClone, addSerdeRename, onStateChange]);

  const handleConvert = useCallback(() => {
    try {
      if (!input.trim()) {
        setOutput('');
        setError('');
        return;
      }

      if (input.length > MAX_LENGTH) {
        setError(t('graphqltorust.error_max_length', { max: MAX_LENGTH.toLocaleString() }));
        setOutput('');
        return;
      }

      // Remove GraphQL comments
      const cleanInput = input.replace(/#.*$/gm, '');

      // Match type, input, interface, enum, union
      const typeRegex = /(type|input|interface|enum|union)\s+([A-Za-z0-9_]+)(?:\s+implements\s+[A-Za-z0-9_,\s]+)?\s*\{([^}]*)\}/g;
      const unionRegex = /union\s+([A-Za-z0-9_]+)\s*=\s*([A-Za-z0-9_|\s]+)/g;

      const codeBlocks: string[] = [];
      const parsedTypes = Object.create(null);

      const derivesList: string[] = [];
      if (deriveSerde) derivesList.push('Serialize', 'Deserialize');
      if (deriveDebug) derivesList.push('Debug');
      if (deriveClone) derivesList.push('Clone');
      derivesList.push('PartialEq');

      const deriveAttr = derivesList.length > 0 ? `#[derive(${derivesList.join(', ')})]` : '';

      const mapScalarType = (gqlType: string): string => {
        let isList = false;
        let isListNonNull = false;
        let isItemNonNull = false;

        let cleanType = gqlType.trim();

        if (cleanType.startsWith('[') && cleanType.endsWith(']')) {
          isList = true;
          cleanType = cleanType.slice(1, -1).trim();
        } else if (cleanType.startsWith('[') && cleanType.endsWith(']!')) {
          isList = true;
          isListNonNull = true;
          cleanType = cleanType.slice(1, -2).trim();
        }

        if (cleanType.endsWith('!')) {
          isItemNonNull = true;
          cleanType = cleanType.slice(0, -1).trim();
        }

        let rustBase = cleanType;
        if (cleanType === 'String') rustBase = 'String';
        else if (cleanType === 'Int') rustBase = intType;
        else if (cleanType === 'Float') rustBase = floatType;
        else if (cleanType === 'Boolean') rustBase = 'bool';
        else if (cleanType === 'ID') rustBase = idType;
        else rustBase = toPascalCase(cleanType);

        let finalType = isItemNonNull ? rustBase : `Option<${rustBase}>`;

        if (isList) {
          finalType = isListNonNull ? `Vec<${finalType}>` : `Option<Vec<${finalType}>>`;
        }

        return finalType;
      };

      let match;
      while ((match = typeRegex.exec(cleanInput)) !== null) {
        const kind = match[1];
        const rawName = match[2];
        const body = match[3];

        const structName = toPascalCase(rawName);
        parsedTypes[structName] = true;

        if (kind === 'enum') {
          const enumValues = body
            .split('\n')
            .map((line) => line.trim())
            .filter((line) => line && !line.startsWith('#'))
            .map((val) => {
              const cleanVal = val.split(/\s+/)[0];
              const safeVariant = toPascalCase(cleanVal);
              const renameAttr = addSerdeRename && deriveSerde ? `  #[serde(rename = "${cleanVal}")]\n` : '';
              return `${renameAttr}  ${safeVariant},`;
            });

          let enumCode = '';
          if (deriveAttr) enumCode += `${deriveAttr}\n`;
          if (deriveSerde && addSerdeRename) {
            enumCode += `#[serde(rename_all = "SCREAMING_SNAKE_CASE")]\n`;
          }
          enumCode += `pub enum ${structName} {\n${enumValues.join('\n')}\n}`;
          codeBlocks.push(enumCode);
        } else {
          // type, input, interface -> struct
          const fieldLines = body
            .split('\n')
            .map((line) => line.trim())
            .filter((line) => line && !line.startsWith('#') && line.includes(':'));

          const fields = fieldLines.map((line) => {
            const parts = line.split(':');
            const rawFieldName = parts[0].trim();
            const rawFieldType = parts.slice(1).join(':').trim();

            let fieldName = rawFieldName;
            if (casingMode === 'snake_case') fieldName = toSnakeCase(rawFieldName);
            else if (casingMode === 'camelCase') fieldName = toCamelCase(rawFieldName);
            else if (casingMode === 'PascalCase') fieldName = toPascalCase(rawFieldName);

            const safeFieldName = sanitizeRustIdentifier(fieldName);
            const rustType = mapScalarType(rawFieldType);

            let renameAttr = '';
            if (addSerdeRename && deriveSerde && (rawFieldName !== safeFieldName || casingMode !== 'original')) {
              renameAttr = `  #[serde(rename = "${rawFieldName}")]\n`;
            }

            return `${renameAttr}  pub ${safeFieldName}: ${rustType},`;
          });

          let structCode = '';
          if (deriveAttr) structCode += `${deriveAttr}\n`;
          if (deriveSerde && addSerdeRename && casingMode !== 'original') {
            structCode += `#[serde(rename_all = "${casingMode === 'snake_case' ? 'snake_case' : casingMode === 'camelCase' ? 'camelCase' : 'PascalCase'}")]\n`;
          }
          structCode += `pub struct ${structName} {\n${fields.join('\n')}\n}`;
          codeBlocks.push(structCode);
        }
      }

      // Parse union types
      while ((match = unionRegex.exec(cleanInput)) !== null) {
        const unionName = toPascalCase(match[1]);
        const members = match[2]
          .split('|')
          .map((m) => m.trim())
          .filter(Boolean)
          .map((m) => {
            const pascalMember = toPascalCase(m);
            return `  ${pascalMember}(${pascalMember}),`;
          });

        let unionCode = '';
        if (deriveAttr) unionCode += `${deriveAttr}\n`;
        if (deriveSerde) unionCode += `#[serde(untagged)]\n`;
        unionCode += `pub enum ${unionName} {\n${members.join('\n')}\n}`;
        codeBlocks.push(unionCode);
      }

      if (codeBlocks.length === 0) {
        setError(t('graphqltorust.no_types_found', 'No valid GraphQL types, inputs, enums or unions found.'));
        setOutput('');
        return;
      }

      let imports = '';
      if (deriveSerde) {
        imports += 'use serde::{Serialize, Deserialize};\n';
      }
      if (idType === 'uuid::Uuid') {
        imports += 'use uuid::Uuid;\n';
      }
      if (imports) imports += '\n';

      setOutput(imports + codeBlocks.join('\n\n'));
      setError('');
    } catch (e: any) {
      setError(t('graphqltorust.error_parsing', 'Error parsing GraphQL schema') + ': ' + e.message);
      setOutput('');
    }
  }, [input, casingMode, idType, intType, floatType, deriveSerde, deriveDebug, deriveClone, addSerdeRename, t]);

  useEffect(() => {
    handleConvert();
  }, [handleConvert]);

  const handleCopy = useCallback(() => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    toast.success(t('graphqltorust.toast_copied', 'Rust structs copied to clipboard!'));
    setTimeout(() => setCopied(false), 2000);
  }, [output, t]);

  const handleClear = useCallback(() => {
    setInput('');
    setOutput('');
    setError('');
    setSelectedPreset(null);
    toast.success(t('graphqltorust.toast_cleared', 'Inputs cleared'));
    setTimeout(() => inputRef.current?.focus(), 0);
  }, [t]);

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'models.rs';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(t('graphqltorust.toast_downloaded', 'Downloaded models.rs file'));
  };

  const handleApplyPreset = (preset: Preset) => {
    setInput(preset.sdl);
    setSelectedPreset(preset.name);
    toast.success(t('graphqltorust.preset_loaded', 'Loaded GraphQL preset: ') + preset.name);
    setTimeout(() => inputRef.current?.focus(), 0);
  };

  const handlersRef = useRef({ handleCopy, handleClear });
  useEffect(() => {
    handlersRef.current = { handleCopy, handleClear };
  }, [handleCopy, handleClear]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const activeElement = document.activeElement;
      const isEditable =
        activeElement instanceof HTMLInputElement ||
        activeElement instanceof HTMLTextAreaElement ||
        activeElement instanceof HTMLSelectElement ||
        activeElement?.getAttribute('contenteditable') === 'true';

      if (isEditable && e.key !== 'Escape') return;
      if (e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;

      if (e.key === 'Escape') {
        e.preventDefault();
        handlersRef.current.handleClear();
      } else if (e.key.toLowerCase() === 'c') {
        e.preventDefault();
        handlersRef.current.handleCopy();
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  return (
    <div className="max-w-6xl mx-auto space-y-8">
      {/* Options & Presets Bar */}
      <div className="bg-slate-50 dark:bg-slate-900/50 p-6 rounded-[2rem] border border-slate-200 dark:border-slate-800 space-y-6">
        <div className="flex items-center gap-2 px-1">
          <Settings className="w-4 h-4 text-indigo-500" />
          <h2 className="text-xs font-black uppercase tracking-widest text-slate-400">
            {t('graphqltorust.options_title', 'Rust Model Configuration')}
          </h2>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
          {/* Casing */}
          <div className="space-y-2">
            <label htmlFor="casing-select" className="text-xs font-bold text-slate-500 px-1">
              {t('graphqltorust.field_casing', 'Field Casing')}
            </label>
            <select
              id="casing-select"
              value={casingMode}
              onChange={(e) => setCasingMode(e.target.value as any)}
              className="w-full p-2.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl outline-none focus:ring-2 focus:ring-indigo-500/20 font-bold text-sm text-slate-700 dark:text-slate-200"
            >
              <option value="snake_case">snake_case (Rust Standard)</option>
              <option value="camelCase">camelCase</option>
              <option value="PascalCase">PascalCase</option>
              <option value="original">Original (As-Is)</option>
            </select>
          </div>

          {/* ID Scalar */}
          <div className="space-y-2">
            <label htmlFor="id-type-select" className="text-xs font-bold text-slate-500 px-1">
              {t('graphqltorust.id_type', 'GraphQL ID Scalar')}
            </label>
            <select
              id="id-type-select"
              value={idType}
              onChange={(e) => setIdType(e.target.value as any)}
              className="w-full p-2.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl outline-none focus:ring-2 focus:ring-indigo-500/20 font-bold text-sm text-slate-700 dark:text-slate-200"
            >
              <option value="String">String</option>
              <option value="uuid::Uuid">uuid::Uuid</option>
              <option value="i64">i64 (64-bit integer)</option>
            </select>
          </div>

          {/* Int Scalar */}
          <div className="space-y-2">
            <label htmlFor="int-type-select" className="text-xs font-bold text-slate-500 px-1">
              {t('graphqltorust.int_type', 'GraphQL Int Scalar')}
            </label>
            <select
              id="int-type-select"
              value={intType}
              onChange={(e) => setIntType(e.target.value as any)}
              className="w-full p-2.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl outline-none focus:ring-2 focus:ring-indigo-500/20 font-bold text-sm text-slate-700 dark:text-slate-200"
            >
              <option value="i32">i32 (32-bit)</option>
              <option value="i64">i64 (64-bit)</option>
            </select>
          </div>

          {/* Float Scalar */}
          <div className="space-y-2">
            <label htmlFor="float-type-select" className="text-xs font-bold text-slate-500 px-1">
              {t('graphqltorust.float_type', 'GraphQL Float Scalar')}
            </label>
            <select
              id="float-type-select"
              value={floatType}
              onChange={(e) => setFloatType(e.target.value as any)}
              className="w-full p-2.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl outline-none focus:ring-2 focus:ring-indigo-500/20 font-bold text-sm text-slate-700 dark:text-slate-200"
            >
              <option value="f64">f64 (Double precision)</option>
              <option value="f32">f32 (Single precision)</option>
            </select>
          </div>
        </div>

        {/* Derive Toggles */}
        <div className="flex flex-wrap gap-6 pt-2">
          <label className="flex items-center gap-2 text-xs font-bold text-slate-700 dark:text-slate-300 cursor-pointer">
            <input
              type="checkbox"
              checked={deriveSerde}
              onChange={(e) => setDeriveSerde(e.target.checked)}
              className="w-4 h-4 rounded text-indigo-600 focus:ring-indigo-500"
            />
            {t('graphqltorust.derive_serde', 'Derive Serde (Serialize, Deserialize)')}
          </label>

          <label className="flex items-center gap-2 text-xs font-bold text-slate-700 dark:text-slate-300 cursor-pointer">
            <input
              type="checkbox"
              checked={deriveDebug}
              onChange={(e) => setDeriveDebug(e.target.checked)}
              className="w-4 h-4 rounded text-indigo-600 focus:ring-indigo-500"
            />
            {t('graphqltorust.derive_debug', 'Derive Debug')}
          </label>

          <label className="flex items-center gap-2 text-xs font-bold text-slate-700 dark:text-slate-300 cursor-pointer">
            <input
              type="checkbox"
              checked={deriveClone}
              onChange={(e) => setDeriveClone(e.target.checked)}
              className="w-4 h-4 rounded text-indigo-600 focus:ring-indigo-500"
            />
            {t('graphqltorust.derive_clone', 'Derive Clone')}
          </label>

          <label className="flex items-center gap-2 text-xs font-bold text-slate-700 dark:text-slate-300 cursor-pointer">
            <input
              type="checkbox"
              checked={addSerdeRename}
              onChange={(e) => setAddSerdeRename(e.target.checked)}
              disabled={!deriveSerde}
              className="w-4 h-4 rounded text-indigo-600 focus:ring-indigo-500 disabled:opacity-50"
            />
            {t('graphqltorust.serde_rename', 'Serde Rename Attributes (#[serde(rename = "...")])')}
          </label>
        </div>

        {/* Presets */}
        <div className="pt-4 border-t border-slate-200 dark:border-slate-800 space-y-2">
          <div className="flex items-center gap-2">
            <Sparkles className="w-3.5 h-3.5 text-indigo-500" />
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">
              {t('graphqltorust.presets_title', 'Quick Start Presets')}
            </span>
          </div>
          <div className="flex flex-wrap gap-2">
            {PRESETS.map((p) => {
              const isSelected = selectedPreset === p.name;
              return (
                <button
                  key={p.name}
                  type="button"
                  onClick={() => handleApplyPreset(p)}
                  aria-pressed={isSelected}
                  className={`px-3 py-1.5 rounded-xl text-xs font-bold border transition-all shadow-sm ${
                    isSelected
                      ? 'bg-indigo-600 text-white border-indigo-600'
                      : 'bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700 hover:border-indigo-400 text-slate-700 dark:text-slate-300'
                  }`}
                >
                  {p.name}
                </button>
              );
            })}
          </div>
        </div>
      </div>

      {/* Editor Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-indigo-500" />
              <label htmlFor="graphql-rust-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                GraphQL SDL Schema
              </label>
            </div>
            <div className="flex items-center gap-2">
              <Kbd modifier={null} className="hidden sm:inline-flex border-rose-200 dark:border-rose-800 text-rose-400 dark:bg-slate-900">
                Esc
              </Kbd>
              <button
                type="button"
                onClick={handleClear}
                disabled={!input && !output}
                className="text-xs font-bold px-3 py-1 rounded-full text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 dark:hover:bg-rose-500/20 transition-all flex items-center gap-1 disabled:opacity-50 disabled:cursor-not-allowed focus-visible:ring-2 focus-visible:ring-rose-500 focus-visible:outline-none"
              >
                <Trash2 className="w-3 h-3" /> {t('common.clear', 'Clear')}
              </button>
            </div>
          </div>
          <textarea
            id="graphql-rust-input"
            ref={inputRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="type User { id: ID!, name: String! }"
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none"
          />
        </div>

        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-emerald-500" />
              <label htmlFor="rust-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                Rust Structs & Enums
              </label>
            </div>
            <div className="flex gap-2">
              <button
                type="button"
                onClick={handleDownload}
                disabled={!output}
                className="text-xs font-bold px-3 py-1 rounded-full text-indigo-500 bg-indigo-50 dark:bg-indigo-500/10 hover:bg-indigo-100 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
              >
                <Download className="w-3 h-3" /> {t('common.download', 'Download')}
              </button>
              <button
                type="button"
                onClick={handleCopy}
                disabled={!output}
                className={`text-xs font-bold px-3 py-1 rounded-full transition-all flex items-center gap-1 focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none border ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-200 dark:border-emerald-500/20'
                    : 'text-slate-500 bg-slate-100 dark:bg-slate-800 border-transparent hover:bg-slate-200'
                } disabled:opacity-50 disabled:cursor-not-allowed`}
              >
                {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />} {copied ? t('common.copied', 'Copied') : t('common.copy', 'Copy')}
                {!copied && <Kbd modifier={null} className="hidden sm:inline-flex w-4 h-4 bg-white/50 dark:bg-black/20 ml-1">C</Kbd>}
              </button>
            </div>
          </div>
          <textarea
            id="rust-output"
            value={output}
            readOnly
            placeholder={t('graphqltorust.output_placeholder', 'Generated Rust structs will appear here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400 resize-none"
          />
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold">
          <AlertCircle className="w-5 h-5" />
          {error}
        </div>
      )}

      {/* Info Card */}
      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <Info className="w-6 h-6 text-indigo-500 mt-1 shrink-0" />
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">{t('graphqltorust.about_title', 'About GraphQL SDL to Rust Conversion')}</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            {t(
              'graphqltorust.about_text',
              'Convert GraphQL SDL schema statements (types, inputs, interfaces, enums, unions) directly into strongly-typed Rust struct and enum definitions. Features Serde derives (Serialize, Deserialize), field casing transformations, Option<T> nullability, and keyword sanitization for async Rust web APIs (async-graphql, juniper).'
            )}
          </p>
        </div>
      </div>
    </div>
  );
}
