import { useState, useEffect, useCallback, useRef } from 'react';
import { FileCode, Copy, Check, Trash2, Download, Info } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;
const MAX_DEPTH = 20;

const JULIA_KEYWORDS = new Set([
  'baremodule', 'begin', 'break', 'catch', 'const', 'continue', 'do', 'else',
  'elseif', 'end', 'export', 'false', 'finally', 'for', 'function', 'global',
  'if', 'import', 'in', 'isa', 'let', 'local', 'macro', 'module', 'quote',
  'return', 'struct', 'true', 'try', 'type', 'using', 'while', 'where', 'mutable'
]);

type CasingMode = 'snake_case' | 'camelCase' | 'PascalCase' | 'original';
type StructKind = 'struct' | 'mutable struct';
type PackageStyle = 'structtypes' | 'json3' | 'plain';

export function JSONToJulia({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  const [input, setInput] = useState(initialData?.input || '');
  const [output, setOutput] = useState(initialData?.output || '');
  const [casing, setCasing] = useState<CasingMode>(initialData?.casing || 'snake_case');
  const [structKind, setStructKind] = useState<StructKind>(initialData?.structKind || 'struct');
  const [packageStyle, setPackageStyle] = useState<PackageStyle>(initialData?.packageStyle || 'structtypes');
  const [useUnionNothing, setUseUnionNothing] = useState(initialData?.useUnionNothing !== false);
  const [generateConstructors, setGenerateConstructors] = useState(initialData?.generateConstructors || false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    onStateChange?.({ input, output, casing, structKind, packageStyle, useUnionNothing, generateConstructors });
  }, [input, output, casing, structKind, packageStyle, useUnionNothing, generateConstructors, onStateChange]);

  const presets = {
    sensor: JSON.stringify({
      sensor_id: "SENS-8842",
      location: "Lab-402",
      is_active: true,
      battery_level: 98.5,
      readings_count: 1200,
      last_reading: {
        timestamp: "2025-09-25T14:30:00Z",
        temperature: 22.4,
        humidity: 45.2,
        pressure_hpa: 1013.25
      },
      tags: ["temperature", "indoor", "calibrated"]
    }, null, 2),

    user: JSON.stringify({
      id: 101,
      username: "alex_dev",
      email: "alex@example.org",
      is_admin: true,
      score: 95.8,
      profile: {
        first_name: "Alex",
        last_name: "Morgan",
        age: 29,
        avatar_url: null
      },
      roles: ["editor", "reviewer"]
    }, null, 2),

    order: JSON.stringify({
      order_id: "ORD-2025-99",
      customer_id: 4022,
      total_amount: 249.99,
      is_paid: true,
      items: [
        { product_id: 12, name: "Wireless Mouse", price: 29.99, quantity: 2 },
        { product_id: 45, name: "Mechanical Keyboard", price: 189.99, quantity: 1 }
      ],
      shipping_address: {
        street: "123 Tech Blvd",
        city: "San Francisco",
        zip_code: "94105",
        country: "USA"
      }
    }, null, 2)
  };

  const sanitizeJuliaIdentifier = (name: string, isField = false): string => {
    let clean = name.replace(/[^a-zA-Z0-9_]/g, '_');
    if (/^[0-9]/.test(clean)) clean = '_' + clean;
    if (isField && JULIA_KEYWORDS.has(clean)) {
      clean = clean + '_val';
    }
    return clean || 'item';
  };

  const toPascalCase = (str: string): string => {
    const clean = str.replace(/[^a-zA-Z0-9_]/g, ' ');
    return clean
      .split(/[\s_]+/)
      .filter(Boolean)
      .map(part => part.charAt(0).toUpperCase() + part.slice(1))
      .join('') || 'AutoGenerated';
  };

  const transformFieldName = (str: string, mode: CasingMode): string => {
    if (mode === 'original') return sanitizeJuliaIdentifier(str, true);
    const words = str.replace(/[^a-zA-Z0-9]/g, ' ').split(/\s+/).filter(Boolean);
    if (words.length === 0) return 'field_val';

    if (mode === 'snake_case') {
      return sanitizeJuliaIdentifier(words.map(w => w.toLowerCase()).join('_'), true);
    } else if (mode === 'camelCase') {
      const camel = words[0].toLowerCase() + words.slice(1).map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join('');
      return sanitizeJuliaIdentifier(camel, true);
    } else if (mode === 'PascalCase') {
      return sanitizeJuliaIdentifier(words.map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join(''), true);
    }
    return sanitizeJuliaIdentifier(str, true);
  };

  const inferJuliaType = (val: any, depth = 0, structsMap: Map<string, string>, currentClassName: string): string => {
    if (val === null || val === undefined) {
      return useUnionNothing ? 'Union{Nothing, Any}' : 'Any';
    }

    const valType = typeof val;
    if (valType === 'boolean') return 'Bool';
    if (valType === 'number') {
      return Number.isInteger(val) ? 'Int64' : 'Float64';
    }
    if (valType === 'string') return 'String';

    if (Array.isArray(val)) {
      if (val.length === 0) return 'Vector{Any}';
      const itemTypes = new Set<string>();
      val.forEach((item, idx) => {
        const itemStructName = currentClassName + 'Item';
        itemTypes.add(inferJuliaType(item, depth + 1, structsMap, itemStructName));
      });
      const typesArr = Array.from(itemTypes);
      if (typesArr.length === 1) {
        return `Vector{${typesArr[0]}}`;
      }
      return `Vector{Union{${typesArr.join(', ')}}}`;
    }

    if (valType === 'object') {
      if (depth >= MAX_DEPTH) return 'Dict{String, Any}';
      const subStructName = toPascalCase(currentClassName);
      generateJuliaStruct(val, subStructName, depth + 1, structsMap);
      return subStructName;
    }

    return 'Any';
  };

  const generateJuliaStruct = (obj: any, structName: string, depth: number, structsMap: Map<string, string>) => {
    if (!obj || typeof obj !== 'object' || Array.isArray(obj) || depth > MAX_DEPTH) return;

    if (structsMap.has(structName)) return;

    const fields: { name: string; origKey: string; type: string; isNullable: boolean }[] = [];
    const nameMapping: { [key: string]: string } = Object.create(null);

    Object.entries(obj).forEach(([key, value]) => {
      if (key === '__proto__' || key === 'constructor' || key === 'prototype') return;

      const fieldName = transformFieldName(key, casing);
      nameMapping[fieldName] = key;
      const isNull = value === null || value === undefined;

      let fieldType = inferJuliaType(value, depth, structsMap, toPascalCase(key));
      if (isNull && useUnionNothing && !fieldType.startsWith('Union{')) {
        fieldType = `Union{Nothing, ${fieldType}}`;
      }

      fields.push({
        name: fieldName,
        origKey: key,
        type: fieldType,
        isNullable: isNull
      });
    });

    let structBody = `${structKind} ${structName}\n`;
    fields.forEach(f => {
      structBody += `    ${f.name}::${f.type}\n`;
    });

    if (generateConstructors && fields.length > 0) {
      structBody += `\n    # Inner constructor\n`;
      structBody += `    function ${structName}(${fields.map(f => f.name).join(', ')})\n`;
      structBody += `        new(${fields.map(f => f.name).join(', ')})\n`;
      structBody += `    end\n`;
    }

    structBody += `end`;

    if (packageStyle === 'structtypes') {
      structBody += `\n\nStructTypes.StructType(::Type{${structName}}) = StructTypes.Struct()`;
      const needsNameMap = fields.some(f => f.name !== f.origKey);
      if (needsNameMap) {
        const pairs = fields.map(f => `:${f.name} => :${f.origKey}`).join(', ');
        structBody += `\nStructTypes.names(::Type{${structName}}) = (${pairs})`;
      }
    } else if (packageStyle === 'json3') {
      structBody += `\n\nJSON3.StructType(::Type{${structName}}) = JSON3.Struct()`;
    }

    structsMap.set(structName, structBody);
  };

  const convertToJulia = useCallback(() => {
    if (!input.trim()) {
      setOutput('');
      setError('');
      return;
    }

    if (input.length > MAX_LENGTH) {
      setError(t('error.max_length', { max: MAX_LENGTH.toLocaleString() }));
      setOutput('');
      return;
    }

    try {
      const parsed = JSON.parse(input);
      setError('');

      const structsMap = new Map<string, string>();
      const rootName = 'RootModel';

      if (Array.isArray(parsed)) {
        if (parsed.length > 0 && typeof parsed[0] === 'object' && parsed[0] !== null) {
          generateJuliaStruct(parsed[0], 'ItemModel', 0, structsMap);
        } else {
          const elemType = inferJuliaType(parsed[0], 0, structsMap, 'ItemModel');
          setOutput(`# Root dataset is an Array of ${elemType}\nconst ${rootName} = Vector{${elemType}}`);
          return;
        }
      } else if (typeof parsed === 'object' && parsed !== null) {
        generateJuliaStruct(parsed, rootName, 0, structsMap);
      } else {
        setOutput(`# Root dataset is a scalar value\nconst ${rootName} = ${inferJuliaType(parsed, 0, structsMap, 'Scalar')}`);
        return;
      }

      let fullOutput = '';
      if (packageStyle === 'structtypes') {
        fullOutput += `using StructTypes\n\n`;
      } else if (packageStyle === 'json3') {
        fullOutput += `using JSON3\n\n`;
      }

      fullOutput += Array.from(structsMap.values()).join('\n\n');
      setOutput(fullOutput);
    } catch (err: any) {
      setError(t('error.invalid_json') + ': ' + err.message);
      setOutput('');
    }
  }, [input, casing, structKind, packageStyle, useUnionNothing, generateConstructors, t]);

  useEffect(() => {
    convertToJulia();
  }, [convertToJulia]);

  const handleCopy = useCallback(() => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    toast.success(t('jsontojulia.copied', 'Julia struct code copied to clipboard!'));
    setTimeout(() => setCopied(false), 2000);
  }, [output, t]);

  const handleClear = useCallback(() => {
    setInput('');
    setOutput('');
    setError('');
    toast.success(t('jsontojulia.cleared', 'Cleared input and output!'));
    setTimeout(() => inputRef.current?.focus(), 0);
  }, [t]);

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'models.jl';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(t('jsontojulia.downloaded', 'Downloaded models.jl!'));
  };

  const loadPreset = (key: 'sensor' | 'user' | 'order') => {
    setInput(presets[key]);
    toast.success(t('jsontojulia.preset_loaded', 'Loaded Julia JSON preset!'));
  };

  const handlersRef = useRef({ handleClear, handleCopy, output });
  useEffect(() => {
    handlersRef.current = { handleClear, handleCopy, output };
  }, [handleClear, handleCopy, output]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const activeElement = document.activeElement;
      const isEditable =
        activeElement instanceof HTMLInputElement ||
        activeElement instanceof HTMLTextAreaElement ||
        activeElement instanceof HTMLSelectElement ||
        activeElement?.getAttribute('contenteditable') === 'true';

      if (isEditable && e.key !== 'Escape') return;

      if (e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;

      if (e.key === 'Escape') {
        e.preventDefault();
        handlersRef.current.handleClear();
      } else if (e.key.toLowerCase() === 'c') {
        if (handlersRef.current.output) {
          e.preventDefault();
          handlersRef.current.handleCopy();
        }
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  return (
    <div ref={containerRef} className="max-w-6xl mx-auto space-y-8 animate-in fade-in duration-500">
      <div className="flex flex-col md:flex-row gap-4 items-start md:items-center justify-between p-6 bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800 rounded-3xl">
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-xs font-bold text-slate-400 select-none mr-1">{t('jsontojulia.presets_title', 'Presets:')}</span>
          <button
            onClick={() => loadPreset('sensor')}
            className="text-xs font-bold px-3 py-1.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 text-slate-600 dark:text-slate-300 rounded-xl transition-all"
          >
            🔬 {t('jsontojulia.preset_sensor', 'Sensor Telemetry')}
          </button>
          <button
            onClick={() => loadPreset('user')}
            className="text-xs font-bold px-3 py-1.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 text-slate-600 dark:text-slate-300 rounded-xl transition-all"
          >
            👤 {t('jsontojulia.preset_user', 'User Profile')}
          </button>
          <button
            onClick={() => loadPreset('order')}
            className="text-xs font-bold px-3 py-1.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 text-slate-600 dark:text-slate-300 rounded-xl transition-all"
          >
            🛒 {t('jsontojulia.preset_order', 'E-Commerce Order')}
          </button>
        </div>

        <div className="flex flex-wrap items-center gap-4">
          <div className="flex items-center gap-2">
            <span className="text-xs font-bold text-slate-400 select-none">{t('jsontojulia.struct_kind', 'Struct Type:')}</span>
            <select
              value={structKind}
              onChange={(e) => setStructKind(e.target.value as StructKind)}
              className="text-xs font-bold px-3 py-1.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl outline-none focus:border-indigo-500"
            >
              <option value="struct">struct (Immutable)</option>
              <option value="mutable struct">mutable struct</option>
            </select>
          </div>

          <div className="flex items-center gap-2">
            <span className="text-xs font-bold text-slate-400 select-none">{t('jsontojulia.package_style', 'Serialization:')}</span>
            <select
              value={packageStyle}
              onChange={(e) => setPackageStyle(e.target.value as PackageStyle)}
              className="text-xs font-bold px-3 py-1.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl outline-none focus:border-indigo-500"
            >
              <option value="structtypes">StructTypes.jl</option>
              <option value="json3">JSON3.jl</option>
              <option value="plain">Plain Julia Struct</option>
            </select>
          </div>

          <div className="flex items-center gap-2">
            <span className="text-xs font-bold text-slate-400 select-none">{t('jsontojulia.casing', 'Casing:')}</span>
            <select
              value={casing}
              onChange={(e) => setCasing(e.target.value as CasingMode)}
              className="text-xs font-bold px-3 py-1.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl outline-none focus:border-indigo-500"
            >
              <option value="snake_case">snake_case (Julia Std)</option>
              <option value="camelCase">camelCase</option>
              <option value="PascalCase">PascalCase</option>
              <option value="original">original</option>
            </select>
          </div>
        </div>
      </div>

      <div className="flex flex-wrap items-center gap-6 px-2 text-xs font-bold text-slate-600 dark:text-slate-300">
        <label className="flex items-center gap-2 cursor-pointer select-none">
          <input
            type="checkbox"
            checked={useUnionNothing}
            onChange={(e) => setUseUnionNothing(e.target.checked)}
            className="w-4 h-4 rounded text-indigo-600 border-slate-300 focus:ring-indigo-500/20"
          />
          {t('jsontojulia.use_union_nothing', 'Union{Nothing, T} for nulls')}
        </label>

        <label className="flex items-center gap-2 cursor-pointer select-none">
          <input
            type="checkbox"
            checked={generateConstructors}
            onChange={(e) => setGenerateConstructors(e.target.checked)}
            className="w-4 h-4 rounded text-indigo-600 border-slate-300 focus:ring-indigo-500/20"
          />
          {t('jsontojulia.generate_constructors', 'Generate Inner Constructors')}
        </label>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-indigo-500" />
              <label htmlFor="json-julia-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">{t('jsontojulia.input_label', 'JSON Input Data')}</label>
            </div>
            <div className="flex items-center gap-2">
              <Kbd modifier={null} className="hidden sm:inline-flex border-rose-200 dark:border-rose-800 text-rose-400 dark:bg-slate-900">Esc</Kbd>
              <button
                onClick={handleClear}
                disabled={!input && !output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 dark:hover:bg-rose-500/20 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-rose-500 focus-visible:outline-none"
              >
                <Trash2 className="w-3 h-3" /> {t('common.clear')}
              </button>
            </div>
          </div>
          <textarea
            id="json-julia-input"
            ref={inputRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder={`{\n  "sensor_id": "SENS-101",\n  "temperature": 24.5,\n  "is_active": true\n}`}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none"
          />
        </div>

        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-emerald-500 animate-pulse" />
              <label htmlFor="julia-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">{t('jsontojulia.output_label', 'Julia Struct Definitions')}</label>
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                disabled={!output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-indigo-500 bg-indigo-50 dark:bg-indigo-500/10 hover:bg-indigo-100 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
              >
                <Download className="w-3 h-3" /> {t('common.download')}
              </button>
              <button
                onClick={handleCopy}
                disabled={!output}
                className={`text-xs font-bold px-3 py-1.5 rounded-xl transition-all flex items-center gap-1 border focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-500/20'
                    : 'text-slate-500 bg-slate-100 dark:bg-slate-800 border-transparent hover:bg-slate-200 dark:hover:bg-slate-700 disabled:opacity-50 disabled:cursor-not-allowed'
                }`}
              >
                {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />} {copied ? t('common.copied') : t('common.copy')}
                {!copied && input && <Kbd modifier={null} className="hidden sm:inline-flex w-4 h-4 bg-white/50 dark:bg-black/20 ml-1">C</Kbd>}
              </button>
            </div>
          </div>
          <textarea
            id="julia-output"
            value={output}
            readOnly
            placeholder={t('jsontojulia.placeholder_output', 'Generated Julia struct definitions will appear here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400 resize-none"
          />
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold animate-in fade-in slide-in-from-top-2">
          {error}
        </div>
      )}

      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <Info className="w-6 h-6 text-indigo-500 mt-1" />
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">{t('jsontojulia.about_title', 'About JSON to Julia Struct Converter')}</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            {t('jsontojulia.about_text', 'Convert JSON payloads into strongly-typed Julia struct or mutable struct definitions. Supports StructTypes.jl and JSON3.jl serialization bindings, property casing transformations (snake_case, camelCase, PascalCase), Union{Nothing, T} nullability, inner constructor generation, and Julia reserved keyword escaping.')}
          </p>
        </div>
      </div>
    </div>
  );
}
