import { useState, useEffect, useCallback, useRef } from 'react';
import { FileCode, Copy, Check, Trash2, AlertCircle, Download, Info, Sparkles } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;
const MAX_DEPTH = 20;

// Swift reserved keywords that require backtick escaping when used as identifiers
const SWIFT_KEYWORDS = new Set([
  'associatedtype', 'class', 'deinit', 'enum', 'extension', 'fileprivate', 'func', 'import',
  'init', 'inout', 'internal', 'let', 'open', 'operator', 'private', 'precedencegroup',
  'protocol', 'public', 'rethrows', 'static', 'struct', 'subscript', 'typealias', 'var',
  'break', 'case', 'catch', 'continue', 'default', 'defer', 'do', 'else', 'fallthrough',
  'for', 'guard', 'if', 'in', 'repeat', 'return', 'throw', 'switch', 'where', 'while',
  'any', 'as', 'await', 'false', 'is', 'nil', 'self', 'Self', 'super', 'true', 'try', 'type'
]);

const PRESETS = {
  user_profile: `{
  "id": 101,
  "first_name": "Sarah",
  "last_name": "Connor",
  "email": "sarah.connor@example.com",
  "is_active": true,
  "role": "admin",
  "created_at": "2024-01-15T08:30:00Z",
  "profile": {
    "avatar_url": "https://example.com/avatar.jpg",
    "bio": "Cybersecurity researcher & engineer",
    "followers_count": 1420
  },
  "tags": ["developer", "security", "swift"]
}`,
  ecommerce_order: `{
  "order_id": "ORD-98231",
  "total_amount": 149.99,
  "currency": "USD",
  "is_paid": true,
  "shipping_address": {
    "street": "123 Tech Boulevard",
    "city": "Cupertino",
    "postal_code": "95014",
    "country": "USA"
  },
  "items": [
    {
      "item_id": "ITEM-1",
      "title": "Wireless Mechanical Keyboard",
      "price": 119.99,
      "quantity": 1
    },
    {
      "item_id": "ITEM-2",
      "title": "USB-C Braided Cable",
      "price": 29.99,
      "quantity": 1
    }
  ]
}`,
  api_config: `{
  "app_name": "MultiTool Studio",
  "version": "2.4.0",
  "environment": "production",
  "max_upload_size_mb": 50,
  "features": {
    "dark_mode": true,
    "beta_access": false,
    "max_concurrent_tasks": 8
  },
  "endpoints": [
    "https://api.example.com/v1",
    "https://backup-api.example.com/v1"
  ]
}`
};

export function JSONToSwift({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const [input, setInput] = useState(initialData?.input || '');
  const [output, setOutput] = useState(initialData?.output || '');
  const [typeKind, setTypeKind] = useState<'struct' | 'class'>(initialData?.typeKind || 'struct');
  const [generateCodingKeys, setGenerateCodingKeys] = useState(initialData?.generateCodingKeys ?? true);
  const [makeOptional, setMakeOptional] = useState(initialData?.makeOptional ?? false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    onStateChange?.({ input, output, typeKind, generateCodingKeys, makeOptional });
  }, [input, output, typeKind, generateCodingKeys, makeOptional, onStateChange]);

  const toPascalCase = (str: string) => {
    let result = str
      .replace(/[^a-z0-9]/gi, ' ')
      .split(' ')
      .filter(Boolean)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');

    if (!result) return 'AutoGenerated';
    if (/^[0-9]/.test(result)) return 'Model' + result;
    if (SWIFT_KEYWORDS.has(result.toLowerCase())) return 'Model' + result;

    return result;
  };

  const toCamelCase = (str: string) => {
    const pascal = toPascalCase(str);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  };

  const formatSwiftField = (key: string): string => {
    let camel = toCamelCase(key);
    camel = camel.replace(/[`\r\n]/g, '');
    if (!camel) camel = 'property';

    const startsWithDigit = /^[0-9]/.test(camel);
    const isKeyword = SWIFT_KEYWORDS.has(camel);

    if (startsWithDigit || isKeyword) {
      return `\`${camel}\``;
    }
    return camel;
  };

  const handleConvert = useCallback(() => {
    try {
      if (!input.trim()) {
        setOutput('');
        setError('');
        return;
      }
      if (input.length > MAX_LENGTH) {
        setError(t('error.max_length', { max: MAX_LENGTH.toLocaleString() }));
        return;
      }
      const parsed = JSON.parse(input);
      const generatedTypes: string[] = [];
      const typeNames = new Set<string>();

      const getSwiftType = (val: any, fieldName: string, depth: number): string => {
        if (depth > MAX_DEPTH) return 'Any';
        if (val === null || val === undefined) return 'Any?';

        if (Array.isArray(val)) {
          const itemType = val.length > 0 ? getSwiftType(val[0], fieldName, depth + 1) : 'Any';
          return `[${itemType}]`;
        }

        if (typeof val === 'object') {
          let name = toPascalCase(fieldName);
          if (name === 'Root') name = 'RootObject';

          let finalName = name;
          let counter = 1;
          while (typeNames.has(finalName)) {
            finalName = name + counter++;
          }

          const fields = Object.entries(val).map(([key, value]) => {
            const swiftKey = formatSwiftField(key);
            let rawType = getSwiftType(value, key, depth + 1);
            if (makeOptional && !rawType.endsWith('?')) {
              rawType += '?';
            }
            return {
              originalKey: key,
              swiftKey,
              type: rawType
            };
          });

          let decl = `public ${typeKind} ${finalName}: Codable {\n`;
          fields.forEach(f => {
            decl += `    public let ${f.swiftKey}: ${f.type}\n`;
          });

          if (fields.length === 0) {
            decl += '    // No properties\n';
          }

          // CodingKeys enum generation for custom/snake_case mapping
          const needsCodingKeys = generateCodingKeys && fields.some(f => f.originalKey !== f.swiftKey.replace(/`/g, ''));
          if (needsCodingKeys && fields.length > 0) {
            decl += '\n    enum CodingKeys: String, CodingKey {\n';
            fields.forEach(f => {
              const cleanSwiftKey = f.swiftKey;
              if (f.originalKey !== cleanSwiftKey.replace(/`/g, '')) {
                decl += `        case ${cleanSwiftKey} = "${f.originalKey}"\n`;
              } else {
                decl += `        case ${cleanSwiftKey}\n`;
              }
            });
            decl += '    }\n';
          }

          decl += '}';

          generatedTypes.push(decl);
          typeNames.add(finalName);
          return finalName;
        }

        if (typeof val === 'string') return 'String';
        if (typeof val === 'number') return Number.isInteger(val) ? 'Int' : 'Double';
        if (typeof val === 'boolean') return 'Bool';

        return 'Any';
      };

      getSwiftType(parsed, 'Root', 0);

      let result = 'import Foundation\n\n';
      result += generatedTypes.reverse().join('\n\n');

      if (generatedTypes.length === 0) {
        const simpleType = getSwiftType(parsed, 'Root', 0);
        result = `import Foundation\n\npublic typealias RootObject = ${simpleType}`;
      }

      setOutput(result);
      setError('');
    } catch (e: any) {
      setError(t('error.invalid_json') + ': ' + e.message);
      setOutput('');
    }
  }, [input, typeKind, generateCodingKeys, makeOptional, t]);

  useEffect(() => {
    handleConvert();
  }, [handleConvert]);

  const handleCopy = useCallback(() => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    toast.success(t('jsontoswift.copied', 'Copied Swift code to clipboard!'));
    setTimeout(() => setCopied(false), 2000);
  }, [output, t]);

  const handleClear = useCallback(() => {
    setInput('');
    setOutput('');
    setError('');
    toast.success(t('jsontoswift.cleared', 'Inputs cleared!'));
    setTimeout(() => inputRef.current?.focus(), 0);
  }, [t]);

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/x-swift' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'Models.swift';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(t('jsontoswift.downloaded', 'Downloaded Models.swift!'));
  };

  const loadPreset = (presetKey: keyof typeof PRESETS) => {
    setInput(PRESETS[presetKey]);
    toast.success(t('jsontoswift.preset_loaded', 'Loaded Swift preset!'));
  };

  const handlersRef = useRef({ handleClear, handleCopy, output });
  useEffect(() => {
    handlersRef.current = { handleClear, handleCopy, output };
  }, [handleClear, handleCopy, output]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const activeElement = document.activeElement;
      const isEditable =
        activeElement instanceof HTMLInputElement ||
        activeElement instanceof HTMLTextAreaElement ||
        activeElement instanceof HTMLSelectElement ||
        activeElement?.getAttribute('contenteditable') === 'true';

      if (isEditable && e.key !== 'Escape') return;
      if (e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;

      if (e.key === 'Escape') {
        e.preventDefault();
        handlersRef.current.handleClear();
      } else if (e.key.toLowerCase() === 'c') {
        if (handlersRef.current.output) {
          e.preventDefault();
          handlersRef.current.handleCopy();
        }
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  return (
    <div className="max-w-6xl mx-auto space-y-8 animate-in fade-in duration-500">
      {/* Presets Bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 p-4 bg-slate-50 dark:bg-slate-900/50 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-amber-500" aria-hidden="true" />
          <span className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('jsontoswift.presets_title', 'Clickable Presets')}
          </span>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={() => loadPreset('user_profile')}
            className="px-3 py-1.5 text-xs font-bold bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
          >
            {t('jsontoswift.preset_user', 'User Profile')}
          </button>
          <button
            onClick={() => loadPreset('ecommerce_order')}
            className="px-3 py-1.5 text-xs font-bold bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
          >
            {t('jsontoswift.preset_order', 'E-Commerce Order')}
          </button>
          <button
            onClick={() => loadPreset('api_config')}
            className="px-3 py-1.5 text-xs font-bold bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
          >
            {t('jsontoswift.preset_api', 'API Config & Settings')}
          </button>
        </div>
      </div>

      {/* Options Panel */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 p-5 bg-white dark:bg-slate-900/60 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="space-y-1.5">
          <label htmlFor="swift-type-kind" className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('jsontoswift.type_kind_label', 'Swift Type Construct')}
          </label>
          <select
            id="swift-type-kind"
            value={typeKind}
            onChange={(e) => setTypeKind(e.target.value as 'struct' | 'class')}
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="struct">struct (Value Type / Recommended)</option>
            <option value="class">class (Reference Type)</option>
          </select>
        </div>

        <div className="flex flex-col justify-center space-y-2 pt-2 sm:pt-4">
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={generateCodingKeys}
              onChange={(e) => setGenerateCodingKeys(e.target.checked)}
              className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
            />
            <span className="text-xs font-bold text-slate-700 dark:text-slate-300">
              {t('jsontoswift.generate_coding_keys', 'Generate CodingKeys Enum')}
            </span>
          </label>
        </div>

        <div className="flex flex-col justify-center space-y-2 pt-2 sm:pt-4">
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={makeOptional}
              onChange={(e) => setMakeOptional(e.target.checked)}
              className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
            />
            <span className="text-xs font-bold text-slate-700 dark:text-slate-300">
              {t('jsontoswift.make_optional', 'Mark Properties as Optional (?)')}
            </span>
          </label>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-indigo-500" aria-hidden="true" />
              <label htmlFor="json-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('common.input')} JSON
              </label>
            </div>
            <div className="flex items-center gap-2">
              <Kbd modifier={null} className="hidden sm:inline-flex border-rose-200 dark:border-rose-800 text-rose-400 dark:bg-slate-900">Esc</Kbd>
              <button
                onClick={handleClear}
                disabled={!input && !output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 dark:hover:bg-rose-500/20 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-rose-500 focus-visible:outline-none"
              >
                <Trash2 className="w-3 h-3" aria-hidden="true" /> {t('common.clear')}
              </button>
            </div>
          </div>
          <textarea
            id="json-input"
            ref={inputRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder='{"id": 1, "name": "John"}'
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none"
          />
        </div>

        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-emerald-500" aria-hidden="true" />
              <label htmlFor="swift-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('jsontoswift.output_label', 'Swift Codable Structs / Classes')}
              </label>
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                disabled={!output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-indigo-500 bg-indigo-50 dark:bg-indigo-500/10 hover:bg-indigo-100 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
              >
                <Download className="w-3 h-3" aria-hidden="true" /> {t('common.download')}
              </button>
              <button
                onClick={handleCopy}
                disabled={!output}
                className={`text-xs font-bold px-3 py-1.5 rounded-xl transition-all flex items-center gap-1 border focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-500/20'
                    : 'text-slate-500 bg-slate-100 dark:bg-slate-800 border-transparent hover:bg-slate-200 dark:hover:bg-slate-700 disabled:opacity-50 disabled:cursor-not-allowed'
                }`}
              >
                {copied ? <Check className="w-3 h-3" aria-hidden="true" /> : <Copy className="w-3 h-3" aria-hidden="true" />} {copied ? t('common.copied') : t('common.copy')}
                {!copied && input && <Kbd modifier={null} className="hidden sm:inline-flex w-4 h-4 bg-white/50 dark:bg-black/20 ml-1">C</Kbd>}
              </button>
            </div>
          </div>
          <textarea
            id="swift-output"
            value={output}
            readOnly
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400 resize-none"
          />
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold animate-in fade-in slide-in-from-top-2">
          <AlertCircle className="w-5 h-5" aria-hidden="true" />
          {error}
        </div>
      )}

      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <Info className="w-6 h-6 text-indigo-500 mt-1" aria-hidden="true" />
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">{t('jsontoswift.about_title', 'À propos de la conversion JSON en Swift')}</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            {t('jsontoswift.about_text', 'Cet outil génère des structures Swift conformes au protocole Codable à partir de vos données JSON. Il gère automatiquement les objets imbriqués, la génération de CodingKeys pour la conversion de snake_case vers camelCase et l’option d’utilisation de structs ou classes.')}
          </p>
        </div>
      </div>
    </div>
  );
}
