import { useState, useEffect, useCallback } from 'react';
import { FileCode, Copy, Check, Trash2, AlertCircle, Terminal, Download, Info } from 'lucide-react';
import { useTranslation } from 'react-i18next';

const MAX_LENGTH = 100000;
const MAX_DEPTH = 20;

interface PHPClass {
  name: string;
  fields: { name: string; type: string }[];
}

export function JSONToPHP({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const [input, setInput] = useState(initialData?.input || '');
  const [output, setOutput] = useState(initialData?.output || '');
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    onStateChange?.({ input, output });
  }, [input, output, onStateChange]);

  const toPascalCase = (str: string) => {
    return str
      .replace(/[^a-z0-9]/gi, ' ')
      .split(' ')
      .filter(Boolean)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('') || 'AutoGenerated';
  };

  const handleConvert = useCallback(() => {
    try {
      if (!input.trim()) {
        setOutput('');
        setError('');
        return;
      }
      if (input.length > MAX_LENGTH) {
        setError(t('error.max_length', { max: MAX_LENGTH.toLocaleString() }));
        return;
      }
      const parsed = JSON.parse(input);
      const classes: PHPClass[] = [];
      const classNames = new Set<string>();

      const getPHPType = (val: any, fieldName: string, depth: number): string => {
        if (depth > MAX_DEPTH) return 'mixed';
        if (val === null || val === undefined) return '?mixed';

        if (Array.isArray(val)) {
          return 'array';
        }

        if (typeof val === 'object') {
          let name = toPascalCase(fieldName);
          if (name === 'Root') name = 'RootObject';

          let finalName = name;
          let counter = 1;
          while (classNames.has(finalName)) {
            finalName = name + counter++;
          }

          const fields = Object.entries(val).map(([key, value]) => ({
            name: key,
            type: getPHPType(value, key, depth + 1),
          }));

          classes.push({ name: finalName, fields });
          classNames.add(finalName);
          return finalName;
        }

        if (typeof val === 'number') return Number.isInteger(val) ? 'int' : 'float';
        if (typeof val === 'boolean') return 'bool';
        if (typeof val === 'string') return 'string';

        return 'mixed';
      };

      getPHPType(parsed, 'Root', 0);

      let result = '<?php\n\n';
      result += classes.reverse().map(cls => {
        let str = `class ${cls.name}\n{\n`;
        cls.fields.forEach(f => {
          str += `    public ${f.type} $${f.name};\n`;
        });
        str += '}\n';
        return str;
      }).join('\n');

      if (classes.length === 0) {
        const simpleType = getPHPType(parsed, 'Root', 0);
        result = `<?php\n\n// RootObject type: ${simpleType}`;
      }

      setOutput(result);
      setError('');
    } catch (e: any) {
      setError(t('error.invalid_json') + ': ' + e.message);
      setOutput('');
    }
  }, [input, t]);

  useEffect(() => {
    handleConvert();
  }, [handleConvert]);

  const handleCopy = () => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleClear = () => {
    setInput('');
    setOutput('');
    setError('');
  };

  return (
    <div className="max-w-6xl mx-auto space-y-8">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-indigo-500" />
              <label htmlFor="json-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">{t('common.input')} JSON</label>
            </div>
            <button
              onClick={handleClear}
              className="text-xs font-bold px-3 py-1 rounded-full text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 transition-all flex items-center gap-1"
            >
              <Trash2 className="w-3 h-3" /> {t('common.clear')}
            </button>
          </div>
          <textarea
            id="json-input"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder='{"id": 1, "name": "John"}'
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed"
          />
        </div>

        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <Terminal className="w-4 h-4 text-emerald-500" />
              <label htmlFor="php-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">{t('common.output')} PHP</label>
            </div>
            <button
              onClick={handleCopy}
              disabled={!output}
              className={`text-xs font-bold px-3 py-1 rounded-full transition-all flex items-center gap-1 ${copied ? 'bg-emerald-50 text-emerald-600' : 'bg-slate-100 dark:bg-slate-800'}`}
            >
              {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />} {copied ? t('common.copied') : t('common.copy')}
            </button>
          </div>
          <textarea
            id="php-output"
            value={output}
            readOnly
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400"
          />
        </div>
      </div>
      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold">
          <AlertCircle className="w-5 h-5" />
          {error}
        </div>
      )}
    </div>
  );
}
