import { useState, useEffect, useCallback, useRef } from 'react';
import { Copy, Check, Trash2, Braces, AlertCircle, Info, Download, Terminal, Sparkles } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;
const MAX_DEPTH = 15;

type AnnotationType = 'none' | 'jackson' | 'gson';
type ConstructType = 'class' | 'record';
type CasingType = 'camelCase' | 'snake_case' | 'PascalCase' | 'original';

interface JavaClass {
  name: string;
  fields: { name: string; type: string; originalKey: string }[];
}

const JAVA_KEYWORDS = new Set([
  'abstract', 'assert', 'boolean', 'break', 'byte', 'case', 'catch', 'char', 'class', 'const',
  'continue', 'default', 'do', 'double', 'else', 'enum', 'extends', 'final', 'finally', 'float',
  'for', 'goto', 'if', 'implements', 'import', 'instanceof', 'int', 'interface', 'long', 'native',
  'new', 'package', 'private', 'protected', 'public', 'return', 'short', 'static', 'strictfp',
  'super', 'switch', 'synchronized', 'this', 'throw', 'throws', 'transient', 'try', 'void',
  'volatile', 'while', 'true', 'false', 'null', 'record'
]);

export function JSONToJava({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const [jsonInput, setJsonInput] = useState(initialData?.jsonInput || '');
  const [output, setOutput] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [constructType, setConstructType] = useState<ConstructType>(initialData?.constructType || 'class');
  const [annotation, setAnnotation] = useState<AnnotationType>(initialData?.annotation || 'none');
  const [casing, setCasing] = useState<CasingType>(initialData?.casing || 'camelCase');
  const [useLombok, setUseLombok] = useState(initialData?.useLombok ?? false);
  const [packageName, setPackageName] = useState(initialData?.packageName || 'com.example.model');

  useEffect(() => {
    onStateChange?.({ jsonInput, constructType, annotation, casing, useLombok, packageName });
  }, [jsonInput, constructType, annotation, casing, useLombok, packageName, onStateChange]);

  const PRESETS = {
    user: JSON.stringify({
      id: 101,
      user_name: "john_doe",
      email_address: "john@example.com",
      is_active: true,
      roles: ["ADMIN", "USER"],
      profile: {
        first_name: "John",
        last_name: "Doe",
        age: 30
      }
    }, null, 2),
    order: JSON.stringify({
      order_id: "ORD-9921",
      customer_id: 5401,
      total_amount: 149.99,
      status: "SHIPPED",
      items: [
        { item_id: 1, product_name: "Wireless Mouse", quantity: 2, unit_price: 24.99 },
        { item_id: 2, product_name: "Mechanical Keyboard", quantity: 1, unit_price: 99.99 }
      ]
    }, null, 2),
    config: JSON.stringify({
      app_name: "Toolbox API",
      version: "2.5.0",
      port: 8080,
      debug_mode: false,
      database: {
        host: "localhost",
        port: 5432,
        name: "production_db"
      }
    }, null, 2)
  };

  const toPascalCase = (str: string) => {
    return str
      .replace(/[^a-zA-Z0-9]/g, ' ')
      .split(' ')
      .filter(Boolean)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('') || 'AutoGenerated';
  };

  const formatFieldName = (str: string, style: CasingType): string => {
    if (style === 'original') return str;
    const pascal = toPascalCase(str);
    if (style === 'PascalCase') return pascal;
    if (style === 'snake_case') {
      return str
        .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
        .replace(/[^a-zA-Z0-9]+/g, '_')
        .toLowerCase();
    }
    // camelCase
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  };

  const escapeJavaString = (str: string) => {
    return str
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r')
      .replace(/\t/g, '\\t');
  };

  const generateJava = useCallback(() => {
    if (!jsonInput.trim()) {
      setOutput('');
      setError(null);
      return;
    }

    if (jsonInput.length > MAX_LENGTH) {
      setError(t('error.max_length', { max: MAX_LENGTH.toLocaleString() }));
      setOutput('');
      return;
    }

    try {
      const parsed = JSON.parse(jsonInput);
      const classes: JavaClass[] = [];
      const classNames = new Set<string>();

      const getJavaType = (val: any, fieldName: string, depth: number): string => {
        if (val === null || val === undefined) return 'Object';
        if (depth > MAX_DEPTH) return 'Object';

        if (Array.isArray(val)) {
          const itemType = val.length > 0 ? getJavaType(val[0], fieldName, depth + 1) : 'Object';
          return `List<${itemType}>`;
        }

        if (typeof val === 'object' && val !== null) {
          let className = toPascalCase(fieldName);
          if (className === 'Root') className = 'RootObject';
          if (className === 'List' || className === 'Object') className += 'Item';

          let finalName = className;
          let counter = 1;
          while (classNames.has(finalName)) {
            finalName = className + counter++;
          }

          const fields = Object.entries(val).map(([key, value]) => {
            let formattedName = formatFieldName(key, casing);
            if (JAVA_KEYWORDS.has(formattedName) || /^[0-9]/.test(formattedName)) {
              formattedName = '_' + formattedName;
            }
            return {
              name: formattedName,
              type: getJavaType(value, key, depth + 1),
              originalKey: key
            };
          });

          classes.push({ name: finalName, fields });
          classNames.add(finalName);
          return finalName;
        }

        if (typeof val === 'number') return Number.isInteger(val) ? 'Integer' : 'Double';
        if (typeof val === 'boolean') return 'Boolean';
        return 'String';
      };

      getJavaType(parsed, 'Root', 0);

      let finalOutput = '';
      if (packageName.trim()) {
        finalOutput += `package ${packageName.trim()};\n\n`;
      }

      if (annotation === 'jackson') {
        finalOutput += 'import com.fasterxml.jackson.annotation.JsonProperty;\n';
      } else if (annotation === 'gson') {
        finalOutput += 'import com.google.gson.annotations.SerializedName;\n';
      }

      finalOutput += 'import java.util.List;\n';
      if (useLombok && constructType === 'class') {
        finalOutput += 'import lombok.Data;\n';
      }
      finalOutput += '\n';

      classes.reverse().forEach((javaClass) => {
        if (constructType === 'record') {
          finalOutput += `public record ${javaClass.name}(\n`;
          const paramLines = javaClass.fields.map(field => {
            const escapedKey = escapeJavaString(field.originalKey);
            let annotationPrefix = '';
            if (annotation === 'jackson') {
              annotationPrefix = `@JsonProperty("${escapedKey}") `;
            } else if (annotation === 'gson') {
              annotationPrefix = `@SerializedName("${escapedKey}") `;
            }
            return `    ${annotationPrefix}${field.type} ${field.name}`;
          });
          finalOutput += paramLines.join(',\n') + '\n) {}\n\n';
        } else {
          if (useLombok) {
            finalOutput += '@Data\n';
          }
          finalOutput += `public class ${javaClass.name} {\n`;

          javaClass.fields.forEach(field => {
            const escapedKey = escapeJavaString(field.originalKey);
            if (annotation === 'jackson') {
              finalOutput += `    @JsonProperty("${escapedKey}")\n`;
            } else if (annotation === 'gson') {
              finalOutput += `    @SerializedName("${escapedKey}")\n`;
            }
            finalOutput += `    private ${field.type} ${field.name};\n`;
          });

          if (!useLombok) {
            javaClass.fields.forEach(field => {
              const capitalized = field.name.charAt(0).toUpperCase() + field.name.slice(1);
              finalOutput += `\n    public ${field.type} get${capitalized}() {\n`;
              finalOutput += `        return ${field.name};\n`;
              finalOutput += `    }\n`;
              finalOutput += `\n    public void set${capitalized}(${field.type} ${field.name}) {\n`;
              finalOutput += `        this.${field.name} = ${field.name};\n`;
              finalOutput += `    }\n`;
            });
          }

          finalOutput += '}\n\n';
        }
      });

      setOutput(finalOutput.trim());
      setError(null);
    } catch (e) {
      setError(t('error.invalid_json'));
      setOutput('');
    }
  }, [jsonInput, constructType, annotation, casing, useLombok, packageName, t]);

  useEffect(() => {
    generateJava();
  }, [generateJava]);

  const handleCopy = useCallback(() => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    toast.success(t('jsontojava.copied', 'Java code copied to clipboard!'));
    setTimeout(() => setCopied(false), 2000);
  }, [output, t]);

  const handleClear = useCallback(() => {
    setJsonInput('');
    setOutput('');
    setError(null);
    toast.success(t('jsontojava.cleared', 'Inputs cleared!'));
    setTimeout(() => inputRef.current?.focus(), 0);
  }, [t]);

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = constructType === 'record' ? 'JavaRecords.java' : 'JavaClasses.java';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(t('common.downloaded', 'Downloaded Java file!'));
  };

  const loadPreset = (presetKey: keyof typeof PRESETS) => {
    setJsonInput(PRESETS[presetKey]);
    toast.success(t('jsontojava.preset_loaded', 'Loaded JSON preset!'));
  };

  const handlersRef = useRef({ handleClear, handleCopy, output });
  useEffect(() => {
    handlersRef.current = { handleClear, handleCopy, output };
  }, [handleClear, handleCopy, output]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const activeElement = document.activeElement;
      const isEditable =
        activeElement instanceof HTMLInputElement ||
        activeElement instanceof HTMLTextAreaElement ||
        activeElement instanceof HTMLSelectElement ||
        activeElement?.getAttribute("contenteditable") === "true";

      if (isEditable && e.key !== 'Escape') return;

      if (e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;

      if (e.key === "Escape") {
        e.preventDefault();
        handlersRef.current.handleClear();
      } else if (e.key.toLowerCase() === "c") {
        if (handlersRef.current.output) {
          e.preventDefault();
          handlersRef.current.handleCopy();
        }
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, []);

  return (
    <div className="max-w-6xl mx-auto space-y-8 animate-in fade-in duration-500">
      {/* Presets Bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 p-4 bg-slate-50 dark:bg-slate-900/50 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-amber-500" aria-hidden="true" />
          <span className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('jsontojava.presets_title', 'Quick Start Presets:')}
          </span>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={() => loadPreset('user')}
            className="px-3 py-1.5 text-xs font-bold bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
          >
            {t('jsontojava.preset_user', 'User Profile')}
          </button>
          <button
            onClick={() => loadPreset('order')}
            className="px-3 py-1.5 text-xs font-bold bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
          >
            {t('jsontojava.preset_order', 'E-Commerce Order')}
          </button>
          <button
            onClick={() => loadPreset('config')}
            className="px-3 py-1.5 text-xs font-bold bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
          >
            {t('jsontojava.preset_config', 'API Config & Settings')}
          </button>
        </div>
      </div>

      {/* Options Panel */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 p-5 bg-white dark:bg-slate-900/60 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="space-y-1.5">
          <label htmlFor="construct-type" className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('jsontojava.construct_kind', 'Construct Type')}
          </label>
          <select
            id="construct-type"
            value={constructType}
            onChange={(e) => setConstructType(e.target.value as ConstructType)}
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="class">POJO Class (public class)</option>
            <option value="record">Java 17+ Record (public record)</option>
          </select>
        </div>

        <div className="space-y-1.5">
          <label htmlFor="annotation-type" className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('jsontojava.annotation_kind', 'JSON Annotations')}
          </label>
          <select
            id="annotation-type"
            value={annotation}
            onChange={(e) => setAnnotation(e.target.value as AnnotationType)}
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="none">None</option>
            <option value="jackson">Jackson (@JsonProperty)</option>
            <option value="gson">Gson (@SerializedName)</option>
          </select>
        </div>

        <div className="space-y-1.5">
          <label htmlFor="casing-type" className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('jsontojava.casing_kind', 'Field Casing')}
          </label>
          <select
            id="casing-type"
            value={casing}
            onChange={(e) => setCasing(e.target.value as CasingType)}
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="camelCase">camelCase</option>
            <option value="snake_case">snake_case</option>
            <option value="PascalCase">PascalCase</option>
            <option value="original">Original</option>
          </select>
        </div>

        <div className="space-y-1.5">
          <label htmlFor="package-name" className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('jsontojava.package_name', 'Package Name')}
          </label>
          <input
            id="package-name"
            type="text"
            value={packageName}
            onChange={(e) => setPackageName(e.target.value)}
            placeholder="com.example.model"
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500"
          />
        </div>

        {constructType === 'class' && (
          <div className="flex items-center pt-2 col-span-full">
            <label className="flex items-center gap-2 text-xs font-bold text-slate-700 dark:text-slate-300 cursor-pointer">
              <input
                type="checkbox"
                checked={useLombok}
                onChange={(e) => setUseLombok(e.target.checked)}
                className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
              />
              {t('jsontojava.lombok', 'Lombok (@Data)')}
            </label>
          </div>
        )}
      </div>

      {/* Editor Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <Braces className="w-4 h-4 text-indigo-500" aria-hidden="true" />
              <label htmlFor="json-java-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('common.input')} (JSON)
              </label>
            </div>
            <div className="flex items-center gap-2">
              <Kbd modifier={null} className="hidden sm:inline-flex border-rose-200 dark:border-rose-800 text-rose-400 dark:bg-slate-900">Esc</Kbd>
              <button
                onClick={handleClear}
                disabled={!jsonInput && !output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 dark:hover:bg-rose-500/20 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-rose-500 focus-visible:outline-none"
              >
                <Trash2 className="w-3 h-3" aria-hidden="true" /> {t('common.clear')}
              </button>
            </div>
          </div>
          <textarea
            id="json-java-input"
            ref={inputRef}
            value={jsonInput}
            onChange={(e) => setJsonInput(e.target.value)}
            placeholder='{"name": "John", "age": 30, "address": {"city": "New York"}}'
            className={`w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border ${error ? 'border-rose-500' : 'border-slate-200 dark:border-slate-800'} rounded-3xl outline-none focus:ring-2 ${error ? 'focus:ring-rose-500/20' : 'focus:ring-indigo-500/20'} transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none`}
          />
        </div>

        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <Terminal className="w-4 h-4 text-emerald-500" aria-hidden="true" />
              <label htmlFor="java-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('jsontojava.output_label', 'Java Code Output')}
              </label>
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                disabled={!output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-indigo-500 bg-indigo-50 dark:bg-indigo-500/10 hover:bg-indigo-100 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
              >
                <Download className="w-3 h-3" aria-hidden="true" /> {t('common.download')}
              </button>
              <button
                onClick={handleCopy}
                disabled={!output}
                className={`text-xs font-bold px-3 py-1.5 rounded-xl transition-all flex items-center gap-1 border focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-500/20'
                    : 'text-slate-500 bg-slate-100 dark:bg-slate-800 border-transparent hover:bg-slate-200 dark:hover:bg-slate-700 disabled:opacity-50 disabled:cursor-not-allowed'
                }`}
              >
                {copied ? <Check className="w-3 h-3" aria-hidden="true" /> : <Copy className="w-3 h-3" aria-hidden="true" />} {copied ? t('common.copied') : t('common.copy')}
                {!copied && jsonInput && <Kbd modifier={null} className="hidden sm:inline-flex w-4 h-4 bg-white/50 dark:bg-black/20 ml-1">C</Kbd>}
              </button>
            </div>
          </div>
          <textarea
            id="java-output"
            value={output}
            readOnly
            placeholder={t('jsontojava.placeholder_output', 'Java class definitions will appear here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400 resize-none"
          />
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold animate-in fade-in slide-in-from-top-2">
          <AlertCircle className="w-5 h-5" aria-hidden="true" />
          {error}
        </div>
      )}

      {/* Info */}
      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <Info className="w-6 h-6 text-indigo-500 mt-1" aria-hidden="true" />
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">{t('jsontojava.about_title', 'About JSON to Java Conversion')}</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            {t('jsontojava.about_text', 'Convert JSON objects into strongly-typed Java POJO classes or Java 17+ Records. Supports Jackson, Gson annotations, Lombok @Data, field casing options, and custom packages.')}
          </p>
        </div>
      </div>
    </div>
  );
}
