import { useState, useEffect, useCallback, useRef } from 'react';
import { Database, Copy, Check, Trash2, FileCode, AlertCircle, Info, Download } from 'lucide-react';
import { useTranslation } from 'react-i18next';

const MAX_LENGTH = 100000;
const MAX_DEPTH = 20;

export function JSONToAvro({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const [json, setJson] = useState(initialData?.json || '{\n  "id": 1,\n  "name": "John Doe",\n  "active": true,\n  "scores": [95, 88],\n  "address": {\n    "city": "New York",\n    "zip": "10001"\n  }\n}');
  const [schemaName, setSchemaName] = useState(initialData?.schemaName || 'User');
  const [namespace, setNamespace] = useState(initialData?.namespace || 'com.example');
  const [output, setOutput] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    onStateChange?.({ json, schemaName, namespace });
  }, [json, schemaName, namespace, onStateChange]);

  const inferAvroType = (val: any, fieldName: string, depth: number, recordNames: Set<string>): any => {
    if (depth > MAX_DEPTH) return "string";
    if (val === null) return ["null", "string"];

    if (Array.isArray(val)) {
      const itemType = val.length > 0 ? inferAvroType(val[0], fieldName + "Item", depth + 1, recordNames) : "string";
      return {
        type: "array",
        items: itemType
      };
    }

    if (typeof val === 'object') {
      let name = fieldName.charAt(0).toUpperCase() + fieldName.slice(1);
      let finalName = name;
      let counter = 1;
      while (recordNames.has(finalName)) {
        finalName = name + counter++;
      }
      recordNames.add(finalName);

      return {
        type: "record",
        name: finalName,
        fields: Object.entries(val).map(([key, value]) => ({
          name: key,
          type: inferAvroType(value, key, depth + 1, recordNames)
        }))
      };
    }

    if (typeof val === 'number') {
      if (Number.isInteger(val)) {
        return val > 2147483647 || val < -2147483648 ? "long" : "int";
      }
      return "double";
    }

    if (typeof val === 'boolean') return "boolean";

    return "string";
  };

  const generateAvro = useCallback(() => {
    if (!json.trim()) {
      setOutput('');
      setError(null);
      return;
    }

    if (json.length > MAX_LENGTH) {
      setError(t('error.max_length', { max: MAX_LENGTH.toLocaleString() }));
      setOutput('');
      return;
    }

    try {
      const parsed = JSON.parse(json);
      const recordNames = new Set<string>();

      const avroSchema = {
        type: "record",
        name: schemaName || "AutoGeneratedSchema",
        namespace: namespace || "com.example",
        fields: Object.entries(parsed).map(([key, value]) => ({
          name: key,
          type: inferAvroType(value, key, 1, recordNames)
        }))
      };

      setOutput(JSON.stringify(avroSchema, null, 2));
      setError(null);
    } catch (e: any) {
      setError(t('error.invalid_json') + ': ' + e.message);
      setOutput('');
    }
  }, [json, schemaName, namespace, t]);

  useEffect(() => {
    const timeout = setTimeout(generateAvro, 300);
    return () => clearTimeout(timeout);
  }, [generateAvro]);

  const handleCopy = () => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleClear = () => {
    setJson('');
    setOutput('');
    setError(null);
    textareaRef.current?.focus();
  };

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${schemaName || 'schema'}.avsc`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-6xl mx-auto space-y-8">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">
        {/* Input Section */}
        <div className="space-y-6">
          <div className="flex justify-between items-center px-1">
            <label htmlFor="avro-json-input" className="text-xs font-black uppercase tracking-widest text-slate-400 flex items-center gap-2">
              <FileCode className="w-4 h-4 text-indigo-500" /> {t('common.input')} JSON
            </label>
            <button
              onClick={handleClear}
              className="text-xs font-bold text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 px-3 py-1.5 rounded-xl flex items-center gap-1 transition-all"
            >
              <Trash2 className="w-3 h-3" /> {t('common.clear')}
            </button>
          </div>

          <div className="bg-white dark:bg-slate-900/40 p-6 rounded-3xl border border-slate-200 dark:border-slate-800 space-y-4">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="space-y-2">
                <label htmlFor="schema-name" className="text-xs font-bold text-slate-500 px-1">{t('json_avro.schema_name')}</label>
                <input
                  id="schema-name"
                  type="text"
                  value={schemaName}
                  onChange={(e) => setSchemaName(e.target.value)}
                  placeholder="User"
                  className="w-full p-3 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all dark:text-slate-300"
                />
              </div>
              <div className="space-y-2">
                <label htmlFor="namespace" className="text-xs font-bold text-slate-500 px-1">{t('json_avro.namespace')}</label>
                <input
                  id="namespace"
                  type="text"
                  value={namespace}
                  onChange={(e) => setNamespace(e.target.value)}
                  placeholder="com.example"
                  className="w-full p-3 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all dark:text-slate-300"
                />
              </div>
            </div>
          </div>

          <textarea
            id="avro-json-input"
            ref={textareaRef}
            value={json}
            onChange={(e) => setJson(e.target.value)}
            placeholder='{"id": 1, "name": "John"}'
            className="w-full h-[400px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none"
          />
        </div>

        {/* Output Section */}
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <label htmlFor="avro-output" className="text-xs font-black uppercase tracking-widest text-slate-400 flex items-center gap-2">
              <Database className="w-4 h-4 text-emerald-500" /> {t('json_avro.output_label')}
            </label>
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                disabled={!output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 hover:bg-slate-200 transition-all flex items-center gap-2 disabled:opacity-50"
              >
                <Download className="w-3.5 h-3.5" /> {t('common.download')}
              </button>
              <button
                onClick={handleCopy}
                disabled={!output}
                className={`text-xs font-bold px-4 py-1.5 rounded-xl transition-all border focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none flex items-center gap-2 ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-200'
                    : 'bg-white dark:bg-slate-800 text-indigo-600 dark:text-indigo-400 border-slate-200 dark:border-slate-700 hover:border-indigo-500/50'
                } disabled:opacity-50`}
              >
                {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                {copied ? t('common.copied') : t('common.copy')}
              </button>
            </div>
          </div>
          <textarea
            id="avro-output"
            readOnly
            value={output}
            placeholder="Avro schema will appear here..."
            className="w-full h-[555px] p-6 bg-slate-900 border border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-300 resize-none"
          />
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold animate-in fade-in slide-in-from-top-2">
          <AlertCircle className="w-5 h-5" />
          {error}
        </div>
      )}

      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <Info className="w-6 h-6 text-indigo-500 mt-1" />
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">{t('json_avro.about_title')}</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            {t('json_avro.about_text')}
          </p>
        </div>
      </div>
    </div>
  );
}
