import { useState, useEffect, useCallback, useRef } from 'react';
import { FileCode, Copy, Check, Trash2, AlertCircle, Download, Info, Sparkles, Code, Braces } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;
const MAX_DEPTH = 20;

const KOTLIN_KEYWORDS = new Set([
  'as', 'break', 'class', 'continue', 'do', 'else', 'false', 'for', 'fun', 'if',
  'in', 'interface', 'is', 'null', 'object', 'package', 'return', 'super', 'this',
  'throw', 'true', 'try', 'typealias', 'val', 'var', 'when', 'while', 'by', 'catch',
  'constructor', 'delegate', 'dynamic', 'field', 'file', 'finally', 'get', 'import',
  'init', 'param', 'property', 'receiver', 'set', 'setparam', 'where', 'actual',
  'abstract', 'annotation', 'companion', 'const', 'crossinline', 'data', 'enum',
  'expect', 'external', 'final', 'infix', 'inline', 'inner', 'internal', 'lateinit',
  'noinline', 'open', 'operator', 'out', 'override', 'private', 'protected', 'public',
  'reified', 'sealed', 'suspend', 'tailrec', 'vararg'
]);

type Framework = 'kotlinx' | 'jackson' | 'moshi' | 'none';

interface Preset {
  nameKey: string;
  data: object;
}

const PRESETS: Preset[] = [
  {
    nameKey: 'jsontokotlin.preset_user',
    data: {
      id: 101,
      username: 'android_dev',
      email: 'dev@company.com',
      is_verified: true,
      profile: {
        full_name: 'Sarah Connor',
        avatar_url: 'https://example.com/sarah.jpg',
        created_at: '2025-02-20T10:15:00Z'
      },
      tags: ['mobile', 'kotlin', 'ui']
    }
  },
  {
    nameKey: 'jsontokotlin.preset_order',
    data: {
      order_number: 'ORD-99201',
      grand_total: 189.50,
      is_shipped: false,
      shipping_address: {
        street_address: '456 Market St',
        city: 'San Francisco',
        postal_code: '94105',
        country_code: 'US'
      },
      items: [
        { item_id: 'SKU-1', title: 'Android Kotlin Book', price: 49.50, qty: 1 },
        { item_id: 'SKU-2', title: 'Wireless Charger', price: 140.00, qty: 1 }
      ]
    }
  },
  {
    nameKey: 'jsontokotlin.preset_health',
    data: {
      status: 'UP',
      uptime_seconds: 864000,
      services: {
        database: { status: 'HEALTHY', latency_ms: 4 },
        cache_redis: { status: 'HEALTHY', latency_ms: 1 }
      },
      version: '2.4.0'
    }
  }
];

export function JSONToKotlin({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const [input, setInput] = useState(initialData?.input || '');
  const [output, setOutput] = useState(initialData?.output || '');
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  // Configuration options
  const [framework, setFramework] = useState<Framework>(initialData?.framework || 'kotlinx');
  const [casing, setCasing] = useState<'camelCase' | 'snake_case' | 'PascalCase' | 'original'>(
    initialData?.casing || 'camelCase'
  );
  const [packageName, setPackageName] = useState(initialData?.packageName || 'com.example.models');
  const [nullableFields, setNullableFields] = useState(initialData?.nullableFields ?? false);
  const [defaultValues, setDefaultValues] = useState(initialData?.defaultValues ?? false);

  useEffect(() => {
    onStateChange?.({
      input,
      output,
      framework,
      casing,
      packageName,
      nullableFields,
      defaultValues,
    });
  }, [input, output, framework, casing, packageName, nullableFields, defaultValues, onStateChange]);

  const toPascalCase = (str: string) => {
    return str
      .replace(/[^a-z0-9]/gi, ' ')
      .split(' ')
      .filter(Boolean)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('') || 'AutoGenerated';
  };

  const toSnakeCase = (str: string) => {
    return str
      .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
      .replace(/[^a-zA-Z0-9]/g, '_')
      .toLowerCase();
  };

  const toCamelCase = (str: string) => {
    const pascal = toPascalCase(str);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  };

  const formatPropName = (key: string): { propName: string; originalKey: string } => {
    let formatted = key;
    if (casing === 'camelCase') {
      formatted = toCamelCase(key);
    } else if (casing === 'snake_case') {
      formatted = toSnakeCase(key);
    } else if (casing === 'PascalCase') {
      formatted = toPascalCase(key);
    }

    let propName = formatted;
    if (/^[0-9]/.test(propName)) {
      propName = 'field' + propName;
    }

    if (KOTLIN_KEYWORDS.has(propName)) {
      propName = '`' + propName + '`';
    }

    return { propName: propName || 'unnamed', originalKey: key };
  };

  const escapeString = (str: string) => {
    return str.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  };

  const handleConvert = useCallback(() => {
    try {
      if (!input.trim()) {
        setOutput('');
        setError('');
        return;
      }
      if (input.length > MAX_LENGTH) {
        setError(t('error.max_length', { max: MAX_LENGTH.toLocaleString() }));
        return;
      }

      const parsed = JSON.parse(input);
      const dataClasses: string[] = [];
      const classNames = new Set<string>();

      const getKotlinType = (val: any, fieldName: string, depth: number): string => {
        if (depth > MAX_DEPTH) return 'Any';
        if (val === null || val === undefined) return 'Any?';

        if (Array.isArray(val)) {
          const itemType = val.length > 0 ? getKotlinType(val[0], fieldName, depth + 1) : 'Any';
          return `List<${itemType}>`;
        }

        if (typeof val === 'object') {
          let name = toPascalCase(fieldName);
          if (name === 'Root') name = 'RootObject';

          let finalName = name;
          let counter = 1;
          while (classNames.has(finalName)) {
            finalName = name + counter++;
          }

          const fields = Object.entries(val).map(([key, value]) => {
            const { propName, originalKey } = formatPropName(key);
            const rawType = getKotlinType(value, key, depth + 1);
            const isNullable = nullableFields || rawType.endsWith('?');
            const typeStr = (nullableFields && !rawType.endsWith('?')) ? `${rawType}?` : rawType;
            const defaultSuffix = (defaultValues && isNullable) ? ' = null' : '';

            let annotations = '';
            if (framework === 'kotlinx') {
              if (originalKey !== propName) {
                annotations = `    @SerialName("${escapeString(originalKey)}")\n`;
              }
            } else if (framework === 'jackson') {
              if (originalKey !== propName) {
                annotations = `    @JsonProperty("${escapeString(originalKey)}")\n`;
              }
            } else if (framework === 'moshi') {
              if (originalKey !== propName) {
                annotations = `    @Json(name = "${escapeString(originalKey)}")\n`;
              }
            }

            return `${annotations}    val ${propName}: ${typeStr}${defaultSuffix}`;
          });

          let classHeader = '';
          if (framework === 'kotlinx') {
            classHeader += '@Serializable\n';
          }
          classHeader += `data class ${finalName}(\n`;
          classHeader += fields.join(',\n');
          classHeader += '\n)';

          dataClasses.push(classHeader);
          classNames.add(finalName);
          return finalName;
        }

        if (typeof val === 'string') return 'String';
        if (typeof val === 'number') return Number.isInteger(val) ? 'Long' : 'Double';
        if (typeof val === 'boolean') return 'Boolean';

        return 'Any';
      };

      getKotlinType(parsed, 'Root', 0);

      let imports = '';
      if (framework === 'kotlinx') {
        imports = 'import kotlinx.serialization.Serializable\nimport kotlinx.serialization.SerialName\n\n';
      } else if (framework === 'jackson') {
        imports = 'import com.fasterxml.jackson.annotation.JsonProperty\n\n';
      } else if (framework === 'moshi') {
        imports = 'import com.squareup.moshi.Json\nimport com.squareup.moshi.JsonClass\n\n';
      }

      let result = '';
      if (packageName.trim()) {
        result += `package ${packageName.trim()}\n\n`;
      }
      result += imports;
      result += dataClasses.reverse().join('\n\n');

      if (dataClasses.length === 0) {
        const simpleType = getKotlinType(parsed, 'Root', 0);
        result += `typealias RootObject = ${simpleType}`;
      }

      setOutput(result.trim());
      setError('');
    } catch (e: any) {
      setError(t('error.invalid_json') + ': ' + e.message);
      setOutput('');
    }
  }, [input, framework, casing, packageName, nullableFields, defaultValues, t]);

  useEffect(() => {
    handleConvert();
  }, [handleConvert]);

  const handleCopy = useCallback(() => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    toast.success(t('jsontokotlin.toast_copied'));
    setTimeout(() => setCopied(false), 2000);
  }, [output, t]);

  const handleClear = useCallback(() => {
    setInput('');
    setOutput('');
    setError('');
    toast.success(t('jsontokotlin.toast_cleared'));
    setTimeout(() => {
      inputRef.current?.focus();
    }, 50);
  }, [t]);

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/x-kotlin' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'Models.kt';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(t('jsontokotlin.toast_downloaded'));
  };

  const loadPreset = (preset: Preset) => {
    setInput(JSON.stringify(preset.data, null, 2));
    toast.success(t('jsontokotlin.toast_preset_loaded'));
    setTimeout(() => {
      inputRef.current?.focus();
    }, 50);
  };

  const handlersRef = useRef({ handleCopy, handleClear });
  useEffect(() => {
    handlersRef.current = { handleCopy, handleClear };
  }, [handleCopy, handleClear]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const isEditable =
        document.activeElement?.tagName === 'INPUT' ||
        document.activeElement?.tagName === 'TEXTAREA' ||
        document.activeElement?.tagName === 'SELECT' ||
        document.activeElement?.getAttribute('contenteditable') === 'true';

      if (isEditable) return;
      if (e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;

      if (e.key === 'Escape') {
        e.preventDefault();
        handlersRef.current.handleClear();
      } else if (e.key.toLowerCase() === 'c') {
        e.preventDefault();
        handlersRef.current.handleCopy();
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  return (
    <div className="max-w-6xl mx-auto space-y-8">
      {/* Presets */}
      <div className="bg-slate-50 dark:bg-slate-900/50 p-6 rounded-[2rem] border border-slate-200 dark:border-slate-800 space-y-3">
        <div className="flex items-center gap-2 px-1">
          <Sparkles className="w-4 h-4 text-indigo-500" />
          <h3 className="text-xs font-black uppercase tracking-widest text-slate-400">{t('jsontokotlin.presets_title')}</h3>
        </div>
        <div className="flex flex-wrap gap-2">
          {PRESETS.map((preset, idx) => (
            <button
              key={idx}
              onClick={() => loadPreset(preset)}
              className="px-4 py-2 bg-white dark:bg-slate-800 hover:bg-indigo-50 dark:hover:bg-indigo-900/30 text-slate-700 dark:text-slate-300 hover:text-indigo-600 dark:hover:text-indigo-400 border border-slate-200 dark:border-slate-700 rounded-xl text-xs font-bold transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 outline-none"
            >
              {t(preset.nameKey)}
            </button>
          ))}
        </div>
      </div>

      {/* Options */}
      <div className="bg-slate-50 dark:bg-slate-900/50 p-6 rounded-[2rem] border border-slate-200 dark:border-slate-800 space-y-4">
        <h3 className="text-xs font-black uppercase tracking-widest text-slate-400 px-1">{t('jsontokotlin.options_title')}</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4 px-1">
          <div>
            <label htmlFor="kotlin-framework" className="text-xs font-bold text-slate-600 dark:text-slate-400 block mb-1">
              {t('jsontokotlin.framework_label')}
            </label>
            <select
              id="kotlin-framework"
              value={framework}
              onChange={(e) => setFramework(e.target.value as Framework)}
              className="w-full px-3 py-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-xs font-semibold text-slate-700 dark:text-slate-300 outline-none focus:ring-2 focus:ring-indigo-500"
            >
              <option value="kotlinx">kotlinx.serialization</option>
              <option value="jackson">Jackson</option>
              <option value="moshi">Moshi</option>
              <option value="none">None</option>
            </select>
          </div>

          <div>
            <label htmlFor="kotlin-casing" className="text-xs font-bold text-slate-600 dark:text-slate-400 block mb-1">
              {t('jsontokotlin.casing_label')}
            </label>
            <select
              id="kotlin-casing"
              value={casing}
              onChange={(e) => setCasing(e.target.value as any)}
              className="w-full px-3 py-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-xs font-semibold text-slate-700 dark:text-slate-300 outline-none focus:ring-2 focus:ring-indigo-500"
            >
              <option value="camelCase">{t('jsontokotlin.casing_camel')}</option>
              <option value="snake_case">{t('jsontokotlin.casing_snake')}</option>
              <option value="PascalCase">{t('jsontokotlin.casing_pascal')}</option>
              <option value="original">{t('jsontokotlin.casing_original')}</option>
            </select>
          </div>

          <div>
            <label htmlFor="kotlin-package" className="text-xs font-bold text-slate-600 dark:text-slate-400 block mb-1">
              {t('jsontokotlin.package_name')}
            </label>
            <input
              id="kotlin-package"
              type="text"
              value={packageName}
              onChange={(e) => setPackageName(e.target.value)}
              placeholder="com.example.models"
              className="w-full px-3 py-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-xs font-semibold text-slate-700 dark:text-slate-300 outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </div>

          <label className="flex items-center gap-2 cursor-pointer group mt-5">
            <input
              type="checkbox"
              checked={nullableFields}
              onChange={(e) => setNullableFields(e.target.checked)}
              className="w-4 h-4 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
            />
            <span className="text-xs font-medium text-slate-600 dark:text-slate-400 group-hover:text-slate-900 dark:group-hover:text-slate-200 transition-colors">
              {t('jsontokotlin.nullable_fields')}
            </span>
          </label>

          <label className="flex items-center gap-2 cursor-pointer group mt-5">
            <input
              type="checkbox"
              checked={defaultValues}
              onChange={(e) => setDefaultValues(e.target.checked)}
              className="w-4 h-4 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
            />
            <span className="text-xs font-medium text-slate-600 dark:text-slate-400 group-hover:text-slate-900 dark:group-hover:text-slate-200 transition-colors">
              {t('jsontokotlin.default_values')}
            </span>
          </label>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <Braces className="w-4 h-4 text-indigo-500" />
              <label htmlFor="json-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">{t('common.input')} JSON</label>
            </div>
            <div className="flex items-center gap-2">
              <Kbd modifier={null} className="hidden sm:inline-flex border-rose-200 dark:border-rose-800 text-rose-400 dark:bg-slate-900">Esc</Kbd>
              <button
                onClick={handleClear}
                disabled={!input && !output}
                className="text-xs font-bold px-3 py-1 rounded-full text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 transition-all flex items-center gap-1 disabled:opacity-50 disabled:cursor-not-allowed focus-visible:ring-2 focus-visible:ring-rose-500 focus-visible:outline-none"
              >
                <Trash2 className="w-3 h-3" /> {t('common.clear')}
              </button>
            </div>
          </div>
          <textarea
            id="json-input"
            ref={inputRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder='{"id": 1, "name": "Kotlin"}'
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none"
          />
        </div>

        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <Code className="w-4 h-4 text-emerald-500" />
              <label htmlFor="kotlin-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">{t('jsontokotlin.output_label')}</label>
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                disabled={!output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 hover:bg-slate-200 transition-all flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <Download className="w-3.5 h-3.5" /> {t('common.download')}
              </button>
              <button
                onClick={handleCopy}
                disabled={!output}
                title={`${t('common.copy')} (C)`}
                className={`text-xs font-bold px-4 py-1.5 rounded-xl transition-all flex items-center gap-2 border focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-200 dark:border-emerald-500/20'
                    : 'bg-white dark:bg-slate-800 text-indigo-600 dark:text-indigo-400 border-slate-200 dark:border-slate-700 hover:border-indigo-500/50 shadow-sm'
                } disabled:opacity-50 disabled:cursor-not-allowed`}
              >
                {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                {copied ? t('common.copied') : t('common.copy')}
                {!copied && <Kbd modifier={null} className="hidden sm:inline-flex w-4 h-4 border-indigo-200 dark:border-indigo-800 text-indigo-400 dark:bg-slate-900 ml-1">C</Kbd>}
              </button>
            </div>
          </div>
          <textarea
            id="kotlin-output"
            value={output}
            readOnly
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400 resize-none"
          />
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold animate-in fade-in slide-in-from-top-2">
          <AlertCircle className="w-5 h-5" />
          {error}
        </div>
      )}

      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <Info className="w-6 h-6 text-indigo-500 mt-1" />
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">{t('jsontokotlin.about_title')}</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            {t('jsontokotlin.about_text')}
          </p>
        </div>
      </div>
    </div>
  );
}
