import { useState, useEffect, useMemo, useCallback, useRef } from 'react';
import { Copy, Check, Trash2, Braces, FileCode, Info, AlertCircle, Download, RotateCcw, HelpCircle } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;
const MAX_DEPTH = 20;

// Sample JSON Schemas for the user
const SAMPLES: Record<string, string> = {
  user: JSON.stringify({
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "User",
    "type": "object",
    "properties": {
      "id": { "type": "integer" },
      "username": { "type": "string" },
      "email": { "type": "string", "format": "email" },
      "age": { "type": "number" },
      "isAdmin": { "type": "boolean" },
      "role": { "type": "string", "enum": ["admin", "user", "guest"] }
    },
    "required": ["id", "username", "email"]
  }, null, 2),
  product: JSON.stringify({
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Product",
    "type": "object",
    "properties": {
      "sku": { "type": "string" },
      "name": { "type": "string" },
      "price": { "type": "number" },
      "tags": {
        "type": "array",
        "items": { "type": "string" }
      },
      "dimensions": {
        "type": "object",
        "properties": {
          "width": { "type": "number" },
          "height": { "type": "number" },
          "depth": { "type": "number" }
        },
        "required": ["width", "height"]
      },
      "warehouse": { "$ref": "#/definitions/Location" }
    },
    "required": ["sku", "name", "price", "dimensions"],
    "definitions": {
      "Location": {
        "type": "object",
        "properties": {
          "id": { "type": "string" },
          "city": { "type": "string" },
          "country": { "type": "string" }
        },
        "required": ["id", "city"]
      }
    }
  }, null, 2),
  todos: JSON.stringify({
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "TodoList",
    "type": "object",
    "properties": {
      "owner": { "type": "string" },
      "items": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "title": { "type": "string" },
            "completed": { "type": "boolean" },
            "priority": { "type": "integer", "enum": [1, 2, 3] }
          },
          "required": ["title", "completed"]
        }
      }
    },
    "required": ["owner", "items"]
  }, null, 2)
};

export function JSONSchemaToTS({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t, i18n } = useTranslation();
  const [schemaInput, setSchemaInput] = useState(initialData?.schemaInput || '');
  const [outputType, setOutputType] = useState<'interface' | 'type' | 'zod' | 'typebox'>(initialData?.outputType || 'interface');
  const [rootName, setRootName] = useState(initialData?.rootName || 'Root');
  const [useExport, setUseExport] = useState(initialData?.useExport ?? true);
  const [isReadOnly, setIsReadOnly] = useState(initialData?.isReadOnly ?? false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Sync state with parent dashboard
  useEffect(() => {
    onStateChange?.({
      schemaInput,
      outputType,
      rootName,
      useExport,
      isReadOnly,
    });
  }, [schemaInput, outputType, rootName, useExport, isReadOnly, onStateChange]);

  const toPascalCase = (str: string): string => {
    return str
      .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
      .replace(/([A-Z])([A-Z][a-z])/g, '$1 $2')
      .replace(/[^a-zA-Z0-9]/g, ' ')
      .split(' ')
      .filter(Boolean)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('') || 'AutoGenerated';
  };

  const handleClear = useCallback(() => {
    setSchemaInput('');
    setError(null);
    toast.info(i18n.language === 'fr' ? 'Saisie effacée' : 'Input cleared');
    setTimeout(() => {
      textareaRef.current?.focus();
    }, 50);
  }, [i18n.language]);

  const loadSample = (key: string) => {
    setSchemaInput(SAMPLES[key]);
    setError(null);
    toast.success(i18n.language === 'fr' ? `Exemple "${key}" chargé` : `Loaded "${key}" sample`);
  };

  // Convert schema logic
  const convertedCode = useMemo(() => {
    if (!schemaInput.trim()) return '';
    if (schemaInput.length > MAX_LENGTH) {
      return `/* Error: Input length exceeds limit of ${MAX_LENGTH} characters. */`;
    }

    let parsedSchema: any;
    try {
      parsedSchema = JSON.parse(schemaInput);
      if (typeof parsedSchema !== 'object' || parsedSchema === null) {
        throw new Error('Schema must be a JSON object');
      }
    } catch (e: any) {
      return `/* Invalid JSON Schema: ${e.message} */`;
    }

    // Prepare helper to extract definitions safely (Prototype Pollution Mitigated)
    const definitions = Object.create(null);
    const rawDefs = parsedSchema.definitions || parsedSchema.$defs || {};
    Object.entries(rawDefs).forEach(([key, val]) => {
      if (key !== '__proto__' && key !== 'constructor' && key !== 'prototype') {
        definitions[key] = val;
      }
    });

    const subInterfaces: string[] = [];
    const generatedNames = new Set<string>();

    const resolveRef = (ref: string): { name: string; schema: any } | null => {
      if (!ref || typeof ref !== 'string') return null;
      // Match simple refs like #/definitions/Name or #/$defs/Name
      const parts = ref.split('/');
      const key = parts[parts.length - 1];
      if (key && definitions[key]) {
        return { name: toPascalCase(key), schema: definitions[key] };
      }
      return null;
    };

    // Main recursive generator
    const generateType = (schema: any, typeName: string, depth: number): string => {
      if (depth > MAX_DEPTH) {
        return 'any';
      }

      if (!schema || typeof schema !== 'object') {
        return 'any';
      }

      // Handle Reference
      if (schema.$ref) {
        const resolved = resolveRef(schema.$ref);
        if (resolved) {
          // Trigger generation of the definition interface/type if not already generated
          if (!generatedNames.has(resolved.name)) {
            generatedNames.add(resolved.name);
            const body = generateType(resolved.schema, resolved.name, depth + 1);
            if (outputType === 'interface' && resolved.schema.type === 'object') {
              subInterfaces.push(`${useExport ? 'export ' : ''}interface ${resolved.name} ${body}`);
            } else if (outputType === 'type') {
              subInterfaces.push(`${useExport ? 'export ' : ''}type ${resolved.name} = ${body};`);
            } else if (outputType === 'zod') {
              subInterfaces.push(`${useExport ? 'export ' : ''}const ${resolved.name}Schema = ${body};`);
            } else if (outputType === 'typebox') {
              subInterfaces.push(`${useExport ? 'export ' : ''}const ${resolved.name} = ${body};`);
            }
          }
          if (outputType === 'zod') {
            return `${resolved.name}Schema`;
          }
          return resolved.name;
        }
        return 'any';
      }

      // Handle Enum
      if (Array.isArray(schema.enum)) {
        if (outputType === 'zod') {
          return `z.enum([${schema.enum.map((v: any) => JSON.stringify(v)).join(', ')}])`;
        }
        if (outputType === 'typebox') {
          return `Type.Union([${schema.enum.map((v: any) => `Type.Literal(${JSON.stringify(v)})`).join(', ')}])`;
        }
        return schema.enum.map((v: any) => JSON.stringify(v)).join(' | ');
      }

      // Handle anyOf, allOf, oneOf
      const combinations = ['anyOf', 'allOf', 'oneOf'];
      for (const comb of combinations) {
        if (Array.isArray(schema[comb])) {
          const innerTypes = schema[comb].map((sub: any) => generateType(sub, typeName, depth + 1));
          if (outputType === 'zod') {
            if (comb === 'allOf') return `z.intersection(${innerTypes.join(', ')})`;
            return `z.union([${innerTypes.join(', ')}])`;
          }
          if (outputType === 'typebox') {
            if (comb === 'allOf') return `Type.Intersect([${innerTypes.join(', ')}])`;
            return `Type.Union([${innerTypes.join(', ')}])`;
          }
          const separator = comb === 'allOf' ? ' & ' : ' | ';
          return `(${innerTypes.join(separator)})`;
        }
      }

      // Handle basic types or custom structures
      const schemaType = schema.type;

      if (schemaType === 'object') {
        const props = schema.properties || {};
        const requiredFields = Array.isArray(schema.required) ? schema.required : [];

        if (outputType === 'zod') {
          let code = 'z.object({\n';
          Object.entries(props).forEach(([key, val]: [string, any]) => {
            if (key === '__proto__' || key === 'constructor' || key === 'prototype') return;
            const subName = toPascalCase(key);
            let propType = generateType(val, subName, depth + 1);
            const isReq = requiredFields.includes(key);
            if (!isReq) {
              propType += '.optional()';
            }
            code += `  ${key}: ${propType},\n`;
          });
          code += '})';
          return code;
        }

        if (outputType === 'typebox') {
          let code = 'Type.Object({\n';
          Object.entries(props).forEach(([key, val]: [string, any]) => {
            if (key === '__proto__' || key === 'constructor' || key === 'prototype') return;
            const subName = toPascalCase(key);
            let propType = generateType(val, subName, depth + 1);
            const isReq = requiredFields.includes(key);
            if (!isReq) {
              propType = `Type.Optional(${propType})`;
            }
            code += `  ${key}: ${propType},\n`;
          });
          code += '})';
          return code;
        }

        // TypeScript Interface / Type literal
        let code = '{\n';
        Object.entries(props).forEach(([key, val]: [string, any]) => {
          if (key === '__proto__' || key === 'constructor' || key === 'prototype') return;
          const subName = toPascalCase(key);
          const isReq = requiredFields.includes(key);
          const isRead = isReadOnly ? 'readonly ' : '';
          const isOpt = !isReq ? '?' : '';
          const propType = generateType(val, subName, depth + 1);
          code += `  ${isRead}${key}${isOpt}: ${propType};\n`;
        });
        code += '}';
        return code;
      }

      if (schemaType === 'array') {
        const items = schema.items || {};
        const itemType = generateType(items, `${typeName}Item`, depth + 1);
        if (outputType === 'zod') {
          return `z.array(${itemType})`;
        }
        if (outputType === 'typebox') {
          return `Type.Array(${itemType})`;
        }
        return `Array<${itemType}>`;
      }

      // Primitives
      switch (schemaType) {
        case 'string':
          if (outputType === 'zod') return 'z.string()';
          if (outputType === 'typebox') return 'Type.String()';
          return 'string';
        case 'number':
        case 'integer':
          if (outputType === 'zod') return 'z.number()';
          if (outputType === 'typebox') return 'Type.Number()';
          return 'number';
        case 'boolean':
          if (outputType === 'zod') return 'z.boolean()';
          if (outputType === 'typebox') return 'Type.Boolean()';
          return 'boolean';
        case 'null':
          if (outputType === 'zod') return 'z.null()';
          if (outputType === 'typebox') return 'Type.Null()';
          return 'null';
        default:
          if (outputType === 'zod') return 'z.any()';
          if (outputType === 'typebox') return 'Type.Any()';
          return 'any';
      }
    };

    // Generate main type body
    const rootPascal = toPascalCase(parsedSchema.title || rootName || 'Root');
    const mainTypeBody = generateType(parsedSchema, rootPascal, 0);

    // Assembly output
    let finalCode = '';
    const exp = useExport ? 'export ' : '';

    if (outputType === 'interface') {
      if (parsedSchema.type === 'object') {
        finalCode += `${exp}interface ${rootPascal} ${mainTypeBody}\n\n`;
      } else {
        finalCode += `${exp}type ${rootPascal} = ${mainTypeBody};\n\n`;
      }
    } else if (outputType === 'type') {
      finalCode += `${exp}type ${rootPascal} = ${mainTypeBody};\n\n`;
    } else if (outputType === 'zod') {
      finalCode += `${exp}const ${rootPascal}Schema = ${mainTypeBody};\n\n`;
    } else if (outputType === 'typebox') {
      finalCode += `${exp}const ${rootPascal} = ${mainTypeBody};\n\n`;
    }

    if (subInterfaces.length > 0) {
      finalCode += `/* Supporting definitions */\n` + subInterfaces.join('\n\n') + '\n';
    }

    return finalCode.trim();
  }, [schemaInput, outputType, rootName, useExport, isReadOnly]);

  // Handle local validation errors
  useEffect(() => {
    if (!schemaInput.trim()) {
      setError(null);
      return;
    }
    try {
      const parsed = JSON.parse(schemaInput);
      if (typeof parsed !== 'object' || parsed === null) {
        setError(i18n.language === 'fr' ? 'La saisie doit être un objet JSON valide' : 'Input must be a valid JSON object');
      } else {
        setError(null);
      }
    } catch (e: any) {
      setError(e.message);
    }
  }, [schemaInput, i18n.language]);

  const handleCopy = useCallback(() => {
    if (!convertedCode) return;
    navigator.clipboard.writeText(convertedCode);
    setCopied(true);
    toast.success(i18n.language === 'fr' ? 'Code copié dans le presse-papiers !' : 'Code copied to clipboard!');
    setTimeout(() => setCopied(false), 2000);
  }, [convertedCode, i18n.language]);

  const handleDownload = () => {
    if (!convertedCode) return;
    const extension = outputType === 'zod' || outputType === 'typebox' ? 'ts' : 'd.ts';
    const blob = new Blob([convertedCode], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${rootName || 'schema'}.${extension}`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success(i18n.language === 'fr' ? 'Téléchargement démarré' : 'Download started');
  };

  // Keyboard shortcut listener utilizing handlersRef wrapper
  const handlersRef = useRef({
    onClear: handleClear,
    onCopy: handleCopy,
  });

  useEffect(() => {
    handlersRef.current = {
      onClear: handleClear,
      onCopy: handleCopy,
    };
  }, [handleClear, handleCopy]);

  useEffect(() => {
    const handleGlobalKeyDown = (e: KeyboardEvent) => {
      const active = document.activeElement;
      const isTyping =
        active instanceof HTMLInputElement ||
        active instanceof HTMLTextAreaElement ||
        active instanceof HTMLSelectElement ||
        active?.getAttribute('contenteditable') === 'true';

      if (isTyping) {
        // If Escape is pressed while typing in our textarea, clear input & restore focus
        if (e.key === 'Escape' && active === textareaRef.current) {
          e.preventDefault();
          handlersRef.current.onClear();
        }
        return;
      }

      if (e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;

      if (e.key === 'Escape') {
        e.preventDefault();
        handlersRef.current.onClear();
      } else if (e.key.toLowerCase() === 'c') {
        e.preventDefault();
        handlersRef.current.onCopy();
      }
    };

    window.addEventListener('keydown', handleGlobalKeyDown);
    return () => window.removeEventListener('keydown', handleGlobalKeyDown);
  }, []);

  return (
    <div className="space-y-6 max-w-6xl mx-auto p-4">
      {/* Title Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b pb-4 dark:border-neutral-800">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <Braces className="h-6 w-6 text-indigo-500" />
            {t('jsonschemato_ts.title')}
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            {t('jsonschemato_ts.description')}
          </p>
        </div>

        {/* Preset Samples */}
        <div className="flex flex-wrap gap-2 items-center">
          <span className="text-xs font-semibold text-muted-foreground">
            {i18n.language === 'fr' ? 'Exemples :' : 'Samples:'}
          </span>
          <button
            onClick={() => loadSample('user')}
            className="px-2.5 py-1 text-xs rounded-md bg-indigo-50 text-indigo-700 hover:bg-indigo-100 dark:bg-indigo-950/40 dark:text-indigo-300 border border-indigo-200/50 dark:border-indigo-800/40 transition"
          >
            {i18n.language === 'fr' ? 'Utilisateur Simple' : 'Simple User'}
          </button>
          <button
            onClick={() => loadSample('product')}
            className="px-2.5 py-1 text-xs rounded-md bg-amber-50 text-amber-700 hover:bg-amber-100 dark:bg-amber-950/40 dark:text-amber-300 border border-amber-200/50 dark:border-amber-800/40 transition"
          >
            {i18n.language === 'fr' ? 'Produit (Références)' : 'Product (Refs)'}
          </button>
          <button
            onClick={() => loadSample('todos')}
            className="px-2.5 py-1 text-xs rounded-md bg-emerald-50 text-emerald-700 hover:bg-emerald-100 dark:bg-emerald-950/40 dark:text-emerald-300 border border-emerald-200/50 dark:border-emerald-800/40 transition"
          >
            {i18n.language === 'fr' ? 'Liste de Tâches' : 'Todo List'}
          </button>
        </div>
      </div>

      {/* Grid Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Side: Input & Options */}
        <div className="lg:col-span-5 space-y-6">
          <div className="rounded-xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-5 shadow-sm space-y-4">
            <div className="flex justify-between items-center">
              <label htmlFor="schema-json-input" className="text-sm font-semibold flex items-center gap-2">
                <FileCode className="h-4 w-4 text-neutral-500" />
                {t('jsonschemato_ts.input_label')}
              </label>
              <div className="flex items-center gap-2">
                <Kbd>Esc</Kbd>
                <button
                  onClick={handleClear}
                  disabled={!schemaInput}
                  className="p-1.5 text-neutral-500 hover:text-red-500 hover:bg-neutral-100 dark:hover:bg-neutral-800 rounded-md disabled:opacity-40 transition"
                  title={i18n.language === 'fr' ? 'Tout effacer' : 'Clear all'}
                >
                  <Trash2 className="h-4 w-4" />
                </button>
              </div>
            </div>

            <textarea
              id="schema-json-input"
              ref={textareaRef}
              value={schemaInput}
              onChange={e => setSchemaInput(e.target.value)}
              placeholder={t('jsonschemato_ts.placeholder')}
              className="w-full h-80 px-3 py-2 text-sm rounded-lg border border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-neutral-950 font-mono focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 resize-y"
            />

            {error && (
              <div className="p-3 bg-red-50 dark:bg-red-950/20 border border-red-200 dark:border-red-900/30 rounded-lg text-xs text-red-600 dark:text-red-400 flex items-start gap-2">
                <AlertCircle className="h-4 w-4 shrink-0 mt-0.5" />
                <span className="font-mono break-all">{error}</span>
              </div>
            )}
          </div>

          {/* Configuration Options */}
          <div className="rounded-xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-5 shadow-sm space-y-4">
            <h3 className="text-sm font-semibold border-b pb-2 dark:border-neutral-800">
              {t('jsonschemato_ts.options_title')}
            </h3>

            <div className="space-y-3">
              {/* Output Type Selector */}
              <div>
                <label htmlFor="output-type-select" className="text-xs font-medium text-muted-foreground block mb-1">
                  {t('jsonschemato_ts.output_format')}
                </label>
                <select
                  id="output-type-select"
                  value={outputType}
                  onChange={e => setOutputType(e.target.value as any)}
                  className="w-full text-sm rounded-md border border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-neutral-950 px-3 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-500/20"
                >
                  <option value="interface">{i18n.language === 'fr' ? 'Interface TypeScript' : 'TypeScript Interface'}</option>
                  <option value="type">{i18n.language === 'fr' ? 'Alias de Type TypeScript' : 'TypeScript Type Alias'}</option>
                  <option value="zod">{i18n.language === 'fr' ? 'Schéma Zod' : 'Zod Schema'}</option>
                  <option value="typebox">{i18n.language === 'fr' ? 'Schéma TypeBox' : 'TypeBox Schema'}</option>
                </select>
              </div>

              {/* Custom Root Name */}
              <div>
                <label htmlFor="root-name-input" className="text-xs font-medium text-muted-foreground block mb-1">
                  {t('jsonschemato_ts.root_name')}
                </label>
                <input
                  id="root-name-input"
                  type="text"
                  value={rootName}
                  onChange={e => setRootName(e.target.value)}
                  placeholder="Root"
                  className="w-full text-sm rounded-md border border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-neutral-950 px-3 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-500/20"
                />
              </div>

              {/* Boolean Toggles */}
              <div className="space-y-2 pt-2">
                <label className="flex items-center gap-3 cursor-pointer select-none">
                  <input
                    type="checkbox"
                    checked={useExport}
                    onChange={e => setUseExport(e.target.checked)}
                    className="rounded text-indigo-600 focus:ring-indigo-500 h-4 w-4 border-neutral-300 dark:border-neutral-700"
                  />
                  <span className="text-sm">
                    {t('jsonschemato_ts.export')}
                  </span>
                </label>

                {/* Read-Only toggle is only relevant for TS Interface/Type */}
                {(outputType === 'interface' || outputType === 'type') && (
                  <label className="flex items-center gap-3 cursor-pointer select-none">
                    <input
                      type="checkbox"
                      checked={isReadOnly}
                      onChange={e => setIsReadOnly(e.target.checked)}
                      className="rounded text-indigo-600 focus:ring-indigo-500 h-4 w-4 border-neutral-300 dark:border-neutral-700"
                    />
                    <span className="text-sm">
                      {t('jsonschemato_ts.readonly')}
                    </span>
                  </label>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Right Side: Output */}
        <div className="lg:col-span-7 space-y-6">
          <div className="rounded-xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-5 shadow-sm space-y-4 flex flex-col h-full min-h-[500px]">
            <div className="flex justify-between items-center">
              <span className="text-sm font-semibold flex items-center gap-2">
                <Braces className="h-4 w-4 text-emerald-500" />
                {t('jsonschemato_ts.output_label')}
              </span>
              <div className="flex items-center gap-2">
                <Kbd>C</Kbd>
                <button
                  onClick={handleCopy}
                  disabled={!convertedCode}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-md bg-indigo-600 hover:bg-indigo-700 text-white disabled:opacity-40 transition"
                >
                  {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
                  {copied ? (i18n.language === 'fr' ? 'Copié !' : 'Copied!') : (i18n.language === 'fr' ? 'Copier' : 'Copy')}
                </button>
                <button
                  onClick={handleDownload}
                  disabled={!convertedCode}
                  className="p-1.5 text-neutral-500 hover:text-indigo-600 hover:bg-neutral-100 dark:hover:bg-neutral-800 rounded-md disabled:opacity-40 transition"
                  title={i18n.language === 'fr' ? 'Télécharger' : 'Download'}
                >
                  <Download className="h-4 w-4" />
                </button>
              </div>
            </div>

            <pre className="flex-1 w-full p-4 rounded-lg bg-neutral-950 text-neutral-100 font-mono text-xs overflow-auto border border-neutral-800 min-h-[400px]">
              {convertedCode || (
                <span className="text-neutral-500 italic">
                  {i18n.language === 'fr'
                    ? '// Le code généré apparaîtra ici après saisie d\'un schéma JSON valide...'
                    : '// Generated code will appear here after entering a valid JSON Schema...'}
                </span>
              )}
            </pre>
          </div>
        </div>
      </div>

      {/* Interactive FAQ / About section */}
      <div className="rounded-xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-6 shadow-sm">
        <h2 className="text-base font-bold flex items-center gap-2 mb-3">
          <HelpCircle className="h-5 w-5 text-indigo-500" />
          {t('jsonschemato_ts.about_title')}
        </h2>
        <div className="text-sm text-muted-foreground space-y-2 leading-relaxed">
          <p>
            {t('jsonschemato_ts.about_text_1')}
          </p>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li>
              <strong>{i18n.language === 'fr' ? 'Structure saine :' : 'Safe Structures:'}</strong>{' '}
              {t('jsonschemato_ts.about_item_1')}
            </li>
            <li>
              <strong>{i18n.language === 'fr' ? 'Zod & TypeBox :' : 'Zod & TypeBox:'}</strong>{' '}
              {t('jsonschemato_ts.about_item_2')}
            </li>
            <li>
              <strong>{i18n.language === 'fr' ? 'Protection contre la pollution :' : 'Pollution Hardening:'}</strong>{' '}
              {t('jsonschemato_ts.about_item_3')}
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
}
