import { useState, useEffect, useCallback, useRef } from 'react';
import { FileCode, Copy, Check, Trash2, AlertCircle, Download, Info, Sparkles, Code, Braces } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;
const MAX_DEPTH = 20;

const RUST_KEYWORDS = new Set([
  'as', 'break', 'const', 'continue', 'crate', 'else', 'enum', 'extern', 'false', 'fn',
  'for', 'if', 'impl', 'in', 'let', 'loop', 'match', 'mod', 'move', 'mut', 'pub', 'ref',
  'return', 'self', 'Self', 'static', 'struct', 'super', 'trait', 'true', 'type', 'unsafe',
  'use', 'where', 'while', 'async', 'await', 'dyn', 'abstract', 'become', 'box', 'do',
  'final', 'macro', 'override', 'priv', 'typeof', 'unsized', 'virtual', 'yield', 'try'
]);

interface Preset {
  nameKey: string;
  data: object;
}

const PRESETS: Preset[] = [
  {
    nameKey: 'jsontorust.preset_user',
    data: {
      user_id: 1042,
      username: 'rustacean',
      email: 'alex@example.com',
      is_active: true,
      profile: {
        bio: 'Rust systems developer',
        avatar_url: 'https://example.com/avatar.png',
        created_at: '2025-01-15T12:00:00Z'
      },
      roles: ['admin', 'developer']
    }
  },
  {
    nameKey: 'jsontorust.preset_order',
    data: {
      order_id: 'ORD-2025-772',
      total_amount: 299.95,
      is_paid: true,
      items: [
        { product_id: 'P-100', name: 'Mechanical Keyboard', price: 149.99, quantity: 1 },
        { product_id: 'P-200', name: 'Ergonomic Mouse', price: 149.96, quantity: 1 }
      ],
      shipping_address: {
        street: '123 Tech Lane',
        city: 'Seattle',
        postal_code: '98101',
        country: 'USA'
      }
    }
  },
  {
    nameKey: 'jsontorust.preset_error',
    data: {
      error: {
        code: 404,
        message: 'Resource not found',
        details: ['Invalid ID provided', 'Entity does not exist in database'],
        timestamp: 1735689600
      },
      success: false
    }
  }
];

export function JSONToRust({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const [input, setInput] = useState(initialData?.input || '');
  const [output, setOutput] = useState(initialData?.output || '');
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  // Configuration options
  const [casing, setCasing] = useState<'snake_case' | 'camelCase' | 'PascalCase' | 'original'>(
    initialData?.casing || 'snake_case'
  );
  const [deriveClone, setDeriveClone] = useState(initialData?.deriveClone ?? true);
  const [derivePartialEq, setDerivePartialEq] = useState(initialData?.derivePartialEq ?? true);
  const [deriveDefault, setDeriveDefault] = useState(initialData?.deriveDefault ?? false);

  useEffect(() => {
    onStateChange?.({ input, output, casing, deriveClone, derivePartialEq, deriveDefault });
  }, [input, output, casing, deriveClone, derivePartialEq, deriveDefault, onStateChange]);

  const toPascalCase = (str: string) => {
    return str
      .replace(/[^a-z0-9]/gi, ' ')
      .split(' ')
      .filter(Boolean)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('') || 'AutoGenerated';
  };

  const toSnakeCase = (str: string) => {
    return str
      .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
      .replace(/[^a-zA-Z0-9]/g, '_')
      .toLowerCase();
  };

  const toCamelCase = (str: string) => {
    const pascal = toPascalCase(str);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  };

  const formatFieldName = (fieldName: string): { rustKey: string; renameAlias?: string } => {
    let formattedKey = fieldName;
    if (casing === 'snake_case') {
      formattedKey = toSnakeCase(fieldName);
    } else if (casing === 'camelCase') {
      formattedKey = toCamelCase(fieldName);
    } else if (casing === 'PascalCase') {
      formattedKey = toPascalCase(fieldName);
    }

    // Handle digits start
    let rustKey = formattedKey;
    if (/^[0-9]/.test(rustKey)) {
      rustKey = 'f_' + rustKey;
    }

    // Handle Rust keywords
    if (RUST_KEYWORDS.has(rustKey)) {
      rustKey = 'r#' + rustKey;
    }

    const renameAlias = (rustKey !== fieldName) ? fieldName : undefined;
    return { rustKey, renameAlias };
  };

  const escapeRustString = (str: string) => {
    return str
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r')
      .replace(/\t/g, '\\t');
  };

  const handleConvert = useCallback(() => {
    try {
      if (!input.trim()) {
        setOutput('');
        setError('');
        return;
      }
      if (input.length > MAX_LENGTH) {
        setError(t('error.max_length', { max: MAX_LENGTH.toLocaleString() }));
        return;
      }

      const parsed = JSON.parse(input);
      const structs: string[] = [];
      const structNames = new Set<string>();

      const getRustType = (val: any, fieldName: string, depth: number): string => {
        if (depth > MAX_DEPTH) return 'serde_json::Value';
        if (val === null || val === undefined) return 'Option<serde_json::Value>';

        if (Array.isArray(val)) {
          const itemType = val.length > 0 ? getRustType(val[0], fieldName, depth + 1) : 'serde_json::Value';
          return `Vec<${itemType}>`;
        }

        if (typeof val === 'object') {
          let name = toPascalCase(fieldName);
          if (name === 'Root') name = 'RootObject';

          let finalName = name;
          let counter = 1;
          while (structNames.has(finalName)) {
            finalName = name + counter++;
          }

          const fields = Object.entries(val).map(([key, value]) => {
            const { rustKey, renameAlias } = formatFieldName(key);
            const type = getRustType(value, key, depth + 1);
            let fieldStr = '';
            if (renameAlias) {
              fieldStr += `    #[serde(rename = "${escapeRustString(renameAlias)}")]\n`;
            }
            fieldStr += `    pub ${rustKey}: ${type},`;
            return fieldStr;
          });

          const derives = ['Debug', 'Serialize', 'Deserialize'];
          if (deriveClone) derives.push('Clone');
          if (derivePartialEq) derives.push('PartialEq');
          if (deriveDefault) derives.push('Default');

          let structStr = `#[derive(${derives.join(', ')})]\n`;
          structStr += `pub struct ${finalName} {\n`;
          structStr += fields.join('\n');
          structStr += '\n}';

          structs.push(structStr);
          structNames.add(finalName);
          return finalName;
        }

        if (typeof val === 'string') return 'String';
        if (typeof val === 'number') return Number.isInteger(val) ? 'i64' : 'f64';
        if (typeof val === 'boolean') return 'bool';

        return 'serde_json::Value';
      };

      getRustType(parsed, 'Root', 0);

      let result = 'use serde::{Serialize, Deserialize};\n\n';
      result += structs.reverse().join('\n\n');

      if (structs.length === 0) {
        const simpleType = getRustType(parsed, 'Root', 0);
        result = `type RootObject = ${simpleType};`;
      }

      setOutput(result);
      setError('');
    } catch (e: any) {
      setError(t('error.invalid_json') + ': ' + e.message);
      setOutput('');
    }
  }, [input, casing, deriveClone, derivePartialEq, deriveDefault, t]);

  useEffect(() => {
    handleConvert();
  }, [handleConvert]);

  const handleCopy = useCallback(() => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    toast.success(t('jsontorust.toast_copied'));
    setTimeout(() => setCopied(false), 2000);
  }, [output, t]);

  const handleClear = useCallback(() => {
    setInput('');
    setOutput('');
    setError('');
    toast.success(t('jsontorust.toast_cleared'));
    setTimeout(() => {
      inputRef.current?.focus();
    }, 50);
  }, [t]);

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/x-rust' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'models.rs';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(t('jsontorust.toast_downloaded'));
  };

  const loadPreset = (preset: Preset) => {
    setInput(JSON.stringify(preset.data, null, 2));
    toast.success(t('jsontorust.toast_preset_loaded'));
    setTimeout(() => {
      inputRef.current?.focus();
    }, 50);
  };

  const handlersRef = useRef({ handleCopy, handleClear });
  useEffect(() => {
    handlersRef.current = { handleCopy, handleClear };
  }, [handleCopy, handleClear]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const isEditable =
        document.activeElement?.tagName === 'INPUT' ||
        document.activeElement?.tagName === 'TEXTAREA' ||
        document.activeElement?.tagName === 'SELECT' ||
        document.activeElement?.getAttribute('contenteditable') === 'true';

      if (isEditable) return;
      if (e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;

      if (e.key === 'Escape') {
        e.preventDefault();
        handlersRef.current.handleClear();
      } else if (e.key.toLowerCase() === 'c') {
        e.preventDefault();
        handlersRef.current.handleCopy();
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  return (
    <div className="max-w-6xl mx-auto space-y-8">
      {/* Presets */}
      <div className="bg-slate-50 dark:bg-slate-900/50 p-6 rounded-[2rem] border border-slate-200 dark:border-slate-800 space-y-3">
        <div className="flex items-center gap-2 px-1">
          <Sparkles className="w-4 h-4 text-indigo-500" />
          <h3 className="text-xs font-black uppercase tracking-widest text-slate-400">{t('jsontorust.presets_title')}</h3>
        </div>
        <div className="flex flex-wrap gap-2">
          {PRESETS.map((preset, idx) => (
            <button
              key={idx}
              onClick={() => loadPreset(preset)}
              className="px-4 py-2 bg-white dark:bg-slate-800 hover:bg-indigo-50 dark:hover:bg-indigo-900/30 text-slate-700 dark:text-slate-300 hover:text-indigo-600 dark:hover:text-indigo-400 border border-slate-200 dark:border-slate-700 rounded-xl text-xs font-bold transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 outline-none"
            >
              {t(preset.nameKey)}
            </button>
          ))}
        </div>
      </div>

      {/* Options */}
      <div className="bg-slate-50 dark:bg-slate-900/50 p-6 rounded-[2rem] border border-slate-200 dark:border-slate-800 space-y-4">
        <h3 className="text-xs font-black uppercase tracking-widest text-slate-400 px-1">{t('jsontorust.options_title')}</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 px-1">
          <div>
            <label htmlFor="rust-casing" className="text-xs font-bold text-slate-600 dark:text-slate-400 block mb-1">
              {t('jsontorust.casing_label')}
            </label>
            <select
              id="rust-casing"
              value={casing}
              onChange={(e) => setCasing(e.target.value as any)}
              className="w-full px-3 py-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-xs font-semibold text-slate-700 dark:text-slate-300 outline-none focus:ring-2 focus:ring-indigo-500"
            >
              <option value="snake_case">{t('jsontorust.casing_snake')}</option>
              <option value="camelCase">{t('jsontorust.casing_camel')}</option>
              <option value="PascalCase">{t('jsontorust.casing_pascal')}</option>
              <option value="original">{t('jsontorust.casing_original')}</option>
            </select>
          </div>

          <label className="flex items-center gap-2 cursor-pointer group mt-5">
            <input
              type="checkbox"
              checked={deriveClone}
              onChange={(e) => setDeriveClone(e.target.checked)}
              className="w-4 h-4 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
            />
            <span className="text-sm font-medium text-slate-600 dark:text-slate-400 group-hover:text-slate-900 dark:group-hover:text-slate-200 transition-colors">
              {t('jsontorust.derive_clone')}
            </span>
          </label>

          <label className="flex items-center gap-2 cursor-pointer group mt-5">
            <input
              type="checkbox"
              checked={derivePartialEq}
              onChange={(e) => setDerivePartialEq(e.target.checked)}
              className="w-4 h-4 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
            />
            <span className="text-sm font-medium text-slate-600 dark:text-slate-400 group-hover:text-slate-900 dark:group-hover:text-slate-200 transition-colors">
              {t('jsontorust.derive_partialeq')}
            </span>
          </label>

          <label className="flex items-center gap-2 cursor-pointer group mt-5">
            <input
              type="checkbox"
              checked={deriveDefault}
              onChange={(e) => setDeriveDefault(e.target.checked)}
              className="w-4 h-4 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
            />
            <span className="text-sm font-medium text-slate-600 dark:text-slate-400 group-hover:text-slate-900 dark:group-hover:text-slate-200 transition-colors">
              {t('jsontorust.derive_default')}
            </span>
          </label>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <Braces className="w-4 h-4 text-indigo-500" />
              <label htmlFor="json-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">{t('common.input')} JSON</label>
            </div>
            <div className="flex items-center gap-2">
              <Kbd modifier={null} className="hidden sm:inline-flex border-rose-200 dark:border-rose-800 text-rose-400 dark:bg-slate-900">Esc</Kbd>
              <button
                onClick={handleClear}
                disabled={!input && !output}
                className="text-xs font-bold px-3 py-1 rounded-full text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 transition-all flex items-center gap-1 disabled:opacity-50 disabled:cursor-not-allowed focus-visible:ring-2 focus-visible:ring-rose-500 focus-visible:outline-none"
              >
                <Trash2 className="w-3 h-3" /> {t('common.clear')}
              </button>
            </div>
          </div>
          <textarea
            id="json-input"
            ref={inputRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder='{"id": 1, "name": "Rust"}'
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none"
          />
        </div>

        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <Code className="w-4 h-4 text-emerald-500" />
              <label htmlFor="rust-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">{t('jsontorust.output_label')}</label>
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                disabled={!output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 hover:bg-slate-200 transition-all flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <Download className="w-3.5 h-3.5" /> {t('common.download')}
              </button>
              <button
                onClick={handleCopy}
                disabled={!output}
                title={`${t('common.copy')} (C)`}
                className={`text-xs font-bold px-4 py-1.5 rounded-xl transition-all flex items-center gap-2 border focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-200 dark:border-emerald-500/20'
                    : 'bg-white dark:bg-slate-800 text-indigo-600 dark:text-indigo-400 border-slate-200 dark:border-slate-700 hover:border-indigo-500/50 shadow-sm'
                } disabled:opacity-50 disabled:cursor-not-allowed`}
              >
                {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                {copied ? t('common.copied') : t('common.copy')}
                {!copied && <Kbd modifier={null} className="hidden sm:inline-flex w-4 h-4 border-indigo-200 dark:border-indigo-800 text-indigo-400 dark:bg-slate-900 ml-1">C</Kbd>}
              </button>
            </div>
          </div>
          <textarea
            id="rust-output"
            value={output}
            readOnly
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400 resize-none"
          />
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold animate-in fade-in slide-in-from-top-2">
          <AlertCircle className="w-5 h-5" />
          {error}
        </div>
      )}

      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <Info className="w-6 h-6 text-indigo-500 mt-1" />
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">{t('jsontorust.about_title')}</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            {t('jsontorust.about_text')}
          </p>
        </div>
      </div>
    </div>
  );
}
