import { useState, useEffect, useCallback, useRef } from 'react';
import { FileCode, Copy, Check, Trash2, AlertCircle, Download, Info, Code, Braces } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;
const MAX_DEPTH = 20;

const PYTHON_KEYWORDS = new Set([
  'False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class',
  'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global',
  'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return',
  'try', 'while', 'with', 'yield'
]);

export function JSONToDjango({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const [input, setInput] = useState(initialData?.input || '');
  const [output, setOutput] = useState(initialData?.output || '');
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  // Configuration options
  const [allowNullBlank, setAllowNullBlank] = useState(initialData?.allowNullBlank ?? true);
  const [generateStrMethod, setGenerateStrMethod] = useState(initialData?.generateStrMethod ?? true);
  const [generateMetaClass, setGenerateMetaClass] = useState(initialData?.generateMetaClass ?? true);
  const [generateAdminCode, setGenerateAdminCode] = useState(initialData?.generateAdminCode ?? true);

  useEffect(() => {
    onStateChange?.({
      input,
      output,
      allowNullBlank,
      generateStrMethod,
      generateMetaClass,
      generateAdminCode,
    });
  }, [input, output, allowNullBlank, generateStrMethod, generateMetaClass, generateAdminCode, onStateChange]);

  const toPascalCase = (str: string) => {
    return str
      .replace(/[^a-z0-9]/gi, ' ')
      .split(' ')
      .filter(Boolean)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('') || 'AutoGenerated';
  };

  const toSnakeCase = (str: string) => {
    return str
      .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
      .replace(/[^a-zA-Z0-9]/g, '_')
      .toLowerCase();
  };

  const toValidPythonIdentifier = (key: string) => {
    let name = toSnakeCase(key);
    if (/^[0-9]/.test(name)) {
      name = 'field_' + name;
    }
    if (PYTHON_KEYWORDS.has(name)) {
      name += '_field';
    }
    return name || 'unnamed_field';
  };

  const inferDjangoField = (val: any, fieldName: string, depth: number, models: string[]): { fieldType: string; isNested: boolean } => {
    if (depth > MAX_DEPTH) {
      return { fieldType: 'models.JSONField()', isNested: false };
    }

    if (val === null || val === undefined) {
      const extra = allowNullBlank ? 'null=True, blank=True' : '';
      return { fieldType: `models.CharField(max_length=255, ${extra})`.replace(/,\s*\)$/, ')'), isNested: false };
    }

    const extraParams: string[] = [];
    if (allowNullBlank) {
      extraParams.push('null=True', 'blank=True');
    }

    if (typeof val === 'boolean') {
      return { fieldType: `models.BooleanField(${extraParams.join(', ')})`.replace(/\(\s*\)/, '()'), isNested: false };
    }

    if (typeof val === 'number') {
      if (Number.isInteger(val)) {
        return { fieldType: `models.IntegerField(${extraParams.join(', ')})`.replace(/\(\s*\)/, '()'), isNested: false };
      }
      return { fieldType: `models.FloatField(${extraParams.join(', ')})`.replace(/\(\s*\)/, '()'), isNested: false };
    }

    if (typeof val === 'string') {
      // Date or timestamp detection
      if (/^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(\.\d{3})?Z?)?$/.test(val)) {
        return { fieldType: `models.DateTimeField(${extraParams.join(', ')})`.replace(/\(\s*\)/, '()'), isNested: false };
      }
      if (/^\d{4}-\d{2}-\d{2}$/.test(val)) {
        return { fieldType: `models.DateField(${extraParams.join(', ')})`.replace(/\(\s*\)/, '()'), isNested: false };
      }
      if (val.length > 255) {
        return { fieldType: `models.TextField(${extraParams.join(', ')})`.replace(/\(\s*\)/, '()'), isNested: false };
      }
      return { fieldType: `models.CharField(max_length=255, ${extraParams.join(', ')})`, isNested: false };
    }

    if (Array.isArray(val)) {
      if (val.length > 0 && typeof val[0] === 'object' && val[0] !== null) {
        // Relation - ForeignKey
        const relationModel = toPascalCase(fieldName);
        generateDjangoModel(val[0], fieldName, depth + 1, models);
        return { fieldType: `models.ForeignKey('${relationModel}', on_delete=models.CASCADE, ${extraParams.join(', ')})`, isNested: true };
      }
      return { fieldType: `models.JSONField(${extraParams.join(', ')})`.replace(/\(\s*\)/, '()'), isNested: false };
    }

    if (typeof val === 'object') {
      const subModelName = toPascalCase(fieldName);
      generateDjangoModel(val, fieldName, depth + 1, models);
      return { fieldType: `models.OneToOneField('${subModelName}', on_delete=models.CASCADE, ${extraParams.join(', ')})`, isNested: true };
    }

    return { fieldType: 'models.JSONField()', isNested: false };
  };

  const generatedClasses = new Set<string>();

  const generateDjangoModel = (obj: any, modelName: string, depth: number, models: string[]) => {
    const className = toPascalCase(modelName);
    if (generatedClasses.has(className)) return;
    generatedClasses.add(className);

    let modelCode = `class ${className}(models.Model):\n`;
    const fields: string[] = [];
    const fieldNamesList: string[] = [];

    Object.entries(obj).forEach(([key, value]) => {
      const pythonName = toValidPythonIdentifier(key);
      const { fieldType } = inferDjangoField(value, key, depth, models);
      const comment = pythonName !== key ? `  # Original JSON key: ${key}` : '';
      fields.push(`    ${pythonName} = ${fieldType}${comment}`);
      fieldNamesList.push(pythonName);
    });

    if (fields.length === 0) {
      fields.push('    pass');
    }

    modelCode += fields.join('\n') + '\n';

    // Meta class
    if (generateMetaClass && fieldNamesList.length > 0) {
      modelCode += `\n    class Meta:\n`;
      modelCode += `        ordering = ['-${fieldNamesList[0]}']\n`;
    }

    // __str__ method
    if (generateStrMethod) {
      const strField = fieldNamesList.find(f => f.includes('name') || f.includes('title')) || fieldNamesList[0] || 'id';
      modelCode += `\n    def __str__(self):\n`;
      modelCode += `        return str(self.${strField})\n`;
    }

    models.push(modelCode);
  };

  const handleConvert = useCallback(() => {
    try {
      if (!input.trim()) {
        setOutput('');
        setError('');
        return;
      }
      if (input.length > MAX_LENGTH) {
        setError(t('error.max_length', { max: MAX_LENGTH.toLocaleString() }));
        return;
      }

      const parsed = JSON.parse(input);
      const models: string[] = [];
      generatedClasses.clear();

      generateDjangoModel(parsed, 'Root', 0, models);

      let finalOutput = `from django.db import models\n\n`;
      finalOutput += models.reverse().join('\n\n');

      if (generateAdminCode && generatedClasses.size > 0) {
        finalOutput += `\n\n# admin.py\nfrom django.contrib import admin\n`;
        const registered = Array.from(generatedClasses);
        finalOutput += `from .models import ${registered.join(', ')}\n\n`;
        registered.forEach(cls => {
          finalOutput += `@admin.register(${cls})\nclass ${cls}Admin(admin.ModelAdmin):\n    pass\n\n`;
        });
      }

      setOutput(finalOutput.trim());
      setError('');
    } catch (e: any) {
      setError(t('error.invalid_json') + ': ' + e.message);
      setOutput('');
    }
  }, [input, allowNullBlank, generateStrMethod, generateMetaClass, generateAdminCode, t]);

  useEffect(() => {
    handleConvert();
  }, [handleConvert]);

  const handleCopy = useCallback(() => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [output]);

  const handleClear = useCallback(() => {
    setInput('');
    setOutput('');
    setError('');
  }, []);

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/x-python' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'models.py';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-6xl mx-auto space-y-8">
      {/* Configuration options */}
      <div className="bg-slate-50 dark:bg-slate-900/50 p-6 rounded-[2rem] border border-slate-200 dark:border-slate-800 space-y-4">
        <h3 className="text-xs font-black uppercase tracking-widest text-slate-400 px-1">{t('common.options')}</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 px-1">
          <label className="flex items-center gap-2 cursor-pointer group">
            <input
              type="checkbox"
              checked={allowNullBlank}
              onChange={(e) => setAllowNullBlank(e.target.checked)}
              className="w-4 h-4 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
            />
            <span className="text-sm font-medium text-slate-600 dark:text-slate-400 group-hover:text-slate-900 dark:group-hover:text-slate-200 transition-colors">
              Allow null=True, blank=True
            </span>
          </label>

          <label className="flex items-center gap-2 cursor-pointer group">
            <input
              type="checkbox"
              checked={generateStrMethod}
              onChange={(e) => setGenerateStrMethod(e.target.checked)}
              className="w-4 h-4 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
            />
            <span className="text-sm font-medium text-slate-600 dark:text-slate-400 group-hover:text-slate-900 dark:group-hover:text-slate-200 transition-colors">
              Generate __str__ method
            </span>
          </label>

          <label className="flex items-center gap-2 cursor-pointer group">
            <input
              type="checkbox"
              checked={generateMetaClass}
              onChange={(e) => setGenerateMetaClass(e.target.checked)}
              className="w-4 h-4 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
            />
            <span className="text-sm font-medium text-slate-600 dark:text-slate-400 group-hover:text-slate-900 dark:group-hover:text-slate-200 transition-colors">
              Generate Meta options
            </span>
          </label>

          <label className="flex items-center gap-2 cursor-pointer group">
            <input
              type="checkbox"
              checked={generateAdminCode}
              onChange={(e) => setGenerateAdminCode(e.target.checked)}
              className="w-4 h-4 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
            />
            <span className="text-sm font-medium text-slate-600 dark:text-slate-400 group-hover:text-slate-900 dark:group-hover:text-slate-200 transition-colors">
              Generate Admin Reg Code
            </span>
          </label>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <Braces className="w-4 h-4 text-indigo-500" />
              <label htmlFor="json-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">{t('common.input')} JSON</label>
            </div>
            <div className="flex items-center gap-2">
              <Kbd modifier={null} className="hidden sm:inline-flex border-rose-200 dark:border-rose-800 text-rose-400 dark:bg-slate-900">Esc</Kbd>
              <button
                onClick={handleClear}
                disabled={!input && !output}
                className="text-xs font-bold px-3 py-1 rounded-full text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-rose-500 focus-visible:outline-none"
              >
                <Trash2 className="w-3 h-3" /> {t('common.clear')}
              </button>
            </div>
          </div>
          <textarea
            id="json-input"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder='{"id": 1, "title": "My Post", "body": "Hello world", "author": {"name": "Admin"}}'
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none"
          />
        </div>

        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <Code className="w-4 h-4 text-emerald-500" />
              <label htmlFor="django-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">Django Models Output</label>
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                disabled={!output}
                className="text-xs font-bold px-3 py-1 rounded-full text-indigo-500 bg-indigo-50 dark:bg-indigo-500/10 hover:bg-indigo-100 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
              >
                <Download className="w-3 h-3" /> {t('common.download')}
              </button>
              <button
                onClick={handleCopy}
                disabled={!output}
                className={`text-xs font-bold px-3 py-1 rounded-full transition-all flex items-center gap-1 border focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-500/20'
                    : 'text-slate-500 bg-slate-100 dark:bg-slate-800 border-transparent hover:bg-slate-200 dark:hover:bg-slate-700 disabled:opacity-50 disabled:cursor-not-allowed'
                }`}
              >
                {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />} {copied ? t('common.copied') : t('common.copy')}
                {!copied && <Kbd modifier={null} className="hidden sm:inline-flex w-4 h-4 bg-white/50 dark:bg-black/20 ml-1">C</Kbd>}
              </button>
            </div>
          </div>
          <textarea
            id="django-output"
            value={output}
            readOnly
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400 resize-none"
          />
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold">
          <AlertCircle className="w-5 h-5" />
          {error}
        </div>
      )}

      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <Info className="w-6 h-6 text-indigo-500 mt-1" />
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">About JSON to Django Models Converter</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            Convert complex JSON objects or payloads directly into clean Python Django Model class structures. Nested objects and relational models are extracted into their own model definitions and dynamically linked via `OneToOneField` or `ForeignKey` relationship descriptors with cascades.
          </p>
        </div>
      </div>
    </div>
  );
}
