import { useState, useEffect, useCallback, useRef } from 'react';
import { FileCode, Copy, Check, Trash2, AlertCircle, Download, Info } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;
const MAX_DEPTH = 20;

export function JSONToDart({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const [input, setInput] = useState(initialData?.input || '');
  const [output, setOutput] = useState(initialData?.output || '');
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  // Premium Options
  const [nullSafety, setNullSafety] = useState(initialData?.nullSafety ?? true);
  const [generateSerialization, setGenerateSerialization] = useState(initialData?.generateSerialization ?? true);
  const [generateCopyWith, setGenerateCopyWith] = useState(initialData?.generateCopyWith ?? false);
  const [generateToString, setGenerateToString] = useState(initialData?.generateToString ?? false);
  const [classNamePrefix, setClassNamePrefix] = useState(initialData?.classNamePrefix || '');
  const [classNameSuffix, setClassNameSuffix] = useState(initialData?.classNameSuffix || '');

  useEffect(() => {
    onStateChange?.({
      input,
      output,
      nullSafety,
      generateSerialization,
      generateCopyWith,
      generateToString,
      classNamePrefix,
      classNameSuffix,
    });
  }, [input, output, nullSafety, generateSerialization, generateCopyWith, generateToString, classNamePrefix, classNameSuffix, onStateChange]);

  const toPascalCase = (str: string) => {
    const cleaned = str.replace(/[^a-z0-9]/gi, ' ');
    const camel = cleaned
      .split(' ')
      .filter(Boolean)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');

    // Prototype pollution defense & validation
    const invalidNames = ['__proto__', 'constructor', 'prototype'];
    let safeName = invalidNames.includes(camel.toLowerCase()) ? 'Safe' + camel : camel;

    return safeName || 'AutoGenerated';
  };

  const toCamelCase = (str: string) => {
    const pascal = toPascalCase(str);
    let result = pascal.charAt(0).toLowerCase() + pascal.slice(1);
    if (!result) result = 'unnamedProperty';

    const keywords = ['abstract', 'as', 'assert', 'async', 'await', 'break', 'case', 'catch', 'class', 'const', 'continue', 'covariant', 'default', 'deferred', 'do', 'dynamic', 'else', 'enum', 'export', 'extends', 'extension', 'external', 'factory', 'false', 'final', 'finally', 'for', 'Function', 'get', 'hide', 'if', 'implements', 'import', 'in', 'interface', 'is', 'library', 'mixin', 'new', 'null', 'on', 'operator', 'part', 'rethrow', 'return', 'set', 'show', 'static', 'super', 'switch', 'sync', 'this', 'throw', 'true', 'try', 'typedef', 'var', 'void', 'while', 'with', 'yield'];
    if (keywords.includes(result) || result === 'hashCode' || result === 'runtimeType') {
      result = 'f_' + result;
    }
    return result;
  };

  const handleConvert = useCallback(() => {
    try {
      if (!input.trim()) {
        setOutput('');
        setError('');
        return;
      }
      if (input.length > MAX_LENGTH) {
        setError(t('error.max_length', { max: MAX_LENGTH.toLocaleString() }));
        return;
      }
      const parsed = JSON.parse(input);
      const classes: string[] = [];
      const classNames = new Set<string>();

      const getDartType = (val: any, fieldName: string, depth: number): string => {
        if (depth > MAX_DEPTH) return 'dynamic';
        if (val === null || val === undefined) return 'dynamic';

        if (Array.isArray(val)) {
          const itemType = val.length > 0 ? getDartType(val[0], fieldName, depth + 1) : 'dynamic';
          return `List<${itemType}>`;
        }

        if (typeof val === 'object') {
          let name = toPascalCase(fieldName);
          if (name === 'Root') name = 'RootObject';

          // Apply Prefix/Suffix rules
          let baseName = `${classNamePrefix}${name}${classNameSuffix}`;
          let finalName = baseName;
          let counter = 1;
          while (classNames.has(finalName)) {
            finalName = baseName + counter++;
          }

          const fieldsList = Object.entries(val);
          const fields = fieldsList.map(([key, value]) => {
            const type = getDartType(value, key, depth + 1);
            const ident = toCamelCase(key);
            const suffix = nullSafety ? '?' : '';
            return {
              originalKey: key,
              ident,
              type,
              declaration: `  final ${type}${suffix} ${ident};`
            };
          });

          let classStr = `class ${finalName} {\n`;
          classStr += fields.map(f => f.declaration).join('\n');

          // Constructor
          classStr += `\n\n  ${finalName}({\n`;
          classStr += fields.map(f => `    this.${f.ident},`).join('\n');
          classStr += '\n  });\n';

          // JSON Deserialization Factory
          if (generateSerialization) {
            classStr += `\n  factory ${finalName}.fromJson(Map<String, dynamic> json) {\n`;
            classStr += `    return ${finalName}(\n`;
            classStr += fields.map(f => {
              if (f.type.startsWith('List<') && f.type.endsWith('>')) {
                const subType = f.type.substring(5, f.type.length - 1);
                // Check if list subtype is a nested object
                if (subType !== 'int' && subType !== 'double' && subType !== 'String' && subType !== 'bool' && subType !== 'dynamic') {
                  return `      ${f.ident}: json['${f.originalKey}'] != null\n          ? List<${subType}>.from(json['${f.originalKey}'].map((x) => ${subType}.fromJson(x)))\n          : null,`;
                }
              } else if (f.type !== 'int' && f.type !== 'double' && f.type !== 'String' && f.type !== 'bool' && f.type !== 'dynamic') {
                return `      ${f.ident}: json['${f.originalKey}'] != null ? ${f.type}.fromJson(json['${f.originalKey}']) : null,`;
              }
              return `      ${f.ident}: json['${f.originalKey}'],`;
            }).join('\n');
            classStr += '\n    );\n  }\n';

            // JSON Serialization method
            classStr += `\n  Map<String, dynamic> toJson() {\n`;
            classStr += `    return {\n`;
            classStr += fields.map(f => {
              if (f.type.startsWith('List<') && f.type.endsWith('>')) {
                const subType = f.type.substring(5, f.type.length - 1);
                if (subType !== 'int' && subType !== 'double' && subType !== 'String' && subType !== 'bool' && subType !== 'dynamic') {
                  return `      '${f.originalKey}': ${f.ident} != null ? List<dynamic>.from(${f.ident}!.map((x) => x.toJson())) : null,`;
                }
              } else if (f.type !== 'int' && f.type !== 'double' && f.type !== 'String' && f.type !== 'bool' && f.type !== 'dynamic') {
                return `      '${f.originalKey}': ${f.ident}?.toJson(),`;
              }
              return `      '${f.originalKey}': ${f.ident},`;
            }).join('\n');
            classStr += '\n    };\n  }\n';
          }

          // copyWith helper method
          if (generateCopyWith) {
            classStr += `\n  ${finalName} copyWith({\n`;
            classStr += fields.map(f => `    ${f.type}? ${f.ident},`).join('\n');
            classStr += '\n  }) {\n';
            classStr += `    return ${finalName}(\n`;
            classStr += fields.map(f => `      ${f.ident}: ${f.ident} ?? this.${f.ident},`).join('\n');
            classStr += '\n    );\n  }\n';
          }

          // toString helper method
          if (generateToString) {
            classStr += `\n  @override\n  String toString() {\n`;
            classStr += `    return '${finalName}(`;
            classStr += fields.map(f => `${f.ident}: \$${f.ident}`).join(', ');
            classStr += `)';\n  }\n`;
          }

          classStr += '}';

          classes.push(classStr);
          classNames.add(finalName);
          return finalName;
        }

        if (typeof val === 'string') return 'String';
        if (typeof val === 'number') return Number.isInteger(val) ? 'int' : 'double';
        if (typeof val === 'boolean') return 'bool';

        return 'dynamic';
      };

      getDartType(parsed, 'Root', 0);

      let result = classes.reverse().join('\n\n');

      if (classes.length === 0) {
        const simpleType = getDartType(parsed, 'Root', 0);
        result = `typedef RootObject = ${simpleType};`;
      }

      setOutput(result);
      setError('');
    } catch (e: any) {
      setError(t('error.invalid_json') + ': ' + e.message);
      setOutput('');
    }
  }, [input, nullSafety, generateSerialization, generateCopyWith, generateToString, classNamePrefix, classNameSuffix, t]);

  useEffect(() => {
    handleConvert();
  }, [handleConvert]);

  const handleCopy = useCallback(() => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    toast.success(t('common.copied') || 'Copied successfully!');
    setTimeout(() => setCopied(false), 2000);
  }, [output, t]);

  const handleClear = useCallback(() => {
    setInput('');
    setOutput('');
    setError('');
    toast.success(t('jsontodart.reset_success') || 'Inputs cleared!');
  }, [t]);

  // Setup useRef handler wrapper for shortcuts
  const handlersRef = useRef({
    onClear: handleClear,
    onCopy: handleCopy,
  });

  useEffect(() => {
    handlersRef.current = {
      onClear: handleClear,
      onCopy: handleCopy,
    };
  }, [handleClear, handleCopy]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const target = e.target as HTMLElement;
      if (target?.tagName === "INPUT" || target?.tagName === "TEXTAREA" || target?.isContentEditable) {
        if (e.key === "Escape") {
          e.preventDefault();
          handlersRef.current.onClear();
        }
        return;
      }
      if (e.key === "Escape") {
        e.preventDefault();
        handlersRef.current.onClear();
      } else if (e.key.toLowerCase() === "c" && !e.ctrlKey && !e.metaKey && !e.altKey) {
        e.preventDefault();
        handlersRef.current.onCopy();
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, []);

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/x-dart' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'models.dart';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-6xl mx-auto space-y-8" role="region" aria-label="JSON to Dart Converter">
      {/* Keyboard Shortcuts indicators */}
      <div className="flex justify-end gap-3 px-1 items-center">
        <span className="flex items-center gap-1.5 text-xs font-bold text-slate-400">
          <Kbd modifier={null} className="bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700 text-slate-400">Esc</Kbd>
          {t('common.clear')}
        </span>
        <span className="flex items-center gap-1.5 text-xs font-bold text-slate-400 mr-2">
          <Kbd modifier={null} className="bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700 text-slate-400">C</Kbd>
          {t('common.copy')}
        </span>
        <button
          onClick={handleClear}
          disabled={!input && !output}
          className="text-xs font-bold px-3 py-1.5 rounded-xl text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 transition-all flex items-center gap-1 disabled:opacity-50"
        >
          <Trash2 className="w-3.5 h-3.5" /> {t('common.clear')}
        </button>
      </div>

      {/* Premium Toggles / Config Section */}
      <div className="p-6 bg-slate-50 dark:bg-slate-900/40 rounded-3xl border border-slate-200 dark:border-slate-800 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {/* Serialization settings */}
        <div className="space-y-3">
          <span className="text-xs font-black uppercase tracking-widest text-slate-400 block">
            {t('jsontodart.generation_options') || "Generation Options"}
          </span>
          <div className="space-y-2">
            <label className="flex items-center gap-2 cursor-pointer text-sm font-semibold text-slate-600 dark:text-slate-400">
              <input
                type="checkbox"
                checked={nullSafety}
                onChange={(e) => setNullSafety(e.target.checked)}
                className="w-4 h-4 rounded text-indigo-600 focus:ring-indigo-500"
              />
              {t('jsontodart.null_safety') || "Null-Safety / Optional fields (?) "}
            </label>
            <label className="flex items-center gap-2 cursor-pointer text-sm font-semibold text-slate-600 dark:text-slate-400">
              <input
                type="checkbox"
                checked={generateSerialization}
                onChange={(e) => setGenerateSerialization(e.target.checked)}
                className="w-4 h-4 rounded text-indigo-600 focus:ring-indigo-500"
              />
              {t('jsontodart.serialization') || "JSON Serialization (fromJson/toJson)"}
            </label>
          </div>
        </div>

        {/* Helpers settings */}
        <div className="space-y-3">
          <span className="text-xs font-black uppercase tracking-widest text-slate-400 block">
            {t('jsontodart.helpers_options') || "Helpers & Utilities"}
          </span>
          <div className="space-y-2">
            <label className="flex items-center gap-2 cursor-pointer text-sm font-semibold text-slate-600 dark:text-slate-400">
              <input
                type="checkbox"
                checked={generateCopyWith}
                onChange={(e) => setGenerateCopyWith(e.target.checked)}
                className="w-4 h-4 rounded text-indigo-600 focus:ring-indigo-500"
              />
              {t('jsontodart.copywith') || "Generate copyWith method"}
            </label>
            <label className="flex items-center gap-2 cursor-pointer text-sm font-semibold text-slate-600 dark:text-slate-400">
              <input
                type="checkbox"
                checked={generateToString}
                onChange={(e) => setGenerateToString(e.target.checked)}
                className="w-4 h-4 rounded text-indigo-600 focus:ring-indigo-500"
              />
              {t('jsontodart.tostring') || "Generate @override toString() method"}
            </label>
          </div>
        </div>

        {/* Name prefixes & suffixes */}
        <div className="space-y-3">
          <span className="text-xs font-black uppercase tracking-widest text-slate-400 block">
            {t('jsontodart.modifiers_options') || "Class Modifiers"}
          </span>
          <div className="grid grid-cols-2 gap-2">
            <div>
              <label htmlFor="prefix-mod" className="text-[10px] font-bold text-slate-500 block mb-1">Prefix</label>
              <input
                id="prefix-mod"
                type="text"
                placeholder="e.g. My"
                value={classNamePrefix}
                onChange={(e) => setClassNamePrefix(e.target.value)}
                className="w-full p-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl outline-none focus:ring-1 focus:ring-indigo-500/20 text-xs font-bold"
              />
            </div>
            <div>
              <label htmlFor="suffix-mod" className="text-[10px] font-bold text-slate-500 block mb-1">Suffix</label>
              <input
                id="suffix-mod"
                type="text"
                placeholder="e.g. Model"
                value={classNameSuffix}
                onChange={(e) => setClassNameSuffix(e.target.value)}
                className="w-full p-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl outline-none focus:ring-1 focus:ring-indigo-500/20 text-xs font-bold"
              />
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-indigo-500" />
              <label htmlFor="json-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">{t('common.input')} JSON</label>
            </div>
          </div>
          <textarea
            id="json-input"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder='{"id": 1, "name": "Dart", "is_awesome": true, "nested": {"version": 3.0}}'
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none"
          />
        </div>

        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-emerald-500" />
              <label htmlFor="dart-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">Dart Classes</label>
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                disabled={!output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-indigo-500 bg-indigo-50 dark:bg-indigo-500/10 hover:bg-indigo-100 transition-all flex items-center gap-1 disabled:opacity-50"
              >
                <Download className="w-3.5 h-3.5" /> {t('common.download')}
              </button>
              <button
                onClick={handleCopy}
                disabled={!output}
                className={`text-xs font-bold px-3 py-1.5 rounded-xl transition-all flex items-center gap-1 focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-500/20'
                    : 'text-slate-500 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200'
                } disabled:opacity-50 disabled:cursor-not-allowed`}
              >
                {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />} {copied ? t('common.copied') : t('common.copy')}
              </button>
            </div>
          </div>
          <textarea
            id="dart-output"
            value={output}
            readOnly
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400 resize-none"
          />
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold">
          <AlertCircle className="w-5 h-5" />
          {error}
        </div>
      )}

      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <Info className="w-6 h-6 text-indigo-500 mt-1" />
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">À propos de la conversion JSON en Dart</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            Cet outil génère des classes de données Dart saines à partir de vos données JSON. Vous pouvez basculer les options de sécurité null (Null-Safety), générer automatiquement les méthodes de sérialisation et de désérialisation JSON (fromJson/toJson) nécessaires pour les services de l'API Flutter, ou ajouter des modificateurs de copie (`copyWith`), d'impression (`toString`) et de préfixe/suffixe sur les noms de classe de manière fluide.
          </p>
        </div>
      </div>
    </div>
  );
}
