import { useState, useEffect, useCallback, useRef } from 'react';
import { FileCode, Copy, Check, Trash2, AlertCircle, Download, Info, Sparkles } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;
const MAX_DEPTH = 20;

type PythonStyle = 'dataclass' | 'typeddict';

interface Preset {
  id: string;
  nameKey: string;
  json: string;
}

const PRESETS: Preset[] = [
  {
    id: 'user',
    nameKey: 'jsontopython.preset_user',
    json: JSON.stringify(
      {
        id: 101,
        username: 'johndoe',
        email: 'john@example.com',
        is_active: true,
        roles: ['admin', 'developer'],
        profile: {
          first_name: 'John',
          last_name: 'Doe',
          age: 30,
          bio: null
        }
      },
      null,
      2
    )
  },
  {
    id: 'ecommerce',
    nameKey: 'jsontopython.preset_ecommerce',
    json: JSON.stringify(
      {
        order_id: 'ORD-99281',
        total_amount: 149.99,
        currency: 'USD',
        is_paid: true,
        items: [
          {
            product_id: 'PRD-1',
            title: 'Wireless Ergonomic Mouse',
            price: 49.99,
            quantity: 1
          },
          {
            product_id: 'PRD-2',
            title: 'Mechanical Gaming Keyboard',
            price: 100.0,
            quantity: 1
          }
        ],
        shipping_address: {
          street: '123 Tech Blvd',
          city: 'San Francisco',
          zip_code: '94105',
          country: 'USA'
        }
      },
      null,
      2
    )
  },
  {
    id: 'config',
    nameKey: 'jsontopython.preset_config',
    json: JSON.stringify(
      {
        app_name: 'ApiGatewayService',
        version: '2.4.0',
        environment: 'production',
        port: 8080,
        debug_mode: false,
        max_connections: 5000,
        rate_limiting: {
          enabled: true,
          requests_per_minute: 120
        },
        endpoints: ['/api/v1/health', '/api/v1/auth', '/api/v1/users']
      },
      null,
      2
    )
  }
];

export function JSONToPython({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const [input, setInput] = useState(initialData?.input ?? PRESETS[0].json);
  const [output, setOutput] = useState(initialData?.output || '');
  const [pythonStyle, setPythonStyle] = useState<PythonStyle>('dataclass');
  const [activePreset, setActivePreset] = useState<string | null>('user');
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  const containerRef = useRef<HTMLDivElement>(null);
  const primaryInputRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    onStateChange?.({ input, output });
  }, [input, output, onStateChange]);

  const toPascalCase = (str: string) => {
    return (
      str
        .replace(/[^a-z0-9]/gi, ' ')
        .split(' ')
        .filter(Boolean)
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
        .join('') || 'AutoGenerated'
    );
  };

  const toSnakeCase = (str: string) => {
    let result = str
      .replace(/([a-z])([A-Z])/g, '$1_$2')
      .replace(/[^a-z0-9]/gi, '_')
      .toLowerCase();

    // Python identifiers cannot start with a digit
    if (/^[0-9]/.test(result)) {
      result = 'f_' + result;
    }

    // Handle Python keywords
    const keywords = [
      'False',
      'None',
      'True',
      'and',
      'as',
      'assert',
      'async',
      'await',
      'break',
      'class',
      'continue',
      'def',
      'del',
      'elif',
      'else',
      'except',
      'finally',
      'for',
      'from',
      'global',
      'if',
      'import',
      'in',
      'is',
      'lambda',
      'nonlocal',
      'not',
      'or',
      'pass',
      'raise',
      'return',
      'try',
      'while',
      'with',
      'yield'
    ];
    if (keywords.includes(result)) {
      result += '_';
    }

    return result;
  };

  const handleConvert = useCallback(() => {
    try {
      if (!input.trim()) {
        setOutput('');
        setError('');
        return;
      }
      if (input.length > MAX_LENGTH) {
        setError(t('error.max_length', { max: MAX_LENGTH.toLocaleString() }));
        return;
      }
      const parsed = JSON.parse(input);
      const classes: string[] = [];
      const classNames = new Set<string>();

      const getPythonType = (val: any, fieldName: string, depth: number): string => {
        if (depth > MAX_DEPTH) return 'Any';
        if (val === null || val === undefined) return 'Optional[Any]';

        if (Array.isArray(val)) {
          const itemType = val.length > 0 ? getPythonType(val[0], fieldName, depth + 1) : 'Any';
          return `List[${itemType}]`;
        }

        if (typeof val === 'object') {
          let name = toPascalCase(fieldName);
          if (name === 'Root') name = 'RootObject';

          let finalName = name;
          let counter = 1;
          while (classNames.has(finalName)) {
            finalName = name + counter++;
          }

          // Mitigate prototype pollution with Object.create(null)
          const safeObj: Record<string, any> = Object.create(null);
          Object.assign(safeObj, val);

          const fields = Object.entries(safeObj).map(([key, value]) => {
            const pythonKey = toSnakeCase(key);
            const type = getPythonType(value, key, depth + 1);
            // Sanitize user-provided key in Python comments to prevent single-line comment breakout
            const safeCommentKey = key.replace(/[\n\r\t\v\f]/g, ' ').replace(/#/g, '');
            const comment = pythonKey !== key ? `  # Original JSON key: ${safeCommentKey}` : '';

            if (pythonStyle === 'dataclass') {
              return `    ${pythonKey}: ${type}${comment}`;
            } else {
              return `    ${pythonKey}: ${type}${comment}`;
            }
          });

          let classStr = '';
          if (pythonStyle === 'dataclass') {
            classStr = `@dataclass\nclass ${finalName}:\n`;
          } else {
            classStr = `class ${finalName}(TypedDict):\n`;
          }

          classStr += fields.join('\n');
          if (fields.length === 0) classStr += '    pass';

          classes.push(classStr);
          classNames.add(finalName);
          return finalName;
        }

        if (typeof val === 'string') return 'str';
        if (typeof val === 'number') return Number.isInteger(val) ? 'int' : 'float';
        if (typeof val === 'boolean') return 'bool';

        return 'Any';
      };

      getPythonType(parsed, 'Root', 0);

      let result = '';
      if (pythonStyle === 'dataclass') {
        result = 'from dataclasses import dataclass\nfrom typing import List, Optional, Any\n\n';
      } else {
        result = 'from typing import TypedDict, List, Optional, Any\n\n';
      }

      result += classes.reverse().join('\n\n');

      if (classes.length === 0) {
        const simpleType = getPythonType(parsed, 'Root', 0);
        result += `RootObject = ${simpleType}`;
      }

      setOutput(result);
      setError('');
    } catch (e: any) {
      setError(t('error.invalid_json') + ': ' + e.message);
      setOutput('');
    }
  }, [input, pythonStyle, t]);

  useEffect(() => {
    handleConvert();
  }, [handleConvert]);

  const handleCopy = useCallback(() => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    toast.success(t('common.copied', { defaultValue: 'Copied to clipboard!' }));
    setTimeout(() => setCopied(false), 2000);
  }, [output, t]);

  const handleClear = useCallback(() => {
    setInput('');
    setOutput('');
    setError('');
    setActivePreset(null);
    toast.info(t('common.cleared', { defaultValue: 'Cleared input' }));
    if (primaryInputRef.current) {
      primaryInputRef.current.focus();
    }
  }, [t]);

  const handlePresetSelect = (preset: Preset) => {
    setInput(preset.json);
    setActivePreset(preset.id);
    toast.success(t('jsontopython.preset_loaded', { defaultValue: 'Preset loaded!' }));
    if (primaryInputRef.current) {
      primaryInputRef.current.focus();
    }
  };

  const handlersRef = useRef({
    handleCopy,
    handleClear
  });

  useEffect(() => {
    handlersRef.current = { handleCopy, handleClear };
  }, [handleCopy, handleClear]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const activeEl = document.activeElement;
      if (containerRef.current && activeEl && activeEl !== document.body && !containerRef.current.contains(activeEl)) {
        return;
      }

      const isEditable =
        activeEl?.tagName === 'INPUT' ||
        activeEl?.tagName === 'TEXTAREA' ||
        activeEl?.tagName === 'SELECT' ||
        activeEl?.getAttribute('contenteditable') === 'true';

      if (e.key === 'Escape') {
        e.preventDefault();
        handlersRef.current.handleClear();
      } else if (!isEditable && e.key.toLowerCase() === 'c' && !e.metaKey && !e.ctrlKey && !e.altKey && !e.shiftKey) {
        e.preventDefault();
        handlersRef.current.handleCopy();
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/x-python' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = pythonStyle === 'dataclass' ? 'dataclasses.py' : 'typed_dicts.py';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(t('common.downloaded', { defaultValue: 'File downloaded!' }));
  };

  return (
    <div ref={containerRef} className="max-w-6xl mx-auto space-y-8">
      {/* Quick Start Presets */}
      <div className="bg-slate-50 dark:bg-slate-900/50 p-4 rounded-2xl border border-slate-200 dark:border-slate-800 space-y-3">
        <div className="flex items-center gap-2 text-xs font-black uppercase tracking-wider text-slate-500 dark:text-slate-400">
          <Sparkles className="w-3.5 h-3.5 text-indigo-500" />
          <span>{t('jsontopython.presets_label', { defaultValue: 'Quick Start Presets' })}</span>
        </div>
        <div className="flex flex-wrap gap-2">
          {PRESETS.map((preset) => (
            <button
              key={preset.id}
              onClick={() => handlePresetSelect(preset)}
              aria-pressed={activePreset === preset.id}
              className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 ${
                activePreset === preset.id
                  ? 'bg-indigo-600 text-white shadow-md shadow-indigo-500/20'
                  : 'bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700 hover:border-indigo-300 dark:hover:border-indigo-700'
              }`}
            >
              {t(preset.nameKey, { defaultValue: preset.id })}
            </button>
          ))}
        </div>
      </div>

      {/* Target Python Style Selector */}
      <div className="flex flex-wrap items-center justify-between gap-4 bg-white dark:bg-slate-900 p-4 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="flex items-center gap-2">
          <span className="text-xs font-black uppercase tracking-wider text-slate-500 dark:text-slate-400">
            {t('jsontopython.style_label', { defaultValue: 'Python Class Type' })}:
          </span>
        </div>
        <div className="flex rounded-xl bg-slate-100 dark:bg-slate-800 p-1 border border-slate-200 dark:border-slate-700">
          <button
            onClick={() => setPythonStyle('dataclass')}
            aria-pressed={pythonStyle === 'dataclass'}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
              pythonStyle === 'dataclass'
                ? 'bg-white dark:bg-slate-700 text-indigo-600 dark:text-indigo-400 shadow-xs'
                : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
            }`}
          >
            {t('jsontopython.style_dataclass', { defaultValue: 'Dataclasses (Python 3.7+)' })}
          </button>
          <button
            onClick={() => setPythonStyle('typeddict')}
            aria-pressed={pythonStyle === 'typeddict'}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
              pythonStyle === 'typeddict'
                ? 'bg-white dark:bg-slate-700 text-indigo-600 dark:text-indigo-400 shadow-xs'
                : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
            }`}
          >
            {t('jsontopython.style_typeddict', { defaultValue: 'TypedDict (Python 3.8+)' })}
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-indigo-500" />
              <label htmlFor="json-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('common.input')} JSON
              </label>
            </div>
            <div className="flex items-center gap-2">
              <Kbd modifier={null} className="hidden sm:inline-flex border-rose-200 dark:border-rose-800 text-rose-400 dark:bg-slate-900">
                Esc
              </Kbd>
              <button
                onClick={handleClear}
                disabled={!input && !output}
                className="text-xs font-bold px-3 py-1 rounded-full text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-rose-500 focus-visible:outline-none"
              >
                <Trash2 className="w-3 h-3" /> {t('common.clear')}
              </button>
            </div>
          </div>
          <textarea
            ref={primaryInputRef}
            id="json-input"
            value={input}
            onChange={(e) => {
              setInput(e.target.value);
              setActivePreset(null);
            }}
            placeholder='{"id": 1, "name": "John"}'
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none"
          />
        </div>

        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-emerald-500" />
              <label htmlFor="python-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('jsontopython.output_label')}
              </label>
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                disabled={!output}
                className="text-xs font-bold px-3 py-1 rounded-full text-indigo-500 bg-indigo-50 dark:bg-indigo-500/10 hover:bg-indigo-100 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
              >
                <Download className="w-3 h-3" /> {t('common.download')}
              </button>
              <button
                onClick={handleCopy}
                disabled={!output}
                className={`text-xs font-bold px-3 py-1 rounded-full transition-all flex items-center gap-1 border focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-500/20'
                    : 'text-slate-500 bg-slate-100 dark:bg-slate-800 border-transparent hover:bg-slate-200 dark:hover:bg-slate-700 disabled:opacity-50 disabled:cursor-not-allowed'
                }`}
              >
                {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}{' '}
                {copied ? t('common.copied') : t('common.copy')}
                {!copied && (
                  <Kbd modifier={null} className="hidden sm:inline-flex w-4 h-4 bg-white/50 dark:bg-black/20 ml-1">
                    C
                  </Kbd>
                )}
              </button>
            </div>
          </div>
          <textarea
            id="python-output"
            value={output}
            readOnly
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400 resize-none"
          />
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold">
          <AlertCircle className="w-5 h-5" />
          {error}
        </div>
      )}

      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <Info className="w-6 h-6 text-indigo-500 mt-1" />
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">{t('jsontopython.about_title')}</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">{t('jsontopython.about_text')}</p>
        </div>
      </div>
    </div>
  );
}
