import { useState, useMemo, useEffect, useCallback, useRef } from 'react';
import { Copy, Check, Trash2, Download, Braces, Share2, Info, ArrowRight, Network } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;
const MAX_DEPTH = 20;

type DiagramMode = 'class' | 'mindmap' | 'flowchart';

export function JSONToMermaid({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const [json, setJson] = useState(initialData?.json || '{\n  "user": {\n    "id": 1,\n    "name": "John Doe",\n    "profile": {\n      "bio": "Developer",\n      "social": ["twitter", "github"]\n    }\n  }\n}');
  const [mode, setMode] = useState<DiagramMode>(initialData?.mode || 'class');
  const [direction, setDirection] = useState<'TD' | 'LR'>(initialData?.direction || 'TD');
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [activePreset, setActivePreset] = useState<string | null>(null);

  useEffect(() => {
    onStateChange?.({ json, mode, direction });
  }, [json, mode, direction, onStateChange]);

  const presets: Record<string, any> = {
    user_profile: {
      user: {
        id: 101,
        username: 'johndoe',
        email: 'john@example.com',
        active: true,
        profile: {
          fullName: 'John Doe',
          bio: 'Senior Software Engineer',
          avatarUrl: 'https://example.com/avatar.png'
        },
        roles: ['admin', 'developer']
      }
    },
    ecommerce_order: {
      order: {
        orderId: 'ORD-98765',
        status: 'PROCESSING',
        totalAmount: 149.99,
        customer: {
          customerId: 'CUST-4321',
          name: 'Alice Smith'
        },
        items: [
          {
            sku: 'PROD-001',
            name: 'Wireless Mouse',
            price: 29.99,
            quantity: 1
          },
          {
            sku: 'PROD-002',
            name: 'Mechanical Keyboard',
            price: 120.0,
            quantity: 1
          }
        ]
      }
    },
    api_config: {
      server: {
        host: 'localhost',
        port: 8080,
        environment: 'production',
        database: {
          dialect: 'postgresql',
          poolSize: 10,
          ssl: true
        },
        features: {
          rateLimiting: true,
          metrics: true
        }
      }
    }
  };

  const sanitizeMermaid = useCallback((str: string, isIdentifier = false) => {
    if (isIdentifier) {
      let ident = str.replace(/[^a-zA-Z0-9_]/g, '_');
      if (/^[0-9]/.test(ident)) ident = '_' + ident;
      return ident || 'unnamed';
    }
    return str
      .replace(/[\n\r]/g, ' ')
      .replace(/[(){}[\]]/g, ' ')
      .replace(/"/g, "'");
  }, []);

  const getClassName = useCallback((key: string) => {
    const sanitized = key.replace(/[^a-zA-Z0-9]/g, '');
    return (sanitized.charAt(0).toUpperCase() + sanitized.slice(1)) || 'AutoGenerated';
  }, []);

  useEffect(() => {
    if (json.length > MAX_LENGTH) {
      setError(t('error.max_length', { max: MAX_LENGTH.toLocaleString() }));
    } else {
      try {
        if (json.trim()) JSON.parse(json);
        setError(null);
      } catch (e) {
        setError(t('error.invalid_json'));
      }
    }
  }, [json, t]);

  const mermaidCode = useMemo(() => {
    if (!json.trim() || json.length > MAX_LENGTH) return '';
    try {
      const parsed = JSON.parse(json);

      if (mode === 'flowchart') {
        let result = `graph ${direction}\n`;
        let nodeCounter = 0;

        const traverseFlowchart = (obj: any, parentId: string, depth = 0) => {
          if (depth > MAX_DEPTH) return;
          if (Array.isArray(obj)) {
            obj.forEach((item, index) => {
              const currentId = `n${nodeCounter++}`;
              const label = typeof item === 'object' && item !== null ? `Item ${index}` : String(item);
              result += `  ${currentId}["${sanitizeMermaid(label)}"]\n`;
              result += `  ${parentId} --> ${currentId}\n`;
              if (typeof item === 'object' && item !== null) {
                traverseFlowchart(item, currentId, depth + 1);
              }
            });
          } else if (typeof obj === 'object' && obj !== null) {
            Object.entries(obj).forEach(([key, value]) => {
              if (key === '__proto__' || key === 'constructor' || key === 'prototype') return;
              const currentId = `n${nodeCounter++}`;
              result += `  ${currentId}["${sanitizeMermaid(key)}"]\n`;
              result += `  ${parentId} --> ${currentId}\n`;
              if (typeof value === 'object' && value !== null) {
                traverseFlowchart(value, currentId, depth + 1);
              } else {
                const leafId = `n${nodeCounter++}`;
                result += `  ${leafId}("${sanitizeMermaid(String(value))}")\n`;
                result += `  ${currentId} --- ${leafId}\n`;
              }
            });
          }
        };

        const rootId = `n${nodeCounter++}`;
        result += `  ${rootId}(("JSON"))\n`;
        traverseFlowchart(parsed, rootId, 0);
        return result;
      } else if (mode === 'mindmap') {
        let result = 'mindmap\n  root((JSON))\n';
        const traverse = (obj: any, depth: number) => {
          if (depth > MAX_DEPTH) return;
          if (Array.isArray(obj)) {
            obj.forEach((item, index) => {
              const label = typeof item === 'object' && item !== null ? `Item ${index}` : String(item);
              result += `${'  '.repeat(depth + 1)}${sanitizeMermaid(label)}\n`;
              if (typeof item === 'object' && item !== null) {
                traverse(item, depth + 1);
              }
            });
          } else if (typeof obj === 'object' && obj !== null) {
            Object.entries(obj).forEach(([key, value]) => {
              if (key === '__proto__' || key === 'constructor' || key === 'prototype') return;
              result += `${'  '.repeat(depth + 1)}${sanitizeMermaid(key)}\n`;
              if (typeof value === 'object' && value !== null) {
                traverse(value, depth + 1);
              }
            });
          }
        };
        traverse(parsed, 1);
        return result;
      } else {
        // Class Diagram mode
        let result = 'classDiagram\n';
        const classes = new Map<string, string>();
        const relations = new Set<string>();

        const traverse = (obj: any, name: string, depth = 0) => {
          if (depth > MAX_DEPTH) return;
          const className = getClassName(name);
          let classBody = `  class ${className} {\n`;

          if (Array.isArray(obj)) {
            classBody += `    +Array items\n`;
            if (obj.length > 0 && typeof obj[0] === 'object' && obj[0] !== null) {
              const subName = name + 'Item';
              traverse(obj[0], subName, depth + 1);
              relations.add(`${className} ..> ${getClassName(subName)} : contains`);
            }
          } else if (typeof obj === 'object' && obj !== null) {
            Object.entries(obj).forEach(([key, value]) => {
              if (key === '__proto__' || key === 'constructor' || key === 'prototype') return;
              const type = Array.isArray(value) ? 'Array' : typeof value;
              classBody += `    +${type} ${sanitizeMermaid(key, true)}\n`;

              if (typeof value === 'object' && value !== null) {
                const subName = key;
                traverse(value, subName, depth + 1);
                relations.add(`${className} --* ${getClassName(subName)}`);
              }
            });
          }

          classBody += '  }\n';
          classes.set(className, classBody);
        };

        traverse(parsed, 'Root', 0);

        classes.forEach((body) => {
          result += body;
        });
        relations.forEach((rel) => {
          result += `  ${rel}\n`;
        });

        return result;
      }
    } catch (e) {
      return '';
    }
  }, [json, mode, direction, sanitizeMermaid, getClassName]);

  const handleCopy = useCallback(() => {
    if (!mermaidCode) return;
    navigator.clipboard.writeText(mermaidCode);
    setCopied(true);
    toast.success(t('common.copied', 'Copied to clipboard!'));
    setTimeout(() => setCopied(false), 2000);
  }, [mermaidCode, t]);

  const handleDownload = useCallback(() => {
    if (!mermaidCode) return;
    const blob = new Blob([mermaidCode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `diagram-${mode}.mmd`;
    link.click();
    URL.revokeObjectURL(url);
    toast.success(t('common.downloaded', 'File downloaded'));
  }, [mermaidCode, mode, t]);

  const handleClear = useCallback(() => {
    setJson('');
    setError(null);
    setActivePreset(null);
    toast.success(t('common.cleared', 'Input cleared!'));
    setTimeout(() => textareaRef.current?.focus(), 0);
  }, [t]);

  const handlePresetSelect = (presetKey: string) => {
    if (presets[presetKey]) {
      setJson(JSON.stringify(presets[presetKey], null, 2));
      setActivePreset(presetKey);
      setError(null);
      toast.success(t('jsontomermaid.preset_loaded', 'Preset loaded!'));
    }
  };

  const handlersRef = useRef({ handleClear, handleCopy, mermaidCode });
  useEffect(() => {
    handlersRef.current = { handleClear, handleCopy, mermaidCode };
  }, [handleClear, handleCopy, mermaidCode]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const activeElement = document.activeElement;
      const isEditable =
        activeElement instanceof HTMLInputElement ||
        activeElement instanceof HTMLTextAreaElement ||
        activeElement instanceof HTMLSelectElement ||
        activeElement?.getAttribute('contenteditable') === 'true';

      if (isEditable && e.key !== 'Escape') return;
      if (e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;

      if (e.key === 'Escape') {
        e.preventDefault();
        handlersRef.current.handleClear();
      } else if (e.key.toLowerCase() === 'c') {
        if (handlersRef.current.mermaidCode) {
          e.preventDefault();
          handlersRef.current.handleCopy();
        }
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  return (
    <div ref={containerRef} className="max-w-6xl mx-auto space-y-8 animate-in fade-in duration-500">
      {/* Presets and options bar */}
      <div className="p-6 bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800 rounded-3xl flex flex-col md:flex-row gap-4 items-start md:items-center justify-between">
        <div className="space-y-2">
          <span className="text-xs font-black uppercase tracking-widest text-slate-400 block">
            {t('jsontomermaid.presets_title', 'Quick Presets:')}
          </span>
          <div className="flex flex-wrap gap-2">
            <button
              onClick={() => handlePresetSelect('user_profile')}
              aria-pressed={activePreset === 'user_profile'}
              className={`text-xs font-bold px-3 py-1.5 rounded-xl transition-all ${
                activePreset === 'user_profile'
                  ? 'bg-indigo-600 text-white shadow-sm ring-2 ring-indigo-500/30'
                  : 'bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-300 border border-slate-200 dark:border-slate-700 hover:border-indigo-500'
              }`}
            >
              👤 {t('jsontomermaid.preset_user', 'User Profile')}
            </button>
            <button
              onClick={() => handlePresetSelect('ecommerce_order')}
              aria-pressed={activePreset === 'ecommerce_order'}
              className={`text-xs font-bold px-3 py-1.5 rounded-xl transition-all ${
                activePreset === 'ecommerce_order'
                  ? 'bg-indigo-600 text-white shadow-sm ring-2 ring-indigo-500/30'
                  : 'bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-300 border border-slate-200 dark:border-slate-700 hover:border-indigo-500'
              }`}
            >
              🛒 {t('jsontomermaid.preset_order', 'E-Commerce Order')}
            </button>
            <button
              onClick={() => handlePresetSelect('api_config')}
              aria-pressed={activePreset === 'api_config'}
              className={`text-xs font-bold px-3 py-1.5 rounded-xl transition-all ${
                activePreset === 'api_config'
                  ? 'bg-indigo-600 text-white shadow-sm ring-2 ring-indigo-500/30'
                  : 'bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-300 border border-slate-200 dark:border-slate-700 hover:border-indigo-500'
              }`}
            >
              ⚙️ {t('jsontomermaid.preset_config', 'API Config')}
            </button>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          <span className="text-xs font-black uppercase tracking-widest text-slate-400">
            {t('jsontomermaid.mode_label', 'Diagram Mode:')}
          </span>
          <div className="flex bg-white dark:bg-slate-800 p-1 rounded-xl border border-slate-200 dark:border-slate-700">
            <button
              onClick={() => setMode('class')}
              aria-pressed={mode === 'class'}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
                mode === 'class'
                  ? 'bg-slate-900 text-white dark:bg-white dark:text-slate-950 shadow-sm'
                  : 'text-slate-500 hover:text-slate-800 dark:hover:text-slate-200'
              }`}
            >
              {t('jsontomermaid.mode_class', 'Class Diagram')}
            </button>
            <button
              onClick={() => setMode('mindmap')}
              aria-pressed={mode === 'mindmap'}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
                mode === 'mindmap'
                  ? 'bg-slate-900 text-white dark:bg-white dark:text-slate-950 shadow-sm'
                  : 'text-slate-500 hover:text-slate-800 dark:hover:text-slate-200'
              }`}
            >
              {t('jsontomermaid.mode_mindmap', 'Mindmap')}
            </button>
            <button
              onClick={() => setMode('flowchart')}
              aria-pressed={mode === 'flowchart'}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
                mode === 'flowchart'
                  ? 'bg-slate-900 text-white dark:bg-white dark:text-slate-950 shadow-sm'
                  : 'text-slate-500 hover:text-slate-800 dark:hover:text-slate-200'
              }`}
            >
              {t('jsontomermaid.mode_flowchart', 'Flowchart')}
            </button>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Left: Input */}
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <Braces className="w-4 h-4 text-indigo-500" />
              <label htmlFor="json-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('common.input')} JSON
              </label>
            </div>
            <div className="flex items-center gap-2">
              <Kbd modifier={null} className="hidden sm:inline-flex border-rose-200 dark:border-rose-800 text-rose-400 dark:bg-slate-900">
                Esc
              </Kbd>
              <button
                onClick={handleClear}
                disabled={!json && !mermaidCode}
                className="text-xs font-bold text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 dark:hover:bg-rose-500/20 px-3 py-1.5 rounded-xl flex items-center gap-1 transition-all disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-rose-500 focus-visible:outline-none"
              >
                <Trash2 className="w-3 h-3" /> {t('common.clear')}
              </button>
            </div>
          </div>
          <div className="relative group">
            <textarea
              id="json-input"
              ref={textareaRef}
              value={json}
              onChange={(e) => {
                setJson(e.target.value);
                setActivePreset(null);
              }}
              placeholder='{"key": "value"}'
              className={`w-full h-[500px] p-6 bg-slate-50 dark:bg-slate-900 border ${
                error ? 'border-rose-500 focus:ring-rose-500/20' : 'border-slate-200 dark:border-slate-800 focus:ring-indigo-500/20'
              } rounded-3xl outline-none focus:ring-2 transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none`}
            />
            {error && (
              <div className="absolute bottom-4 right-4 px-3 py-1 bg-rose-500 text-white text-xs font-bold rounded-lg animate-in fade-in zoom-in">
                {error}
              </div>
            )}
          </div>
        </div>

        {/* Right: Output */}
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <Network className="w-4 h-4 text-emerald-500 animate-pulse" />
              <label htmlFor="mermaid-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('jsontomermaid.output_label', 'Mermaid Syntax')}
              </label>
            </div>
            <div className="flex items-center gap-2">
              {mode === 'flowchart' && (
                <div className="flex bg-slate-100 dark:bg-slate-800 p-1 rounded-xl border border-slate-200 dark:border-slate-700">
                  <button
                    onClick={() => setDirection('TD')}
                    aria-pressed={direction === 'TD'}
                    className={`px-3 py-1 rounded-lg text-[10px] font-black transition-all ${
                      direction === 'TD' ? 'bg-white dark:bg-slate-700 text-indigo-600 shadow-sm' : 'text-slate-500'
                    }`}
                  >
                    {t('jsontomermaid.direction_td', 'Top-Down')}
                  </button>
                  <button
                    onClick={() => setDirection('LR')}
                    aria-pressed={direction === 'LR'}
                    className={`px-3 py-1 rounded-lg text-[10px] font-black transition-all ${
                      direction === 'LR' ? 'bg-white dark:bg-slate-700 text-indigo-600 shadow-sm' : 'text-slate-500'
                    }`}
                  >
                    {t('jsontomermaid.direction_lr', 'Left-Right')}
                  </button>
                </div>
              )}
              <button
                onClick={handleDownload}
                disabled={!mermaidCode}
                className="text-xs font-bold text-indigo-500 bg-indigo-50 dark:bg-indigo-500/10 hover:bg-indigo-100 px-3 py-1.5 rounded-xl flex items-center gap-1 transition-all disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
              >
                <Download className="w-3 h-3" /> {t('common.download')}
              </button>
              <button
                onClick={handleCopy}
                disabled={!mermaidCode}
                className={`text-xs font-bold px-3 py-1.5 rounded-xl transition-all flex items-center gap-1 border focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-200 dark:border-emerald-500/20'
                    : 'text-slate-600 dark:text-slate-400 bg-slate-100 dark:bg-slate-800 border-transparent hover:bg-slate-200 dark:hover:bg-slate-700'
                } disabled:opacity-50`}
              >
                {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                {copied ? t('common.copied') : t('common.copy')}
                {!copied && json && <Kbd modifier={null} className="hidden sm:inline-flex w-4 h-4 bg-white/50 dark:bg-black/20 ml-1">C</Kbd>}
              </button>
            </div>
          </div>
          <div className="relative group">
            <textarea
              id="mermaid-output"
              value={mermaidCode}
              readOnly
              placeholder={t('common.waiting')}
              className="w-full h-[500px] p-6 bg-slate-900 text-slate-100 rounded-3xl outline-none font-mono text-sm leading-relaxed border border-slate-800 resize-none"
            />
          </div>
        </div>
      </div>

      {/* Info Sections */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 pt-12 border-t border-slate-100 dark:border-slate-800">
        <div className="space-y-4">
          <h4 className="font-bold dark:text-white flex items-center gap-2 text-indigo-500">
            <Info className="w-4 h-4" /> {t('jsontomermaid.what_is_title', 'What is this tool?')}
          </h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            {t('jsontomermaid.what_is_text', 'Convert your JSON data structures into Mermaid.js diagram code. Mermaid is a markdown-like script language for generating charts and diagrams. This tool helps you visualize complex nested objects and their relationships.')}
          </p>
        </div>
        <div className="space-y-4">
          <h4 className="font-bold dark:text-white flex items-center gap-2 text-indigo-500">
            <ArrowRight className="w-4 h-4" /> {t('jsontomermaid.modes_title', 'Diagram Modes')}
          </h4>
          <ul className="text-sm text-slate-500 dark:text-slate-400 space-y-2">
            <li>
              <strong>Class Diagram:</strong> {t('jsontomermaid.class_desc', 'Shows objects as classes with typed properties and composition relationships.')}
            </li>
            <li>
              <strong>Mindmap:</strong> {t('jsontomermaid.mindmap_desc', 'Visualizes the JSON as a hierarchical tree or mindmap, perfect for seeing nesting levels.')}
            </li>
            <li>
              <strong>Flowchart:</strong> {t('jsontomermaid.flowchart_desc', 'Generates a node-link diagram representing the structure as a process flow.')}
            </li>
          </ul>
        </div>
        <div className="space-y-4">
          <h4 className="font-bold dark:text-white flex items-center gap-2 text-indigo-500">
            <Share2 className="w-4 h-4" /> {t('jsontomermaid.usage_title', 'How to use?')}
          </h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            {t('jsontomermaid.usage_text', 'Paste your JSON on the left. The Mermaid code is generated instantly on the right. You can then copy this code and paste it into any Mermaid-compatible editor (like Notion, GitHub, or Mermaid Live Editor) to render the graphic.')}
          </p>
        </div>
      </div>
    </div>
  );
}
