import { useState, useEffect, useCallback, useRef } from 'react';
import { FileCode, Copy, Check, Trash2, AlertCircle, Download, Info, Settings, Sparkles } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;
const MAX_DEPTH = 20;

interface Preset {
  name: string;
  data: object;
}

const PRESETS: Preset[] = [
  {
    name: 'User Profile & Roles',
    data: {
      id: 101,
      username: 'alex_developer',
      email: 'alex@example.com',
      is_active: true,
      roles: ['admin', 'developer'],
      profile: {
        first_name: 'Alex',
        last_name: 'Rivera',
        avatar_url: 'https://example.com/avatars/alex.png',
        created_at: '2025-01-15T08:30:00Z'
      }
    }
  },
  {
    name: 'E-Commerce Order',
    data: {
      order_id: 'ORD-98765',
      customer_id: 452,
      total_amount: 149.99,
      status: 'SHIPPED',
      items: [
        { product_id: 'PRD-001', quantity: 2, unit_price: 49.99 },
        { product_id: 'PRD-004', quantity: 1, unit_price: 50.0 }
      ],
      shipping_address: {
        street: '123 Tech Lane',
        city: 'San Francisco',
        country: 'USA',
        postal_code: '94105'
      }
    }
  },
  {
    name: 'API Health Status',
    data: {
      service: 'payment-gateway-api',
      status: 'HEALTHY',
      uptime_seconds: 86400,
      checks: {
        database: true,
        redis_cache: true,
        third_party_webhooks: true
      },
      latency_ms: 12.5
    }
  },
  {
    name: 'System Metrics',
    data: {
      timestamp: 1735689600,
      cpu_usage_percent: 42.8,
      memory_mb: 8192,
      disk: {
        total_gb: 512,
        used_gb: 210.5,
        free_gb: 301.5
      },
      active_threads: 24
    }
  }
];

const sanitizeKey = (key: string): string => {
  if (key === '__proto__' || key === 'constructor' || key === 'prototype') {
    return '_' + key;
  }
  return key;
};

const toCamelCase = (str: string) => {
  return str.replace(/_([a-z0-9])/gi, (_, letter) => letter.toUpperCase());
};

const toSnakeCase = (str: string) => {
  return str
    .replace(/([A-Z])/g, '_$1')
    .toLowerCase()
    .replace(/^_/, '')
    .replace(/[^a-z0-9_]/g, '_');
};

const toPascalCase = (str: string) => {
  return (
    str
      .replace(/[^a-z0-9]/gi, ' ')
      .split(' ')
      .filter(Boolean)
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('') || 'AutoGenerated'
  );
};

export function JSONToProtobuf({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const [input, setInput] = useState(initialData?.input || '');
  const [output, setOutput] = useState(initialData?.output || '');
  const [packageName, setPackageName] = useState(initialData?.packageName || 'model');
  const [syntaxVersion, setSyntaxVersion] = useState<'proto3' | 'proto2'>(initialData?.syntaxVersion || 'proto3');
  const [casingMode, setCasingMode] = useState<'original' | 'snake_case' | 'camelCase'>(initialData?.casingMode || 'original');
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  const inputRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    onStateChange?.({ input, output, packageName, syntaxVersion, casingMode });
  }, [input, output, packageName, syntaxVersion, casingMode, onStateChange]);

  const handleConvert = useCallback(() => {
    try {
      if (!input.trim()) {
        setOutput('');
        setError('');
        return;
      }
      if (input.length > MAX_LENGTH) {
        setError(t('jsontoprotobuf.error_max_length', { max: MAX_LENGTH.toLocaleString() }));
        setOutput('');
        return;
      }
      const parsed = JSON.parse(input);
      const messages: string[] = [];
      const messageNames = new Set<string>();

      const getProtoType = (val: any, fieldName: string, depth: number): string => {
        if (depth > MAX_DEPTH) return 'google.protobuf.Value';
        if (val === null || val === undefined) return 'google.protobuf.Value';

        if (Array.isArray(val)) {
          const itemType = val.length > 0 ? getProtoType(val[0], fieldName, depth + 1) : 'google.protobuf.Value';
          return `repeated ${itemType}`;
        }

        if (typeof val === 'object') {
          let name = toPascalCase(fieldName);
          if (name === 'Root') name = 'RootObject';

          let finalName = name;
          let counter = 1;
          while (messageNames.has(finalName)) {
            finalName = name + counter++;
          }

          const fields = Object.entries(val).map(([rawKey, value], index) => {
            const key = sanitizeKey(rawKey);
            const type = getProtoType(value, key, depth + 1);

            let transformedKey = key;
            if (casingMode === 'snake_case') transformedKey = toSnakeCase(key);
            else if (casingMode === 'camelCase') transformedKey = toCamelCase(key);

            let safeKey = transformedKey.replace(/[^a-zA-Z0-9_]/g, '_');
            if (/^[0-9]/.test(safeKey)) safeKey = 'f_' + safeKey;
            if (!safeKey || safeKey === '_') safeKey = `field_${index + 1}`;

            const safeCommentKey = key.replace(/[\n\r\t\v\f]/g, ' ').replace(/\*\//g, '* /');
            const comment = key !== safeKey ? ` // Original JSON key: ${safeCommentKey}` : '';
            const optionalModifier = syntaxVersion === 'proto2' && !type.startsWith('repeated ') ? 'optional ' : '';
            return `  ${optionalModifier}${type} ${safeKey} = ${index + 1};${comment}`;
          });

          let messageStr = `message ${finalName} {\n`;
          messageStr += fields.join('\n');
          messageStr += '\n}';

          messages.push(messageStr);
          messageNames.add(finalName);
          return finalName;
        }

        if (typeof val === 'string') return 'string';
        if (typeof val === 'number') return Number.isInteger(val) ? 'int32' : 'double';
        if (typeof val === 'boolean') return 'bool';

        return 'google.protobuf.Value';
      };

      getProtoType(parsed, 'Root', 0);

      const pkg = packageName.trim() ? packageName.trim().replace(/[^a-zA-Z0-9._]/g, '_') : 'model';
      let result = `syntax = "${syntaxVersion}";\n\npackage ${pkg};\n\n`;
      result += messages.reverse().join('\n\n');

      if (messages.length === 0) {
        const simpleType = getProtoType(parsed, 'Root', 0);
        result = `syntax = "${syntaxVersion}";\n\npackage ${pkg};\n\n// Root was not an object\n// type RootObject = ${simpleType}`;
      }

      setOutput(result);
      setError('');
    } catch (e: any) {
      setError(t('jsontoprotobuf.error_invalid_json', 'Invalid JSON syntax') + ': ' + e.message);
      setOutput('');
    }
  }, [input, packageName, syntaxVersion, casingMode, t]);

  useEffect(() => {
    handleConvert();
  }, [handleConvert]);

  const handleCopy = useCallback(() => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    toast.success(t('jsontoprotobuf.toast_copied', 'Protobuf schema copied to clipboard!'));
    setTimeout(() => setCopied(false), 2000);
  }, [output, t]);

  const handleClear = useCallback(() => {
    setInput('');
    setOutput('');
    setError('');
    toast.success(t('jsontoprotobuf.toast_cleared', 'Inputs cleared'));
    setTimeout(() => inputRef.current?.focus(), 0);
  }, [t]);

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${packageName || 'model'}.proto`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(t('jsontoprotobuf.toast_downloaded', 'Downloaded .proto file'));
  };

  const handleApplyPreset = (preset: Preset) => {
    setInput(JSON.stringify(preset.data, null, 2));
    toast.success(t('jsontoprotobuf.toast_preset', 'Applied preset: ') + preset.name);
    setTimeout(() => inputRef.current?.focus(), 0);
  };

  const handlersRef = useRef({ handleCopy, handleClear });
  useEffect(() => {
    handlersRef.current = { handleCopy, handleClear };
  }, [handleCopy, handleClear]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const activeElement = document.activeElement;
      const isEditable =
        activeElement instanceof HTMLInputElement ||
        activeElement instanceof HTMLTextAreaElement ||
        activeElement instanceof HTMLSelectElement ||
        activeElement?.getAttribute('contenteditable') === 'true';

      if (isEditable && e.key !== 'Escape') return;
      if (e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;

      if (e.key === 'Escape') {
        e.preventDefault();
        handlersRef.current.handleClear();
      } else if (e.key.toLowerCase() === 'c') {
        e.preventDefault();
        handlersRef.current.handleCopy();
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  return (
    <div className="max-w-6xl mx-auto space-y-8">
      {/* Configuration & Options Card */}
      <div className="bg-slate-50 dark:bg-slate-900/50 p-6 rounded-[2rem] border border-slate-200 dark:border-slate-800 space-y-6">
        <div className="flex items-center gap-2 px-1">
          <Settings className="w-4 h-4 text-indigo-500" />
          <h2 className="text-xs font-black uppercase tracking-widest text-slate-400">
            {t('jsontoprotobuf.options_title', 'Protobuf Configuration')}
          </h2>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {/* Package Name */}
          <div className="space-y-2">
            <label htmlFor="package-name-input" className="text-xs font-bold text-slate-500 px-1">
              {t('jsontoprotobuf.package_name', 'Package Name')}
            </label>
            <input
              id="package-name-input"
              type="text"
              value={packageName}
              onChange={(e) => setPackageName(e.target.value)}
              placeholder="model"
              className="w-full p-2.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl outline-none focus:ring-2 focus:ring-indigo-500/20 font-mono text-sm text-slate-700 dark:text-slate-200"
            />
          </div>

          {/* Syntax Version */}
          <div className="space-y-2">
            <label htmlFor="syntax-version-select" className="text-xs font-bold text-slate-500 px-1">
              {t('jsontoprotobuf.syntax_version', 'Protobuf Syntax')}
            </label>
            <select
              id="syntax-version-select"
              value={syntaxVersion}
              onChange={(e) => setSyntaxVersion(e.target.value as 'proto3' | 'proto2')}
              className="w-full p-2.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl outline-none focus:ring-2 focus:ring-indigo-500/20 font-bold text-sm text-slate-700 dark:text-slate-200"
            >
              <option value="proto3">proto3 (Standard Modern)</option>
              <option value="proto2">proto2 (Legacy)</option>
            </select>
          </div>

          {/* Casing Mode */}
          <div className="space-y-2">
            <label htmlFor="casing-mode-select" className="text-xs font-bold text-slate-500 px-1">
              {t('jsontoprotobuf.casing_mode', 'Field Casing')}
            </label>
            <select
              id="casing-mode-select"
              value={casingMode}
              onChange={(e) => setCasingMode(e.target.value as any)}
              className="w-full p-2.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl outline-none focus:ring-2 focus:ring-indigo-500/20 font-bold text-sm text-slate-700 dark:text-slate-200"
            >
              <option value="original">{t('jsontoprotobuf.case_original', 'As-Is (JSON original)')}</option>
              <option value="snake_case">snake_case (Protobuf standard)</option>
              <option value="camelCase">camelCase</option>
            </select>
          </div>
        </div>

        {/* Presets */}
        <div className="pt-4 border-t border-slate-200 dark:border-slate-800 space-y-2">
          <div className="flex items-center gap-2">
            <Sparkles className="w-3.5 h-3.5 text-indigo-500" />
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">
              {t('jsontoprotobuf.presets_title', 'Quick Start Presets')}
            </span>
          </div>
          <div className="flex flex-wrap gap-2">
            {PRESETS.map((p) => (
              <button
                key={p.name}
                type="button"
                onClick={() => handleApplyPreset(p)}
                className="px-3 py-1.5 rounded-xl text-xs font-bold bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-400 dark:hover:border-indigo-500 text-slate-700 dark:text-slate-300 transition-all shadow-sm"
              >
                {p.name}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Inputs / Outputs grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-indigo-500" />
              <label htmlFor="json-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('common.input', 'Input')} JSON
              </label>
            </div>
            <div className="flex items-center gap-2">
              <Kbd modifier={null} className="hidden sm:inline-flex border-rose-200 dark:border-rose-800 text-rose-400 dark:bg-slate-900">
                Esc
              </Kbd>
              <button
                type="button"
                onClick={handleClear}
                disabled={!input && !output}
                className="text-xs font-bold px-3 py-1 rounded-full text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 dark:hover:bg-rose-500/20 transition-all flex items-center gap-1 disabled:opacity-50 disabled:cursor-not-allowed focus-visible:ring-2 focus-visible:ring-rose-500 focus-visible:outline-none"
              >
                <Trash2 className="w-3 h-3" /> {t('common.clear', 'Clear')}
              </button>
            </div>
          </div>
          <textarea
            id="json-input"
            ref={inputRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder='{"id": 1, "name": "Protobuf", "tags": ["serialization", "binary"]}'
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none"
          />
        </div>

        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-emerald-500" />
              <label htmlFor="proto-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                Protobuf ({syntaxVersion})
              </label>
            </div>
            <div className="flex gap-2">
              <button
                type="button"
                onClick={handleDownload}
                disabled={!output}
                className="text-xs font-bold px-3 py-1 rounded-full text-indigo-500 bg-indigo-50 dark:bg-indigo-500/10 hover:bg-indigo-100 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
              >
                <Download className="w-3 h-3" /> {t('common.download', 'Download')}
              </button>
              <button
                type="button"
                onClick={handleCopy}
                disabled={!output}
                className={`text-xs font-bold px-3 py-1 rounded-full transition-all flex items-center gap-1 focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none border ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-200 dark:border-emerald-500/20'
                    : 'text-slate-500 bg-slate-100 dark:bg-slate-800 border-transparent hover:bg-slate-200'
                } disabled:opacity-50 disabled:cursor-not-allowed`}
              >
                {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />} {copied ? t('common.copied', 'Copied') : t('common.copy', 'Copy')}
                {!copied && <Kbd modifier={null} className="hidden sm:inline-flex w-4 h-4 bg-white/50 dark:bg-black/20 ml-1">C</Kbd>}
              </button>
            </div>
          </div>
          <textarea
            id="proto-output"
            value={output}
            readOnly
            placeholder={t('jsontoprotobuf.output_placeholder', 'Generated .proto definitions will appear here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400 resize-none"
          />
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold">
          <AlertCircle className="w-5 h-5" />
          {error}
        </div>
      )}

      {/* Info Card */}
      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <Info className="w-6 h-6 text-indigo-500 mt-1 shrink-0" />
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">{t('jsontoprotobuf.about_title', 'About JSON to Protobuf Conversion')}</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            {t(
              'jsontoprotobuf.about_text',
              'Protocol Buffers (Protobuf) is a language-neutral, platform-neutral mechanism for serializing structured data. This tool generates proto3 or proto2 message definitions from your JSON payloads. Nested objects are extracted into standalone messages and arrays are typed using the repeated modifier.'
            )}
          </p>
        </div>
      </div>
    </div>
  );
}
