import React, { useState, useEffect, useCallback, useRef } from 'react';
import { FileCode, Copy, Check, Trash2, AlertCircle, Download, Info, Sparkles, RefreshCw } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;
const MAX_DEPTH = 20;

interface Preset {
  id: string;
  nameKey: string;
  defaultName: string;
  data: object;
}

const PRESETS: Preset[] = [
  {
    id: 'user',
    nameKey: 'jsontoruby.preset_user',
    defaultName: 'User Profile',
    data: {
      id: 101,
      username: 'alex_ruby',
      email: 'alex@example.com',
      is_admin: true,
      roles: ['admin', 'developer'],
      created_at: '2025-01-15T08:30:00Z',
    },
  },
  {
    id: 'order',
    nameKey: 'jsontoruby.preset_order',
    defaultName: 'E-Commerce Order',
    data: {
      order_id: 'ORD-9872',
      total_amount: 149.99,
      currency: 'USD',
      items: [
        { item_id: 201, name: 'Mechanical Keyboard', quantity: 1, price: 149.99 },
      ],
      shipping: {
        address: '123 Tech Blvd',
        city: 'San Francisco',
        zip_code: '94105',
      },
    },
  },
  {
    id: 'config',
    nameKey: 'jsontoruby.preset_config',
    defaultName: 'API Config & Settings',
    data: {
      service_name: 'auth-service',
      version: '2.4.0',
      port: 8080,
      features: {
        enable_2fa: true,
        max_login_attempts: 5,
      },
      database: {
        host: 'localhost',
        max_connections: 20,
      },
    },
  },
];

export function JSONToRuby({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const [input, setInput] = useState(initialData?.input || JSON.stringify(PRESETS[0].data, null, 2));
  const [output, setOutput] = useState(initialData?.output || '');
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  const [activePreset, setActivePreset] = useState<string | null>('user');

  // Options
  const [accessorMode, setAccessorMode] = useState<'accessor' | 'reader' | 'accessor_frozen'>(
    initialData?.accessorMode || 'accessor'
  );
  const [constructMode, setConstructMode] = useState<'class' | 'data' | 'struct'>(
    initialData?.constructMode || 'class'
  );
  const [paramStyle, setParamStyle] = useState<'kwargs' | 'positional' | 'hash'>(
    initialData?.paramStyle || 'kwargs'
  );

  const containerRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    onStateChange?.({ input, output, accessorMode, constructMode, paramStyle });
  }, [input, output, accessorMode, constructMode, paramStyle, onStateChange]);

  const toPascalCase = (str: string) => {
    const sanitized = str.replace(/[^a-zA-Z0-9]/g, ' ').trim();
    if (!sanitized) return 'AutoGenerated';
    const pascal = sanitized
      .split(/\s+/)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');
    return /^[0-9]/.test(pascal) ? `Model${pascal}` : pascal;
  };

  const toSnakeCase = (str: string) => {
    let result = str
      .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
      .replace(/[^a-zA-Z0-9]/g, '_')
      .toLowerCase()
      .replace(/_+/g, '_')
      .replace(/^_+|_+$/g, '');

    if (!result) {
      result = 'property';
    }

    if (/^[0-9]/.test(result)) {
      result = 'r_' + result;
    }

    const keywords = [
      '__ENCODING__', '__LINE__', '__FILE__', 'BEGIN', 'END', 'alias', 'and', 'begin',
      'break', 'case', 'class', 'def', 'defined', 'do', 'else', 'elsif', 'end', 'ensure',
      'false', 'for', 'if', 'in', 'module', 'next', 'nil', 'not', 'or', 'redo', 'rescue',
      'retry', 'return', 'self', 'super', 'then', 'true', 'undef', 'unless', 'until', 'when',
      'while', 'yield'
    ];
    if (keywords.includes(result)) {
      result += '_';
    }

    return result;
  };

  const handleConvert = useCallback(() => {
    try {
      if (!input.trim()) {
        setOutput('');
        setError('');
        return;
      }
      if (input.length > MAX_LENGTH) {
        setError(t('error.max_length', { max: MAX_LENGTH.toLocaleString() }));
        return;
      }
      const parsed = JSON.parse(input);
      const classes: string[] = [];
      const classNames = new Set<string>();

      const getRubyType = (val: any, fieldName: string, depth: number): string => {
        if (depth > MAX_DEPTH) return 'Object';
        if (val === null || val === undefined) return 'NilClass';

        if (Array.isArray(val)) {
          const itemType = val.length > 0 ? getRubyType(val[0], fieldName, depth + 1) : 'Object';
          return `Array<${itemType}>`;
        }

        if (typeof val === 'object') {
          let name = toPascalCase(fieldName);
          if (name === 'Root') name = 'RootObject';

          let finalName = name;
          let counter = 1;
          while (classNames.has(finalName)) {
            finalName = `${name}${counter++}`;
          }

          const fieldEntries = Object.entries(val);
          const fields = fieldEntries.map(([key]) => toSnakeCase(key));

          // Recurse to generate nested types first
          fieldEntries.forEach(([key, value]) => {
            getRubyType(value, key, depth + 1);
          });

          let classStr = '';

          if (constructMode === 'data') {
            // Ruby 3.2+ Data.define
            if (fields.length > 0) {
              classStr = `${finalName} = Data.define(${fields.map(f => `:${f}`).join(', ')})`;
            } else {
              classStr = `${finalName} = Data.define`;
            }
          } else if (constructMode === 'struct') {
            // Struct.new
            if (fields.length > 0) {
              classStr = `${finalName} = Struct.new(${fields.map(f => `:${f}`).join(', ')}, keyword_init: true) do\n`;
              classStr += `  # Additional helper methods can be added here\n`;
              classStr += `end`;
            } else {
              classStr = `${finalName} = Struct.new do\n  # Empty struct\nend`;
            }
          } else {
            // Standard Ruby class
            classStr = `class ${finalName}\n`;
            if (fields.length > 0) {
              const attrDirective = accessorMode === 'reader' || accessorMode === 'accessor_frozen' ? 'attr_reader' : 'attr_accessor';
              classStr += `  ${attrDirective} ${fields.map(f => `:${f}`).join(', ')}\n\n`;

              if (paramStyle === 'kwargs') {
                classStr += `  def initialize(${fields.map(f => `${f}:`).join(', ')})\n`;
                fields.forEach(f => {
                  if (accessorMode === 'accessor_frozen') {
                    classStr += `    @${f} = ${f}.freeze\n`;
                  } else {
                    classStr += `    @${f} = ${f}\n`;
                  }
                });
                classStr += `  end\n`;
              } else if (paramStyle === 'positional') {
                classStr += `  def initialize(${fields.join(', ')})\n`;
                fields.forEach(f => {
                  if (accessorMode === 'accessor_frozen') {
                    classStr += `    @${f} = ${f}.freeze\n`;
                  } else {
                    classStr += `    @${f} = ${f}\n`;
                  }
                });
                classStr += `  end\n`;
              } else {
                // Hash attributes
                classStr += `  def initialize(attributes = {})\n`;
                fields.forEach(f => {
                  classStr += `    @${f} = attributes[:${f}] || attributes['${f}']\n`;
                });
                classStr += `  end\n`;
              }
            } else {
              classStr += '  # No properties\n';
            }
            classStr += 'end';
          }

          classes.push(classStr);
          classNames.add(finalName);
          return finalName;
        }

        if (typeof val === 'string') return 'String';
        if (typeof val === 'number') return Number.isInteger(val) ? 'Integer' : 'Float';
        if (typeof val === 'boolean') return 'Boolean';

        return 'Object';
      };

      getRubyType(parsed, 'Root', 0);

      let result = `# Frozen string literal for Ruby performance\n# frozen_string_literal: true\n\n`;
      result += classes.reverse().join('\n\n');

      if (classes.length === 0) {
        const simpleType = getRubyType(parsed, 'Root', 0);
        result = `# Ruby type representation\n# Root object is a ${simpleType}`;
      }

      setOutput(result);
      setError('');
    } catch (e: any) {
      setError(t('error.invalid_json') + ': ' + e.message);
      setOutput('');
    }
  }, [input, constructMode, accessorMode, paramStyle, t]);

  useEffect(() => {
    handleConvert();
  }, [handleConvert]);

  const handlePresetSelect = (preset: Preset) => {
    const formatted = JSON.stringify(preset.data, null, 2);
    setInput(formatted);
    setActivePreset(preset.id);
    toast.success(t('jsontoruby.preset_applied', { name: t(preset.nameKey, preset.defaultName) }));
  };

  const handleCopy = () => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    toast.success(t('common.copied', 'Copied to clipboard!'));
    setTimeout(() => setCopied(false), 2000);
  };

  const handleClear = () => {
    setInput('');
    setOutput('');
    setError('');
    setActivePreset(null);
    toast.success(t('common.cleared', 'Cleared input'));
    inputRef.current?.focus();
  };

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/x-ruby' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'models.rb';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(t('common.downloaded', 'Downloaded models.rb'));
  };

  // Keyboard shortcut handler
  const handlersRef = useRef({ handleCopy, handleClear });
  useEffect(() => {
    handlersRef.current = { handleCopy, handleClear };
  });

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const isInput = e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement;
      if (e.key === 'Escape') {
        e.preventDefault();
        handlersRef.current.handleClear();
      } else if ((e.key === 'c' || e.key === 'C') && !isInput && (e.metaKey || e.ctrlKey)) {
        e.preventDefault();
        handlersRef.current.handleCopy();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  return (
    <div ref={containerRef} className="max-w-6xl mx-auto space-y-8">
      {/* Presets */}
      <div className="space-y-3">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-indigo-500" aria-hidden="true" />
          <span className="text-xs font-black uppercase tracking-widest text-slate-400">
            {t('jsontoruby.quick_presets', 'Quick Presets')}
          </span>
        </div>
        <div className="flex flex-wrap gap-2">
          {PRESETS.map((preset) => {
            const isActive = activePreset === preset.id;
            return (
              <button
                key={preset.id}
                onClick={() => handlePresetSelect(preset)}
                aria-pressed={isActive}
                className={`px-4 py-2 rounded-xl text-xs font-bold transition-all border ${
                  isActive
                    ? 'bg-indigo-600 text-white border-indigo-600 shadow-md shadow-indigo-500/20'
                    : 'bg-white dark:bg-slate-900 text-slate-600 dark:text-slate-300 border-slate-200 dark:border-slate-800 hover:border-indigo-500'
                }`}
              >
                {t(preset.nameKey, preset.defaultName)}
              </button>
            );
          })}
        </div>
      </div>

      {/* Options Panel */}
      <div className="p-6 bg-slate-50 dark:bg-slate-900/50 border border-slate-200 dark:border-slate-800 rounded-3xl space-y-4">
        <h3 className="text-xs font-black uppercase tracking-widest text-slate-400">
          {t('jsontoruby.generator_options', 'Generator Options')}
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div>
            <label htmlFor="ruby-construct" className="block text-xs font-bold text-slate-500 dark:text-slate-400 mb-2">
              {t('jsontoruby.construct_style', 'Class / Construct Style')}
            </label>
            <select
              id="ruby-construct"
              value={constructMode}
              onChange={(e) => setConstructMode(e.target.value as any)}
              className="w-full p-3 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500/20"
            >
              <option value="class">Standard Class (class Model)</option>
              <option value="data">Ruby 3.2+ Data (Data.define)</option>
              <option value="struct">Struct (Struct.new)</option>
            </select>
          </div>

          {constructMode === 'class' && (
            <>
              <div>
                <label htmlFor="ruby-accessor" className="block text-xs font-bold text-slate-500 dark:text-slate-400 mb-2">
                  {t('jsontoruby.accessor_style', 'Accessor Directive')}
                </label>
                <select
                  id="ruby-accessor"
                  value={accessorMode}
                  onChange={(e) => setAccessorMode(e.target.value as any)}
                  className="w-full p-3 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500/20"
                >
                  <option value="accessor">attr_accessor (Read/Write)</option>
                  <option value="reader">attr_reader (Read-only)</option>
                  <option value="accessor_frozen">attr_reader + freeze</option>
                </select>
              </div>

              <div>
                <label htmlFor="ruby-params" className="block text-xs font-bold text-slate-500 dark:text-slate-400 mb-2">
                  {t('jsontoruby.param_style', 'Initialize Parameter Style')}
                </label>
                <select
                  id="ruby-params"
                  value={paramStyle}
                  onChange={(e) => setParamStyle(e.target.value as any)}
                  className="w-full p-3 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500/20"
                >
                  <option value="kwargs">Keyword Arguments (name:)</option>
                  <option value="positional">Positional Arguments (name)</option>
                  <option value="hash">Attributes Hash (attributes = {})</option>
                </select>
              </div>
            </>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-indigo-500" aria-hidden="true" />
              <label htmlFor="json-ruby-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('common.input')} JSON
              </label>
            </div>
            <div className="flex items-center gap-2">
              <Kbd modifier="none">Esc</Kbd>
              <button
                onClick={handleClear}
                disabled={!input && !output}
                className="text-xs font-bold px-3 py-1 rounded-full text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 transition-all flex items-center gap-1 disabled:opacity-50"
              >
                <Trash2 className="w-3 h-3" /> {t('common.clear')}
              </button>
            </div>
          </div>
          <textarea
            id="json-ruby-input"
            ref={inputRef}
            value={input}
            onChange={(e) => {
              setInput(e.target.value);
              setActivePreset(null);
            }}
            placeholder='{"id": 1, "name": "John"}'
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none"
          />
        </div>

        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-emerald-500" aria-hidden="true" />
              <label htmlFor="ruby-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                Ruby Output
              </label>
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={handleDownload}
                disabled={!output}
                className="text-xs font-bold px-3 py-1 rounded-full text-indigo-500 bg-indigo-50 dark:bg-indigo-500/10 hover:bg-indigo-100 transition-all flex items-center gap-1 disabled:opacity-50"
              >
                <Download className="w-3 h-3" /> {t('common.download')}
              </button>
              <Kbd modifier="cmd">C</Kbd>
              <button
                onClick={handleCopy}
                disabled={!output}
                className={`text-xs font-bold px-3 py-1 rounded-full transition-all flex items-center gap-1 focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-500/20'
                    : 'text-slate-500 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200'
                } disabled:opacity-50 disabled:cursor-not-allowed`}
              >
                {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />} {copied ? t('common.copied') : t('common.copy')}
              </button>
            </div>
          </div>
          <textarea
            id="ruby-output"
            value={output}
            readOnly
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400 resize-none"
          />
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold">
          <AlertCircle className="w-5 h-5" />
          {error}
        </div>
      )}

      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <Info className="w-6 h-6 text-indigo-500 mt-1" />
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">{t('jsontoruby.about_title', 'À propos de la conversion JSON en Ruby')}</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            {t('jsontoruby.about_text', 'Cet outil génère des classes Ruby avec des accesseurs de données (attr_accessor) ou Data.define à partir de vos données JSON. Il gère les types de base et les objets imbriqués, en suivant les conventions de nommage Ruby (snake_case pour les méthodes et variables, PascalCase pour les classes).')}
          </p>
        </div>
      </div>
    </div>
  );
}
