import { useState, useEffect, useCallback, useRef } from 'react';
import { FileCode, Copy, Check, Trash2, AlertCircle, Download, Info, Database, Sparkles } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;

export function SQLToGraphQL({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const [input, setInput] = useState(initialData?.input || '');
  const [output, setOutput] = useState(initialData?.output || '');
  const [includeInputTypes, setIncludeInputTypes] = useState(initialData?.includeInputTypes ?? true);
  const [includeQueryMutation, setIncludeQueryMutation] = useState(initialData?.includeQueryMutation ?? true);
  const [useDateTimeScalar, setUseDateTimeScalar] = useState(initialData?.useDateTimeScalar ?? true);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    onStateChange?.({ input, output, includeInputTypes, includeQueryMutation, useDateTimeScalar });
  }, [input, output, includeInputTypes, includeQueryMutation, useDateTimeScalar, onStateChange]);

  const toPascalCase = (str: string) => {
    let result = str
      .replace(/[^a-zA-Z0-9]/g, ' ')
      .split(' ')
      .filter(Boolean)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');

    if (/^[0-9]/.test(result)) {
      result = 'T' + result;
    }

    return result || 'AutoGeneratedType';
  };

  const toCamelCase = (str: string) => {
    const pascal = toPascalCase(str);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  };

  const PRESETS = {
    ecommerce: `-- E-Commerce Catalog Schema
CREATE TABLE categories (
  id INT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) UNIQUE NOT NULL,
  parent_id INT DEFAULT NULL
);

CREATE TABLE products (
  id INT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  sku VARCHAR(50) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  category_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  metadata JSON
);`,
    user_auth: `-- User Authentication & Roles Schema
CREATE TABLE users (
  id UUID PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(100),
  is_verified BOOLEAN DEFAULT FALSE,
  login_count INT DEFAULT 0,
  last_login TIMESTAMP,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE roles (
  id INT PRIMARY KEY,
  role_name VARCHAR(50) NOT NULL,
  permissions JSON
);`
  };

  const mapSqlTypeToGraphQL = (sqlType: string, isPrimaryKey: boolean): string => {
    if (!sqlType) return 'String';
    const type = sqlType.toUpperCase();

    if (isPrimaryKey || type.includes('UUID')) {
      return 'ID';
    }
    if (type.includes('INT') || type.includes('SERIAL')) {
      return 'Int';
    }
    if (type.includes('BOOL') || type.includes('BIT')) {
      return 'Boolean';
    }
    if (type.includes('FLOAT') || type.includes('DOUBLE') || type.includes('DECIMAL') || type.includes('NUMERIC') || type.includes('REAL')) {
      return 'Float';
    }
    if (type.includes('DATE') || type.includes('TIME') || type.includes('TIMESTAMP')) {
      return useDateTimeScalar ? 'DateTime' : 'String';
    }
    if (type.includes('JSON')) {
      return 'JSON';
    }

    return 'String';
  };

  const handleConvert = useCallback(() => {
    try {
      if (!input.trim()) {
        setOutput('');
        setError('');
        return;
      }
      if (input.length > MAX_LENGTH) {
        setError(t('error.max_length', { max: MAX_LENGTH.toLocaleString() }));
        return;
      }

      // Strip comments
      const cleanInput = input
        .replace(/--.*$/gm, '')
        .replace(/\/\*[\s\S]*?\*\//g, '');

      const tableRegex = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:["`]?(\w+)["`]?\.)?["`]?(\w+)["`]?\s*\(([\s\S]*?)\);/gi;
      let match;
      const tables: { typeName: string; rawName: string; fields: { name: string; gqlType: string; isNonNull: boolean; isPrimaryKey: boolean }[] }[] = [];
      const usedScalars = new Set<string>();

      while ((match = tableRegex.exec(cleanInput)) !== null) {
        const tableName = match[2];
        const columnsContent = match[3];
        const typeName = toPascalCase(tableName);

        const columnLines: string[] = [];
        let currentLine = '';
        let inQuotes = false;
        let quoteChar = '';
        let parenDepth = 0;

        for (let i = 0; i < columnsContent.length; i++) {
          const char = columnsContent[i];
          if ((char === '"' || char === '`' || char === "'") && columnsContent[i - 1] !== '\\') {
            if (!inQuotes) {
              inQuotes = true;
              quoteChar = char;
            } else if (char === quoteChar) {
              inQuotes = false;
            }
          }

          if (!inQuotes) {
            if (char === '(') parenDepth++;
            if (char === ')') parenDepth--;
          }

          if (char === ',' && !inQuotes && parenDepth === 0) {
            columnLines.push(currentLine.trim());
            currentLine = '';
          } else {
            currentLine += char;
          }
        }
        if (currentLine.trim()) columnLines.push(currentLine.trim());

        const filteredLines = columnLines.map(line => line.trim()).filter(line => {
          if (!line) return false;
          const upper = line.toUpperCase();
          return !upper.startsWith('PRIMARY KEY') &&
                 !upper.startsWith('CONSTRAINT') &&
                 !upper.startsWith('UNIQUE') &&
                 !upper.startsWith('FOREIGN KEY') &&
                 !upper.startsWith('INDEX') &&
                 !upper.startsWith('KEY');
        });

        const fields = filteredLines.map(line => {
          let rawName = '';
          let sqlType = '';

          if (line.startsWith('"') || line.startsWith('`') || line.startsWith("'")) {
            const quote = line[0];
            let i = 1;
            rawName = '';
            while (i < line.length && (line[i] !== quote || line[i - 1] === '\\')) {
              rawName += line[i];
              i++;
            }
            const remaining = line.substring(i + 1).trim();
            sqlType = remaining.split(/\s+/)[0];
          } else {
            const parts = line.split(/\s+/);
            rawName = parts[0];
            sqlType = parts[1];
          }

          if (!rawName) return null;

          // Sanitize field name for GraphQL identifiers
          let safeFieldName = rawName.replace(/[^a-zA-Z0-9_]/g, '_');
          if (/^[0-9]/.test(safeFieldName)) safeFieldName = 'f_' + safeFieldName;

          const upperLine = line.toUpperCase();
          const isPrimaryKey = upperLine.includes('PRIMARY KEY') || safeFieldName.toLowerCase() === 'id';
          const isNonNull = (upperLine.includes('NOT NULL') || isPrimaryKey) && !upperLine.includes('DEFAULT NULL');

          const gqlType = mapSqlTypeToGraphQL(sqlType || 'VARCHAR', isPrimaryKey);
          if (gqlType === 'DateTime' || gqlType === 'JSON') {
            usedScalars.add(gqlType);
          }

          return {
            name: safeFieldName,
            gqlType,
            isNonNull,
            isPrimaryKey
          };
        }).filter(Boolean) as { name: string; gqlType: string; isNonNull: boolean; isPrimaryKey: boolean }[];

        tables.push({ typeName, rawName: tableName, fields });
      }

      if (tables.length === 0) {
        setError(t('sqltographql.no_tables_found', 'No valid CREATE TABLE statements found.'));
        setOutput('');
        return;
      }

      const resultBlocks: string[] = [];

      // Add custom scalars if used
      if (usedScalars.size > 0) {
        Array.from(usedScalars).sort().forEach(scalar => {
          resultBlocks.push(`scalar ${scalar}`);
        });
      }

      // Generate GraphQL Object Types
      tables.forEach(table => {
        let typeStr = `type ${table.typeName} {\n`;
        table.fields.forEach(f => {
          typeStr += `  ${f.name}: ${f.gqlType}${f.isNonNull ? '!' : ''}\n`;
        });
        typeStr += '}';
        resultBlocks.push(typeStr);
      });

      // Generate Input Types if enabled
      if (includeInputTypes) {
        tables.forEach(table => {
          // Create Input
          let createInputStr = `input Create${table.typeName}Input {\n`;
          table.fields.forEach(f => {
            if (!f.isPrimaryKey) {
              createInputStr += `  ${f.name}: ${f.gqlType}${f.isNonNull ? '!' : ''}\n`;
            }
          });
          createInputStr += '}';
          resultBlocks.push(createInputStr);

          // Update Input
          let updateInputStr = `input Update${table.typeName}Input {\n`;
          table.fields.forEach(f => {
            // In update inputs, primary key is non-null, rest optional
            updateInputStr += `  ${f.name}: ${f.gqlType}${f.isPrimaryKey ? '!' : ''}\n`;
          });
          updateInputStr += '}';
          resultBlocks.push(updateInputStr);
        });
      }

      // Generate Query and Mutation root types if enabled
      if (includeQueryMutation) {
        let queryStr = `type Query {\n`;
        tables.forEach(table => {
          const singular = toCamelCase(table.typeName);
          const plural = singular.endsWith('y') ? singular.slice(0, -1) + 'ies' : `${singular}s`;
          const pkField = table.fields.find(f => f.isPrimaryKey) || table.fields[0];
          const pkName = pkField ? pkField.name : 'id';
          const pkType = pkField ? pkField.gqlType : 'ID';

          queryStr += `  ${singular}(${pkName}: ${pkType}!): ${table.typeName}\n`;
          queryStr += `  ${plural}: [${table.typeName}!]!\n`;
        });
        queryStr += '}';
        resultBlocks.push(queryStr);

        let mutationStr = `type Mutation {\n`;
        tables.forEach(table => {
          const singular = toCamelCase(table.typeName);
          const pasName = table.typeName;
          const pkField = table.fields.find(f => f.isPrimaryKey) || table.fields[0];
          const pkName = pkField ? pkField.name : 'id';
          const pkType = pkField ? pkField.gqlType : 'ID';

          mutationStr += `  create${pasName}(input: Create${pasName}Input!): ${pasName}!\n`;
          mutationStr += `  update${pasName}(input: Update${pasName}Input!): ${pasName}!\n`;
          mutationStr += `  delete${pasName}(${pkName}: ${pkType}!): Boolean!\n`;
        });
        mutationStr += '}';
        resultBlocks.push(mutationStr);
      }

      setOutput(resultBlocks.join('\n\n'));
      setError('');
    } catch (e: any) {
      setError(t('sqltographql.error_parsing', 'Error parsing SQL DDL') + ': ' + e.message);
      setOutput('');
    }
  }, [input, includeInputTypes, includeQueryMutation, useDateTimeScalar, t]);

  useEffect(() => {
    handleConvert();
  }, [handleConvert]);

  const handleCopy = useCallback(() => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    toast.success(t('common.copied', 'Copied to clipboard!'));
    setTimeout(() => setCopied(false), 2000);
  }, [output, t]);

  const handleClear = useCallback(() => {
    setInput('');
    setOutput('');
    setError('');
    toast.success(t('common.cleared', 'Cleared!'));
    setTimeout(() => inputRef.current?.focus(), 0);
  }, [t]);

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'schema.graphql';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(t('common.downloaded', 'Downloaded schema.graphql!'));
  };

  const loadPreset = (presetKey: keyof typeof PRESETS) => {
    setInput(PRESETS[presetKey]);
    toast.success(t('sqltographql.preset_loaded', 'Loaded SQL preset!'));
  };

  const handlersRef = useRef({ handleClear, handleCopy, output });
  useEffect(() => {
    handlersRef.current = { handleClear, handleCopy, output };
  }, [handleClear, handleCopy, output]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const activeElement = document.activeElement;
      const isEditable =
        activeElement instanceof HTMLInputElement ||
        activeElement instanceof HTMLTextAreaElement ||
        activeElement instanceof HTMLSelectElement ||
        activeElement?.getAttribute("contenteditable") === "true";

      if (isEditable && e.key !== 'Escape') return;

      if (e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;

      if (e.key === "Escape") {
        e.preventDefault();
        handlersRef.current.handleClear();
      } else if (e.key.toLowerCase() === "c") {
        if (handlersRef.current.output) {
          e.preventDefault();
          handlersRef.current.handleCopy();
        }
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, []);

  return (
    <div className="max-w-6xl mx-auto space-y-8 animate-in fade-in duration-500">
      {/* Presets Bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 p-4 bg-slate-50 dark:bg-slate-900/50 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-amber-500" aria-hidden="true" />
          <span className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltographql.presets_title', 'Clickable Presets')}
          </span>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={() => loadPreset('ecommerce')}
            className="px-3 py-1.5 text-xs font-bold bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
          >
            {t('sqltographql.preset_ecommerce', 'E-Commerce Catalog')}
          </button>
          <button
            onClick={() => loadPreset('user_auth')}
            className="px-3 py-1.5 text-xs font-bold bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
          >
            {t('sqltographql.preset_user_auth', 'User Auth & Roles')}
          </button>
        </div>
      </div>

      {/* Options Panel */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 p-5 bg-white dark:bg-slate-900/60 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="flex items-center gap-3">
          <input
            id="include-inputs"
            type="checkbox"
            checked={includeInputTypes}
            onChange={(e) => setIncludeInputTypes(e.target.checked)}
            className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
          />
          <label htmlFor="include-inputs" className="text-xs font-bold text-slate-700 dark:text-slate-300 cursor-pointer">
            {t('sqltographql.include_inputs', 'Generate Create/Update Input Types')}
          </label>
        </div>

        <div className="flex items-center gap-3">
          <input
            id="include-query-mutation"
            type="checkbox"
            checked={includeQueryMutation}
            onChange={(e) => setIncludeQueryMutation(e.target.checked)}
            className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
          />
          <label htmlFor="include-query-mutation" className="text-xs font-bold text-slate-700 dark:text-slate-300 cursor-pointer">
            {t('sqltographql.include_query_mutation', 'Generate Query & Mutation Root Types')}
          </label>
        </div>

        <div className="flex items-center gap-3">
          <input
            id="use-datetime"
            type="checkbox"
            checked={useDateTimeScalar}
            onChange={(e) => setUseDateTimeScalar(e.target.checked)}
            className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
          />
          <label htmlFor="use-datetime" className="text-xs font-bold text-slate-700 dark:text-slate-300 cursor-pointer">
            {t('sqltographql.use_datetime', 'Use DateTime Scalar for Date/Time')}
          </label>
        </div>
      </div>

      {/* Editor Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <Database className="w-4 h-4 text-indigo-500" aria-hidden="true" />
              <label htmlFor="sql-graphql-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('sqltographql.sql_input_label', 'SQL CREATE TABLE DDL')}
              </label>
            </div>
            <div className="flex items-center gap-2">
              <Kbd modifier={null} className="hidden sm:inline-flex border-rose-200 dark:border-rose-800 text-rose-400 dark:bg-slate-900">Esc</Kbd>
              <button
                onClick={handleClear}
                disabled={!input && !output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 dark:hover:bg-rose-500/20 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-rose-500 focus-visible:outline-none"
              >
                <Trash2 className="w-3 h-3" aria-hidden="true" /> {t('common.clear')}
              </button>
            </div>
          </div>
          <textarea
            id="sql-graphql-input"
            ref={inputRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder={t('sqltographql.placeholder_sql', 'Paste SQL CREATE TABLE DDL statements here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none"
          />
        </div>

        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-emerald-500" aria-hidden="true" />
              <label htmlFor="graphql-schema-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('sqltographql.output_label', 'GraphQL SDL Schema')}
              </label>
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                disabled={!output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-indigo-500 bg-indigo-50 dark:bg-indigo-500/10 hover:bg-indigo-100 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
              >
                <Download className="w-3 h-3" aria-hidden="true" /> {t('common.download')}
              </button>
              <button
                onClick={handleCopy}
                disabled={!output}
                className={`text-xs font-bold px-3 py-1.5 rounded-xl transition-all flex items-center gap-1 border focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-500/20'
                    : 'text-slate-500 bg-slate-100 dark:bg-slate-800 border-transparent hover:bg-slate-200 dark:hover:bg-slate-700 disabled:opacity-50 disabled:cursor-not-allowed'
                }`}
              >
                {copied ? <Check className="w-3 h-3" aria-hidden="true" /> : <Copy className="w-3 h-3" aria-hidden="true" />} {copied ? t('common.copied') : t('common.copy')}
                {!copied && input && <Kbd modifier={null} className="hidden sm:inline-flex w-4 h-4 bg-white/50 dark:bg-black/20 ml-1">C</Kbd>}
              </button>
            </div>
          </div>
          <textarea
            id="graphql-schema-output"
            value={output}
            readOnly
            placeholder={t('sqltographql.placeholder_output', 'GraphQL SDL schema code will appear here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400 resize-none"
          />
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold animate-in fade-in slide-in-from-top-2">
          <AlertCircle className="w-5 h-5" aria-hidden="true" />
          {error}
        </div>
      )}

      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <Info className="w-6 h-6 text-indigo-500 mt-1" aria-hidden="true" />
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">{t('sqltographql.about_title', 'About SQL to GraphQL Schema Generator')}</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            {t('sqltographql.about_text', 'Convert SQL CREATE TABLE DDL statements into GraphQL SDL types, input types, and query/mutation schemas. Automatically maps SQL types to GraphQL scalars, handles primary keys (ID!), and supports custom DateTime/JSON scalars.')}
          </p>
        </div>
      </div>
    </div>
  );
}
