import { useState, useEffect, useCallback, useRef } from 'react';
import { FileCode, Copy, Check, Trash2, AlertCircle, Download, Info, Database, Sparkles } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;

export function SQLToPydantic({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const [input, setInput] = useState(initialData?.input || '');
  const [output, setOutput] = useState(initialData?.output || '');
  const [version, setModeVersion] = useState<'v2' | 'v1' | 'dataclass'>(initialData?.version || 'v2');
  const [useDecimal, setUseDecimal] = useState(initialData?.useDecimal || false);
  const [useUUID, setUseUUID] = useState(initialData?.useUUID || false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    onStateChange?.({ input, output, version, useDecimal, useUUID });
  }, [input, output, version, useDecimal, useUUID, onStateChange]);

  const toPascalCase = (str: string) => {
    return str
      .replace(/[^a-zA-Z0-9]/g, ' ')
      .split(' ')
      .filter(Boolean)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('') || 'AutoGeneratedModel';
  };

  const toSnakeCase = (str: string) => {
    return str
      .replace(/([a-z])([A-Z])/g, '$1_$2')
      .replace(/[^a-zA-Z0-9]/g, '_')
      .replace(/_+/g, '_')
      .toLowerCase();
  };

  const PYTHON_KEYWORDS = new Set([
    'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue',
    'def', 'del', 'elif', 'else', 'except', 'false', 'finally', 'for',
    'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'none',
    'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'true', 'try',
    'while', 'with', 'yield', 'type', 'id', 'input', 'list', 'dict', 'set'
  ]);

  const PRESETS = {
    ecommerce: `-- E-Commerce Catalog Schema
CREATE TABLE categories (
  id INT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) UNIQUE NOT NULL,
  parent_id INT DEFAULT NULL
);

CREATE TABLE products (
  id INT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  sku VARCHAR(50) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  category_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  metadata JSON
);`,
    user_auth: `-- User Authentication & Roles Schema
CREATE TABLE users (
  user_id UUID PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(100),
  is_verified BOOLEAN DEFAULT FALSE,
  login_count INT DEFAULT 0,
  last_login TIMESTAMP,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE roles (
  role_id INT PRIMARY KEY,
  role_name VARCHAR(50) NOT NULL,
  permissions JSON
);`
  };

  const mapSqlTypeToPython = (sqlType: string): string => {
    if (!sqlType) return 'Any';
    const type = sqlType.toUpperCase();

    if (type.includes('UUID') && useUUID) {
      return 'UUID';
    }
    if (type.includes('INT') || type.includes('SERIAL')) {
      return 'int';
    }
    if (type.includes('BOOL') || type.includes('BIT')) {
      return 'bool';
    }
    if (type.includes('DECIMAL') || type.includes('NUMERIC')) {
      return useDecimal ? 'Decimal' : 'float';
    }
    if (type.includes('FLOAT') || type.includes('DOUBLE') || type.includes('REAL')) {
      return 'float';
    }
    if (type.includes('CHAR') || type.includes('TEXT') || type.includes('UUID') || type.includes('VARCHAR') || type.includes('ENUM')) {
      return 'str';
    }
    if (type.includes('DATE') && !type.includes('TIME')) {
      return 'date';
    }
    if (type.includes('TIME') || type.includes('TIMESTAMP') || type.includes('DATETIME')) {
      return 'datetime';
    }
    if (type.includes('JSON') || type.includes('JSONB')) {
      return 'Dict[str, Any]';
    }

    return 'Any';
  };

  const handleConvert = useCallback(() => {
    try {
      if (!input.trim()) {
        setOutput('');
        setError('');
        return;
      }
      if (input.length > MAX_LENGTH) {
        setError(t('error.max_length', { max: MAX_LENGTH.toLocaleString() }));
        return;
      }

      // Clean SQL comments
      const cleanInput = input
        .replace(/--.*$/gm, '')
        .replace(/\/\*[\s\S]*?\*\//g, '');

      const tableRegex = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:["`]?(\w+)["`]?\.)?["`]?(\w+)["`]?\s*\(([\s\S]*?)\);/gi;
      let match;
      const models: { className: string; fields: { name: string; pyType: string; isOptional: boolean; originalName: string }[] }[] = [];

      const usedTypes = new Set<string>();

      while ((match = tableRegex.exec(cleanInput)) !== null) {
        const tableName = match[2];
        const columnsContent = match[3];
        const className = toPascalCase(tableName);

        const columnLines: string[] = [];
        let currentLine = '';
        let inQuotes = false;
        let quoteChar = '';
        let parenDepth = 0;

        for (let i = 0; i < columnsContent.length; i++) {
          const char = columnsContent[i];
          if ((char === '"' || char === '`' || char === "'") && columnsContent[i - 1] !== '\\') {
            if (!inQuotes) {
              inQuotes = true;
              quoteChar = char;
            } else if (char === quoteChar) {
              inQuotes = false;
            }
          }

          if (!inQuotes) {
            if (char === '(') parenDepth++;
            if (char === ')') parenDepth--;
          }

          if (char === ',' && !inQuotes && parenDepth === 0) {
            columnLines.push(currentLine.trim());
            currentLine = '';
          } else {
            currentLine += char;
          }
        }
        if (currentLine.trim()) columnLines.push(currentLine.trim());

        const filteredLines = columnLines.map(line => line.trim()).filter(line => {
          if (!line) return false;
          const upper = line.toUpperCase();
          return !upper.startsWith('PRIMARY KEY') &&
                 !upper.startsWith('CONSTRAINT') &&
                 !upper.startsWith('UNIQUE') &&
                 !upper.startsWith('FOREIGN KEY') &&
                 !upper.startsWith('INDEX') &&
                 !upper.startsWith('KEY');
        });

        const fields = filteredLines.map(line => {
          let rawName = '';
          let sqlType = '';

          if (line.startsWith('"') || line.startsWith('`') || line.startsWith("'")) {
            const quote = line[0];
            let i = 1;
            rawName = '';
            while (i < line.length && (line[i] !== quote || line[i - 1] === '\\')) {
              rawName += line[i];
              i++;
            }
            const remaining = line.substring(i + 1).trim();
            sqlType = remaining.split(/\s+/)[0];
          } else {
            const parts = line.split(/\s+/);
            rawName = parts[0];
            sqlType = parts[1];
          }

          if (!rawName) return null;

          const upperLine = line.toUpperCase();
          const isNullable = (!upperLine.includes('NOT NULL') && !upperLine.includes('PRIMARY KEY')) || upperLine.includes('DEFAULT NULL');
          const pyType = mapSqlTypeToPython(sqlType || 'TEXT');

          usedTypes.add(pyType);

          return {
            name: rawName,
            pyType,
            isOptional: isNullable,
            originalName: rawName
          };
        }).filter(Boolean) as { name: string; pyType: string; isOptional: boolean; originalName: string }[];

        models.push({ className, fields });
      }

      if (models.length === 0) {
        setError(t('sqltopydantic.no_tables_found', 'No valid CREATE TABLE statements found.'));
        setOutput('');
        return;
      }

      // Build imports
      const imports: string[] = [];
      const typingImports = new Set<string>();
      if (models.some(m => m.fields.some(f => f.isOptional))) typingImports.add('Optional');
      if (usedTypes.has('Dict[str, Any]') || usedTypes.has('Any')) typingImports.add('Any').add('Dict');

      if (typingImports.size > 0) {
        imports.push(`from typing import ${Array.from(typingImports).sort().join(', ')}`);
      }

      if (usedTypes.has('datetime') || usedTypes.has('date')) {
        const dtImports = [];
        if (usedTypes.has('datetime')) dtImports.push('datetime');
        if (usedTypes.has('date')) dtImports.push('date');
        imports.push(`from datetime import ${dtImports.join(', ')}`);
      }

      if (usedTypes.has('Decimal')) {
        imports.push(`from decimal import Decimal`);
      }

      if (usedTypes.has('UUID')) {
        imports.push(`from uuid import UUID`);
      }

      if (version === 'v2') {
        imports.push(`from pydantic import BaseModel, ConfigDict, Field`);
      } else if (version === 'v1') {
        imports.push(`from pydantic import BaseModel, Field`);
      } else {
        imports.push(`from dataclasses import dataclass, field`);
      }

      let generatedCode = imports.join('\n') + '\n\n';

      models.forEach(model => {
        if (version === 'v2') {
          generatedCode += `class ${model.className}(BaseModel):\n`;
          generatedCode += `    model_config = ConfigDict(populate_by_name=True)\n\n`;

          model.fields.forEach(field => {
            let pyName = toSnakeCase(field.name);
            const needsAlias = PYTHON_KEYWORDS.has(pyName) || pyName !== field.originalName;

            let typeStr = field.isOptional ? `Optional[${field.pyType}] = None` : field.pyType;

            if (needsAlias) {
              if (field.isOptional) {
                generatedCode += `    ${pyName}: Optional[${field.pyType}] = Field(default=None, alias="${field.originalName}")\n`;
              } else {
                generatedCode += `    ${pyName}: ${field.pyType} = Field(alias="${field.originalName}")\n`;
              }
            } else {
              generatedCode += `    ${pyName}: ${typeStr}\n`;
            }
          });

        } else if (version === 'v1') {
          generatedCode += `class ${model.className}(BaseModel):\n`;

          model.fields.forEach(field => {
            let pyName = toSnakeCase(field.name);
            const needsAlias = PYTHON_KEYWORDS.has(pyName) || pyName !== field.originalName;

            if (needsAlias) {
              if (field.isOptional) {
                generatedCode += `    ${pyName}: Optional[${field.pyType}] = Field(None, alias="${field.originalName}")\n`;
              } else {
                generatedCode += `    ${pyName}: ${field.pyType} = Field(..., alias="${field.originalName}")\n`;
              }
            } else {
              let typeStr = field.isOptional ? `Optional[${field.pyType}] = None` : field.pyType;
              generatedCode += `    ${pyName}: ${typeStr}\n`;
            }
          });

          generatedCode += `\n    class Config:\n        allow_population_by_field_name = True\n`;

        } else {
          generatedCode += `@dataclass\nclass ${model.className}:\n`;
          model.fields.forEach(field => {
            let pyName = toSnakeCase(field.name);
            let typeStr = field.isOptional ? `Optional[${field.pyType}] = None` : field.pyType;
            generatedCode += `    ${pyName}: ${typeStr}\n`;
          });
        }

        generatedCode += '\n';
      });

      setOutput(generatedCode.trim());
      setError('');
    } catch (e: any) {
      setError(t('sqltopydantic.error_parsing', 'Error parsing SQL DDL') + ': ' + e.message);
      setOutput('');
    }
  }, [input, version, useDecimal, useUUID, t]);

  useEffect(() => {
    handleConvert();
  }, [handleConvert]);

  const handleCopy = useCallback(() => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    toast.success(t('common.copied', 'Copied to clipboard!'));
    setTimeout(() => setCopied(false), 2000);
  }, [output, t]);

  const handleClear = useCallback(() => {
    setInput('');
    setOutput('');
    setError('');
    toast.success(t('common.cleared', 'Cleared!'));
    setTimeout(() => inputRef.current?.focus(), 0);
  }, [t]);

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/x-python' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'models.py';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(t('common.downloaded', 'Downloaded models.py!'));
  };

  const loadPreset = (presetKey: keyof typeof PRESETS) => {
    setInput(PRESETS[presetKey]);
    toast.success(t('sqltopydantic.preset_loaded', 'Loaded SQL preset!'));
  };

  const handlersRef = useRef({ handleClear, handleCopy, output });
  useEffect(() => {
    handlersRef.current = { handleClear, handleCopy, output };
  }, [handleClear, handleCopy, output]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const activeElement = document.activeElement;
      const isEditable =
        activeElement instanceof HTMLInputElement ||
        activeElement instanceof HTMLTextAreaElement ||
        activeElement instanceof HTMLSelectElement ||
        activeElement?.getAttribute("contenteditable") === "true";

      if (isEditable && e.key !== 'Escape') return;

      if (e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;

      if (e.key === "Escape") {
        e.preventDefault();
        handlersRef.current.handleClear();
      } else if (e.key.toLowerCase() === "c") {
        if (handlersRef.current.output) {
          e.preventDefault();
          handlersRef.current.handleCopy();
        }
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, []);

  return (
    <div className="max-w-6xl mx-auto space-y-8 animate-in fade-in duration-500">
      {/* Presets Bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 p-4 bg-slate-50 dark:bg-slate-900/50 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-amber-500" aria-hidden="true" />
          <span className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltopydantic.presets_title', 'Clickable Presets')}
          </span>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={() => loadPreset('ecommerce')}
            className="px-3 py-1.5 text-xs font-bold bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
          >
            {t('sqltopydantic.preset_ecommerce', 'E-Commerce Catalog')}
          </button>
          <button
            onClick={() => loadPreset('user_auth')}
            className="px-3 py-1.5 text-xs font-bold bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
          >
            {t('sqltopydantic.preset_user_auth', 'User Auth & Roles')}
          </button>
        </div>
      </div>

      {/* Options Panel */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 p-5 bg-white dark:bg-slate-900/60 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="space-y-1.5">
          <label htmlFor="pydantic-version" className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltopydantic.target_format', 'Python Target Format')}
          </label>
          <select
            id="pydantic-version"
            value={version}
            onChange={(e) => setModeVersion(e.target.value as any)}
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="v2">Pydantic V2 (ConfigDict, Field)</option>
            <option value="v1">Pydantic V1 (BaseModel, class Config)</option>
            <option value="dataclass">Python Dataclasses (@dataclass)</option>
          </select>
        </div>

        <div className="flex items-center gap-3 pt-6">
          <input
            id="use-decimal"
            type="checkbox"
            checked={useDecimal}
            onChange={(e) => setUseDecimal(e.target.checked)}
            className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
          />
          <label htmlFor="use-decimal" className="text-xs font-bold text-slate-700 dark:text-slate-300 cursor-pointer">
            {t('sqltopydantic.use_decimal', 'Use Decimal for NUMERIC / DECIMAL')}
          </label>
        </div>

        <div className="flex items-center gap-3 pt-6">
          <input
            id="use-uuid"
            type="checkbox"
            checked={useUUID}
            onChange={(e) => setUseUUID(e.target.checked)}
            className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
          />
          <label htmlFor="use-uuid" className="text-xs font-bold text-slate-700 dark:text-slate-300 cursor-pointer">
            {t('sqltopydantic.use_uuid', 'Import UUID for UUID columns')}
          </label>
        </div>
      </div>

      {/* Editor Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <Database className="w-4 h-4 text-indigo-500" aria-hidden="true" />
              <label htmlFor="sql-pydantic-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('sqltopydantic.sql_input_label', 'SQL CREATE TABLE DDL')}
              </label>
            </div>
            <div className="flex items-center gap-2">
              <Kbd modifier={null} className="hidden sm:inline-flex border-rose-200 dark:border-rose-800 text-rose-400 dark:bg-slate-900">Esc</Kbd>
              <button
                onClick={handleClear}
                disabled={!input && !output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 dark:hover:bg-rose-500/20 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-rose-500 focus-visible:outline-none"
              >
                <Trash2 className="w-3 h-3" aria-hidden="true" /> {t('common.clear')}
              </button>
            </div>
          </div>
          <textarea
            id="sql-pydantic-input"
            ref={inputRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder={t('sqltopydantic.placeholder_sql', 'Paste SQL CREATE TABLE DDL statements here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none"
          />
        </div>

        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-emerald-500" aria-hidden="true" />
              <label htmlFor="pydantic-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('sqltopydantic.output_label', 'Python Pydantic Models')}
              </label>
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                disabled={!output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-indigo-500 bg-indigo-50 dark:bg-indigo-500/10 hover:bg-indigo-100 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
              >
                <Download className="w-3 h-3" aria-hidden="true" /> {t('common.download')}
              </button>
              <button
                onClick={handleCopy}
                disabled={!output}
                className={`text-xs font-bold px-3 py-1.5 rounded-xl transition-all flex items-center gap-1 border focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-500/20'
                    : 'text-slate-500 bg-slate-100 dark:bg-slate-800 border-transparent hover:bg-slate-200 dark:hover:bg-slate-700 disabled:opacity-50 disabled:cursor-not-allowed'
                }`}
              >
                {copied ? <Check className="w-3 h-3" aria-hidden="true" /> : <Copy className="w-3 h-3" aria-hidden="true" />} {copied ? t('common.copied') : t('common.copy')}
                {!copied && input && <Kbd modifier={null} className="hidden sm:inline-flex w-4 h-4 bg-white/50 dark:bg-black/20 ml-1">C</Kbd>}
              </button>
            </div>
          </div>
          <textarea
            id="pydantic-output"
            value={output}
            readOnly
            placeholder={t('sqltopydantic.placeholder_output', 'Python Pydantic class code will appear here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400 resize-none"
          />
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold animate-in fade-in slide-in-from-top-2">
          <AlertCircle className="w-5 h-5" aria-hidden="true" />
          {error}
        </div>
      )}

      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <Info className="w-6 h-6 text-indigo-500 mt-1" aria-hidden="true" />
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">{t('sqltopydantic.about_title', 'About SQL to Pydantic Converter')}</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            {t('sqltopydantic.about_text', 'Convert SQL CREATE TABLE DDL queries directly into typed Python Pydantic V2 / V1 models or dataclasses. The parser automatically detects column types, handles NOT NULL constraints, maps reserved Python keywords to Field aliases, and formats models for FastAPI and FastAPI/SQLAlchemy applications.')}
          </p>
        </div>
      </div>
    </div>
  );
}
