import { useState, useEffect, useCallback, useRef } from 'react';
import { FileCode, Copy, Check, Trash2, AlertCircle, Download, Info, Database, Sparkles } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;

type Framework = 'kotlinx' | 'jackson' | 'moshi' | 'none';

export function SQLToKotlin({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const [input, setInput] = useState(initialData?.input || '');
  const [output, setOutput] = useState(initialData?.output || '');
  const [framework, setFramework] = useState<Framework>(initialData?.framework || 'kotlinx');
  const [casing, setCasing] = useState<'camelCase' | 'snake_case' | 'PascalCase' | 'original'>(
    initialData?.casing || 'camelCase'
  );
  const [packageName, setPackageName] = useState(initialData?.packageName || 'com.example.models');
  const [useNullable, setUseNullable] = useState(initialData?.useNullable ?? true);
  const [defaultValues, setDefaultValues] = useState(initialData?.defaultValues ?? false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    onStateChange?.({
      input,
      output,
      framework,
      casing,
      packageName,
      useNullable,
      defaultValues,
    });
  }, [input, output, framework, casing, packageName, useNullable, defaultValues, onStateChange]);

  const PRESETS = {
    ecommerce: `-- E-Commerce Catalog Schema
CREATE TABLE categories (
  category_id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) UNIQUE NOT NULL,
  description TEXT,
  parent_id INT DEFAULT NULL
);

CREATE TABLE products (
  product_id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  sku VARCHAR(50) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  category_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  metadata JSON
);`,
    user_auth: `-- User Authentication & Roles Schema
CREATE TABLE users (
  user_id UUID PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(100),
  is_verified BOOLEAN DEFAULT FALSE,
  login_count INT DEFAULT 0,
  last_login TIMESTAMP,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE roles (
  role_id INT PRIMARY KEY,
  role_name VARCHAR(50) NOT NULL,
  permissions JSON
);`,
    telemetry: `-- Server Telemetry Schema
CREATE TABLE server_metrics (
  metric_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  server_host VARCHAR(255) NOT NULL,
  cpu_utilization DOUBLE NOT NULL,
  memory_used_bytes BIGINT NOT NULL,
  is_alert_active BOOLEAN DEFAULT FALSE,
  recorded_at DATETIME NOT NULL,
  extra_payload JSON
);`
  };

  const KOTLIN_KEYWORDS = new Set([
    'as', 'break', 'class', 'continue', 'do', 'else', 'false', 'for', 'fun', 'if',
    'in', 'interface', 'is', 'null', 'object', 'package', 'return', 'super', 'this',
    'throw', 'true', 'try', 'typealias', 'val', 'var', 'when', 'while', 'by', 'catch',
    'constructor', 'delegate', 'dynamic', 'field', 'file', 'finally', 'get', 'import',
    'init', 'param', 'property', 'receiver', 'set', 'setparam', 'where', 'actual',
    'abstract', 'annotation', 'companion', 'const', 'crossinline', 'data', 'enum',
    'expect', 'external', 'final', 'infix', 'inline', 'inner', 'internal', 'lateinit',
    'noinline', 'open', 'operator', 'out', 'override', 'private', 'protected', 'public',
    'reified', 'sealed', 'suspend', 'tailrec', 'vararg'
  ]);

  const escapeKotlinString = (str: string) => {
    return str
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\$/g, '\\$')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r')
      .replace(/\t/g, '\\t');
  };

  const toPascalCase = (str: string) => {
    const pascal = str
      .replace(/[^a-zA-Z0-9]/g, ' ')
      .split(' ')
      .filter(Boolean)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');
    if (!pascal) return 'AutoGenerated';
    return /^[0-9]/.test(pascal) ? `Model${pascal}` : pascal;
  };

  const toCamelCase = (str: string) => {
    const pascal = toPascalCase(str);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  };

  const toSnakeCase = (str: string) => {
    return str
      .replace(/([a-z])([A-Z])/g, '$1_$2')
      .replace(/[^a-zA-Z0-9]/g, '_')
      .replace(/_+/g, '_')
      .toLowerCase();
  };

  const formatPropertyName = (name: string): { propName: string; originalKey: string } => {
    let formatted = name;
    if (casing === 'camelCase') {
      formatted = toCamelCase(name);
    } else if (casing === 'snake_case') {
      formatted = toSnakeCase(name);
    } else if (casing === 'PascalCase') {
      formatted = toPascalCase(name);
    }

    let propName = formatted;
    if (/^[0-9]/.test(propName)) {
      propName = 'field' + propName;
    }

    const isValidStandardIdentifier = /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(propName);
    if (!isValidStandardIdentifier || KOTLIN_KEYWORDS.has(propName)) {
      const sanitized = propName.replace(/`/g, '').replace(/[\n\r]/g, '_');
      propName = '`' + (sanitized || 'field') + '`';
    }

    return { propName, originalKey: name };
  };

  const mapSqlTypeToKotlin = (sqlType: string): string => {
    if (!sqlType) return 'String';
    const type = sqlType.toUpperCase();

    if (type.includes('BIGINT')) return 'Long';
    if (type.includes('TINYINT(1)') || type.includes('BOOLEAN') || type.includes('BOOL') || type.includes('BIT')) return 'Boolean';
    if (type.includes('SMALLINT')) return 'Short';
    if (type.includes('INT') || type.includes('SERIAL')) return 'Int';
    if (type.includes('DECIMAL') || type.includes('NUMERIC') || type.includes('DOUBLE') || type.includes('REAL')) return 'Double';
    if (type.includes('FLOAT')) return 'Float';

    return 'String';
  };

  const handleConvert = useCallback(() => {
    try {
      if (!input.trim()) {
        setOutput('');
        setError('');
        return;
      }

      if (input.length > MAX_LENGTH) {
        setError(t('error.max_length', { max: MAX_LENGTH.toLocaleString() }));
        return;
      }

      const cleanInput = input
        .replace(/--.*$/gm, '')
        .replace(/\/\*[\s\S]*?\*\//g, '');

      const tableRegex = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:["`]?(\w+)["`]?\.)?["`]?(\w+)["`]?\s*\(([\s\S]*?)\);/gi;
      let match;
      const dataClasses: string[] = [];

      while ((match = tableRegex.exec(cleanInput)) !== null) {
        const rawTableName = match[2];
        const columnsContent = match[3];
        let className = toPascalCase(rawTableName);
        if (KOTLIN_KEYWORDS.has(className.toLowerCase())) {
          className = `${className}Model`;
        }

        const columnLines: string[] = [];
        let currentLine = '';
        let inQuotes = false;
        let quoteChar = '';
        let parenDepth = 0;

        for (let i = 0; i < columnsContent.length; i++) {
          const char = columnsContent[i];
          if ((char === '"' || char === '`' || char === "'") && columnsContent[i - 1] !== '\\') {
            if (!inQuotes) {
              inQuotes = true;
              quoteChar = char;
            } else if (char === quoteChar) {
              inQuotes = false;
            }
          }

          if (!inQuotes) {
            if (char === '(') parenDepth++;
            if (char === ')') parenDepth--;
          }

          if (char === ',' && !inQuotes && parenDepth === 0) {
            columnLines.push(currentLine.trim());
            currentLine = '';
          } else {
            currentLine += char;
          }
        }
        if (currentLine.trim()) columnLines.push(currentLine.trim());

        const filteredLines = columnLines.map(line => line.trim()).filter(line => {
          if (!line) return false;
          const upper = line.toUpperCase();
          return !upper.startsWith('PRIMARY KEY') &&
                 !upper.startsWith('CONSTRAINT') &&
                 !upper.startsWith('UNIQUE') &&
                 !upper.startsWith('FOREIGN KEY') &&
                 !upper.startsWith('INDEX') &&
                 !upper.startsWith('KEY');
        });

        const fields: string[] = [];

        filteredLines.forEach(line => {
          let rawName = '';
          let sqlType = '';

          if (line.startsWith('"') || line.startsWith('`') || line.startsWith("'")) {
            const quote = line[0];
            let i = 1;
            rawName = '';
            while (i < line.length && (line[i] !== quote || line[i - 1] === '\\')) {
              rawName += line[i];
              i++;
            }
            const remaining = line.substring(i + 1).trim();
            sqlType = remaining.split(/\s+/)[0];
          } else {
            const parts = line.split(/\s+/);
            rawName = parts[0];
            sqlType = parts[1];
          }

          if (!rawName) return;

          const upperLine = line.toUpperCase();
          const isPrimaryKey = upperLine.includes('PRIMARY KEY');
          const isNullable = (!upperLine.includes('NOT NULL') && !isPrimaryKey) || upperLine.includes('DEFAULT NULL');
          const kotlinType = mapSqlTypeToKotlin(sqlType || 'TEXT');

          const finalNullable = isNullable && useNullable;
          const typeStr = finalNullable ? `${kotlinType}?` : kotlinType;
          const defaultSuffix = (defaultValues && finalNullable) ? ' = null' : '';

          const { propName, originalKey } = formatPropertyName(rawName);

          let annotation = '';
          const escapedOriginalKey = escapeKotlinString(originalKey);
          if (framework === 'kotlinx') {
            if (originalKey !== propName) {
              annotation = `    @SerialName("${escapedOriginalKey}")\n`;
            }
          } else if (framework === 'jackson') {
            if (originalKey !== propName) {
              annotation = `    @JsonProperty("${escapedOriginalKey}")\n`;
            }
          } else if (framework === 'moshi') {
            if (originalKey !== propName) {
              annotation = `    @Json(name = "${escapedOriginalKey}")\n`;
            }
          }

          fields.push(`${annotation}    val ${propName}: ${typeStr}${defaultSuffix}`);
        });

        let classHeader = '';
        if (framework === 'kotlinx') {
          classHeader += '@Serializable\n';
        }
        classHeader += `data class ${className}(\n`;
        classHeader += fields.join(',\n');
        classHeader += '\n)';

        dataClasses.push(classHeader);
      }

      if (dataClasses.length === 0) {
        setError(t('sqltokotlin.no_tables_found', 'No valid CREATE TABLE statements found.'));
        setOutput('');
        return;
      }

      let imports = '';
      if (framework === 'kotlinx') {
        imports = 'import kotlinx.serialization.Serializable\nimport kotlinx.serialization.SerialName\n\n';
      } else if (framework === 'jackson') {
        imports = 'import com.fasterxml.jackson.annotation.JsonProperty\n\n';
      } else if (framework === 'moshi') {
        imports = 'import com.squareup.moshi.Json\nimport com.squareup.moshi.JsonClass\n\n';
      }

      let result = '';
      if (packageName.trim()) {
        const sanitizedPackage = packageName.trim().replace(/[^a-zA-Z0-9_.]/g, '');
        if (sanitizedPackage) {
          result += `package ${sanitizedPackage}\n\n`;
        }
      }
      result += imports;
      result += dataClasses.join('\n\n');

      setOutput(result.trim());
      setError('');
    } catch (e: any) {
      setError(t('sqltokotlin.error_parsing', 'Error parsing SQL DDL') + ': ' + e.message);
      setOutput('');
    }
  }, [input, framework, casing, packageName, useNullable, defaultValues, t]);

  useEffect(() => {
    handleConvert();
  }, [handleConvert]);

  const handleCopy = useCallback(() => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    toast.success(t('sqltokotlin.toast_copied', 'Kotlin code copied to clipboard!'));
    setTimeout(() => setCopied(false), 2000);
  }, [output, t]);

  const handleClear = useCallback(() => {
    setInput('');
    setOutput('');
    setError('');
    toast.success(t('common.cleared', 'Cleared!'));
    setTimeout(() => inputRef.current?.focus(), 0);
  }, [t]);

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/x-kotlin' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'Models.kt';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(t('common.downloaded', 'Downloaded Models.kt!'));
  };

  const loadPreset = (presetKey: keyof typeof PRESETS) => {
    setInput(PRESETS[presetKey]);
    toast.success(t('sqltokotlin.preset_loaded', 'Loaded SQL preset!'));
  };

  const handlersRef = useRef({ handleClear, handleCopy, output });
  useEffect(() => {
    handlersRef.current = { handleClear, handleCopy, output };
  }, [handleClear, handleCopy, output]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const activeElement = document.activeElement;
      const isEditable =
        activeElement instanceof HTMLInputElement ||
        activeElement instanceof HTMLTextAreaElement ||
        activeElement instanceof HTMLSelectElement ||
        activeElement?.getAttribute('contenteditable') === 'true';

      if (isEditable && e.key !== 'Escape') return;

      if (e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;

      if (e.key === 'Escape') {
        e.preventDefault();
        handlersRef.current.handleClear();
      } else if (e.key.toLowerCase() === 'c') {
        if (handlersRef.current.output) {
          e.preventDefault();
          handlersRef.current.handleCopy();
        }
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  return (
    <div className="max-w-6xl mx-auto space-y-8 animate-in fade-in duration-500">
      {/* Presets Bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 p-4 bg-slate-50 dark:bg-slate-900/50 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-amber-500" aria-hidden="true" />
          <span className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltokotlin.presets_title', 'Quick Presets')}
          </span>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={() => loadPreset('ecommerce')}
            className="px-3 py-1.5 text-xs font-bold bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
          >
            {t('sqltokotlin.preset_ecommerce', 'E-Commerce Catalog')}
          </button>
          <button
            onClick={() => loadPreset('user_auth')}
            className="px-3 py-1.5 text-xs font-bold bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
          >
            {t('sqltokotlin.preset_user_auth', 'User Auth & Roles')}
          </button>
          <button
            onClick={() => loadPreset('telemetry')}
            className="px-3 py-1.5 text-xs font-bold bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
          >
            {t('sqltokotlin.preset_telemetry', 'Server Telemetry')}
          </button>
        </div>
      </div>

      {/* Options Panel */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 p-5 bg-white dark:bg-slate-900/60 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="space-y-1.5">
          <label htmlFor="kotlin-framework" className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltokotlin.framework_label', 'Serialization Framework')}
          </label>
          <select
            id="kotlin-framework"
            value={framework}
            onChange={(e) => setFramework(e.target.value as Framework)}
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="kotlinx">kotlinx.serialization (@Serializable)</option>
            <option value="jackson">Jackson (@JsonProperty)</option>
            <option value="moshi">Moshi (@Json)</option>
            <option value="none">None</option>
          </select>
        </div>

        <div className="space-y-1.5">
          <label htmlFor="kotlin-casing" className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltokotlin.casing_label', 'Property Casing')}
          </label>
          <select
            id="kotlin-casing"
            value={casing}
            onChange={(e) => setCasing(e.target.value as any)}
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="camelCase">camelCase (Standard Kotlin)</option>
            <option value="snake_case">snake_case</option>
            <option value="PascalCase">PascalCase</option>
            <option value="original">Original Column Name</option>
          </select>
        </div>

        <div className="space-y-1.5">
          <label htmlFor="kotlin-package" className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltokotlin.package_name', 'Package Name')}
          </label>
          <input
            id="kotlin-package"
            type="text"
            value={packageName}
            onChange={(e) => setPackageName(e.target.value)}
            placeholder="e.g. com.example.models"
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500"
          />
        </div>

        <div className="col-span-1 md:col-span-3 flex flex-wrap items-center gap-6 pt-2 border-t border-slate-100 dark:border-slate-800">
          <div className="flex items-center gap-2">
            <input
              id="use-nullable-fields"
              type="checkbox"
              checked={useNullable}
              onChange={(e) => setUseNullable(e.target.checked)}
              className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
            />
            <label htmlFor="use-nullable-fields" className="text-xs font-bold text-slate-700 dark:text-slate-300 cursor-pointer">
              {t('sqltokotlin.nullable_fields', 'Nullable types (?) for NULL columns')}
            </label>
          </div>

          <div className="flex items-center gap-2">
            <input
              id="use-default-values"
              type="checkbox"
              checked={defaultValues}
              onChange={(e) => setDefaultValues(e.target.checked)}
              className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
            />
            <label htmlFor="use-default-values" className="text-xs font-bold text-slate-700 dark:text-slate-300 cursor-pointer">
              {t('sqltokotlin.default_values', 'Default "= null" for nullable fields')}
            </label>
          </div>
        </div>
      </div>

      {/* Editor Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <Database className="w-4 h-4 text-indigo-500" aria-hidden="true" />
              <label htmlFor="sql-kotlin-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('sqltokotlin.sql_input_label', 'SQL CREATE TABLE DDL')}
              </label>
            </div>
            <div className="flex items-center gap-2">
              <Kbd modifier={null} className="hidden sm:inline-flex border-rose-200 dark:border-rose-800 text-rose-400 dark:bg-slate-900">Esc</Kbd>
              <button
                onClick={handleClear}
                disabled={!input && !output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 dark:hover:bg-rose-500/20 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-rose-500 focus-visible:outline-none"
              >
                <Trash2 className="w-3 h-3" aria-hidden="true" /> {t('common.clear')}
              </button>
            </div>
          </div>
          <textarea
            id="sql-kotlin-input"
            ref={inputRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder={t('sqltokotlin.placeholder_sql', 'Paste SQL CREATE TABLE DDL statements here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none"
          />
        </div>

        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-emerald-500" aria-hidden="true" />
              <label htmlFor="kotlin-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('sqltokotlin.output_label', 'Generated Kotlin Data Classes')}
              </label>
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                disabled={!output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-indigo-500 bg-indigo-50 dark:bg-indigo-500/10 hover:bg-indigo-100 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
              >
                <Download className="w-3 h-3" aria-hidden="true" /> {t('common.download')}
              </button>
              <button
                onClick={handleCopy}
                disabled={!output}
                className={`text-xs font-bold px-3 py-1.5 rounded-xl transition-all flex items-center gap-1 border focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-500/20'
                    : 'text-slate-500 bg-slate-100 dark:bg-slate-800 border-transparent hover:bg-slate-200 dark:hover:bg-slate-700 disabled:opacity-50 disabled:cursor-not-allowed'
                }`}
              >
                {copied ? <Check className="w-3 h-3" aria-hidden="true" /> : <Copy className="w-3 h-3" aria-hidden="true" />} {copied ? t('common.copied') : t('common.copy')}
                {!copied && input && <Kbd modifier={null} className="hidden sm:inline-flex w-4 h-4 bg-white/50 dark:bg-black/20 ml-1">C</Kbd>}
              </button>
            </div>
          </div>
          <textarea
            id="kotlin-output"
            value={output}
            readOnly
            placeholder={t('sqltokotlin.placeholder_output', 'Generated Kotlin code will appear here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400 resize-none"
          />
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold animate-in fade-in slide-in-from-top-2">
          <AlertCircle className="w-5 h-5" aria-hidden="true" />
          {error}
        </div>
      )}

      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <Info className="w-6 h-6 text-indigo-500 mt-1" aria-hidden="true" />
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">{t('sqltokotlin.about_title', 'About SQL to Kotlin Data Class Generator')}</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            {t('sqltokotlin.about_text', 'Convert SQL CREATE TABLE DDL queries directly into typed Kotlin data classes. Supports kotlinx.serialization, Jackson, Moshi annotations, property casing options, nullability handling, and custom package names.')}
          </p>
        </div>
      </div>
    </div>
  );
}
