import { useState, useEffect, useCallback, useRef } from 'react';
import { Database, Copy, Check, Trash2, Download, Info, AlertCircle } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;

const JULIA_KEYWORDS = new Set([
  'baremodule', 'begin', 'break', 'catch', 'const', 'continue', 'do', 'else',
  'elseif', 'end', 'export', 'false', 'finally', 'for', 'function', 'global',
  'if', 'import', 'in', 'isa', 'let', 'local', 'macro', 'module', 'quote',
  'return', 'struct', 'true', 'try', 'type', 'using', 'while', 'where', 'mutable'
]);

type CasingMode = 'snake_case' | 'camelCase' | 'PascalCase' | 'original';
type StructKind = 'struct' | 'mutable struct';
type PackageStyle = 'structtypes' | 'json3' | 'plain';

export function SQLToJulia({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  const [input, setInput] = useState(initialData?.input || '');
  const [output, setOutput] = useState(initialData?.output || '');
  const [casing, setCasing] = useState<CasingMode>(initialData?.casing || 'snake_case');
  const [structKind, setStructKind] = useState<StructKind>(initialData?.structKind || 'struct');
  const [packageStyle, setPackageStyle] = useState<PackageStyle>(initialData?.packageStyle || 'structtypes');
  const [useUnionNothing, setUseUnionNothing] = useState(initialData?.useUnionNothing !== false);
  const [useDateTime, setUseDateTime] = useState(initialData?.useDateTime !== false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    onStateChange?.({ input, output, casing, structKind, packageStyle, useUnionNothing, useDateTime });
  }, [input, output, casing, structKind, packageStyle, useUnionNothing, useDateTime, onStateChange]);

  const presets = {
    ecommerce: `CREATE TABLE products (
  product_id INT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  sku VARCHAR(50) UNIQUE,
  price DECIMAL(10,2) NOT NULL,
  stock_quantity INT DEFAULT 0,
  is_available BOOLEAN DEFAULT true,
  created_at TIMESTAMP
);

CREATE TABLE categories (
  id INT PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  description TEXT
);`,

    user_auth: `CREATE TABLE users (
  user_id BIGINT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  is_verified BOOLEAN DEFAULT false,
  login_count INT DEFAULT 0,
  last_login_at DATETIME
);

CREATE TABLE roles (
  role_id INT PRIMARY KEY,
  role_name VARCHAR(50) NOT NULL
);`,

    blog: `CREATE TABLE posts (
  id INT PRIMARY KEY,
  author_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT,
  view_count INT DEFAULT 0,
  published_at TIMESTAMP,
  is_published BOOLEAN DEFAULT false
);

CREATE TABLE comments (
  comment_id INT PRIMARY KEY,
  post_id INT NOT NULL,
  author_name VARCHAR(100) NOT NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMP
);`
  };

  const sanitizeJuliaIdentifier = (name: string, isField = false): string => {
    let clean = name.replace(/[^a-zA-Z0-9_]/g, '_');
    if (/^[0-9]/.test(clean)) clean = '_' + clean;
    if (isField && JULIA_KEYWORDS.has(clean)) {
      clean = clean + '_val';
    }
    return clean || 'item';
  };

  const toPascalCase = (str: string): string => {
    const clean = str.replace(/[^a-zA-Z0-9_]/g, ' ');
    return clean
      .split(/[\s_]+/)
      .filter(Boolean)
      .map(part => part.charAt(0).toUpperCase() + part.slice(1))
      .join('') || 'AutoGenerated';
  };

  const transformFieldName = (str: string, mode: CasingMode): string => {
    if (mode === 'original') return sanitizeJuliaIdentifier(str, true);
    const words = str.replace(/[^a-zA-Z0-9]/g, ' ').split(/\s+/).filter(Boolean);
    if (words.length === 0) return 'field_val';

    if (mode === 'snake_case') {
      return sanitizeJuliaIdentifier(words.map(w => w.toLowerCase()).join('_'), true);
    } else if (mode === 'camelCase') {
      const camel = words[0].toLowerCase() + words.slice(1).map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join('');
      return sanitizeJuliaIdentifier(camel, true);
    } else if (mode === 'PascalCase') {
      return sanitizeJuliaIdentifier(words.map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join(''), true);
    }
    return sanitizeJuliaIdentifier(str, true);
  };

  const mapSqlTypeToJulia = (sqlType: string): string => {
    const upper = sqlType.toUpperCase().trim();
    if (upper.includes('INT') || upper.includes('SERIAL')) {
      return upper.includes('BIG') ? 'Int64' : 'Int64';
    }
    if (upper.includes('FLOAT') || upper.includes('DOUBLE') || upper.includes('REAL') || upper.includes('DECIMAL') || upper.includes('NUMERIC')) {
      return 'Float64';
    }
    if (upper.includes('BOOL')) {
      return 'Bool';
    }
    if (upper.includes('DATE') || upper.includes('TIME')) {
      return useDateTime ? 'DateTime' : 'String';
    }
    if (upper.includes('BLOB') || upper.includes('BYTEA') || upper.includes('BINARY')) {
      return 'Vector{UInt8}';
    }
    return 'String';
  };

  const convertSqlToJulia = useCallback(() => {
    if (!input.trim()) {
      setOutput('');
      setError('');
      return;
    }

    if (input.length > MAX_LENGTH) {
      setError(t('error.max_length', { max: MAX_LENGTH.toLocaleString() }));
      setOutput('');
      return;
    }

    try {
      // Strip comments
      const cleanInput = input
        .replace(/--.*$/gm, '')
        .replace(/\/\*[\s\S]*?\*\//g, '');

      const structsList: string[] = [];
      const structNames = new Set<string>();

      let pos = 0;
      while (true) {
        const matchIndex = cleanInput.toUpperCase().indexOf('CREATE TABLE', pos);
        if (matchIndex === -1) break;

        const openParenIndex = cleanInput.indexOf('(', matchIndex);
        if (openParenIndex === -1) {
          pos = matchIndex + 12;
          continue;
        }

        const tableHeader = cleanInput.substring(matchIndex + 12, openParenIndex).trim();
        const headerParts = tableHeader.split(/\s+/).filter(Boolean);
        let rawTableName = '';
        if (headerParts.length > 0) {
          rawTableName = headerParts[headerParts.length - 1].replace(/["`]/g, '');
        }

        const rawNameSanitized = rawTableName.split('.').pop() || 'Table';
        const structName = toPascalCase(rawNameSanitized);

        let parenDepth = 1;
        let closeParenIndex = -1;
        let inQuotes = false;
        let quoteChar = '';

        for (let i = openParenIndex + 1; i < cleanInput.length; i++) {
          const char = cleanInput[i];
          if ((char === '"' || char === '`' || char === "'") && cleanInput[i - 1] !== '\\') {
            if (!inQuotes) {
              inQuotes = true;
              quoteChar = char;
            } else if (char === quoteChar) {
              inQuotes = false;
            }
          }
          if (!inQuotes) {
            if (char === '(') parenDepth++;
            if (char === ')') parenDepth--;
            if (parenDepth === 0) {
              closeParenIndex = i;
              break;
            }
          }
        }

        if (closeParenIndex === -1) {
          pos = openParenIndex + 1;
          continue;
        }

        const body = cleanInput.substring(openParenIndex + 1, closeParenIndex);

        // Split body lines
        const lines: string[] = [];
        let currentLine = '';
        let subParenDepth = 0;
        let subInQuotes = false;
        let subQuoteChar = '';

        for (let i = 0; i < body.length; i++) {
          const char = body[i];
          if ((char === '"' || char === '`' || char === "'") && body[i - 1] !== '\\') {
            if (!subInQuotes) {
              subInQuotes = true;
              subQuoteChar = char;
            } else if (char === subQuoteChar) {
              subInQuotes = false;
            }
          }
          if (!subInQuotes) {
            if (char === '(') subParenDepth++;
            if (char === ')') subParenDepth--;
          }

          if (char === ',' && subParenDepth === 0 && !subInQuotes) {
            lines.push(currentLine.trim());
            currentLine = '';
          } else {
            currentLine += char;
          }
        }
        if (currentLine.trim()) lines.push(currentLine.trim());

        const fields: { name: string; origKey: string; type: string }[] = [];

        lines.forEach(line => {
          const upperLine = line.toUpperCase().trim();
          if (!upperLine) return;

          if (
            upperLine.startsWith('PRIMARY KEY') ||
            upperLine.startsWith('FOREIGN KEY') ||
            upperLine.startsWith('CONSTRAINT') ||
            upperLine.startsWith('UNIQUE') ||
            upperLine.startsWith('CHECK') ||
            upperLine.startsWith('INDEX') ||
            upperLine.startsWith('KEY')
          ) {
            return;
          }

          let colName = '';
          let rest = '';

          if (line.startsWith('"') || line.startsWith('`') || line.startsWith("'")) {
            const quote = line[0];
            let i = 1;
            while (i < line.length && (line[i] !== quote || line[i - 1] === '\\')) {
              colName += line[i];
              i++;
            }
            rest = line.substring(i + 1).trim();
          } else {
            const parts = line.split(/\s+/);
            colName = parts[0];
            rest = parts.slice(1).join(' ').trim();
          }

          if (!colName) return;

          const rawColName = colName.replace(/["`]/g, '');
          const fieldName = transformFieldName(rawColName, casing);

          const partsRest = rest.split(/\s+/);
          const rawSqlType = partsRest[0] || 'VARCHAR';
          let juliaType = mapSqlTypeToJulia(rawSqlType);

          const isNotNull = upperLine.includes('NOT NULL') || upperLine.includes('PRIMARY KEY');
          if (!isNotNull && useUnionNothing) {
            juliaType = `Union{Nothing, ${juliaType}}`;
          }

          fields.push({
            name: fieldName,
            origKey: rawColName,
            type: juliaType
          });
        });

        let structCode = `${structKind} ${structName}\n`;
        fields.forEach(f => {
          structCode += `    ${f.name}::${f.type}\n`;
        });
        structCode += `end`;

        if (packageStyle === 'structtypes') {
          structCode += `\n\nStructTypes.StructType(::Type{${structName}}) = StructTypes.Struct()`;
          const needsMap = fields.some(f => f.name !== f.origKey);
          if (needsMap) {
            const pairs = fields.map(f => `:${f.name} => :${f.origKey}`).join(', ');
            structCode += `\nStructTypes.names(::Type{${structName}}) = (${pairs})`;
          }
        } else if (packageStyle === 'json3') {
          structCode += `\n\nJSON3.StructType(::Type{${structName}}) = JSON3.Struct()`;
        }

        structsList.push(structCode);
        structNames.add(structName);

        pos = closeParenIndex + 1;
      }

      if (structsList.length === 0) {
        setError(t('sqltojulia.no_tables_found', 'No valid CREATE TABLE statements found.'));
        setOutput('');
        return;
      }

      let header = '';
      if (useDateTime) {
        header += `using Dates\n`;
      }
      if (packageStyle === 'structtypes') {
        header += `using StructTypes\n`;
      } else if (packageStyle === 'json3') {
        header += `using JSON3\n`;
      }
      if (header) header += `\n`;

      setOutput(header + structsList.join('\n\n'));
      setError('');
    } catch (err: any) {
      setError(t('sqltojulia.error_parsing', 'Error parsing SQL DDL') + ': ' + err.message);
      setOutput('');
    }
  }, [input, casing, structKind, packageStyle, useUnionNothing, useDateTime, t]);

  useEffect(() => {
    convertSqlToJulia();
  }, [convertSqlToJulia]);

  const handleCopy = useCallback(() => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    toast.success(t('sqltojulia.copied', 'Julia struct code copied to clipboard!'));
    setTimeout(() => setCopied(false), 2000);
  }, [output, t]);

  const handleClear = useCallback(() => {
    setInput('');
    setOutput('');
    setError('');
    toast.success(t('sqltojulia.cleared', 'Cleared input and output!'));
    setTimeout(() => inputRef.current?.focus(), 0);
  }, [t]);

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'models.jl';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(t('sqltojulia.downloaded', 'Downloaded models.jl!'));
  };

  const loadPreset = (key: 'ecommerce' | 'user_auth' | 'blog') => {
    setInput(presets[key]);
    toast.success(t('sqltojulia.preset_loaded', 'Loaded SQL DDL preset!'));
  };

  const handlersRef = useRef({ handleClear, handleCopy, output });
  useEffect(() => {
    handlersRef.current = { handleClear, handleCopy, output };
  }, [handleClear, handleCopy, output]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const activeElement = document.activeElement;
      const isEditable =
        activeElement instanceof HTMLInputElement ||
        activeElement instanceof HTMLTextAreaElement ||
        activeElement instanceof HTMLSelectElement ||
        activeElement?.getAttribute('contenteditable') === 'true';

      if (isEditable && e.key !== 'Escape') return;

      if (e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;

      if (e.key === 'Escape') {
        e.preventDefault();
        handlersRef.current.handleClear();
      } else if (e.key.toLowerCase() === 'c') {
        if (handlersRef.current.output) {
          e.preventDefault();
          handlersRef.current.handleCopy();
        }
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  return (
    <div ref={containerRef} className="max-w-6xl mx-auto space-y-8 animate-in fade-in duration-500">
      <div className="flex flex-col md:flex-row gap-4 items-start md:items-center justify-between p-6 bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800 rounded-3xl">
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-xs font-bold text-slate-400 select-none mr-1">{t('sqltojulia.presets_title', 'Presets:')}</span>
          <button
            onClick={() => loadPreset('ecommerce')}
            className="text-xs font-bold px-3 py-1.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 text-slate-600 dark:text-slate-300 rounded-xl transition-all"
          >
            🛒 {t('sqltojulia.preset_ecommerce', 'E-Commerce Catalog')}
          </button>
          <button
            onClick={() => loadPreset('user_auth')}
            className="text-xs font-bold px-3 py-1.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 text-slate-600 dark:text-slate-300 rounded-xl transition-all"
          >
            🔐 {t('sqltojulia.preset_user_auth', 'User Auth & Roles')}
          </button>
          <button
            onClick={() => loadPreset('blog')}
            className="text-xs font-bold px-3 py-1.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 text-slate-600 dark:text-slate-300 rounded-xl transition-all"
          >
            📝 {t('sqltojulia.preset_blog', 'Blog CMS')}
          </button>
        </div>

        <div className="flex flex-wrap items-center gap-4">
          <div className="flex items-center gap-2">
            <span className="text-xs font-bold text-slate-400 select-none">{t('sqltojulia.struct_kind', 'Struct Type:')}</span>
            <select
              value={structKind}
              onChange={(e) => setStructKind(e.target.value as StructKind)}
              className="text-xs font-bold px-3 py-1.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl outline-none focus:border-indigo-500"
            >
              <option value="struct">struct (Immutable)</option>
              <option value="mutable struct">mutable struct</option>
            </select>
          </div>

          <div className="flex items-center gap-2">
            <span className="text-xs font-bold text-slate-400 select-none">{t('sqltojulia.package_style', 'Serialization:')}</span>
            <select
              value={packageStyle}
              onChange={(e) => setPackageStyle(e.target.value as PackageStyle)}
              className="text-xs font-bold px-3 py-1.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl outline-none focus:border-indigo-500"
            >
              <option value="structtypes">StructTypes.jl</option>
              <option value="json3">JSON3.jl</option>
              <option value="plain">Plain Julia Struct</option>
            </select>
          </div>

          <div className="flex items-center gap-2">
            <span className="text-xs font-bold text-slate-400 select-none">{t('sqltojulia.casing', 'Casing:')}</span>
            <select
              value={casing}
              onChange={(e) => setCasing(e.target.value as CasingMode)}
              className="text-xs font-bold px-3 py-1.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl outline-none focus:border-indigo-500"
            >
              <option value="snake_case">snake_case (Julia Std)</option>
              <option value="camelCase">camelCase</option>
              <option value="PascalCase">PascalCase</option>
              <option value="original">original</option>
            </select>
          </div>
        </div>
      </div>

      <div className="flex flex-wrap items-center gap-6 px-2 text-xs font-bold text-slate-600 dark:text-slate-300">
        <label className="flex items-center gap-2 cursor-pointer select-none">
          <input
            type="checkbox"
            checked={useUnionNothing}
            onChange={(e) => setUseUnionNothing(e.target.checked)}
            className="w-4 h-4 rounded text-indigo-600 border-slate-300 focus:ring-indigo-500/20"
          />
          {t('sqltojulia.use_union_nothing', 'Union{Nothing, T} for NULL columns')}
        </label>

        <label className="flex items-center gap-2 cursor-pointer select-none">
          <input
            type="checkbox"
            checked={useDateTime}
            onChange={(e) => setUseDateTime(e.target.checked)}
            className="w-4 h-4 rounded text-indigo-600 border-slate-300 focus:ring-indigo-500/20"
          />
          {t('sqltojulia.use_datetime', 'Use Dates.DateTime for timestamps')}
        </label>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <Database className="w-4 h-4 text-indigo-500" />
              <label htmlFor="sql-julia-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">{t('sqltojulia.input_label', 'SQL CREATE TABLE DDL')}</label>
            </div>
            <div className="flex items-center gap-2">
              <Kbd modifier={null} className="hidden sm:inline-flex border-rose-200 dark:border-rose-800 text-rose-400 dark:bg-slate-900">Esc</Kbd>
              <button
                onClick={handleClear}
                disabled={!input && !output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 dark:hover:bg-rose-500/20 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-rose-500 focus-visible:outline-none"
              >
                <Trash2 className="w-3 h-3" /> {t('common.clear')}
              </button>
            </div>
          </div>
          <textarea
            id="sql-julia-input"
            ref={inputRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder={`CREATE TABLE users (\n  id INT PRIMARY KEY,\n  username VARCHAR(50) NOT NULL,\n  email VARCHAR(100),\n  created_at TIMESTAMP\n);`}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none"
          />
        </div>

        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <Database className="w-4 h-4 text-emerald-500 animate-pulse" />
              <label htmlFor="julia-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">{t('sqltojulia.output_label', 'Julia Struct Definitions')}</label>
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                disabled={!output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-indigo-500 bg-indigo-50 dark:bg-indigo-500/10 hover:bg-indigo-100 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
              >
                <Download className="w-3 h-3" /> {t('common.download')}
              </button>
              <button
                onClick={handleCopy}
                disabled={!output}
                className={`text-xs font-bold px-3 py-1.5 rounded-xl transition-all flex items-center gap-1 border focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-500/20'
                    : 'text-slate-500 bg-slate-100 dark:bg-slate-800 border-transparent hover:bg-slate-200 dark:hover:bg-slate-700 disabled:opacity-50 disabled:cursor-not-allowed'
                }`}
              >
                {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />} {copied ? t('common.copied') : t('common.copy')}
                {!copied && input && <Kbd modifier={null} className="hidden sm:inline-flex w-4 h-4 bg-white/50 dark:bg-black/20 ml-1">C</Kbd>}
              </button>
            </div>
          </div>
          <textarea
            id="julia-output"
            value={output}
            readOnly
            placeholder={t('sqltojulia.placeholder_output', 'Generated Julia struct definitions will appear here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400 resize-none"
          />
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold animate-in fade-in slide-in-from-top-2">
          <AlertCircle className="w-5 h-5" />
          {error}
        </div>
      )}

      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <Info className="w-6 h-6 text-indigo-500 mt-1" />
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">{t('sqltojulia.about_title', 'About SQL DDL to Julia Struct Generator')}</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            {t('sqltojulia.about_text', 'Convert SQL CREATE TABLE DDL queries into strongly-typed Julia struct or mutable struct definitions. Supports column type inferencing (Int64, Float64, String, Bool, Dates.DateTime), Union{Nothing, T} nullability for nullable SQL columns, StructTypes.jl or JSON3.jl serialization bindings, field casing transformations, and Julia reserved keyword escaping.')}
          </p>
        </div>
      </div>
    </div>
  );
}
