import { useState, useEffect, useCallback, useRef } from 'react';
import { FileCode, Copy, Check, Trash2, AlertCircle, Download, Info, Database, Sparkles } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;

const RUST_KEYWORDS = new Set([
  'as', 'break', 'const', 'continue', 'crate', 'else', 'enum', 'extern', 'false', 'fn',
  'for', 'if', 'impl', 'in', 'let', 'loop', 'match', 'mod', 'move', 'mut', 'pub', 'ref',
  'return', 'self', 'Self', 'static', 'struct', 'super', 'trait', 'true', 'type', 'unsafe',
  'use', 'where', 'while', 'async', 'await', 'dyn', 'abstract', 'become', 'box', 'do',
  'final', 'macro', 'override', 'priv', 'typeof', 'unsized', 'virtual', 'yield', 'try'
]);

const PRESETS = {
  ecommerce: `-- E-Commerce Catalog Schema
CREATE TABLE categories (
  id INT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) UNIQUE NOT NULL,
  parent_id INT DEFAULT NULL
);

CREATE TABLE products (
  id INT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  sku VARCHAR(50) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  category_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  metadata JSON
);`,
  user_auth: `-- User Auth & Roles Schema
CREATE TABLE users (
  user_id UUID PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(100),
  is_verified BOOLEAN DEFAULT FALSE,
  login_count INT DEFAULT 0,
  last_login TIMESTAMP,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE roles (
  role_id INT PRIMARY KEY,
  role_name VARCHAR(50) NOT NULL,
  permissions JSON
);`,
  blog_cms: `-- Blog CMS & Comments Schema
CREATE TABLE posts (
  post_id INT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  slug VARCHAR(200) NOT NULL,
  content TEXT,
  author_id UUID NOT NULL,
  published_at TIMESTAMP,
  is_draft BOOLEAN DEFAULT TRUE
);

CREATE TABLE comments (
  comment_id INT PRIMARY KEY,
  post_id INT NOT NULL,
  author_name VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL
);`
};

export function SQLToSeaORM({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const [input, setInput] = useState(initialData?.input || '');
  const [output, setOutput] = useState(initialData?.output || '');
  const [activePreset, setActivePreset] = useState<string | null>(null);
  const [outputMode, setOutputMode] = useState<'full' | 'model_only'>('full');
  const [casing, setCasing] = useState<'snake_case' | 'camelCase' | 'PascalCase' | 'original'>(
    initialData?.casing || 'snake_case'
  );
  const [deriveSerde, setDeriveSerde] = useState(initialData?.deriveSerde ?? true);
  const [deriveEq, setDeriveEq] = useState(initialData?.deriveEq ?? true);
  const [primaryKeyAutoIncrement, setPrimaryKeyAutoIncrement] = useState(initialData?.primaryKeyAutoIncrement ?? true);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    onStateChange?.({
      input,
      output,
      outputMode,
      casing,
      deriveSerde,
      deriveEq,
      primaryKeyAutoIncrement
    });
  }, [input, output, outputMode, casing, deriveSerde, deriveEq, primaryKeyAutoIncrement, onStateChange]);

  const toPascalCase = (str: string) => {
    return str
      .replace(/[^a-zA-Z0-9]/g, ' ')
      .split(' ')
      .filter(Boolean)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('') || 'AutoGeneratedEntity';
  };

  const toSnakeCase = (str: string) => {
    let result = str
      .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
      .replace(/[^a-zA-Z0-9]/g, '_')
      .replace(/_+/g, '_')
      .toLowerCase();

    if (/^[0-9]/.test(result)) {
      result = 'f_' + result;
    }
    return result;
  };

  const toCamelCase = (str: string) => {
    const pascal = toPascalCase(str);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  };

  const formatFieldName = (fieldName: string): { rustKey: string; originalName: string } => {
    let formattedKey = fieldName;
    if (casing === 'snake_case') {
      formattedKey = toSnakeCase(fieldName);
    } else if (casing === 'camelCase') {
      formattedKey = toCamelCase(fieldName);
    } else if (casing === 'PascalCase') {
      formattedKey = toPascalCase(fieldName);
    }

    let rustKey = formattedKey;
    if (/^[0-9]/.test(rustKey)) {
      rustKey = 'f_' + rustKey;
    }

    if (RUST_KEYWORDS.has(rustKey)) {
      rustKey = 'r#' + rustKey;
    }

    return { rustKey, originalName: fieldName };
  };

  const mapSqlTypeToSeaORM = (sqlType: string): { rustType: string; columnType?: string } => {
    if (!sqlType) return { rustType: 'String' };
    const type = sqlType.toUpperCase();

    if (type.includes('UUID')) {
      return { rustType: 'Uuid' };
    }
    if (type.includes('BIGINT') || type.includes('BIGSERIAL')) {
      return { rustType: 'i64' };
    }
    if (type.includes('INT') || type.includes('SERIAL')) {
      return { rustType: 'i32' };
    }
    if (type.includes('SMALLINT')) {
      return { rustType: 'i16' };
    }
    if (type.includes('TINYINT') || type.includes('BOOL') || type.includes('BIT')) {
      return { rustType: 'bool' };
    }
    if (type.includes('DECIMAL') || type.includes('NUMERIC')) {
      return { rustType: 'Decimal' };
    }
    if (type.includes('FLOAT') || type.includes('DOUBLE') || type.includes('REAL')) {
      return { rustType: 'f64' };
    }
    if (type.includes('DATE') && !type.includes('TIME')) {
      return { rustType: 'Date' };
    }
    if (type.includes('TIME') || type.includes('TIMESTAMP') || type.includes('DATETIME')) {
      return { rustType: 'DateTime' };
    }
    if (type.includes('JSON') || type.includes('JSONB')) {
      return { rustType: 'Json', columnType: type.includes('JSONB') ? 'JsonBinary' : 'Json' };
    }
    if (type.includes('TEXT')) {
      return { rustType: 'String', columnType: 'Text' };
    }
    if (type.includes('BYTEA') || type.includes('BLOB')) {
      return { rustType: 'Vec<u8>' };
    }

    return { rustType: 'String' };
  };

  const handleConvert = useCallback(() => {
    try {
      if (!input.trim()) {
        setOutput('');
        setError('');
        return;
      }
      if (input.length > MAX_LENGTH) {
        setError(t('error.max_length', { max: MAX_LENGTH.toLocaleString() }));
        return;
      }

      const cleanInput = input
        .replace(/--.*$/gm, '')
        .replace(/\/\*[\s\S]*?\*\//g, '');

      const tableRegex = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:["`]?(\w+)["`]?\.)?["`]?(\w+)["`]?\s*\(([\s\S]*?)\);/gi;
      let match;
      const entities: Array<{
        tableName: string;
        moduleName: string;
        fields: Array<{
          name: string;
          rustKey: string;
          originalName: string;
          rustType: string;
          columnType?: string;
          isPrimaryKey: boolean;
          isOptional: boolean;
        }>;
        foreignKeys: Array<{
          column: string;
          refTable: string;
          refColumn: string;
        }>;
      }> = [];

      while ((match = tableRegex.exec(cleanInput)) !== null) {
        const tableName = match[2];
        const columnsContent = match[3];
        const moduleName = toSnakeCase(tableName);

        const columnLines: string[] = [];
        let currentLine = '';
        let inQuotes = false;
        let quoteChar = '';
        let parenDepth = 0;

        for (let i = 0; i < columnsContent.length; i++) {
          const char = columnsContent[i];
          if ((char === '"' || char === '`' || char === "'") && columnsContent[i - 1] !== '\\') {
            if (!inQuotes) {
              inQuotes = true;
              quoteChar = char;
            } else if (char === quoteChar) {
              inQuotes = false;
            }
          }

          if (!inQuotes) {
            if (char === '(') parenDepth++;
            if (char === ')') parenDepth--;
          }

          if (char === ',' && !inQuotes && parenDepth === 0) {
            columnLines.push(currentLine.trim());
            currentLine = '';
          } else {
            currentLine += char;
          }
        }
        if (currentLine.trim()) columnLines.push(currentLine.trim());

        const foreignKeys: Array<{ column: string; refTable: string; refColumn: string }> = [];

        // Check composite PRIMARY KEY or FOREIGN KEY constraint lines
        filteredConstraintCheck(columnLines, foreignKeys);

        const fields = columnLines.map(line => {
          const trimmed = line.trim();
          if (!trimmed) return null;
          const upper = trimmed.toUpperCase();
          if (
            upper.startsWith('PRIMARY KEY') ||
            upper.startsWith('CONSTRAINT') ||
            upper.startsWith('UNIQUE') ||
            upper.startsWith('FOREIGN KEY') ||
            upper.startsWith('INDEX') ||
            upper.startsWith('KEY')
          ) {
            return null;
          }

          let rawName = '';
          let sqlType = '';

          if (trimmed.startsWith('"') || trimmed.startsWith('`') || trimmed.startsWith("'")) {
            const quote = trimmed[0];
            let i = 1;
            rawName = '';
            while (i < trimmed.length && (trimmed[i] !== quote || trimmed[i - 1] === '\\')) {
              rawName += trimmed[i];
              i++;
            }
            const remaining = trimmed.substring(i + 1).trim();
            sqlType = remaining.split(/\s+/)[0];
          } else {
            const parts = trimmed.split(/\s+/);
            rawName = parts[0];
            sqlType = parts[1];
          }

          if (!rawName) return null;

          const isPrimaryKey = upper.includes('PRIMARY KEY');
          const isNullable = (!upper.includes('NOT NULL') && !isPrimaryKey) || upper.includes('DEFAULT NULL');
          const { rustType, columnType } = mapSqlTypeToSeaORM(sqlType || 'VARCHAR');
          const { rustKey, originalName } = formatFieldName(rawName);

          return {
            name: rawName,
            rustKey,
            originalName,
            rustType,
            columnType,
            isPrimaryKey,
            isOptional: isNullable
          };
        }).filter(Boolean) as any[];

        entities.push({
          tableName,
          moduleName,
          fields,
          foreignKeys
        });
      }

      if (entities.length === 0) {
        setError(t('sqltoseaorm.no_tables_found', 'No valid CREATE TABLE statements found.'));
        setOutput('');
        return;
      }

      let generatedCode = 'use sea_orm::entity::prelude::*;\n';
      if (deriveSerde) {
        generatedCode += 'use serde::{Serialize, Deserialize};\n';
      }
      generatedCode += '\n';

      entities.forEach((entity, idx) => {
        const derives = ['Clone', 'Debug', 'PartialEq', 'DeriveEntityModel'];
        if (deriveEq) derives.push('Eq');
        if (deriveSerde) derives.push('Serialize', 'Deserialize');

        if (outputMode === 'full' && entities.length > 1) {
          generatedCode += `pub mod ${entity.moduleName} {\n    use super::*;\n\n`;
        }

        const indent = (outputMode === 'full' && entities.length > 1) ? '    ' : '';

        generatedCode += `${indent}#[derive(${derives.join(', ')})]\n`;
        generatedCode += `${indent}#[sea_orm(table_name = "${entity.tableName}")]\n`;
        generatedCode += `${indent}pub struct Model {\n`;

        entity.fields.forEach(field => {
          const attributes: string[] = [];
          if (field.isPrimaryKey) {
            if (!primaryKeyAutoIncrement) {
              attributes.push('primary_key', 'auto_increment = false');
            } else {
              attributes.push('primary_key');
            }
          }
          if (field.columnType) {
            attributes.push(`column_type = "${field.columnType}"`);
          }
          if (field.rustKey !== field.originalName) {
            attributes.push(`column_name = "${field.originalName}"`);
          }

          if (attributes.length > 0) {
            generatedCode += `${indent}    #[sea_orm(${attributes.join(', ')})]\n`;
          }

          const fieldTypeStr = field.isOptional ? `Option<${field.rustType}>` : field.rustType;
          generatedCode += `${indent}    pub ${field.rustKey}: ${fieldTypeStr},\n`;
        });

        generatedCode += `${indent}}\n\n`;

        // Relation Enum
        generatedCode += `${indent}#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]\n`;
        if (entity.foreignKeys.length > 0) {
          generatedCode += `${indent}pub enum Relation {\n`;
          entity.foreignKeys.forEach(fk => {
            const refEntity = toPascalCase(fk.refTable);
            generatedCode += `${indent}    #[sea_orm(\n`;
            generatedCode += `${indent}        belongs_to = "super::${toSnakeCase(fk.refTable)}::Entity",\n`;
            generatedCode += `${indent}        from = "Column::${toPascalCase(fk.column)}",\n`;
            generatedCode += `${indent}        to = "super::${toSnakeCase(fk.refTable)}::Column::${toPascalCase(fk.refColumn)}",\n`;
            generatedCode += `${indent}        on_update = "NoAction",\n`;
            generatedCode += `${indent}        on_delete = "NoAction"\n`;
            generatedCode += `${indent}    )]\n`;
            generatedCode += `${indent}    ${refEntity},\n`;
          });
          generatedCode += `${indent}}\n\n`;
        } else {
          generatedCode += `${indent}pub enum Relation {}\n\n`;
        }

        generatedCode += `${indent}impl ActiveModelBehavior for ActiveModel {}\n`;

        if (outputMode === 'full' && entities.length > 1) {
          generatedCode += `}\n\n`;
        } else if (idx < entities.length - 1) {
          generatedCode += '\n' + '-'.repeat(40) + '\n\n';
        }
      });

      setOutput(generatedCode.trim());
      setError('');
    } catch (e: any) {
      setError(t('sqltoseaorm.error_parsing', 'Error parsing SQL DDL') + ': ' + e.message);
      setOutput('');
    }
  }, [input, outputMode, casing, deriveSerde, deriveEq, primaryKeyAutoIncrement, t]);

  function filteredConstraintCheck(lines: string[], foreignKeys: Array<{ column: string; refTable: string; refColumn: string }>) {
    lines.forEach(line => {
      const fkMatch = line.match(/FOREIGN\s+KEY\s*\((?:["`]?(\w+)["`]?)\)\s*REFERENCES\s*(?:["`]?(\w+)["`]?)\s*\((?:["`]?(\w+)["`]?)\)/i);
      if (fkMatch) {
        foreignKeys.push({
          column: fkMatch[1],
          refTable: fkMatch[2],
          refColumn: fkMatch[3]
        });
      }
    });
  }

  useEffect(() => {
    handleConvert();
  }, [handleConvert]);

  const handleCopy = useCallback(() => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    toast.success(t('common.copied', 'Copied to clipboard!'));
    setTimeout(() => setCopied(false), 2000);
  }, [output, t]);

  const handleClear = useCallback(() => {
    setInput('');
    setOutput('');
    setError('');
    setActivePreset(null);
    toast.success(t('common.cleared', 'Cleared!'));
    setTimeout(() => inputRef.current?.focus(), 0);
  }, [t]);

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/x-rust' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'entity.rs';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(t('common.downloaded', 'Downloaded entity.rs!'));
  };

  const loadPreset = (presetKey: keyof typeof PRESETS) => {
    setInput(PRESETS[presetKey]);
    setActivePreset(presetKey);
    toast.success(t('sqltoseaorm.preset_loaded', 'Loaded SeaORM SQL preset!'));
  };

  const handlersRef = useRef({ handleClear, handleCopy, output });
  useEffect(() => {
    handlersRef.current = { handleClear, handleCopy, output };
  }, [handleClear, handleCopy, output]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const activeElement = document.activeElement;
      const isEditable =
        activeElement instanceof HTMLInputElement ||
        activeElement instanceof HTMLTextAreaElement ||
        activeElement instanceof HTMLSelectElement ||
        activeElement?.getAttribute("contenteditable") === "true";

      if (isEditable && e.key !== 'Escape') return;

      if (e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;

      if (e.key === "Escape") {
        e.preventDefault();
        handlersRef.current.handleClear();
      } else if (e.key.toLowerCase() === "c") {
        if (handlersRef.current.output) {
          e.preventDefault();
          handlersRef.current.handleCopy();
        }
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, []);

  return (
    <div className="max-w-6xl mx-auto space-y-8 animate-in fade-in duration-500">
      {/* Presets Bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 p-4 bg-slate-50 dark:bg-slate-900/50 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-amber-500" aria-hidden="true" />
          <span className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltoseaorm.presets_title', 'Clickable Presets')}
          </span>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={() => loadPreset('ecommerce')}
            aria-pressed={activePreset === 'ecommerce'}
            className={`px-3 py-1.5 text-xs font-bold rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
              activePreset === 'ecommerce'
                ? 'bg-indigo-600 text-white border-indigo-600'
                : 'bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500'
            }`}
          >
            {t('sqltoseaorm.preset_ecommerce', 'E-Commerce Catalog')}
          </button>
          <button
            onClick={() => loadPreset('user_auth')}
            aria-pressed={activePreset === 'user_auth'}
            className={`px-3 py-1.5 text-xs font-bold rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
              activePreset === 'user_auth'
                ? 'bg-indigo-600 text-white border-indigo-600'
                : 'bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500'
            }`}
          >
            {t('sqltoseaorm.preset_user_auth', 'User Auth & Roles')}
          </button>
          <button
            onClick={() => loadPreset('blog_cms')}
            aria-pressed={activePreset === 'blog_cms'}
            className={`px-3 py-1.5 text-xs font-bold rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
              activePreset === 'blog_cms'
                ? 'bg-indigo-600 text-white border-indigo-600'
                : 'bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500'
            }`}
          >
            {t('sqltoseaorm.preset_blog_cms', 'Blog CMS & Comments')}
          </button>
        </div>
      </div>

      {/* Options Panel */}
      <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-4 p-5 bg-white dark:bg-slate-900/60 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="space-y-1.5">
          <label htmlFor="seaorm-output-mode" className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltoseaorm.output_mode_label', 'Output Layout')}
          </label>
          <select
            id="seaorm-output-mode"
            value={outputMode}
            onChange={(e) => setOutputMode(e.target.value as any)}
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="full">Full Entity Modules (pub mod)</option>
            <option value="model_only">Model Struct Only</option>
          </select>
        </div>

        <div className="space-y-1.5">
          <label htmlFor="seaorm-casing" className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltoseaorm.casing_label', 'Field Casing')}
          </label>
          <select
            id="seaorm-casing"
            value={casing}
            onChange={(e) => setCasing(e.target.value as any)}
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="snake_case">snake_case (Rust standard)</option>
            <option value="camelCase">camelCase</option>
            <option value="PascalCase">PascalCase</option>
            <option value="original">original (unchanged)</option>
          </select>
        </div>

        <div className="flex flex-col justify-center space-y-2 pt-2">
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={deriveSerde}
              onChange={(e) => setDeriveSerde(e.target.checked)}
              className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
            />
            <span className="text-xs font-bold text-slate-700 dark:text-slate-300">
              Derive Serde (Serialize, Deserialize)
            </span>
          </label>
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={deriveEq}
              onChange={(e) => setDeriveEq(e.target.checked)}
              className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
            />
            <span className="text-xs font-bold text-slate-700 dark:text-slate-300">
              Derive Eq
            </span>
          </label>
        </div>

        <div className="flex flex-col justify-center space-y-2 pt-2">
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={primaryKeyAutoIncrement}
              onChange={(e) => setPrimaryKeyAutoIncrement(e.target.checked)}
              className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
            />
            <span className="text-xs font-bold text-slate-700 dark:text-slate-300">
              Auto-increment Primary Keys
            </span>
          </label>
        </div>
      </div>

      {/* Editor Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <Database className="w-4 h-4 text-indigo-500" aria-hidden="true" />
              <label htmlFor="sql-seaorm-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('sqltoseaorm.sql_input_label', 'SQL CREATE TABLE DDL')}
              </label>
            </div>
            <div className="flex items-center gap-2">
              <Kbd modifier={null} className="hidden sm:inline-flex border-rose-200 dark:border-rose-800 text-rose-400 dark:bg-slate-900">Esc</Kbd>
              <button
                onClick={handleClear}
                disabled={!input && !output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 dark:hover:bg-rose-500/20 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-rose-500 focus-visible:outline-none"
              >
                <Trash2 className="w-3 h-3" aria-hidden="true" /> {t('common.clear')}
              </button>
            </div>
          </div>
          <textarea
            id="sql-seaorm-input"
            ref={inputRef}
            value={input}
            onChange={(e) => {
              setInput(e.target.value);
              setActivePreset(null);
            }}
            placeholder={t('sqltoseaorm.placeholder_sql', 'Paste SQL CREATE TABLE DDL statements here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none"
          />
        </div>

        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-emerald-500" aria-hidden="true" />
              <label htmlFor="seaorm-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('sqltoseaorm.output_label', 'SeaORM Entity Definitions')}
              </label>
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                disabled={!output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-indigo-500 bg-indigo-50 dark:bg-indigo-500/10 hover:bg-indigo-100 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
              >
                <Download className="w-3 h-3" aria-hidden="true" /> {t('common.download')}
              </button>
              <button
                onClick={handleCopy}
                disabled={!output}
                className={`text-xs font-bold px-3 py-1.5 rounded-xl transition-all flex items-center gap-1 border focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-500/20'
                    : 'text-slate-500 bg-slate-100 dark:bg-slate-800 border-transparent hover:bg-slate-200 dark:hover:bg-slate-700 disabled:opacity-50 disabled:cursor-not-allowed'
                }`}
              >
                {copied ? <Check className="w-3 h-3" aria-hidden="true" /> : <Copy className="w-3 h-3" aria-hidden="true" />} {copied ? t('common.copied') : t('common.copy')}
                {!copied && input && <Kbd modifier={null} className="hidden sm:inline-flex w-4 h-4 bg-white/50 dark:bg-black/20 ml-1">C</Kbd>}
              </button>
            </div>
          </div>
          <textarea
            id="seaorm-output"
            value={output}
            readOnly
            placeholder={t('sqltoseaorm.placeholder_output', 'Rust SeaORM entity definitions will appear here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400 resize-none"
          />
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold animate-in fade-in slide-in-from-top-2">
          <AlertCircle className="w-5 h-5" aria-hidden="true" />
          {error}
        </div>
      )}

      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <Info className="w-6 h-6 text-indigo-500 mt-1" aria-hidden="true" />
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">{t('sqltoseaorm.about_title', 'About SQL to SeaORM Entity Generator')}</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            {t('sqltoseaorm.about_text', 'Convert SQL CREATE TABLE DDL queries into Rust SeaORM Entity models. Generates DeriveEntityModel attributes, Relation enums with foreign key attributes, ActiveModelBehavior implementations, primary keys, and data type mappings for async Rust backend applications.')}
          </p>
        </div>
      </div>
    </div>
  );
}
