import { useState, useEffect, useCallback, useRef } from 'react';
import { FileCode, Copy, Check, Trash2, AlertCircle, Download, Info, Database, Sparkles } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;

const RUST_KEYWORDS = new Set([
  'as', 'break', 'const', 'continue', 'crate', 'else', 'enum', 'extern', 'false', 'fn',
  'for', 'if', 'impl', 'in', 'let', 'loop', 'match', 'mod', 'move', 'mut', 'pub', 'ref',
  'return', 'self', 'Self', 'static', 'struct', 'super', 'trait', 'true', 'type', 'unsafe',
  'use', 'where', 'while', 'async', 'await', 'dyn', 'abstract', 'become', 'box', 'do',
  'final', 'macro', 'override', 'priv', 'typeof', 'unsized', 'virtual', 'yield', 'try'
]);

const PRESETS = {
  ecommerce: `-- E-Commerce Catalog Schema
CREATE TABLE categories (
  id INT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) UNIQUE NOT NULL,
  parent_id INT DEFAULT NULL
);

CREATE TABLE products (
  id INT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  sku VARCHAR(50) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  category_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  metadata JSON
);`,
  user_auth: `-- User Auth & Roles Schema
CREATE TABLE users (
  user_id UUID PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(100),
  is_verified BOOLEAN DEFAULT FALSE,
  login_count INT DEFAULT 0,
  last_login TIMESTAMP,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE roles (
  role_id INT PRIMARY KEY,
  role_name VARCHAR(50) NOT NULL,
  permissions JSON
);`,
  blog_cms: `-- Blog CMS & Comments Schema
CREATE TABLE posts (
  post_id INT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  slug VARCHAR(200) NOT NULL,
  content TEXT,
  author_id UUID NOT NULL,
  published_at TIMESTAMP,
  is_draft BOOLEAN DEFAULT TRUE
);

CREATE TABLE comments (
  comment_id INT PRIMARY KEY,
  post_id INT NOT NULL,
  author_name VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL
);`
};

export function SQLToDiesel({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const [input, setInput] = useState(initialData?.input || '');
  const [output, setOutput] = useState(initialData?.output || '');
  const [activePreset, setActivePreset] = useState<string | null>(null);
  const [outputMode, setOutputMode] = useState<'full' | 'schema_only' | 'struct_only'>('full');
  const [casing, setCasing] = useState<'snake_case' | 'camelCase' | 'PascalCase' | 'original'>(
    initialData?.casing || 'snake_case'
  );
  const [deriveSerde, setDeriveSerde] = useState(initialData?.deriveSerde ?? true);
  const [deriveChangeset, setDeriveChangeset] = useState(initialData?.deriveChangeset ?? true);
  const [useChrono, setUseChrono] = useState(initialData?.useChrono ?? true);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    onStateChange?.({
      input,
      output,
      outputMode,
      casing,
      deriveSerde,
      deriveChangeset,
      useChrono
    });
  }, [input, output, outputMode, casing, deriveSerde, deriveChangeset, useChrono, onStateChange]);

  const toPascalCase = (str: string) => {
    return str
      .replace(/[^a-zA-Z0-9]/g, ' ')
      .split(' ')
      .filter(Boolean)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('') || 'AutoGeneratedEntity';
  };

  const toSnakeCase = (str: string) => {
    let result = str
      .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
      .replace(/[^a-zA-Z0-9]/g, '_')
      .replace(/_+/g, '_')
      .toLowerCase();

    if (/^[0-9]/.test(result)) {
      result = 'f_' + result;
    }
    return result;
  };

  const toCamelCase = (str: string) => {
    const pascal = toPascalCase(str);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  };

  const formatFieldName = (fieldName: string): { rustKey: string; originalName: string } => {
    let formattedKey = fieldName;
    if (casing === 'snake_case') {
      formattedKey = toSnakeCase(fieldName);
    } else if (casing === 'camelCase') {
      formattedKey = toCamelCase(fieldName);
    } else if (casing === 'PascalCase') {
      formattedKey = toPascalCase(fieldName);
    }

    let rustKey = formattedKey;
    if (/^[0-9]/.test(rustKey)) {
      rustKey = 'f_' + rustKey;
    }

    if (RUST_KEYWORDS.has(rustKey)) {
      rustKey = 'r#' + rustKey;
    }

    return { rustKey, originalName: fieldName };
  };

  const mapSqlTypeToDiesel = (sqlType: string): { dieselType: string; rustType: string } => {
    if (!sqlType) return { dieselType: 'Varchar', rustType: 'String' };
    const type = sqlType.toUpperCase();

    if (type.includes('UUID')) {
      return { dieselType: 'Uuid', rustType: 'uuid::Uuid' };
    }
    if (type.includes('BIGINT') || type.includes('BIGSERIAL')) {
      return { dieselType: 'BigInt', rustType: 'i64' };
    }
    if (type.includes('INT') || type.includes('SERIAL')) {
      return { dieselType: 'Integer', rustType: 'i32' };
    }
    if (type.includes('SMALLINT')) {
      return { dieselType: 'SmallInt', rustType: 'i16' };
    }
    if (type.includes('TINYINT') || type.includes('BOOL') || type.includes('BIT')) {
      return { dieselType: 'Bool', rustType: 'bool' };
    }
    if (type.includes('DECIMAL') || type.includes('NUMERIC')) {
      return { dieselType: 'Numeric', rustType: 'f64' };
    }
    if (type.includes('FLOAT') || type.includes('REAL')) {
      return { dieselType: 'Float', rustType: 'f32' };
    }
    if (type.includes('DOUBLE')) {
      return { dieselType: 'Double', rustType: 'f64' };
    }
    if (type.includes('DATE') && !type.includes('TIME')) {
      return { dieselType: 'Date', rustType: useChrono ? 'chrono::NaiveDate' : 'String' };
    }
    if (type.includes('TIME') || type.includes('TIMESTAMP') || type.includes('DATETIME')) {
      return { dieselType: 'Timestamp', rustType: useChrono ? 'chrono::NaiveDateTime' : 'String' };
    }
    if (type.includes('JSON') || type.includes('JSONB')) {
      return { dieselType: 'Jsonb', rustType: 'serde_json::Value' };
    }
    if (type.includes('TEXT')) {
      return { dieselType: 'Text', rustType: 'String' };
    }
    if (type.includes('BYTEA') || type.includes('BLOB')) {
      return { dieselType: 'Bytea', rustType: 'Vec<u8>' };
    }

    return { dieselType: 'Varchar', rustType: 'String' };
  };

  const handleConvert = useCallback(() => {
    try {
      if (!input.trim()) {
        setOutput('');
        setError('');
        return;
      }
      if (input.length > MAX_LENGTH) {
        setError(t('error.max_length', { max: MAX_LENGTH.toLocaleString() }));
        return;
      }

      const cleanInput = input
        .replace(/--.*$/gm, '')
        .replace(/\/\*[\s\S]*?\*\//g, '');

      const tableRegex = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:["`]?(\w+)["`]?\.)?["`]?(\w+)["`]?\s*\(([\s\S]*?)\);/gi;
      let match;
      const tables: Array<{
        tableName: string;
        structName: string;
        primaryKey: string;
        fields: Array<{
          name: string;
          rustKey: string;
          dieselType: string;
          rustType: string;
          isPrimaryKey: boolean;
          isNullable: boolean;
        }>;
      }> = [];

      while ((match = tableRegex.exec(cleanInput)) !== null) {
        const tableName = match[2];
        const columnsContent = match[3];
        const structName = toPascalCase(tableName);

        const columnLines: string[] = [];
        let currentLine = '';
        let inQuotes = false;
        let quoteChar = '';
        let parenDepth = 0;

        for (let i = 0; i < columnsContent.length; i++) {
          const char = columnsContent[i];
          if ((char === '"' || char === '`' || char === "'") && columnsContent[i - 1] !== '\\') {
            if (!inQuotes) {
              inQuotes = true;
              quoteChar = char;
            } else if (char === quoteChar) {
              inQuotes = false;
            }
          }

          if (!inQuotes) {
            if (char === '(') parenDepth++;
            if (char === ')') parenDepth--;
          }

          if (char === ',' && !inQuotes && parenDepth === 0) {
            columnLines.push(currentLine.trim());
            currentLine = '';
          } else {
            currentLine += char;
          }
        }
        if (currentLine.trim()) columnLines.push(currentLine.trim());

        let tablePrimaryKey = 'id';

        const fields = columnLines.map(line => {
          const trimmed = line.trim();
          if (!trimmed) return null;
          const upper = trimmed.toUpperCase();

          if (upper.startsWith('PRIMARY KEY')) {
            const pkMatch = trimmed.match(/PRIMARY\s+KEY\s*\((?:["`]?(\w+)["`]?)\)/i);
            if (pkMatch) tablePrimaryKey = pkMatch[1];
            return null;
          }

          if (
            upper.startsWith('CONSTRAINT') ||
            upper.startsWith('UNIQUE') ||
            upper.startsWith('FOREIGN KEY') ||
            upper.startsWith('INDEX') ||
            upper.startsWith('KEY')
          ) {
            return null;
          }

          let rawName = '';
          let sqlType = '';

          if (trimmed.startsWith('"') || trimmed.startsWith('`') || trimmed.startsWith("'")) {
            const quote = trimmed[0];
            let i = 1;
            rawName = '';
            while (i < trimmed.length && (trimmed[i] !== quote || trimmed[i - 1] === '\\')) {
              rawName += trimmed[i];
              i++;
            }
            const remaining = trimmed.substring(i + 1).trim();
            sqlType = remaining.split(/\s+/)[0];
          } else {
            const parts = trimmed.split(/\s+/);
            rawName = parts[0];
            sqlType = parts[1];
          }

          if (!rawName) return null;

          const isPrimaryKey = upper.includes('PRIMARY KEY');
          if (isPrimaryKey) tablePrimaryKey = rawName;

          const isNullable = (!upper.includes('NOT NULL') && !isPrimaryKey) || upper.includes('DEFAULT NULL');
          const { dieselType, rustType } = mapSqlTypeToDiesel(sqlType || 'VARCHAR');
          const { rustKey } = formatFieldName(rawName);

          return {
            name: rawName,
            rustKey,
            dieselType,
            rustType,
            isPrimaryKey,
            isNullable
          };
        }).filter(Boolean) as any[];

        tables.push({
          tableName,
          structName,
          primaryKey: tablePrimaryKey,
          fields
        });
      }

      if (tables.length === 0) {
        setError(t('sqltodiesel.no_tables_found', 'No valid CREATE TABLE statements found.'));
        setOutput('');
        return;
      }

      let generatedCode = '// Generated by Multi-Tool Box - SQL to Diesel ORM\n';
      generatedCode += 'use diesel::prelude::*;\n';
      if (deriveSerde) {
        generatedCode += 'use serde::{Serialize, Deserialize};\n';
      }
      generatedCode += '\n';

      tables.forEach((table) => {
        // Schema table! macro
        if (outputMode === 'full' || outputMode === 'schema_only') {
          generatedCode += `diesel::table! {\n`;
          generatedCode += `    ${table.tableName} (${table.primaryKey}) {\n`;
          table.fields.forEach(field => {
            const typeStr = field.isNullable ? `Nullable<${field.dieselType}>` : field.dieselType;
            generatedCode += `        ${field.rustKey} -> ${typeStr},\n`;
          });
          generatedCode += `    }\n}\n\n`;
        }

        // Struct definitions
        if (outputMode === 'full' || outputMode === 'struct_only') {
          const derives = ['Queryable', 'Selectable', 'Identifiable'];
          if (deriveChangeset) derives.push('AsChangeset');
          if (deriveSerde) derives.push('Serialize', 'Deserialize');

          generatedCode += `#[derive(${derives.join(', ')})]\n`;
          generatedCode += `#[diesel(table_name = crate::schema::${table.tableName})]\n`;
          generatedCode += `#[diesel(primary_key(${table.primaryKey}))]\n`;
          generatedCode += `pub struct ${table.structName} {\n`;

          table.fields.forEach(field => {
            const fieldTypeStr = field.isNullable ? `Option<${field.rustType}>` : field.rustType;
            generatedCode += `    pub ${field.rustKey}: ${fieldTypeStr},\n`;
          });

          generatedCode += `}\n\n`;

          // Insertable struct
          const insertDerives = ['Insertable'];
          if (deriveSerde) insertDerives.push('Serialize', 'Deserialize');

          generatedCode += `#[derive(${insertDerives.join(', ')})]\n`;
          generatedCode += `#[diesel(table_name = crate::schema::${table.tableName})]\n`;
          generatedCode += `pub struct New${table.structName} {\n`;

          table.fields.filter(f => !f.isPrimaryKey).forEach(field => {
            const fieldTypeStr = field.isNullable ? `Option<${field.rustType}>` : field.rustType;
            generatedCode += `    pub ${field.rustKey}: ${fieldTypeStr},\n`;
          });

          generatedCode += `}\n\n`;
        }
      });

      setOutput(generatedCode.trim());
      setError('');
    } catch (e: any) {
      setError(t('sqltodiesel.error_parsing', 'Error parsing SQL DDL') + ': ' + e.message);
      setOutput('');
    }
  }, [input, outputMode, casing, deriveSerde, deriveChangeset, useChrono, t]);

  useEffect(() => {
    handleConvert();
  }, [handleConvert]);

  const handleCopy = useCallback(() => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    toast.success(t('common.copied', 'Copied to clipboard!'));
    setTimeout(() => setCopied(false), 2000);
  }, [output, t]);

  const handleClear = useCallback(() => {
    setInput('');
    setOutput('');
    setError('');
    setActivePreset(null);
    toast.success(t('common.cleared', 'Cleared!'));
    setTimeout(() => inputRef.current?.focus(), 0);
  }, [t]);

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/x-rust' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'schema.rs';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(t('common.downloaded', 'Downloaded schema.rs!'));
  };

  const loadPreset = (presetKey: keyof typeof PRESETS) => {
    setInput(PRESETS[presetKey]);
    setActivePreset(presetKey);
    toast.success(t('sqltodiesel.preset_loaded', 'Loaded Diesel SQL preset!'));
  };

  const handlersRef = useRef({ handleClear, handleCopy, output });
  useEffect(() => {
    handlersRef.current = { handleClear, handleCopy, output };
  }, [handleClear, handleCopy, output]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const activeElement = document.activeElement;
      const isEditable =
        activeElement instanceof HTMLInputElement ||
        activeElement instanceof HTMLTextAreaElement ||
        activeElement instanceof HTMLSelectElement ||
        activeElement?.getAttribute("contenteditable") === "true";

      if (isEditable && e.key !== 'Escape') return;

      if (e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;

      if (e.key === "Escape") {
        e.preventDefault();
        handlersRef.current.handleClear();
      } else if (e.key.toLowerCase() === "c") {
        if (handlersRef.current.output) {
          e.preventDefault();
          handlersRef.current.handleCopy();
        }
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, []);

  return (
    <div className="max-w-6xl mx-auto space-y-8 animate-in fade-in duration-500">
      {/* Presets Bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 p-4 bg-slate-50 dark:bg-slate-900/50 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-amber-500" aria-hidden="true" />
          <span className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltodiesel.presets_title', 'Clickable Presets')}
          </span>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={() => loadPreset('ecommerce')}
            aria-pressed={activePreset === 'ecommerce'}
            className={`px-3 py-1.5 text-xs font-bold rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
              activePreset === 'ecommerce'
                ? 'bg-indigo-600 text-white border-indigo-600'
                : 'bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500'
            }`}
          >
            {t('sqltodiesel.preset_ecommerce', 'E-Commerce Catalog')}
          </button>
          <button
            onClick={() => loadPreset('user_auth')}
            aria-pressed={activePreset === 'user_auth'}
            className={`px-3 py-1.5 text-xs font-bold rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
              activePreset === 'user_auth'
                ? 'bg-indigo-600 text-white border-indigo-600'
                : 'bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500'
            }`}
          >
            {t('sqltodiesel.preset_user_auth', 'User Auth & Roles')}
          </button>
          <button
            onClick={() => loadPreset('blog_cms')}
            aria-pressed={activePreset === 'blog_cms'}
            className={`px-3 py-1.5 text-xs font-bold rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
              activePreset === 'blog_cms'
                ? 'bg-indigo-600 text-white border-indigo-600'
                : 'bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500'
            }`}
          >
            {t('sqltodiesel.preset_blog_cms', 'Blog CMS & Comments')}
          </button>
        </div>
      </div>

      {/* Options Panel */}
      <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-4 p-5 bg-white dark:bg-slate-900/60 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="space-y-1.5">
          <label htmlFor="diesel-output-mode" className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltodiesel.output_mode_label', 'Output Layout')}
          </label>
          <select
            id="diesel-output-mode"
            value={outputMode}
            onChange={(e) => setOutputMode(e.target.value as any)}
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="full">Full (table! + Model & NewModel)</option>
            <option value="schema_only">Schema table! Only</option>
            <option value="struct_only">Struct Models Only</option>
          </select>
        </div>

        <div className="space-y-1.5">
          <label htmlFor="diesel-casing" className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltodiesel.casing_label', 'Field Casing')}
          </label>
          <select
            id="diesel-casing"
            value={casing}
            onChange={(e) => setCasing(e.target.value as any)}
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="snake_case">snake_case (Rust standard)</option>
            <option value="camelCase">camelCase</option>
            <option value="PascalCase">PascalCase</option>
            <option value="original">original (unchanged)</option>
          </select>
        </div>

        <div className="flex flex-col justify-center space-y-2 pt-2">
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={deriveSerde}
              onChange={(e) => setDeriveSerde(e.target.checked)}
              className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
            />
            <span className="text-xs font-bold text-slate-700 dark:text-slate-300">
              Derive Serde (Serialize, Deserialize)
            </span>
          </label>
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={deriveChangeset}
              onChange={(e) => setDeriveChangeset(e.target.checked)}
              className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
            />
            <span className="text-xs font-bold text-slate-700 dark:text-slate-300">
              Derive AsChangeset
            </span>
          </label>
        </div>

        <div className="flex flex-col justify-center space-y-2 pt-2">
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={useChrono}
              onChange={(e) => setUseChrono(e.target.checked)}
              className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
            />
            <span className="text-xs font-bold text-slate-700 dark:text-slate-300">
              Use Chrono for Date/Time
            </span>
          </label>
        </div>
      </div>

      {/* Editor Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <Database className="w-4 h-4 text-indigo-500" aria-hidden="true" />
              <label htmlFor="sql-diesel-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('sqltodiesel.sql_input_label', 'SQL CREATE TABLE DDL')}
              </label>
            </div>
            <div className="flex items-center gap-2">
              <Kbd modifier={null} className="hidden sm:inline-flex border-rose-200 dark:border-rose-800 text-rose-400 dark:bg-slate-900">Esc</Kbd>
              <button
                onClick={handleClear}
                disabled={!input && !output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 dark:hover:bg-rose-500/20 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-rose-500 focus-visible:outline-none"
              >
                <Trash2 className="w-3 h-3" aria-hidden="true" /> {t('common.clear')}
              </button>
            </div>
          </div>
          <textarea
            id="sql-diesel-input"
            ref={inputRef}
            value={input}
            onChange={(e) => {
              setInput(e.target.value);
              setActivePreset(null);
            }}
            placeholder={t('sqltodiesel.placeholder_sql', 'Paste SQL CREATE TABLE DDL statements here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none"
          />
        </div>

        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-emerald-500" aria-hidden="true" />
              <label htmlFor="diesel-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('sqltodiesel.output_label', 'Diesel ORM Schema & Structs')}
              </label>
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                disabled={!output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-indigo-500 bg-indigo-50 dark:bg-indigo-500/10 hover:bg-indigo-100 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
              >
                <Download className="w-3 h-3" aria-hidden="true" /> {t('common.download')}
              </button>
              <button
                onClick={handleCopy}
                disabled={!output}
                className={`text-xs font-bold px-3 py-1.5 rounded-xl transition-all flex items-center gap-1 border focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-500/20'
                    : 'text-slate-500 bg-slate-100 dark:bg-slate-800 border-transparent hover:bg-slate-200 dark:hover:bg-slate-700 disabled:opacity-50 disabled:cursor-not-allowed'
                }`}
              >
                {copied ? <Check className="w-3 h-3" aria-hidden="true" /> : <Copy className="w-3 h-3" aria-hidden="true" />} {copied ? t('common.copied') : t('common.copy')}
                {!copied && input && <Kbd modifier={null} className="hidden sm:inline-flex w-4 h-4 bg-white/50 dark:bg-black/20 ml-1">C</Kbd>}
              </button>
            </div>
          </div>
          <textarea
            id="diesel-output"
            value={output}
            readOnly
            placeholder={t('sqltodiesel.placeholder_output', 'Rust Diesel table! macro & model structs will appear here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400 resize-none"
          />
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold animate-in fade-in slide-in-from-top-2">
          <AlertCircle className="w-5 h-5" aria-hidden="true" />
          {error}
        </div>
      )}

      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <Info className="w-6 h-6 text-indigo-500 mt-1" aria-hidden="true" />
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">{t('sqltodiesel.about_title', 'About SQL to Diesel ORM Schema Generator')}</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            {t('sqltodiesel.about_text', 'Convert SQL CREATE TABLE DDL queries into Rust Diesel ORM table! macros and model structs (Queryable, Selectable, Insertable, Identifiable, AsChangeset). Includes full support for Nullable types, Serde derives, and field casing options.')}
          </p>
        </div>
      </div>
    </div>
  );
}
