import { useState, useEffect, useCallback, useRef } from 'react';
import { FileCode, Copy, Check, Trash2, AlertCircle, Download, Info, Database, Sparkles } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;

const RUST_KEYWORDS = new Set([
  'as', 'break', 'const', 'continue', 'crate', 'else', 'enum', 'extern', 'false', 'fn',
  'for', 'if', 'impl', 'in', 'let', 'loop', 'match', 'mod', 'move', 'mut', 'pub', 'ref',
  'return', 'self', 'Self', 'static', 'struct', 'super', 'trait', 'true', 'type', 'unsafe',
  'use', 'where', 'while', 'async', 'await', 'dyn', 'abstract', 'become', 'box', 'do',
  'final', 'macro', 'override', 'priv', 'typeof', 'unsized', 'virtual', 'yield', 'try'
]);

const PRESETS = {
  ecommerce: `-- E-Commerce Catalog Schema
CREATE TABLE categories (
  id INT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) UNIQUE NOT NULL,
  parent_id INT DEFAULT NULL
);

CREATE TABLE products (
  id INT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  sku VARCHAR(50) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  category_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  metadata JSON
);`,
  user_auth: `-- User Auth & Roles Schema
CREATE TABLE users (
  user_id UUID PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(100),
  is_verified BOOLEAN DEFAULT FALSE,
  login_count INT DEFAULT 0,
  last_login TIMESTAMP,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE roles (
  role_id INT PRIMARY KEY,
  role_name VARCHAR(50) NOT NULL,
  permissions JSON
);`
};

export function SQLToRust({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const [input, setInput] = useState(initialData?.input || '');
  const [output, setOutput] = useState(initialData?.output || '');
  const [casing, setCasing] = useState<'snake_case' | 'camelCase' | 'PascalCase' | 'original'>(
    initialData?.casing || 'snake_case'
  );
  const [framework, setFramework] = useState<'none' | 'serde' | 'sqlx' | 'diesel'>(
    initialData?.framework || 'serde'
  );
  const [deriveClone, setDeriveClone] = useState(initialData?.deriveClone ?? true);
  const [derivePartialEq, setDerivePartialEq] = useState(initialData?.derivePartialEq ?? true);
  const [deriveDefault, setDeriveDefault] = useState(initialData?.deriveDefault ?? false);
  const [useDecimal, setUseDecimal] = useState(initialData?.useDecimal ?? false);
  const [useChrono, setUseChrono] = useState(initialData?.useChrono ?? true);
  const [useUuid, setUseUuid] = useState(initialData?.useUuid ?? true);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    onStateChange?.({
      input,
      output,
      casing,
      framework,
      deriveClone,
      derivePartialEq,
      deriveDefault,
      useDecimal,
      useChrono,
      useUuid
    });
  }, [input, output, casing, framework, deriveClone, derivePartialEq, deriveDefault, useDecimal, useChrono, useUuid, onStateChange]);

  const toPascalCase = (str: string) => {
    return str
      .replace(/[^a-zA-Z0-9]/g, ' ')
      .split(' ')
      .filter(Boolean)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('') || 'AutoGeneratedStruct';
  };

  const toSnakeCase = (str: string) => {
    let result = str
      .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
      .replace(/[^a-zA-Z0-9]/g, '_')
      .replace(/_+/g, '_')
      .toLowerCase();

    if (/^[0-9]/.test(result)) {
      result = 'f_' + result;
    }
    return result;
  };

  const toCamelCase = (str: string) => {
    const pascal = toPascalCase(str);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  };

  const formatFieldName = (fieldName: string): { rustKey: string; originalName: string } => {
    let formattedKey = fieldName;
    if (casing === 'snake_case') {
      formattedKey = toSnakeCase(fieldName);
    } else if (casing === 'camelCase') {
      formattedKey = toCamelCase(fieldName);
    } else if (casing === 'PascalCase') {
      formattedKey = toPascalCase(fieldName);
    }

    let rustKey = formattedKey;
    if (/^[0-9]/.test(rustKey)) {
      rustKey = 'f_' + rustKey;
    }

    if (RUST_KEYWORDS.has(rustKey)) {
      rustKey = 'r#' + rustKey;
    }

    return { rustKey, originalName: fieldName };
  };

  const mapSqlTypeToRust = (sqlType: string): string => {
    if (!sqlType) return 'String';
    const type = sqlType.toUpperCase();

    if (type.includes('UUID') && useUuid) {
      return 'Uuid';
    }
    if (type.includes('BIGINT') || type.includes('BIGSERIAL')) {
      return 'i64';
    }
    if (type.includes('INT') || type.includes('SERIAL')) {
      return 'i32';
    }
    if (type.includes('SMALLINT')) {
      return 'i16';
    }
    if (type.includes('TINYINT') || type.includes('BOOL') || type.includes('BIT')) {
      return 'bool';
    }
    if (type.includes('DECIMAL') || type.includes('NUMERIC')) {
      return useDecimal ? 'Decimal' : 'f64';
    }
    if (type.includes('FLOAT') || type.includes('DOUBLE') || type.includes('REAL')) {
      return 'f64';
    }
    if (type.includes('DATE') && !type.includes('TIME')) {
      return useChrono ? 'NaiveDate' : 'String';
    }
    if (type.includes('TIME') || type.includes('TIMESTAMP') || type.includes('DATETIME')) {
      return useChrono ? 'NaiveDateTime' : 'String';
    }
    if (type.includes('JSON') || type.includes('JSONB')) {
      return 'serde_json::Value';
    }

    return 'String';
  };

  const escapeRustString = (str: string) => {
    return str
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r')
      .replace(/\t/g, '\\t');
  };

  const handleConvert = useCallback(() => {
    try {
      if (!input.trim()) {
        setOutput('');
        setError('');
        return;
      }
      if (input.length > MAX_LENGTH) {
        setError(t('error.max_length', { max: MAX_LENGTH.toLocaleString() }));
        return;
      }

      const cleanInput = input
        .replace(/--.*$/gm, '')
        .replace(/\/\*[\s\S]*?\*\//g, '');

      const tableRegex = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:["`]?(\w+)["`]?\.)?["`]?(\w+)["`]?\s*\(([\s\S]*?)\);/gi;
      let match;
      const models: { tableName: string; structName: string; fields: { name: string; rustType: string; isOptional: boolean; originalName: string }[] }[] = [];
      const usedTypes = new Set<string>();

      while ((match = tableRegex.exec(cleanInput)) !== null) {
        const tableName = match[2];
        const columnsContent = match[3];
        const structName = toPascalCase(tableName);

        const columnLines: string[] = [];
        let currentLine = '';
        let inQuotes = false;
        let quoteChar = '';
        let parenDepth = 0;

        for (let i = 0; i < columnsContent.length; i++) {
          const char = columnsContent[i];
          if ((char === '"' || char === '`' || char === "'") && columnsContent[i - 1] !== '\\') {
            if (!inQuotes) {
              inQuotes = true;
              quoteChar = char;
            } else if (char === quoteChar) {
              inQuotes = false;
            }
          }

          if (!inQuotes) {
            if (char === '(') parenDepth++;
            if (char === ')') parenDepth--;
          }

          if (char === ',' && !inQuotes && parenDepth === 0) {
            columnLines.push(currentLine.trim());
            currentLine = '';
          } else {
            currentLine += char;
          }
        }
        if (currentLine.trim()) columnLines.push(currentLine.trim());

        const filteredLines = columnLines.map(line => line.trim()).filter(line => {
          if (!line) return false;
          const upper = line.toUpperCase();
          return !upper.startsWith('PRIMARY KEY') &&
                 !upper.startsWith('CONSTRAINT') &&
                 !upper.startsWith('UNIQUE') &&
                 !upper.startsWith('FOREIGN KEY') &&
                 !upper.startsWith('INDEX') &&
                 !upper.startsWith('KEY');
        });

        const fields = filteredLines.map(line => {
          let rawName = '';
          let sqlType = '';

          if (line.startsWith('"') || line.startsWith('`') || line.startsWith("'")) {
            const quote = line[0];
            let i = 1;
            rawName = '';
            while (i < line.length && (line[i] !== quote || line[i - 1] === '\\')) {
              rawName += line[i];
              i++;
            }
            const remaining = line.substring(i + 1).trim();
            sqlType = remaining.split(/\s+/)[0];
          } else {
            const parts = line.split(/\s+/);
            rawName = parts[0];
            sqlType = parts[1];
          }

          if (!rawName) return null;

          const upperLine = line.toUpperCase();
          const isNullable = (!upperLine.includes('NOT NULL') && !upperLine.includes('PRIMARY KEY')) || upperLine.includes('DEFAULT NULL');
          const rustType = mapSqlTypeToRust(sqlType || 'VARCHAR');

          usedTypes.add(rustType);

          return {
            name: rawName,
            rustType,
            isOptional: isNullable,
            originalName: rawName
          };
        }).filter(Boolean) as { name: string; rustType: string; isOptional: boolean; originalName: string }[];

        models.push({ tableName, structName, fields });
      }

      if (models.length === 0) {
        setError(t('sqltorust.no_tables_found', 'No valid CREATE TABLE statements found.'));
        setOutput('');
        return;
      }

      // Build imports
      const imports: string[] = [];
      if (framework === 'serde' || framework === 'sqlx') {
        imports.push('use serde::{Serialize, Deserialize};');
      }
      if (framework === 'sqlx') {
        imports.push('use sqlx::FromRow;');
      }
      if (framework === 'diesel') {
        imports.push('use diesel::prelude::*;');
      }
      if (usedTypes.has('Uuid')) {
        imports.push('use uuid::Uuid;');
      }
      if (usedTypes.has('NaiveDate') || usedTypes.has('NaiveDateTime')) {
        const chronoItems = [];
        if (usedTypes.has('NaiveDate')) chronoItems.push('NaiveDate');
        if (usedTypes.has('NaiveDateTime')) chronoItems.push('NaiveDateTime');
        imports.push(`use chrono::{${chronoItems.join(', ')}};`);
      }
      if (usedTypes.has('Decimal')) {
        imports.push('use rust_decimal::Decimal;');
      }

      let generatedCode = imports.length > 0 ? imports.join('\n') + '\n\n' : '';

      models.forEach(model => {
        const derives = ['Debug'];
        if (framework === 'serde' || framework === 'sqlx') {
          derives.push('Serialize', 'Deserialize');
        }
        if (framework === 'sqlx') {
          derives.push('FromRow');
        }
        if (framework === 'diesel') {
          derives.push('Queryable', 'Selectable', 'Insertable');
        }
        if (deriveClone) derives.push('Clone');
        if (derivePartialEq) derives.push('PartialEq');
        if (deriveDefault) derives.push('Default');

        if (framework === 'diesel') {
          generatedCode += `#[diesel(table_name = crate::schema::${toSnakeCase(model.tableName)})]\n`;
        }

        generatedCode += `#[derive(${derives.join(', ')})]\n`;
        generatedCode += `pub struct ${model.structName} {\n`;

        model.fields.forEach(field => {
          const { rustKey, originalName } = formatFieldName(field.name);
          const needsRename = rustKey !== originalName || rustKey.startsWith('r#');

          if (framework === 'serde' && needsRename) {
            generatedCode += `    #[serde(rename = "${escapeRustString(originalName)}")]\n`;
          } else if (framework === 'sqlx' && needsRename) {
            generatedCode += `    #[sqlx(rename = "${escapeRustString(originalName)}")]\n`;
          } else if (framework === 'diesel' && needsRename) {
            generatedCode += `    #[diesel(column_name = ${toSnakeCase(originalName)})]\n`;
          }

          const typeStr = field.isOptional ? `Option<${field.rustType}>` : field.rustType;
          generatedCode += `    pub ${rustKey}: ${typeStr},\n`;
        });

        generatedCode += '}\n\n';
      });

      setOutput(generatedCode.trim());
      setError('');
    } catch (e: any) {
      setError(t('sqltorust.error_parsing', 'Error parsing SQL DDL') + ': ' + e.message);
      setOutput('');
    }
  }, [input, casing, framework, deriveClone, derivePartialEq, deriveDefault, useDecimal, useChrono, useUuid, t]);

  useEffect(() => {
    handleConvert();
  }, [handleConvert]);

  const handleCopy = useCallback(() => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    toast.success(t('common.copied', 'Copied to clipboard!'));
    setTimeout(() => setCopied(false), 2000);
  }, [output, t]);

  const handleClear = useCallback(() => {
    setInput('');
    setOutput('');
    setError('');
    toast.success(t('common.cleared', 'Cleared!'));
    setTimeout(() => inputRef.current?.focus(), 0);
  }, [t]);

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/x-rust' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'models.rs';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(t('common.downloaded', 'Downloaded models.rs!'));
  };

  const loadPreset = (presetKey: keyof typeof PRESETS) => {
    setInput(PRESETS[presetKey]);
    toast.success(t('sqltorust.preset_loaded', 'Loaded SQL preset!'));
  };

  const handlersRef = useRef({ handleClear, handleCopy, output });
  useEffect(() => {
    handlersRef.current = { handleClear, handleCopy, output };
  }, [handleClear, handleCopy, output]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const activeElement = document.activeElement;
      const isEditable =
        activeElement instanceof HTMLInputElement ||
        activeElement instanceof HTMLTextAreaElement ||
        activeElement instanceof HTMLSelectElement ||
        activeElement?.getAttribute("contenteditable") === "true";

      if (isEditable && e.key !== 'Escape') return;

      if (e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;

      if (e.key === "Escape") {
        e.preventDefault();
        handlersRef.current.handleClear();
      } else if (e.key.toLowerCase() === "c") {
        if (handlersRef.current.output) {
          e.preventDefault();
          handlersRef.current.handleCopy();
        }
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, []);

  return (
    <div className="max-w-6xl mx-auto space-y-8 animate-in fade-in duration-500">
      {/* Presets Bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 p-4 bg-slate-50 dark:bg-slate-900/50 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-amber-500" aria-hidden="true" />
          <span className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltorust.presets_title', 'Clickable Presets')}
          </span>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={() => loadPreset('ecommerce')}
            className="px-3 py-1.5 text-xs font-bold bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
          >
            {t('sqltorust.preset_ecommerce', 'E-Commerce Catalog')}
          </button>
          <button
            onClick={() => loadPreset('user_auth')}
            className="px-3 py-1.5 text-xs font-bold bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
          >
            {t('sqltorust.preset_user_auth', 'User Auth & Roles')}
          </button>
        </div>
      </div>

      {/* Options Panel */}
      <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-4 p-5 bg-white dark:bg-slate-900/60 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="space-y-1.5">
          <label htmlFor="rust-framework" className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltorust.framework_label', 'Framework / Derives')}
          </label>
          <select
            id="rust-framework"
            value={framework}
            onChange={(e) => setFramework(e.target.value as any)}
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="serde">serde (Serialize, Deserialize)</option>
            <option value="sqlx">sqlx (FromRow, serde)</option>
            <option value="diesel">diesel (Queryable, Insertable)</option>
            <option value="none">Standard Rust (None)</option>
          </select>
        </div>

        <div className="space-y-1.5">
          <label htmlFor="rust-casing" className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltorust.casing_label', 'Field Casing')}
          </label>
          <select
            id="rust-casing"
            value={casing}
            onChange={(e) => setCasing(e.target.value as any)}
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="snake_case">snake_case (Rust standard)</option>
            <option value="camelCase">camelCase</option>
            <option value="PascalCase">PascalCase</option>
            <option value="original">original (unchanged)</option>
          </select>
        </div>

        <div className="flex flex-col justify-center space-y-2 pt-2">
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={deriveClone}
              onChange={(e) => setDeriveClone(e.target.checked)}
              className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
            />
            <span className="text-xs font-bold text-slate-700 dark:text-slate-300">
              Derive Clone
            </span>
          </label>
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={derivePartialEq}
              onChange={(e) => setDerivePartialEq(e.target.checked)}
              className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
            />
            <span className="text-xs font-bold text-slate-700 dark:text-slate-300">
              Derive PartialEq
            </span>
          </label>
        </div>

        <div className="flex flex-col justify-center space-y-2 pt-2">
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={useChrono}
              onChange={(e) => setUseChrono(e.target.checked)}
              className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
            />
            <span className="text-xs font-bold text-slate-700 dark:text-slate-300">
              Use chrono (NaiveDate / NaiveDateTime)
            </span>
          </label>
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={useUuid}
              onChange={(e) => setUseUuid(e.target.checked)}
              className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
            />
            <span className="text-xs font-bold text-slate-700 dark:text-slate-300">
              Use uuid::Uuid
            </span>
          </label>
        </div>
      </div>

      {/* Editor Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <Database className="w-4 h-4 text-indigo-500" aria-hidden="true" />
              <label htmlFor="sql-rust-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('sqltorust.sql_input_label', 'SQL CREATE TABLE DDL')}
              </label>
            </div>
            <div className="flex items-center gap-2">
              <Kbd modifier={null} className="hidden sm:inline-flex border-rose-200 dark:border-rose-800 text-rose-400 dark:bg-slate-900">Esc</Kbd>
              <button
                onClick={handleClear}
                disabled={!input && !output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 dark:hover:bg-rose-500/20 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-rose-500 focus-visible:outline-none"
              >
                <Trash2 className="w-3 h-3" aria-hidden="true" /> {t('common.clear')}
              </button>
            </div>
          </div>
          <textarea
            id="sql-rust-input"
            ref={inputRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder={t('sqltorust.placeholder_sql', 'Paste SQL CREATE TABLE DDL statements here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none"
          />
        </div>

        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-emerald-500" aria-hidden="true" />
              <label htmlFor="rust-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('sqltorust.output_label', 'Rust Struct Definitions')}
              </label>
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                disabled={!output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-indigo-500 bg-indigo-50 dark:bg-indigo-500/10 hover:bg-indigo-100 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
              >
                <Download className="w-3 h-3" aria-hidden="true" /> {t('common.download')}
              </button>
              <button
                onClick={handleCopy}
                disabled={!output}
                className={`text-xs font-bold px-3 py-1.5 rounded-xl transition-all flex items-center gap-1 border focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-500/20'
                    : 'text-slate-500 bg-slate-100 dark:bg-slate-800 border-transparent hover:bg-slate-200 dark:hover:bg-slate-700 disabled:opacity-50 disabled:cursor-not-allowed'
                }`}
              >
                {copied ? <Check className="w-3 h-3" aria-hidden="true" /> : <Copy className="w-3 h-3" aria-hidden="true" />} {copied ? t('common.copied') : t('common.copy')}
                {!copied && input && <Kbd modifier={null} className="hidden sm:inline-flex w-4 h-4 bg-white/50 dark:bg-black/20 ml-1">C</Kbd>}
              </button>
            </div>
          </div>
          <textarea
            id="rust-output"
            value={output}
            readOnly
            placeholder={t('sqltorust.placeholder_output', 'Rust struct code will appear here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400 resize-none"
          />
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold animate-in fade-in slide-in-from-top-2">
          <AlertCircle className="w-5 h-5" aria-hidden="true" />
          {error}
        </div>
      )}

      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <Info className="w-6 h-6 text-indigo-500 mt-1" aria-hidden="true" />
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">{t('sqltorust.about_title', 'About SQL to Rust Converter')}</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            {t('sqltorust.about_text', 'Convert SQL CREATE TABLE DDL queries into strongly-typed Rust struct models. Supports serde, sqlx, and diesel attributes, Option<T> nullability, chrono date/time types, uuid::Uuid, and raw Rust keyword escaping.')}
          </p>
        </div>
      </div>
    </div>
  );
}
