import { useState, useEffect, useCallback, useRef } from 'react';
import { FileCode, Copy, Check, Trash2, AlertCircle, Download, Info, Database, Sparkles } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;

export function SQLToTypeScript({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const [input, setInput] = useState(initialData?.input || '');
  const [output, setOutput] = useState(initialData?.output || '');
  const [outputMode, setOutputMode] = useState<'interface' | 'type' | 'zod'>(initialData?.outputMode || 'interface');
  const [casing, setCasing] = useState<'original' | 'camelCase' | 'snake_case'>(initialData?.casing || 'camelCase');
  const [useReadonly, setUseReadonly] = useState(initialData?.useReadonly || false);
  const [interfacePrefix, setInterfacePrefix] = useState(initialData?.interfacePrefix || '');
  const [useNullType, setUseNullType] = useState(initialData?.useNullType || false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    onStateChange?.({ input, output, outputMode, casing, useReadonly, interfacePrefix, useNullType });
  }, [input, output, outputMode, casing, useReadonly, interfacePrefix, useNullType, onStateChange]);

  const PRESETS = {
    ecommerce: `-- E-Commerce Catalog Schema
CREATE TABLE categories (
  id INT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) UNIQUE NOT NULL,
  parent_id INT DEFAULT NULL
);

CREATE TABLE products (
  id INT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  sku VARCHAR(50) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  category_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  metadata JSON
);`,
    user_auth: `-- User Authentication & Roles Schema
CREATE TABLE users (
  user_id UUID PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(100),
  is_verified BOOLEAN DEFAULT FALSE,
  login_count INT DEFAULT 0,
  last_login TIMESTAMP,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE roles (
  role_id INT PRIMARY KEY,
  role_name VARCHAR(50) NOT NULL,
  permissions JSON
);`
  };

  const toPascalCase = (str: string) => {
    return str
      .replace(/[^a-zA-Z0-9]/g, ' ')
      .split(' ')
      .filter(Boolean)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('') || 'AutoGenerated';
  };

  const toCamelCase = (str: string) => {
    const pascal = toPascalCase(str);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  };

  const toSnakeCase = (str: string) => {
    return str
      .replace(/([a-z])([A-Z])/g, '$1_$2')
      .replace(/[^a-zA-Z0-9]/g, '_')
      .replace(/_+/g, '_')
      .toLowerCase();
  };

  const formatPropertyName = (name: string) => {
    let formatted = name;
    if (casing === 'camelCase') {
      formatted = toCamelCase(name);
    } else if (casing === 'snake_case') {
      formatted = toSnakeCase(name);
    }

    const isValidIdent = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(formatted);
    return isValidIdent ? formatted : `"${formatted.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
  };

  const getSafeInterfaceName = (name: string) => {
    let pascal = toPascalCase(name);
    const reserved = new Set([
      'constructor', 'prototype', '__proto__', 'string', 'number',
      'boolean', 'any', 'unknown', 'never', 'void', 'null', 'undefined',
      'object', 'symbol', 'bigint', 'interface', 'class', 'type', 'export', 'default'
    ]);
    if (reserved.has(pascal.toLowerCase())) {
      pascal = 'I' + pascal;
    }
    return (interfacePrefix ? interfacePrefix.trim() : '') + pascal;
  };

  const mapSqlTypeToTs = (sqlType: string): string => {
    if (!sqlType) return 'any';
    const type = sqlType.toUpperCase();
    if (type.includes('INT') || type.includes('DECIMAL') || type.includes('NUMERIC') || type.includes('FLOAT') || type.includes('DOUBLE') || type.includes('REAL') || type.includes('SERIAL')) {
      return 'number';
    }
    if (type.includes('CHAR') || type.includes('TEXT') || type.includes('UUID') || type.includes('BINARY') || type.includes('VARBINARY') || type.includes('ENUM') || type.includes('VARCHAR')) {
      return 'string';
    }
    if (type.includes('BOOL') || type.includes('BIT')) {
      return 'boolean';
    }
    if (type.includes('DATE') || type.includes('TIME') || type.includes('TIMESTAMP') || type.includes('DATETIME')) {
      return 'Date | string';
    }
    if (type.includes('JSON') || type.includes('JSONB')) {
      return 'Record<string, any>';
    }
    return 'any';
  };

  const mapSqlTypeToZod = (sqlType: string, isNullable: boolean): string => {
    if (!sqlType) return 'z.any()';
    const type = sqlType.toUpperCase();
    let zodType = 'z.any()';

    if (type.includes('INT') || type.includes('DECIMAL') || type.includes('NUMERIC') || type.includes('FLOAT') || type.includes('DOUBLE') || type.includes('REAL') || type.includes('SERIAL')) {
      zodType = 'z.number()';
    } else if (type.includes('UUID')) {
      zodType = 'z.string().uuid()';
    } else if (type.includes('CHAR') || type.includes('TEXT') || type.includes('VARCHAR') || type.includes('ENUM')) {
      zodType = 'z.string()';
    } else if (type.includes('BOOL') || type.includes('BIT')) {
      zodType = 'z.boolean()';
    } else if (type.includes('DATE') || type.includes('TIME') || type.includes('TIMESTAMP') || type.includes('DATETIME')) {
      zodType = 'z.date().or(z.string())';
    } else if (type.includes('JSON') || type.includes('JSONB')) {
      zodType = 'z.record(z.any())';
    }

    if (isNullable) {
      zodType += '.nullable().optional()';
    }

    return zodType;
  };

  const handleConvert = useCallback(() => {
    try {
      if (!input.trim()) {
        setOutput('');
        setError('');
        return;
      }
      if (input.length > MAX_LENGTH) {
        setError(t('error.max_length', { max: MAX_LENGTH.toLocaleString() }));
        return;
      }

      // Strip comments
      const cleanInput = input
        .replace(/--.*$/gm, '')
        .replace(/\/\*[\s\S]*?\*\//g, '');

      const tableRegex = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:["`]?(\w+)["`]?\.)?["`]?(\w+)["`]?\s*\(([\s\S]*?)\);/gi;
      let match;
      const outputs: string[] = [];

      while ((match = tableRegex.exec(cleanInput)) !== null) {
        const tableName = match[2];
        const columnsContent = match[3];
        const name = getSafeInterfaceName(tableName);

        const columnLines: string[] = [];
        let currentLine = '';
        let inQuotes = false;
        let quoteChar = '';
        let parenDepth = 0;

        for (let i = 0; i < columnsContent.length; i++) {
          const char = columnsContent[i];
          if ((char === '"' || char === '`' || char === "'") && columnsContent[i - 1] !== '\\') {
            if (!inQuotes) {
              inQuotes = true;
              quoteChar = char;
            } else if (char === quoteChar) {
              inQuotes = false;
            }
          }

          if (!inQuotes) {
            if (char === '(') parenDepth++;
            if (char === ')') parenDepth--;
          }

          if (char === ',' && !inQuotes && parenDepth === 0) {
            columnLines.push(currentLine.trim());
            currentLine = '';
          } else {
            currentLine += char;
          }
        }
        if (currentLine.trim()) columnLines.push(currentLine.trim());

        const filteredLines = columnLines.map(line => line.trim()).filter(line => {
          if (!line) return false;
          const upper = line.toUpperCase();
          return !upper.startsWith('PRIMARY KEY') &&
                 !upper.startsWith('CONSTRAINT') &&
                 !upper.startsWith('UNIQUE') &&
                 !upper.startsWith('FOREIGN KEY') &&
                 !upper.startsWith('INDEX') &&
                 !upper.startsWith('KEY');
        });

        if (outputMode === 'zod') {
          const fields = filteredLines.map(line => {
            let rawName = '';
            let type = '';

            if (line.startsWith('"') || line.startsWith('`') || line.startsWith("'")) {
              const quote = line[0];
              let i = 1;
              rawName = '';
              while (i < line.length && (line[i] !== quote || line[i - 1] === '\\')) {
                rawName += line[i];
                i++;
              }
              const remaining = line.substring(i + 1).trim();
              type = remaining.split(/\s+/)[0];
            } else {
              const parts = line.split(/\s+/);
              rawName = parts[0];
              type = parts[1];
            }
            if (!rawName) return null;

            const upperLine = line.toUpperCase();
            const isNullable = (!upperLine.includes('NOT NULL') && !upperLine.includes('PRIMARY KEY')) || upperLine.includes('DEFAULT NULL');
            const formattedProp = formatPropertyName(rawName);
            const zodTypeDef = mapSqlTypeToZod(type || 'TEXT', isNullable);

            return `  ${formattedProp}: ${zodTypeDef},`;
          }).filter(Boolean);

          const zodSchemaName = toCamelCase(tableName) + 'Schema';
          const typeInferName = getSafeInterfaceName(tableName);

          outputs.push(`export const ${zodSchemaName} = z.object({\n${fields.join('\n')}\n});\n\nexport type ${typeInferName} = z.infer<typeof ${zodSchemaName}>;`);

        } else if (outputMode === 'type') {
          const fields = filteredLines.map(line => {
            let rawName = '';
            let type = '';

            if (line.startsWith('"') || line.startsWith('`') || line.startsWith("'")) {
              const quote = line[0];
              let i = 1;
              rawName = '';
              while (i < line.length && (line[i] !== quote || line[i - 1] === '\\')) {
                rawName += line[i];
                i++;
              }
              const remaining = line.substring(i + 1).trim();
              type = remaining.split(/\s+/)[0];
            } else {
              const parts = line.split(/\s+/);
              rawName = parts[0];
              type = parts[1];
            }
            if (!rawName) return null;

            const upperLine = line.toUpperCase();
            const isNullable = (!upperLine.includes('NOT NULL') && !upperLine.includes('PRIMARY KEY')) || upperLine.includes('DEFAULT NULL');
            const formattedProp = formatPropertyName(rawName);
            const tsType = mapSqlTypeToTs(type || 'any');

            const roPrefix = useReadonly ? 'readonly ' : '';
            const optionalMark = isNullable && !useNullType ? '?' : '';
            const nullSuffix = isNullable && useNullType ? ' | null' : '';

            return `  ${roPrefix}${formattedProp}${optionalMark}: ${tsType}${nullSuffix};`;
          }).filter(Boolean);

          outputs.push(`export type ${name} = {\n${fields.join('\n')}\n};`);

        } else {
          // Default: interface
          const fields = filteredLines.map(line => {
            let rawName = '';
            let type = '';

            if (line.startsWith('"') || line.startsWith('`') || line.startsWith("'")) {
              const quote = line[0];
              let i = 1;
              rawName = '';
              while (i < line.length && (line[i] !== quote || line[i - 1] === '\\')) {
                rawName += line[i];
                i++;
              }
              const remaining = line.substring(i + 1).trim();
              type = remaining.split(/\s+/)[0];
            } else {
              const parts = line.split(/\s+/);
              rawName = parts[0];
              type = parts[1];
            }
            if (!rawName) return null;

            const upperLine = line.toUpperCase();
            const isNullable = (!upperLine.includes('NOT NULL') && !upperLine.includes('PRIMARY KEY')) || upperLine.includes('DEFAULT NULL');
            const formattedProp = formatPropertyName(rawName);
            const tsType = mapSqlTypeToTs(type || 'any');

            const roPrefix = useReadonly ? 'readonly ' : '';
            const optionalMark = isNullable && !useNullType ? '?' : '';
            const nullSuffix = isNullable && useNullType ? ' | null' : '';

            return `  ${roPrefix}${formattedProp}${optionalMark}: ${tsType}${nullSuffix};`;
          }).filter(Boolean);

          outputs.push(`export interface ${name} {\n${fields.join('\n')}\n}`);
        }
      }

      if (outputs.length === 0) {
        setError(t('sqltots.no_tables_found', 'No valid CREATE TABLE statements found.'));
        setOutput('');
      } else {
        const header = outputMode === 'zod' ? 'import { z } from "zod";\n\n' : '';
        setOutput(header + outputs.join('\n\n'));
        setError('');
      }
    } catch (e: any) {
      setError(t('sqltots.error_parsing', 'Error parsing SQL') + ': ' + e.message);
      setOutput('');
    }
  }, [input, outputMode, casing, useReadonly, interfacePrefix, useNullType, t]);

  useEffect(() => {
    handleConvert();
  }, [handleConvert]);

  const handleCopy = useCallback(() => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    toast.success(t('common.copied', 'Copied to clipboard!'));
    setTimeout(() => setCopied(false), 2000);
  }, [output, t]);

  const handleClear = useCallback(() => {
    setInput('');
    setOutput('');
    setError('');
    toast.success(t('common.cleared', 'Cleared!'));
    setTimeout(() => inputRef.current?.focus(), 0);
  }, [t]);

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/typescript' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = outputMode === 'zod' ? 'schemas.ts' : 'models.ts';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(t('common.downloaded', 'Downloaded models.ts!'));
  };

  const loadPreset = (presetKey: keyof typeof PRESETS) => {
    setInput(PRESETS[presetKey]);
    toast.success(t('sqltots.preset_loaded', 'Loaded SQL preset!'));
  };

  const handlersRef = useRef({ handleClear, handleCopy, output });
  useEffect(() => {
    handlersRef.current = { handleClear, handleCopy, output };
  }, [handleClear, handleCopy, output]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const activeElement = document.activeElement;
      const isEditable =
        activeElement instanceof HTMLInputElement ||
        activeElement instanceof HTMLTextAreaElement ||
        activeElement instanceof HTMLSelectElement ||
        activeElement?.getAttribute("contenteditable") === "true";

      if (isEditable && e.key !== 'Escape') return;

      if (e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;

      if (e.key === "Escape") {
        e.preventDefault();
        handlersRef.current.handleClear();
      } else if (e.key.toLowerCase() === "c") {
        if (handlersRef.current.output) {
          e.preventDefault();
          handlersRef.current.handleCopy();
        }
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, []);

  return (
    <div className="max-w-6xl mx-auto space-y-8 animate-in fade-in duration-500">
      {/* Presets Bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 p-4 bg-slate-50 dark:bg-slate-900/50 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-amber-500" aria-hidden="true" />
          <span className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltots.presets_title', 'Clickable Presets')}
          </span>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={() => loadPreset('ecommerce')}
            className="px-3 py-1.5 text-xs font-bold bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
          >
            {t('sqltots.preset_ecommerce', 'E-Commerce Catalog')}
          </button>
          <button
            onClick={() => loadPreset('user_auth')}
            className="px-3 py-1.5 text-xs font-bold bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
          >
            {t('sqltots.preset_user_auth', 'User Auth & Roles')}
          </button>
        </div>
      </div>

      {/* Options Controls */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4 p-5 bg-white dark:bg-slate-900/60 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="space-y-1.5">
          <label htmlFor="output-mode" className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltots.output_mode', 'Output Format')}
          </label>
          <select
            id="output-mode"
            value={outputMode}
            onChange={(e) => setOutputMode(e.target.value as any)}
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="interface">TypeScript Interface</option>
            <option value="type">TypeScript Type Alias</option>
            <option value="zod">Zod Schema (z.object)</option>
          </select>
        </div>

        <div className="space-y-1.5">
          <label htmlFor="casing-strategy" className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltots.casing_strategy', 'Property Casing')}
          </label>
          <select
            id="casing-strategy"
            value={casing}
            onChange={(e) => setCasing(e.target.value as any)}
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="camelCase">camelCase</option>
            <option value="snake_case">snake_case</option>
            <option value="original">Original Column Name</option>
          </select>
        </div>

        <div className="space-y-1.5">
          <label htmlFor="interface-prefix" className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltots.interface_prefix', 'Name Prefix')}
          </label>
          <input
            id="interface-prefix"
            type="text"
            value={interfacePrefix}
            onChange={(e) => setInterfacePrefix(e.target.value)}
            placeholder="e.g. I or Model"
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500"
          />
        </div>

        <div className="flex flex-col gap-2 pt-1">
          <div className="flex items-center gap-2">
            <input
              id="use-readonly"
              type="checkbox"
              checked={useReadonly}
              onChange={(e) => setUseReadonly(e.target.checked)}
              disabled={outputMode === 'zod'}
              className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
            />
            <label htmlFor="use-readonly" className="text-xs font-bold text-slate-700 dark:text-slate-300 cursor-pointer">
              {t('sqltots.use_readonly', 'Add readonly modifier')}
            </label>
          </div>

          <div className="flex items-center gap-2">
            <input
              id="use-null-type"
              type="checkbox"
              checked={useNullType}
              onChange={(e) => setUseNullType(e.target.checked)}
              disabled={outputMode === 'zod'}
              className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
            />
            <label htmlFor="use-null-type" className="text-xs font-bold text-slate-700 dark:text-slate-300 cursor-pointer">
              {t('sqltots.use_null_type', 'Use "| null" instead of "?"')}
            </label>
          </div>
        </div>
      </div>

      {/* Editor Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <Database className="w-4 h-4 text-indigo-500" aria-hidden="true" />
              <label htmlFor="sql-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('sqltots.sql_input_label', 'SQL CREATE TABLE DDL')}
              </label>
            </div>
            <div className="flex items-center gap-2">
              <Kbd modifier={null} className="hidden sm:inline-flex border-rose-200 dark:border-rose-800 text-rose-400 dark:bg-slate-900">Esc</Kbd>
              <button
                onClick={handleClear}
                disabled={!input && !output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 dark:hover:bg-rose-500/20 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-rose-500 focus-visible:outline-none"
              >
                <Trash2 className="w-3 h-3" aria-hidden="true" /> {t('common.clear')}
              </button>
            </div>
          </div>
          <textarea
            id="sql-input"
            ref={inputRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder={t('sqltots.placeholder_sql', 'Paste SQL CREATE TABLE DDL statements here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none"
          />
        </div>

        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-emerald-500" aria-hidden="true" />
              <label htmlFor="ts-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {outputMode === 'zod' ? t('sqltots.zod_schemas', 'Zod Schemas') : t('sqltots.ts_interfaces', 'TypeScript Definitions')}
              </label>
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                disabled={!output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-indigo-500 bg-indigo-50 dark:bg-indigo-500/10 hover:bg-indigo-100 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
              >
                <Download className="w-3 h-3" aria-hidden="true" /> {t('common.download')}
              </button>
              <button
                onClick={handleCopy}
                disabled={!output}
                className={`text-xs font-bold px-3 py-1.5 rounded-xl transition-all flex items-center gap-1 border focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-500/20'
                    : 'text-slate-500 bg-slate-100 dark:bg-slate-800 border-transparent hover:bg-slate-200 dark:hover:bg-slate-700 disabled:opacity-50 disabled:cursor-not-allowed'
                }`}
              >
                {copied ? <Check className="w-3 h-3" aria-hidden="true" /> : <Copy className="w-3 h-3" aria-hidden="true" />} {copied ? t('common.copied') : t('common.copy')}
                {!copied && input && <Kbd modifier={null} className="hidden sm:inline-flex w-4 h-4 bg-white/50 dark:bg-black/20 ml-1">C</Kbd>}
              </button>
            </div>
          </div>
          <textarea
            id="ts-output"
            value={output}
            readOnly
            placeholder={t('sqltots.placeholder_ts', 'Generated TypeScript code will appear here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400 resize-none"
          />
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold animate-in fade-in slide-in-from-top-2">
          <AlertCircle className="w-5 h-5" aria-hidden="true" />
          {error}
        </div>
      )}

      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <Info className="w-6 h-6 text-indigo-500 mt-1" aria-hidden="true" />
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">{t('sqltots.about_title', 'About SQL to TypeScript / Zod Converter')}</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            {t('sqltots.about_text', 'Convert SQL CREATE TABLE statements into TypeScript interfaces, type aliases, or runtime Zod validation schemas. Supports property casing transformations (camelCase, snake_case), nullable handling, readonly fields, and custom prefixes.')}
          </p>
        </div>
      </div>
    </div>
  );
}
