import { useState, useEffect, useCallback, useRef } from 'react';
import { FileCode, Copy, Check, Trash2, AlertCircle, Download, Info, Database, Sparkles } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Kbd } from './ui/Kbd';

const MAX_LENGTH = 100000;

export function SQLToJava({ initialData, onStateChange }: { initialData?: any; onStateChange?: (state: any) => void }) {
  const { t } = useTranslation();
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const [input, setInput] = useState(initialData?.input || '');
  const [output, setOutput] = useState(initialData?.output || '');
  const [typeMode, setTypeMode] = useState<'class' | 'record'>(initialData?.typeMode || 'class');
  const [casing, setCasing] = useState<'camelCase' | 'snake_case' | 'PascalCase' | 'original'>(initialData?.casing || 'camelCase');
  const [jsonAttribute, setJsonAttribute] = useState<'none' | 'jackson' | 'gson'>(initialData?.jsonAttribute || 'jackson');
  const [useJpa, setUseJpa] = useState(initialData?.useJpa ?? true);
  const [useLombok, setUseLombok] = useState(initialData?.useLombok ?? true);
  const [useNullable, setUseNullable] = useState(initialData?.useNullable ?? true);
  const [packageName, setPackageName] = useState(initialData?.packageName || '');
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    onStateChange?.({
      input,
      output,
      typeMode,
      casing,
      jsonAttribute,
      useJpa,
      useLombok,
      useNullable,
      packageName,
    });
  }, [input, output, typeMode, casing, jsonAttribute, useJpa, useLombok, useNullable, packageName, onStateChange]);

  const PRESETS = {
    ecommerce: `-- E-Commerce Catalog Schema
CREATE TABLE categories (
  category_id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) UNIQUE NOT NULL,
  description TEXT,
  parent_id INT DEFAULT NULL
);

CREATE TABLE products (
  product_id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  sku VARCHAR(50) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  category_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  metadata JSON
);`,
    user_auth: `-- User Authentication & Roles Schema
CREATE TABLE users (
  user_id UUID PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(100),
  is_verified BOOLEAN DEFAULT FALSE,
  login_count INT DEFAULT 0,
  last_login TIMESTAMP,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE roles (
  role_id INT PRIMARY KEY,
  role_name VARCHAR(50) NOT NULL,
  permissions JSON
);`,
    financial: `-- Financial Audit Log Schema
CREATE TABLE audit_logs (
  log_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  account_number VARCHAR(34) NOT NULL,
  amount DECIMAL(15, 4) NOT NULL,
  currency VARCHAR(3) NOT NULL,
  transaction_type VARCHAR(20) NOT NULL,
  is_flagged BOOLEAN DEFAULT FALSE,
  executed_at DATETIME NOT NULL,
  details JSON
);`
  };

  const JAVA_KEYWORDS = new Set([
    'abstract', 'assert', 'boolean', 'break', 'byte', 'case', 'catch', 'char', 'class',
    'const', 'continue', 'default', 'do', 'double', 'else', 'enum', 'extends', 'final',
    'finally', 'float', 'for', 'goto', 'if', 'implements', 'import', 'instanceof', 'int',
    'interface', 'long', 'native', 'new', 'package', 'private', 'protected', 'public',
    'return', 'short', 'static', 'strictfp', 'super', 'switch', 'synchronized', 'this',
    'throw', 'throws', 'transient', 'try', 'void', 'volatile', 'while', 'true', 'false',
    'null', 'record', 'var', 'yield', 'sealed', 'non-sealed', 'permits'
  ]);

  const escapeJavaString = (str: string) => {
    return str
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r')
      .replace(/\t/g, '\\t');
  };

  const toPascalCase = (str: string) => {
    const pascal = str
      .replace(/[^a-zA-Z0-9]/g, ' ')
      .split(' ')
      .filter(Boolean)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');
    if (!pascal) return 'AutoGeneratedClass';
    return /^[0-9]/.test(pascal) ? `Model${pascal}` : pascal;
  };

  const toCamelCase = (str: string) => {
    const pascal = toPascalCase(str);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  };

  const toSnakeCase = (str: string) => {
    return str
      .replace(/([a-z])([A-Z])/g, '$1_$2')
      .replace(/[^a-zA-Z0-9]/g, '_')
      .replace(/_+/g, '_')
      .toLowerCase();
  };

  const formatPropertyName = (name: string) => {
    let formatted = name;
    if (casing === 'camelCase') {
      formatted = toCamelCase(name);
    } else if (casing === 'PascalCase') {
      formatted = toPascalCase(name);
    } else if (casing === 'snake_case') {
      formatted = toSnakeCase(name);
    }

    if (JAVA_KEYWORDS.has(formatted.toLowerCase()) || /^[0-9]/.test(formatted)) {
      formatted = `_${formatted}`;
    }

    return formatted;
  };

  const getSafeClassName = (tableName: string) => {
    let name = toPascalCase(tableName);
    if (JAVA_KEYWORDS.has(name.toLowerCase())) {
      name = `${name}Entity`;
    }
    return name;
  };

  const mapSqlTypeToJava = (sqlType: string, isNullable: boolean): string => {
    if (!sqlType) return 'String';
    const type = sqlType.toUpperCase();

    if (type.includes('BIGINT')) return useNullable ? 'Long' : 'long';
    if (type.includes('TINYINT(1)') || type.includes('BOOLEAN') || type.includes('BOOL') || type.includes('BIT')) {
      return useNullable ? 'Boolean' : 'boolean';
    }
    if (type.includes('SMALLINT')) return useNullable ? 'Short' : 'short';
    if (type.includes('INT') || type.includes('SERIAL')) return useNullable ? 'Integer' : 'int';
    if (type.includes('DECIMAL') || type.includes('NUMERIC') || type.includes('MONEY')) return 'BigDecimal';
    if (type.includes('FLOAT') || type.includes('REAL')) return useNullable ? 'Float' : 'float';
    if (type.includes('DOUBLE')) return useNullable ? 'Double' : 'double';
    if (type.includes('UUID') || type.includes('UNIQUEIDENTIFIER')) return 'UUID';
    if (type.includes('DATETIME2') || type.includes('TIMESTAMP') || type.includes('DATETIME')) return 'LocalDateTime';
    if (type.includes('DATE')) return 'LocalDate';
    if (type.includes('TIME') && !type.includes('TIMESTAMP') && !type.includes('DATETIME')) return 'LocalTime';
    if (type.includes('BLOB') || type.includes('BYTEA') || type.includes('VARBINARY')) return 'byte[]';

    return 'String';
  };

  const handleConvert = useCallback(() => {
    try {
      if (!input.trim()) {
        setOutput('');
        setError('');
        return;
      }

      if (input.length > MAX_LENGTH) {
        setError(t('error.max_length', { max: MAX_LENGTH.toLocaleString() }));
        return;
      }

      const cleanInput = input
        .replace(/--.*$/gm, '')
        .replace(/\/\*[\s\S]*?\*\//g, '');

      const tableRegex = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:["`]?(\w+)["`]?\.)?["`]?(\w+)["`]?\s*\(([\s\S]*?)\);/gi;
      let match;
      const classBlocks: string[] = [];
      const imports = new Set<string>();

      if (jsonAttribute === 'jackson') {
        imports.add('import com.fasterxml.jackson.annotation.JsonProperty;');
      } else if (jsonAttribute === 'gson') {
        imports.add('import com.google.gson.annotations.SerializedName;');
      }

      if (useJpa) {
        imports.add('import jakarta.persistence.*;');
      }

      if (useLombok && typeMode === 'class') {
        imports.add('import lombok.Data;');
        imports.add('import lombok.NoArgsConstructor;');
        imports.add('import lombok.AllArgsConstructor;');
        imports.add('import lombok.Builder;');
      }

      while ((match = tableRegex.exec(cleanInput)) !== null) {
        const rawTableName = match[2];
        const columnsContent = match[3];
        const className = getSafeClassName(rawTableName);

        const columnLines: string[] = [];
        let currentLine = '';
        let inQuotes = false;
        let quoteChar = '';
        let parenDepth = 0;

        for (let i = 0; i < columnsContent.length; i++) {
          const char = columnsContent[i];
          if ((char === '"' || char === '`' || char === "'") && columnsContent[i - 1] !== '\\') {
            if (!inQuotes) {
              inQuotes = true;
              quoteChar = char;
            } else if (char === quoteChar) {
              inQuotes = false;
            }
          }

          if (!inQuotes) {
            if (char === '(') parenDepth++;
            if (char === ')') parenDepth--;
          }

          if (char === ',' && !inQuotes && parenDepth === 0) {
            columnLines.push(currentLine.trim());
            currentLine = '';
          } else {
            currentLine += char;
          }
        }
        if (currentLine.trim()) columnLines.push(currentLine.trim());

        const filteredLines = columnLines.map(line => line.trim()).filter(line => {
          if (!line) return false;
          const upper = line.toUpperCase();
          return !upper.startsWith('PRIMARY KEY') &&
                 !upper.startsWith('CONSTRAINT') &&
                 !upper.startsWith('UNIQUE') &&
                 !upper.startsWith('FOREIGN KEY') &&
                 !upper.startsWith('INDEX') &&
                 !upper.startsWith('KEY');
        });

        const properties: {
          rawName: string;
          propName: string;
          javaType: string;
          isPrimaryKey: boolean;
          isNullable: boolean;
          attrStr: string;
        }[] = [];

        filteredLines.forEach(line => {
          let rawName = '';
          let sqlType = '';

          if (line.startsWith('"') || line.startsWith('`') || line.startsWith("'")) {
            const quote = line[0];
            let i = 1;
            rawName = '';
            while (i < line.length && (line[i] !== quote || line[i - 1] === '\\')) {
              rawName += line[i];
              i++;
            }
            const remaining = line.substring(i + 1).trim();
            sqlType = remaining.split(/\s+/)[0];
          } else {
            const parts = line.split(/\s+/);
            rawName = parts[0];
            sqlType = parts[1];
          }

          if (!rawName) return;

          const upperLine = line.toUpperCase();
          const isPrimaryKey = upperLine.includes('PRIMARY KEY');
          const isNullable = (!upperLine.includes('NOT NULL') && !isPrimaryKey) || upperLine.includes('DEFAULT NULL');
          const javaType = mapSqlTypeToJava(sqlType || 'VARCHAR', isNullable);

          if (javaType === 'BigDecimal') {
            imports.add('import java.math.BigDecimal;');
          } else if (javaType === 'UUID') {
            imports.add('import java.util.UUID;');
          } else if (javaType === 'LocalDateTime') {
            imports.add('import java.time.LocalDateTime;');
          } else if (javaType === 'LocalDate') {
            imports.add('import java.time.LocalDate;');
          } else if (javaType === 'LocalTime') {
            imports.add('import java.time.LocalTime;');
          }

          const propName = formatPropertyName(rawName);
          const escapedRawName = escapeJavaString(rawName);

          const attributes: string[] = [];

          if (useJpa) {
            if (isPrimaryKey) {
              attributes.push('    @Id');
              if (upperLine.includes('AUTO_INCREMENT') || upperLine.includes('SERIAL') || upperLine.includes('IDENTITY')) {
                attributes.push('    @GeneratedValue(strategy = GenerationType.IDENTITY)');
              }
            }
            attributes.push(`    @Column(name = "${escapedRawName}"${!isNullable ? ', nullable = false' : ''})`);
          }

          if (jsonAttribute === 'jackson') {
            attributes.push(`    @JsonProperty("${escapedRawName}")`);
          } else if (jsonAttribute === 'gson') {
            attributes.push(`    @SerializedName("${escapedRawName}")`);
          }

          const attrStr = attributes.length > 0 ? `${attributes.join('\n')}\n` : '';
          properties.push({
            rawName,
            propName,
            javaType,
            isPrimaryKey,
            isNullable,
            attrStr
          });
        });

        const classAttributes: string[] = [];
        if (useJpa) {
          classAttributes.push('@Entity');
          classAttributes.push(`@Table(name = "${escapeJavaString(rawTableName)}")`);
        }

        if (useLombok && typeMode === 'class') {
          classAttributes.push('@Data');
          classAttributes.push('@NoArgsConstructor');
          classAttributes.push('@AllArgsConstructor');
          classAttributes.push('@Builder');
        }

        const classAttrHeader = classAttributes.length > 0 ? `${classAttributes.join('\n')}\n` : '';

        if (typeMode === 'record') {
          const recordFields = properties
            .map(p => {
              const annos = p.attrStr ? p.attrStr.trim() + ' ' : '';
              return `${annos}${p.javaType} ${p.propName}`;
            })
            .join(',\n    ');

          classBlocks.push(`${classAttrHeader}public record ${className}(\n    ${recordFields}\n) {}`);
        } else {
          const fieldDeclarations = properties
            .map(p => `${p.attrStr}    private ${p.javaType} ${p.propName};`)
            .join('\n\n');

          let methodsCode = '';
          if (!useLombok) {
            // Getters & Setters
            methodsCode = '\n\n' + properties.map(p => {
              const capitalized = p.propName.charAt(0).toUpperCase() + p.propName.slice(1);
              const getter = `    public ${p.javaType} get${capitalized}() {\n        return ${p.propName};\n    }`;
              const setter = `    public void set${capitalized}(${p.javaType} ${p.propName}) {\n        this.${p.propName} = ${p.propName};\n    }`;
              return `${getter}\n\n${setter}`;
            }).join('\n\n');
          }

          classBlocks.push(`${classAttrHeader}public class ${className} {\n${fieldDeclarations}${methodsCode}\n}`);
        }
      }

      if (classBlocks.length === 0) {
        setError(t('sqltojava.no_tables_found', 'No valid CREATE TABLE statements found.'));
        setOutput('');
        return;
      }

      const sortedImports = Array.from(imports).sort().join('\n');
      let fullCode = '';

      if (packageName.trim()) {
        const safePackage = packageName.trim().replace(/[^a-zA-Z0-9_.]/g, '');
        fullCode += `package ${safePackage};\n\n`;
      }

      if (sortedImports) {
        fullCode += `${sortedImports}\n\n`;
      }

      fullCode += classBlocks.join('\n\n');

      setOutput(fullCode);
      setError('');
    } catch (e: any) {
      setError(t('sqltojava.error_parsing', 'Error parsing SQL DDL') + ': ' + e.message);
      setOutput('');
    }
  }, [input, typeMode, casing, jsonAttribute, useJpa, useLombok, useNullable, packageName, t]);

  useEffect(() => {
    handleConvert();
  }, [handleConvert]);

  const handleCopy = useCallback(() => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    toast.success(t('common.copied', 'Copied to clipboard!'));
    setTimeout(() => setCopied(false), 2000);
  }, [output, t]);

  const handleClear = useCallback(() => {
    setInput('');
    setOutput('');
    setError('');
    toast.success(t('common.cleared', 'Cleared!'));
    setTimeout(() => inputRef.current?.focus(), 0);
  }, [t]);

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'Models.java';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(t('common.downloaded', 'Downloaded Models.java!'));
  };

  const loadPreset = (presetKey: keyof typeof PRESETS) => {
    setInput(PRESETS[presetKey]);
    toast.success(t('sqltojava.preset_loaded', 'Loaded SQL preset!'));
  };

  const handlersRef = useRef({ handleClear, handleCopy, output });
  useEffect(() => {
    handlersRef.current = { handleClear, handleCopy, output };
  }, [handleClear, handleCopy, output]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const activeElement = document.activeElement;
      const isEditable =
        activeElement instanceof HTMLInputElement ||
        activeElement instanceof HTMLTextAreaElement ||
        activeElement instanceof HTMLSelectElement ||
        activeElement?.getAttribute('contenteditable') === 'true';

      if (isEditable && e.key !== 'Escape') return;

      if (e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;

      if (e.key === 'Escape') {
        e.preventDefault();
        handlersRef.current.handleClear();
      } else if (e.key.toLowerCase() === 'c') {
        if (handlersRef.current.output) {
          e.preventDefault();
          handlersRef.current.handleCopy();
        }
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  return (
    <div className="max-w-6xl mx-auto space-y-8 animate-in fade-in duration-500">
      {/* Presets Bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 p-4 bg-slate-50 dark:bg-slate-900/50 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-amber-500" aria-hidden="true" />
          <span className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltojava.presets_title', 'Clickable Presets')}
          </span>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={() => loadPreset('ecommerce')}
            className="px-3 py-1.5 text-xs font-bold bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
          >
            {t('sqltojava.preset_ecommerce', 'E-Commerce Catalog')}
          </button>
          <button
            onClick={() => loadPreset('user_auth')}
            className="px-3 py-1.5 text-xs font-bold bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
          >
            {t('sqltojava.preset_user_auth', 'User Auth & Roles')}
          </button>
          <button
            onClick={() => loadPreset('financial')}
            className="px-3 py-1.5 text-xs font-bold bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-500 rounded-xl transition-all shadow-sm focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
          >
            {t('sqltojava.preset_financial', 'Financial Audit Log')}
          </button>
        </div>
      </div>

      {/* Options Panel */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4 p-5 bg-white dark:bg-slate-900/60 rounded-2xl border border-slate-200 dark:border-slate-800">
        <div className="space-y-1.5">
          <label htmlFor="java-type-mode" className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltojava.type_mode', 'Java Structure Type')}
          </label>
          <select
            id="java-type-mode"
            value={typeMode}
            onChange={(e) => setTypeMode(e.target.value as any)}
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="class">Class (public class)</option>
            <option value="record">Record (public record)</option>
          </select>
        </div>

        <div className="space-y-1.5">
          <label htmlFor="java-casing" className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltojava.casing', 'Property Casing')}
          </label>
          <select
            id="java-casing"
            value={casing}
            onChange={(e) => setCasing(e.target.value as any)}
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="camelCase">camelCase (Standard Java)</option>
            <option value="PascalCase">PascalCase</option>
            <option value="snake_case">snake_case</option>
            <option value="original">Original Column Name</option>
          </select>
        </div>

        <div className="space-y-1.5">
          <label htmlFor="java-json-lib" className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltojava.json_lib', 'JSON Annotations')}
          </label>
          <select
            id="java-json-lib"
            value={jsonAttribute}
            onChange={(e) => setJsonAttribute(e.target.value as any)}
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="jackson">Jackson (@JsonProperty)</option>
            <option value="gson">Gson (@SerializedName)</option>
            <option value="none">None</option>
          </select>
        </div>

        <div className="space-y-1.5">
          <label htmlFor="java-package" className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
            {t('sqltojava.package_name', 'Package Name (Optional)')}
          </label>
          <input
            id="java-package"
            type="text"
            value={packageName}
            onChange={(e) => setPackageName(e.target.value)}
            placeholder="e.g. com.example.models"
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold outline-none focus:ring-2 focus:ring-indigo-500"
          />
        </div>

        <div className="col-span-1 md:col-span-4 flex flex-wrap items-center gap-6 pt-2 border-t border-slate-100 dark:border-slate-800">
          <div className="flex items-center gap-2">
            <input
              id="use-jpa"
              type="checkbox"
              checked={useJpa}
              onChange={(e) => setUseJpa(e.target.checked)}
              className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
            />
            <label htmlFor="use-jpa" className="text-xs font-bold text-slate-700 dark:text-slate-300 cursor-pointer">
              {t('sqltojava.use_jpa', 'JPA Annotations (@Entity, @Table, @Id, @Column)')}
            </label>
          </div>

          <div className="flex items-center gap-2">
            <input
              id="use-lombok"
              type="checkbox"
              checked={useLombok}
              disabled={typeMode === 'record'}
              onChange={(e) => setUseLombok(e.target.checked)}
              className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500 disabled:opacity-50"
            />
            <label htmlFor="use-lombok" className={`text-xs font-bold text-slate-700 dark:text-slate-300 cursor-pointer ${typeMode === 'record' ? 'opacity-50' : ''}`}>
              {t('sqltojava.use_lombok', 'Lombok Annotations (@Data, @NoArgsConstructor, @Builder)')}
            </label>
          </div>

          <div className="flex items-center gap-2">
            <input
              id="use-nullable"
              type="checkbox"
              checked={useNullable}
              onChange={(e) => setUseNullable(e.target.checked)}
              className="w-4 h-4 text-indigo-600 rounded border-slate-300 focus:ring-indigo-500"
            />
            <label htmlFor="use-nullable" className="text-xs font-bold text-slate-700 dark:text-slate-300 cursor-pointer">
              {t('sqltojava.use_nullable', 'Use Wrapper Objects (Integer, Long, Boolean) for Nullables')}
            </label>
          </div>
        </div>
      </div>

      {/* Editor Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <Database className="w-4 h-4 text-indigo-500" aria-hidden="true" />
              <label htmlFor="sql-java-input" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('sqltojava.sql_input_label', 'SQL CREATE TABLE DDL')}
              </label>
            </div>
            <div className="flex items-center gap-2">
              <Kbd modifier={null} className="hidden sm:inline-flex border-rose-200 dark:border-rose-800 text-rose-400 dark:bg-slate-900">Esc</Kbd>
              <button
                onClick={handleClear}
                disabled={!input && !output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-rose-500 bg-rose-50 dark:bg-rose-500/10 hover:bg-rose-100 dark:hover:bg-rose-500/20 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-rose-500 focus-visible:outline-none"
              >
                <Trash2 className="w-3 h-3" aria-hidden="true" /> {t('common.clear')}
              </button>
            </div>
          </div>
          <textarea
            id="sql-java-input"
            ref={inputRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder={t('sqltojava.placeholder_sql', 'Paste SQL CREATE TABLE DDL statements here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all font-mono text-sm leading-relaxed dark:text-slate-300 resize-none"
          />
        </div>

        <div className="space-y-4">
          <div className="flex justify-between items-center px-1">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-emerald-500" aria-hidden="true" />
              <label htmlFor="java-output" className="text-xs font-black uppercase tracking-widest text-slate-400 cursor-pointer">
                {t('sqltojava.output_label', 'Generated Java Classes')}
              </label>
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                disabled={!output}
                className="text-xs font-bold px-3 py-1.5 rounded-xl text-indigo-500 bg-indigo-50 dark:bg-indigo-500/10 hover:bg-indigo-100 transition-all flex items-center gap-1 disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none"
              >
                <Download className="w-3 h-3" aria-hidden="true" /> {t('common.download')}
              </button>
              <button
                onClick={handleCopy}
                disabled={!output}
                className={`text-xs font-bold px-3 py-1.5 rounded-xl transition-all flex items-center gap-1 border focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
                  copied
                    ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-500/20'
                    : 'text-slate-500 bg-slate-100 dark:bg-slate-800 border-transparent hover:bg-slate-200 dark:hover:bg-slate-700 disabled:opacity-50 disabled:cursor-not-allowed'
                }`}
              >
                {copied ? <Check className="w-3 h-3" aria-hidden="true" /> : <Copy className="w-3 h-3" aria-hidden="true" />} {copied ? t('common.copied') : t('common.copy')}
                {!copied && input && <Kbd modifier={null} className="hidden sm:inline-flex w-4 h-4 bg-white/50 dark:bg-black/20 ml-1">C</Kbd>}
              </button>
            </div>
          </div>
          <textarea
            id="java-output"
            value={output}
            readOnly
            placeholder={t('sqltojava.placeholder_output', 'Generated Java code will appear here...')}
            className="w-full h-[450px] p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl outline-none font-mono text-sm leading-relaxed text-indigo-600 dark:text-indigo-400 resize-none"
          />
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-800 p-4 rounded-2xl flex items-center gap-3 text-rose-600 dark:text-rose-400 font-bold animate-in fade-in slide-in-from-top-2">
          <AlertCircle className="w-5 h-5" aria-hidden="true" />
          {error}
        </div>
      )}

      <div className="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/20 flex items-start gap-4">
        <Info className="w-6 h-6 text-indigo-500 mt-1" aria-hidden="true" />
        <div className="space-y-2">
          <h4 className="font-bold dark:text-white">{t('sqltojava.about_title', 'About SQL to Java Class Generator')}</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
            {t('sqltojava.about_text', 'Convert SQL CREATE TABLE DDL queries into strongly-typed Java POJOs, JPA entities, or Java 17+ records. Supports JPA/Hibernate annotations (@Entity, @Table, @Column), Jackson (@JsonProperty), Gson (@SerializedName), Lombok (@Data, @Builder), property casing options, and package name customization.')}
          </p>
        </div>
      </div>
    </div>
  );
}
